//! TypeScript emission for `fragment` declarations (ADR-033, Phase F).
//!
//! Each `fragment Name(args) { body }` decl emits a typed React function
//! component into `fragments.tsx`. Consumer components reference fragments
//! by name; the compiler validates arity / types at the call site so the
//! generated TSX needs no fragment-specific runtime machinery.
//!
//! Example input:
//!
//! ```vox
//! // vox:skip — illustrative
//! fragment Row(item: str, idx: int) {
//!   text() { item }
//! }
//! ```
//!
//! Emits roughly:
//!
//! ```ts
//! // Generated by vox-compiler — do not edit.
//! import React from "react";
//!
//! export interface RowArgs {
//!   item: string;
//!   idx: number;
//! }
//!
//! export function Row({ item, idx }: RowArgs): React.ReactElement {
//!   return text({ children: item });
//! }
//! ```

use crate::codegen_ts::hir_emit::{emit_hir_expr, map_hir_type_to_ts};
use vox_compiler::hir::{HirFragmentDecl, HirModule};
use std::collections::HashSet;

/// Filename for the generated fragment module.
pub const FRAGMENTS_FILENAME: &str = "fragments.tsx";

/// Emit `fragments.tsx` content covering every `fragment` declaration in `hir`.
/// Returns an empty string when there are no fragments.
pub fn emit_fragment_decls(hir: &HirModule) -> String {
    if hir.fragments.is_empty() {
        return String::new();
    }
    let mut out = String::from("// Generated by vox-compiler — do not edit.\n");
    out.push_str("import React from \"react\";\n\n");
    for frag in &hir.fragments {
        emit_one(frag, &mut out);
        out.push('\n');
    }
    out
}

fn emit_one(frag: &HirFragmentDecl, out: &mut String) {
    let name = &frag.name;

    // Args interface — typed prop shape derived from the parameter list.
    out.push_str(&format!("export interface {name}Args {{\n"));
    for p in &frag.params {
        let ty_str = p
            .type_ann
            .as_ref()
            .map(map_hir_type_to_ts)
            .unwrap_or_else(|| "unknown".to_string());
        out.push_str(&format!("  {}: {ty_str};\n", p.name));
    }
    out.push_str("}\n\n");

    // Function signature: destructured params for direct in-body use.
    if frag.params.is_empty() {
        out.push_str(&format!(
            "export function {name}(): React.ReactElement {{\n"
        ));
    } else {
        let names: Vec<String> = frag.params.iter().map(|p| p.name.clone()).collect();
        out.push_str(&format!(
            "export function {name}({{ {} }}: {name}Args): React.ReactElement {{\n",
            names.join(", ")
        ));
    }

    // Body — emit the markup expression. Param names are visible to the body
    // (no `state_names` rewriting needed; fragments don't host reactive state).
    let empty_state: HashSet<String> = HashSet::new();
    let body = emit_hir_expr(&frag.body, &empty_state);
    out.push_str(&format!("  return ({body});\n"));
    out.push_str("}\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use vox_compiler::hir::{DefId, HirExpr, HirParam, HirType};

    fn fragment(name: &str, params: Vec<HirParam>, body: HirExpr) -> HirFragmentDecl {
        HirFragmentDecl {
            name: name.to_string(),
            params,
            body,
            span: vox_compiler::ast::span::Span::new(0, 0),
        }
    }

    fn param(name: &str, ty: HirType) -> HirParam {
        HirParam {
            id: DefId(0),
            name: name.to_string(),
            type_ann: Some(ty),
            default: None,
            span: vox_compiler::ast::span::Span::new(0, 0),
        }
    }

    fn module_with(frags: Vec<HirFragmentDecl>) -> HirModule {
        let mut m = HirModule::default();
        m.fragments = frags;
        m
    }

    #[test]
    fn emits_empty_string_when_no_fragments() {
        let m = HirModule::default();
        assert_eq!(emit_fragment_decls(&m), "");
    }

    #[test]
    fn emits_args_interface_and_function_signature() {
        let m = module_with(vec![fragment(
            "Row",
            vec![
                param("item", HirType::Named("str".into())),
                param("idx", HirType::Named("int".into())),
            ],
            HirExpr::StringLit("body".into(), vox_compiler::ast::span::Span::new(0, 0)),
        )]);
        let out = emit_fragment_decls(&m);
        assert!(out.contains("export interface RowArgs {"), "{out}");
        assert!(out.contains("item: string;"), "{out}");
        assert!(out.contains("idx: number;"), "{out}");
        assert!(
            out.contains("export function Row({ item, idx }: RowArgs): React.ReactElement {"),
            "{out}"
        );
    }

    #[test]
    fn emits_no_arg_signature_for_paramless_fragment() {
        let m = module_with(vec![fragment(
            "Greeting",
            vec![],
            HirExpr::StringLit("hi".into(), vox_compiler::ast::span::Span::new(0, 0)),
        )]);
        let out = emit_fragment_decls(&m);
        assert!(
            out.contains("export function Greeting(): React.ReactElement {"),
            "{out}"
        );
    }

    #[test]
    fn emits_react_import_and_header_comment_when_at_least_one_fragment() {
        let m = module_with(vec![fragment(
            "Greeting",
            vec![],
            HirExpr::StringLit("hi".into(), vox_compiler::ast::span::Span::new(0, 0)),
        )]);
        let out = emit_fragment_decls(&m);
        assert!(out.starts_with("// Generated by vox-compiler"), "{out}");
        assert!(out.contains("import React from \"react\""), "{out}");
    }

    /// End-to-end: a real source string with a `fragment` decl produces a
    /// `fragments.tsx` file in the codegen output.
    #[test]
    fn emitter_generate_includes_fragments_tsx() {
        let src = "fragment Greeting() { text() { \"hi\" } }";
        let tokens = vox_compiler::lexer::lex(src);
        let module = vox_compiler::parser::parse(tokens).expect("parse");
        let hir = vox_compiler::hir::lower::lower_module(&module);
        let out = crate::codegen_ts::generate(&hir).expect("codegen");
        let frag = out
            .files
            .iter()
            .find(|(n, _)| n == FRAGMENTS_FILENAME)
            .map(|(_, c)| c.as_str())
            .expect("fragments.tsx should be emitted when the module has a fragment");
        assert!(frag.contains("export interface GreetingArgs"), "{frag}");
        assert!(
            frag.contains("export function Greeting(): React.ReactElement"),
            "{frag}"
        );
    }

    #[test]
    fn emits_one_function_per_fragment() {
        let m = module_with(vec![
            fragment(
                "A",
                vec![],
                HirExpr::StringLit("a".into(), vox_compiler::ast::span::Span::new(0, 0)),
            ),
            fragment(
                "B",
                vec![],
                HirExpr::StringLit("b".into(), vox_compiler::ast::span::Span::new(0, 0)),
            ),
        ]);
        let out = emit_fragment_decls(&m);
        assert!(out.contains("export function A("), "{out}");
        assert!(out.contains("export function B("), "{out}");
    }
}
