//! Optional `package.json` for Library (`client` target / `vox emit client`) outputs.

use serde_json::{Map, Value, json};

/// Emit a **`private`** npm manifest so consumers can run `pnpm install` / link the folder as a workspace package.
///
/// Paths match files emitted by [`super::emitter::generate_with_options`] in [`super::emitter::BuildMode::Library`].
#[must_use]
pub fn emit_library_package_json(config: LibraryPackageConfig) -> String {
    let LibraryPackageConfig {
        has_vox_client,
        has_types,
        has_schemas,
        has_openapi,
        has_schema_ts,
    } = config;

    let mut exports = Map::new();
    if has_vox_client {
        exports.insert(".".to_string(), json!("./vox-client.ts"));
        exports.insert("./vox-client".to_string(), json!("./vox-client.ts"));
    }
    if has_types {
        exports.insert("./types".to_string(), json!("./types.ts"));
    }
    if has_schemas {
        exports.insert("./schemas".to_string(), json!("./schemas.ts"));
    }
    if has_schema_ts {
        exports.insert("./schema".to_string(), json!("./schema.ts"));
    }
    if has_openapi {
        exports.insert("./openapi.json".to_string(), json!("./openapi.json"));
    }

    let pkg = json!({
        "name": "vox-generated-client",
        "version": "0.0.0",
        "private": true,
        "type": "module",
        "description": "Generated by Vox (`vox build --target=client` or `vox emit client`). Bump version before publishing.",
        "exports": Value::Object(exports),
        "peerDependencies": {
            "zod": "^3.23.0"
        }
    });

    serde_json::to_string_pretty(&pkg).expect("library package.json serializes")
}

pub struct LibraryPackageConfig {
    pub has_vox_client: bool,
    pub has_types: bool,
    pub has_schemas: bool,
    pub has_openapi: bool,
    /// `schema.ts` from `@table` emit (distinct from Zod `schemas.ts`).
    pub has_schema_ts: bool,
}

impl LibraryPackageConfig {
    #[must_use]
    pub fn any_export(&self) -> bool {
        self.has_vox_client
            || self.has_types
            || self.has_schemas
            || self.has_schema_ts
            || self.has_openapi
    }
}
