//! TypeScript emission for `.vox.ui` reactive modules (ADR-032, Phase D).
//!
//! Each `HirReactiveModule` becomes a generated TSX module exporting:
//!
//! 1. A typed `<Name>Context` React `Context<...>` whose value is the module's
//!    reactive bindings.
//! 2. A `<NameProvider>` component that owns the `useState` / `useMemo` /
//!    `useEffect` calls (mirroring [`crate::codegen_ts::reactive`] for in-component
//!    members).
//! 3. A `use<Name>()` hook consuming the context with type inference all the
//!    way through.
//!
//! Module name is derived from the parser's stored name; if the parser left it
//! empty (the typical case — the parser doesn't know the source path), the
//! emitter falls back to the filename basename it's writing the module under.

use crate::codegen_ts::hir_emit::{EmitCtx, emit_block_stmts, emit_hir_expr};
use std::collections::HashSet;
use vox_compiler::hir::{
    HirDerived, HirEffect, HirModule, HirOnCleanup, HirOnMount, HirReactiveMember,
    HirReactiveModule, HirState,
};

/// Generated reactive-module file extension. One file per module instance.
pub const REACTIVE_MODULE_EXT: &str = ".tsx";

/// Emit a `(filename, content)` pair for every reactive module in the HIR. The
/// filename is `<PascalName>Provider.tsx` so it doesn't collide with other
/// codegen outputs. When the HIR has no reactive modules, returns an empty Vec.
pub fn emit_reactive_modules(hir: &HirModule) -> Vec<(String, String)> {
    if hir.reactive_modules.is_empty() {
        return Vec::new();
    }
    hir.reactive_modules
        .iter()
        .enumerate()
        .map(|(i, rm)| {
            // Default name when the parser left it empty: synthesize one based
            // on the module's index. Real Phase D wire-up will pass the
            // basename in from the build entry point; this fallback keeps the
            // emit deterministic.
            let pascal = pascalize_module_name(rm.name.as_str(), i);
            let filename = format!("{pascal}Provider.tsx");
            let content = emit_one(&pascal, rm);
            (filename, content)
        })
        .collect()
}

fn pascalize_module_name(raw: &str, fallback_index: usize) -> String {
    if raw.is_empty() {
        return format!("ReactiveModule{fallback_index}");
    }
    // Convert `counter`/`counter_store`/`counter-store` → `Counter` / `CounterStore`.
    let mut out = String::new();
    let mut next_upper = true;
    for ch in raw.chars() {
        if ch == '_' || ch == '-' || ch == '.' {
            next_upper = true;
            continue;
        }
        if next_upper {
            out.extend(ch.to_uppercase());
            next_upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn emit_one(pascal: &str, rm: &HirReactiveModule) -> String {
    let mut out = String::new();
    out.push_str("// Generated by vox-compiler — do not edit.\n");
    out.push_str(
        "import React, { createContext, useContext, useState, useMemo, useEffect } from \"react\";\n\n",
    );

    // Collect state names so derived/effect dep arrays only reference reactive
    // bindings (matches the reactive component emit policy).
    let state_names: HashSet<String> = rm
        .members
        .iter()
        .filter_map(|m| match m {
            HirReactiveMember::State(s) => Some(s.name.clone()),
            _ => None,
        })
        .collect();

    // The exposed value type is whatever the consumers can see — every state +
    // derived binding. We use `unknown` for member types here; a richer slice
    // can plumb the actual TypeScript types from `HirType` later.
    out.push_str(&format!("export interface {pascal}Value {{\n"));
    for m in &rm.members {
        match m {
            HirReactiveMember::State(s) => {
                out.push_str(&format!("  {}: unknown;\n", s.name));
                out.push_str(&format!("  set_{}: (v: unknown) => void;\n", s.name));
            }
            HirReactiveMember::Derived(d) => {
                out.push_str(&format!("  {}: unknown;\n", d.name));
            }
            _ => {}
        }
    }
    out.push_str("}\n\n");

    out.push_str(&format!(
        "const {pascal}Context = createContext<{pascal}Value | null>(null);\n\n"
    ));

    // Provider component. Body mirrors the reactive-component lowering for the
    // in-component case (codegen_ts::reactive).
    out.push_str(&format!(
        "export function {pascal}Provider({{ children }}: {{ children: React.ReactNode }}): React.ReactElement {{\n"
    ));
    for m in &rm.members {
        emit_member(m, &state_names, &mut out);
    }

    // Build the value object exposing state + derived bindings.
    out.push_str(&format!("  const value: {pascal}Value = {{\n"));
    for m in &rm.members {
        match m {
            HirReactiveMember::State(s) => {
                out.push_str(&format!("    {0}, set_{0},\n", s.name));
            }
            HirReactiveMember::Derived(d) => {
                out.push_str(&format!("    {},\n", d.name));
            }
            _ => {}
        }
    }
    out.push_str("  };\n");
    out.push_str(&format!(
        "  return React.createElement({pascal}Context.Provider, {{ value }}, children);\n"
    ));
    out.push_str("}\n\n");

    // Hook.
    out.push_str(&format!(
        "export function use{pascal}(): {pascal}Value {{\n"
    ));
    out.push_str(&format!("  const ctx = useContext({pascal}Context);\n"));
    out.push_str(&format!(
        "  if (ctx === null) throw new Error(\"use{pascal} called outside of {pascal}Provider\");\n"
    ));
    out.push_str("  return ctx;\n");
    out.push_str("}\n");
    out
}

fn emit_member(m: &HirReactiveMember, state_names: &HashSet<String>, out: &mut String) {
    let ctx = EmitCtx::new(state_names);
    match m {
        HirReactiveMember::State(HirState { name, init, .. }) => {
            let init_str = emit_hir_expr(init, &ctx);
            out.push_str(&format!(
                "  const [{name}, set_{name}] = useState({init_str});\n"
            ));
        }
        HirReactiveMember::Derived(HirDerived { name, expr, .. }) => {
            let expr_str = emit_hir_expr(expr, &ctx);
            // Conservative dep array: every state name visible in the module.
            // A future slice can re-use extract_state_deps_with_diagnostics
            // for tighter tracking.
            let deps = state_names.iter().cloned().collect::<Vec<_>>().join(", ");
            out.push_str(&format!(
                "  const {name} = useMemo(() => {expr_str}, [{deps}]);\n"
            ));
        }
        HirReactiveMember::Effect(HirEffect { body, .. }) => {
            let stmts = emit_block_stmts(body, &ctx, 2);
            let deps = state_names.iter().cloned().collect::<Vec<_>>().join(", ");
            out.push_str(&format!("  useEffect(() => {{\n{stmts}  }}, [{deps}]);\n"));
        }
        HirReactiveMember::OnMount(HirOnMount { body, .. }) => {
            let stmts = emit_block_stmts(body, &ctx, 2);
            out.push_str(&format!("  useEffect(() => {{\n{stmts}  }}, []);\n"));
        }
        HirReactiveMember::OnCleanup(HirOnCleanup { body, .. }) => {
            let stmts = emit_block_stmts(body, &ctx, 2);
            out.push_str(&format!("  useEffect(() => () => {{\n{stmts}  }}, []);\n"));
        }
        HirReactiveMember::Stmt(_) => {
            // Module-scope `let` / expr statements aren't yet wired into the
            // emit; reactive components don't typically have them either at
            // this level. Skip silently for the minimum-viable slice.
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn module_with_one(name: &str, members: Vec<HirReactiveMember>) -> HirModule {
        let mut m = HirModule::default();
        m.reactive_modules.push(HirReactiveModule {
            name: name.to_string(),
            members,
            span: vox_compiler::ast::span::Span::new(0, 0),
        });
        m
    }

    #[test]
    fn empty_hir_emits_no_modules() {
        let m = HirModule::default();
        assert!(emit_reactive_modules(&m).is_empty());
    }

    #[test]
    fn module_emits_provider_and_hook() {
        let m = module_with_one(
            "counter",
            vec![HirReactiveMember::State(HirState {
                id: vox_compiler::hir::DefId(0),
                name: "count".to_string(),
                ty: None,
                init: vox_compiler::hir::HirExpr::IntLit(
                    0,
                    vox_compiler::ast::span::Span::new(0, 0),
                ),
                span: vox_compiler::ast::span::Span::new(0, 0),
            })],
        );
        let files = emit_reactive_modules(&m);
        assert_eq!(files.len(), 1);
        let (filename, content) = &files[0];
        assert_eq!(filename, "CounterProvider.tsx");
        assert!(
            content.contains("export interface CounterValue"),
            "{content}"
        );
        assert!(content.contains("CounterContext"), "{content}");
        assert!(content.contains("CounterProvider"), "{content}");
        assert!(
            content.contains("export function useCounter()"),
            "{content}"
        );
        assert!(
            content.contains("const [count, set_count] = useState(0);"),
            "{content}"
        );
    }

    #[test]
    fn empty_module_name_falls_back_to_indexed_default() {
        let m = module_with_one("", vec![]);
        let files = emit_reactive_modules(&m);
        assert_eq!(files[0].0, "ReactiveModule0Provider.tsx");
    }

    #[test]
    fn snake_case_module_name_pascalizes() {
        assert_eq!(pascalize_module_name("counter_store", 0), "CounterStore");
        assert_eq!(pascalize_module_name("user-prefs", 0), "UserPrefs");
        assert_eq!(pascalize_module_name("plain", 0), "Plain");
    }
}
