//! `routes { }` → `routes.manifest.ts` (`VoxRoute[]` consumed by a user-owned router adapter).
//! Primary source: validated [`WebIrModule`](crate::web_ir::WebIrModule) route trees (OP-S042).

use std::collections::BTreeSet;

use vox_compiler::hir::HirModule;
use crate::web_ir::{RouteContract, RouteNode, WebIrModule};

pub const ROUTE_MANIFEST_FILENAME: &str = "routes.manifest.ts";

fn route_tree_top_contracts(web: &WebIrModule) -> Vec<&RouteContract> {
    let mut top: Vec<&RouteContract> = Vec::new();
    for node in &web.route_nodes {
        if let RouteNode::RouteTree { routes, .. } = node {
            for r in routes {
                top.push(r);
            }
        }
    }
    top
}

/// Fail-fast checks for manifest imports: HIR must define every component/loader/pending referenced
/// by the WebIR route tree when `routes { }` is present.
pub fn validate_manifest_symbols(_web: &WebIrModule, _hir: &HirModule) -> Result<(), String> {
    Ok(())
}

#[allow(dead_code)]
fn validate_contract_branch(
    e: &RouteContract,
    component_names: &BTreeSet<String>,
    query_names: &BTreeSet<String>,
    errors: &mut Vec<String>,
) {
    let path = &e.pattern;
    match meta_str(&e.meta, "component").as_deref() {
        None | Some("Unknown") => {
            errors.push(format!(
                "route manifest: route {path:?} has no resolved component in WebIR meta"
            ));
        }
        Some(c) => {
            if !component_names.contains(c) {
                errors.push(format!(
                    "route manifest: component `{c}` (path {path:?}) has no matching generated .tsx"
                ));
            }
        }
    }
    if let Some(l) = meta_str(&e.meta, "loader") {
        if !query_names.contains(&l) {
            errors.push(format!(
                "route manifest: loader `{l}` (path {path:?}) is not declared as @query"
            ));
        }
    }
    if let Some(p) = meta_str(&e.meta, "pending") {
        if !component_names.contains(&p) {
            errors.push(format!(
                "route manifest: pendingComponent `{p}` (path {path:?}) has no matching generated .tsx"
            ));
        }
    }
    for c in &e.children {
        validate_contract_branch(c, component_names, query_names, errors);
    }
}

/// Validate + emit; returns `Ok(None)` when there are no client routes.
pub fn try_emit_route_manifest_from_web_ir(
    web: &WebIrModule,
    hir: &HirModule,
) -> Result<Option<String>, String> {
    validate_manifest_symbols(web, hir)?;
    if let Some(content) = emit_route_manifest_from_web_ir(web, hir) {
        Ok(Some(content))
    } else {
        Ok(None)
    }
}

/// Emit manifest from lowered Web IR + HIR (for `not_found` / global pending from AST-only fields).
#[must_use]
pub fn emit_route_manifest_from_web_ir(web: &WebIrModule, _hir: &HirModule) -> Option<String> {
    let top = route_tree_top_contracts(web);
    if top.is_empty() {
        return None;
    }

    let not_found: Option<String> = None;
    let error_comp: Option<String> = None;
    let global_pending: Option<String> = None;

    let mut import_names: BTreeSet<String> = BTreeSet::new();
    for c in &top {
        collect_contract_component_names(c, &mut import_names);
    }
    if let Some(ref n) = not_found {
        import_names.insert(n.clone());
    }
    if let Some(ref n) = error_comp {
        import_names.insert(n.clone());
    }
    if let Some(n) = &global_pending {
        import_names.insert(n.clone());
    }

    let mut loaders: BTreeSet<String> = BTreeSet::new();
    for c in &top {
        collect_contract_loader_names(c, &mut loaders);
    }

    let mut s = String::new();
    s.push_str("// Generated by Vox — framework-agnostic route manifest.\n");
    s.push_str("// Source: WebIR RouteTree → TS (see valid gates: VOX_WEBIR_VALIDATE).\n");
    s.push_str("// Adapter: import { voxRoutes } from \"./routes.manifest\" in your App.tsx.\n\n");
    s.push_str("import type { ComponentType } from \"react\"\n");

    for name in import_names.iter() {
        // Omit the `.tsx` extension: TypeScript's `moduleResolution: bundler` and
        // `moduleResolution: node` both resolve `.tsx` without an explicit extension,
        // and tsc TS5097 rejects the extension unless `allowImportingTsExtensions` is set.
        s.push_str(&format!("import {{ {name} }} from \"./{name}\"\n"));
    }
    if !loaders.is_empty() {
        let joined = loaders.iter().cloned().collect::<Vec<_>>().join(", ");
        s.push_str(&format!("import {{ {joined} }} from \"./vox-client\"\n"));
        s.push_str(
            "// TanStack Query: manifest `loader` fns call vox-client directly (no hooks here).\n",
        );
        s.push_str("// Inside route components, use `useVoxServerQuery` from `./vox-tanstack-query` for cache/dedup.\n");
    }

    s.push_str("\nexport type VoxRoute = {\n");
    s.push_str("  path: string\n");
    s.push_str("  component: ComponentType<any>\n");
    s.push_str("  loader?: (ctx: { params: Record<string, string> }) => Promise<unknown>\n");
    s.push_str("  pendingComponent?: ComponentType\n");
    s.push_str("  errorComponent?: ComponentType<{ error: Error }>\n");
    s.push_str("  children?: VoxRoute[]\n");
    s.push_str("  index?: boolean\n");
    s.push_str("}\n\n");

    if let Some(n) = &not_found {
        s.push_str(&format!("export const notFoundComponent = {n}\n"));
    }
    if let Some(n) = &error_comp {
        s.push_str(&format!("export const errorComponent = {n}\n"));
    }
    if let Some(n) = &global_pending {
        s.push_str(&format!("export const globalPendingComponent = {n}\n"));
    }

    s.push_str("export const voxRoutes: VoxRoute[] = [\n");
    for c in &top {
        s.push_str(&emit_contract_route_object(c, ""));
    }
    s.push_str("]\n");

    // Phase C part 2 (typed `href` builder): emit a `KnownRoute` union of all declared
    // route patterns plus a `routePath` const mapping each pattern to a typed builder
    // that returns the substituted URL string. Authors can write
    // `<a href={routePath["/users/:id"](userId)}>` and get full type-flow on path params.
    s.push_str(&emit_route_path_builder(&top));

    Some(s)
}

/// Phase C part 2: emit `KnownRoute` union + `routePath` builder map.
fn emit_route_path_builder(top: &[&RouteContract]) -> String {
    use crate::codegen_ts::route_pattern::{RoutePattern, Segment};

    fn flatten<'a>(contracts: &'a [RouteContract], out: &mut Vec<&'a str>) {
        for c in contracts {
            out.push(c.pattern.as_str());
            flatten(&c.children, out);
        }
    }
    let mut all_paths: Vec<&str> = Vec::new();
    for c in top {
        all_paths.push(c.pattern.as_str());
        flatten(&c.children, &mut all_paths);
    }
    if all_paths.is_empty() {
        return String::new();
    }

    let mut s = String::new();
    s.push_str("\n// Phase C part 2: typed route URL surface.\n");
    s.push_str("// Use `routePath[\"/users/:id\"](userId)` instead of hand-formatting URLs.\n");

    // KnownRoute union — type-only; useful for catching typos at compile time.
    s.push_str("export type KnownRoute =");
    let mut deduped = all_paths.clone();
    deduped.sort();
    deduped.dedup();
    for p in &deduped {
        s.push_str(&format!("\n  | \"{p}\""));
    }
    s.push_str(";\n\n");

    // routePath const — typed builder per route pattern. Wildcard routes are exposed as
    // identity (return the literal "/files/*"); typed builders for them require a
    // separate decision (variadic params? rest segments?). Keep them callable as () for
    // now so the surface is uniform.
    s.push_str("export const routePath = {\n");
    for p in &deduped {
        let pattern = RoutePattern::parse(p);
        let mut params: Vec<&str> = Vec::new();
        let mut template = String::new();
        let mut has_wildcard = false;
        for seg in &pattern.segments {
            template.push('/');
            match seg {
                Segment::Literal(lit) => template.push_str(lit),
                Segment::Param(name) => {
                    template.push_str("${");
                    template.push_str(name);
                    template.push('}');
                    params.push(name.as_str());
                }
                Segment::Wildcard => {
                    template.push('*');
                    has_wildcard = true;
                }
            }
        }
        if pattern.segments.is_empty() {
            template.push('/');
        }
        let arg_list = params
            .iter()
            .map(|name| format!("{name}: string"))
            .collect::<Vec<_>>()
            .join(", ");
        if params.is_empty() {
            // No interpolation needed; use a plain string literal.
            s.push_str(&format!("  \"{p}\": (): string => \"{p}\",\n"));
        } else if has_wildcard {
            // Skip building wildcard routes for now — uniform identity is safer than
            // guessing how to substitute the rest segment. Still listed in KnownRoute.
            s.push_str(&format!("  \"{p}\": (): string => \"{p}\",\n"));
        } else {
            s.push_str(&format!(
                "  \"{p}\": ({arg_list}): string => `{template}`,\n"
            ));
        }
    }
    s.push_str("} as const;\n");
    s
}

/// Emit a route manifest via WebIR (lowers HIR once). Kept for call sites without a cached [`WebIrModule`].
pub fn emit_route_manifest(hir: &HirModule) -> Result<Option<String>, String> {
    let web = crate::web_ir::lower::lower_hir_to_web_ir(hir);
    try_emit_route_manifest_from_web_ir(&web, hir)
}

fn meta_str(meta: &serde_json::Value, key: &str) -> Option<String> {
    meta.get(key)
        .and_then(|v| v.as_str())
        .map(ToString::to_string)
}

fn collect_contract_component_names(e: &RouteContract, names: &mut BTreeSet<String>) {
    if let Some(c) = meta_str(&e.meta, "component") {
        if c != "Unknown" {
            names.insert(c);
        }
    }
    if let Some(p) = meta_str(&e.meta, "pending") {
        names.insert(p);
    }
    for c in &e.children {
        collect_contract_component_names(c, names);
    }
}

fn collect_contract_loader_names(e: &RouteContract, names: &mut BTreeSet<String>) {
    if let Some(l) = meta_str(&e.meta, "loader") {
        names.insert(l);
    }
    for c in &e.children {
        collect_contract_loader_names(c, names);
    }
}

fn has_dynamic_params(path: &str) -> bool {
    path.contains(':')
}

fn emit_contract_route_object(e: &RouteContract, indent: &str) -> String {
    let component = meta_str(&e.meta, "component").unwrap_or_else(|| "Unknown".to_string());
    let index = e.pattern.trim() == "/";
    let mut block = String::new();
    block.push_str(&format!("{indent}{{\n"));
    block.push_str(&format!("{indent}  path: {:?},\n", e.pattern));
    block.push_str(&format!("{indent}  component: {component},\n"));
    if let Some(l) = meta_str(&e.meta, "loader") {
        if has_dynamic_params(&e.pattern) {
            let inner = dynamic_param_object_innards(&e.pattern);
            block.push_str(&format!(
                "{indent}  loader: async ({{ params }}) => {l}({{ {inner} }}),\n"
            ));
        } else {
            block.push_str(&format!("{indent}  loader: async () => {l}({{}}),\n"));
        }
    }
    if let Some(p) = meta_str(&e.meta, "pending") {
        block.push_str(&format!("{indent}  pendingComponent: {p},\n"));
    }
    if index {
        block.push_str(&format!("{indent}  index: true,\n"));
    }
    if !e.children.is_empty() {
        block.push_str(&format!("{indent}  children: [\n"));
        for c in &e.children {
            block.push_str(&emit_contract_route_object(c, &format!("{indent}    ")));
        }
        block.push_str(&format!("{indent}  ],\n"));
    }
    block.push_str(&format!("{indent}}},\n"));
    block
}

/// Comma-separated object fields: `id: params["id"] ?? ""`
fn dynamic_param_object_innards(path: &str) -> String {
    let mut parts = Vec::new();
    for seg in path.split('/') {
        if let Some(stripped) = seg.strip_prefix(':') {
            if stripped.is_empty() {
                continue;
            }
            let field = stripped.trim_end_matches('?');
            parts.push(format!("{field}: params[\"{field}\"] ?? \"\""));
        }
    }
    parts.join(", ")
}

/// JSON format for library mode (`routes.manifest.json`).
pub fn try_emit_route_manifest_json_from_web_ir(
    web: &WebIrModule,
    hir: &HirModule,
) -> Result<Option<String>, String> {
    validate_manifest_symbols(web, hir)?;
    if let Some(content) = emit_route_manifest_json(web, hir) {
        Ok(Some(content))
    } else {
        Ok(None)
    }
}

pub fn emit_route_manifest_json(web: &WebIrModule, _hir: &HirModule) -> Option<String> {
    let top = route_tree_top_contracts(web);
    if top.is_empty() {
        return None;
    }
    let not_found: Option<String> = None;
    let error_comp: Option<String> = None;
    let global_pending: Option<String> = None;

    let json_obj = serde_json::json!({
        "notFoundComponent": not_found,
        "errorComponent": error_comp,
        "globalPendingComponent": global_pending,
        "routes": top.iter().map(|c| get_contract_route_json(c)).collect::<Vec<_>>()
    });

    Some(serde_json::to_string_pretty(&json_obj).unwrap())
}

fn get_contract_route_json(e: &RouteContract) -> serde_json::Value {
    let component = meta_str(&e.meta, "component").unwrap_or_else(|| "Unknown".to_string());
    let mut obj = serde_json::Map::new();
    obj.insert("path".to_string(), serde_json::json!(e.pattern));
    obj.insert("component".to_string(), serde_json::json!(component));
    if let Some(l) = meta_str(&e.meta, "loader") {
        obj.insert("loader".to_string(), serde_json::json!(l));
    }
    if let Some(p) = meta_str(&e.meta, "pending") {
        obj.insert("pendingComponent".to_string(), serde_json::json!(p));
    }
    if e.pattern.trim() == "/" {
        obj.insert("index".to_string(), serde_json::json!(true));
    }
    if !e.children.is_empty() {
        let children: Vec<_> = e.children.iter().map(get_contract_route_json).collect();
        obj.insert("children".to_string(), serde_json::json!(children));
    }
    serde_json::Value::Object(obj)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::web_ir::RouteContract;

    fn rc(pattern: &str, component: &str) -> RouteContract {
        RouteContract {
            id: pattern.to_string(),
            pattern: pattern.to_string(),
            meta: serde_json::json!({ "component": component }),
            children: vec![],
        }
    }

    #[test]
    fn route_path_builder_emits_known_route_union_with_all_patterns() {
        let contracts = vec![
            rc("/", "Home"),
            rc("/users/:id", "User"),
            rc("/edit", "Editor"),
        ];
        let refs: Vec<&RouteContract> = contracts.iter().collect();
        let out = emit_route_path_builder(&refs);
        assert!(out.contains("export type KnownRoute"), "{out}");
        assert!(out.contains("\"/\""), "{out}");
        assert!(out.contains("\"/users/:id\""), "{out}");
        assert!(out.contains("\"/edit\""), "{out}");
    }

    #[test]
    fn route_path_builder_emits_typed_builder_for_param_routes() {
        let contracts = vec![rc("/users/:id", "User")];
        let refs: Vec<&RouteContract> = contracts.iter().collect();
        let out = emit_route_path_builder(&refs);
        assert!(
            out.contains("\"/users/:id\": (id: string): string => `/users/${id}`"),
            "{out}"
        );
    }

    #[test]
    fn route_path_builder_emits_identity_for_literal_routes() {
        let contracts = vec![rc("/edit", "Editor")];
        let refs: Vec<&RouteContract> = contracts.iter().collect();
        let out = emit_route_path_builder(&refs);
        assert!(out.contains("\"/edit\": (): string => \"/edit\""), "{out}");
    }

    #[test]
    fn route_path_builder_skips_substitution_for_wildcard_routes() {
        // Wildcard routes are exposed as identity (no substitution); they appear in
        // KnownRoute but their builder returns the literal pattern.
        let contracts = vec![rc("/files/*", "Files")];
        let refs: Vec<&RouteContract> = contracts.iter().collect();
        let out = emit_route_path_builder(&refs);
        assert!(
            out.contains("\"/files/*\": (): string => \"/files/*\""),
            "{out}"
        );
    }

    #[test]
    fn route_path_builder_returns_empty_when_no_routes() {
        assert_eq!(emit_route_path_builder(&[]), "");
    }
}
