//! Emit CSS and TypeScript artifacts from design-token declarations.
//!
//! Two entry points:
//! - `emit_tokens_css` / `emit_tokens_ts` — from a loaded `TokenRegistry`
//!   (JSON-file-based legacy path; called when `vox.tokens.json` is present).
//! - `emit_hir_tokens_css` / `emit_hir_tokens_ts` — from `HirTokensDecl`
//!   nodes lowered from `tokens { … }` source blocks (GA-20 / CC-23).

use vox_compiler::hir::nodes::tokens::HirTokensDecl;
use vox_compiler::tokens::TokenRegistry;

// ── HIR-based token emit (GA-20 / CC-23) ──────────────────────────────────

/// Emit `:root { --vox-* }` CSS custom properties from HIR token declarations.
///
/// Color tokens emit both `--vox-<name>-light` and `--vox-<name>-dark`
/// variants plus a `--vox-<name>` alias that resolves to the light value; a
/// companion `@media (prefers-color-scheme: dark)` block overrides the alias.
#[must_use]
pub fn emit_hir_tokens_css(decls: &[HirTokensDecl]) -> String {
    let mut light = String::new();
    let mut dark_overrides = String::new();

    for decl in decls {
        for tok in &decl.colors {
            let css_name = tok.name.replace('.', "-").to_lowercase();
            light.push_str(&format!("  --vox-{css_name}: {};\n", tok.light));
            light.push_str(&format!("  --vox-{css_name}-light: {};\n", tok.light));
            light.push_str(&format!("  --vox-{css_name}-dark: {};\n", tok.dark));
            dark_overrides.push_str(&format!("    --vox-{css_name}: {};\n", tok.dark));
        }
        for tok in &decl.spacing {
            let css_name = tok.name.replace('.', "-").to_lowercase();
            light.push_str(&format!("  --vox-{css_name}: {};\n", tok.value));
        }
        for tok in &decl.radius {
            let css_name = tok.name.replace('.', "-").to_lowercase();
            light.push_str(&format!("  --vox-{css_name}: {};\n", tok.value));
        }
        for tok in &decl.shadows {
            let css_name = tok.name.replace('.', "-").to_lowercase();
            light.push_str(&format!("  --vox-{css_name}: {};\n", tok.value));
        }
        for tok in &decl.fonts {
            let css_name = tok.name.replace('.', "-").to_lowercase();
            light.push_str(&format!("  --vox-{css_name}: {};\n", tok.family));
        }
    }

    let mut out = format!(":root {{\n{light}}}\n");
    if !dark_overrides.is_empty() {
        out.push_str(&format!(
            "@media (prefers-color-scheme: dark) {{\n  :root {{\n{dark_overrides}  }}\n}}\n"
        ));
    }
    out
}

/// Emit a typed `VoxTokens` constant for TypeScript consumers from HIR token declarations.
///
/// Each token key maps to its CSS `var(--vox-*)` reference so TS consumers
/// reference tokens by name without hardcoding CSS variable spellings.
#[must_use]
pub fn emit_hir_tokens_ts(decls: &[HirTokensDecl]) -> String {
    let mut entries: Vec<(String, String)> = Vec::new();

    for decl in decls {
        for tok in &decl.colors {
            let css_name = tok.name.replace('.', "-").to_lowercase();
            entries.push((tok.name.clone(), format!("var(--vox-{css_name})")));
        }
        for tok in &decl.spacing {
            let css_name = tok.name.replace('.', "-").to_lowercase();
            entries.push((tok.name.clone(), format!("var(--vox-{css_name})")));
        }
        for tok in &decl.radius {
            let css_name = tok.name.replace('.', "-").to_lowercase();
            entries.push((tok.name.clone(), format!("var(--vox-{css_name})")));
        }
        for tok in &decl.shadows {
            let css_name = tok.name.replace('.', "-").to_lowercase();
            entries.push((tok.name.clone(), format!("var(--vox-{css_name})")));
        }
        for tok in &decl.fonts {
            let css_name = tok.name.replace('.', "-").to_lowercase();
            entries.push((tok.name.clone(), format!("var(--vox-{css_name})")));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::from(
        "// Generated by Vox compiler from tokens { … } declarations. Do not edit.\n\n",
    );
    out.push_str("export const VoxTokens = {\n");
    for (name, var_ref) in &entries {
        out.push_str(&format!("  \"{name}\": \"{var_ref}\",\n"));
    }
    out.push_str("} as const;\n\n");
    out.push_str("export type VoxTokenKey = keyof typeof VoxTokens;\n");
    out
}

/// Emit `:root { --vox-* }` CSS custom properties from the registry.
///
/// Entries are sorted for deterministic output. Annotated tokens emit their
/// resolved hex value (not the raw JSON object).
pub fn emit_tokens_css(registry: &TokenRegistry) -> String {
    let mut entries: Vec<(&str, &str)> = registry
        .by_css_var
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();
    entries.sort_by_key(|(k, _)| *k);

    let mut out = String::from(":root {\n");
    for (key, value) in entries {
        // Keys must only contain safe CSS identifier characters.  The
        // TokenRegistry loader is the primary enforcement point; this
        // debug_assert is the emitter's last-line-of-defense guard.
        debug_assert!(
            key.chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'),
            "token key '{key}' contains characters unsafe for CSS custom property names"
        );
        out.push_str(&format!("  --vox-{}: {};\n", key, value));
    }
    out.push_str("}\n");
    out
}

/// Emit a typed `voxTokens` constant for TypeScript consumers.
///
/// Keys match the CSS custom property suffix: `"color-primary"` maps to
/// `"var(--vox-color-primary)"`. The object is `as const` so property-level
/// types are preserved.
pub fn emit_tokens_ts(registry: &TokenRegistry) -> String {
    let mut entries: Vec<(&str, &str)> = registry
        .by_css_var
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();
    entries.sort_by_key(|(k, _)| *k);

    let mut out =
        String::from("// Generated by Vox compiler from vox.tokens.json. Do not edit.\n\n");
    out.push_str("export const voxTokens = {\n");
    for (key, _) in &entries {
        out.push_str(&format!("  \"{key}\": \"var(--vox-{key})\",\n", key = key));
    }
    out.push_str("} as const;\n\n");
    out.push_str("export type VoxTokenKey = keyof typeof voxTokens;\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn minimal_registry() -> TokenRegistry {
        TokenRegistry::load_from_str(
            r##"{
            "color": {
                "primary": "#3a86ff",
                "background": "#ffffff",
                "text": {
                    "value": "#1d3557",
                    "on": "color.background",
                    "text_role": "body"
                }
            },
            "spacing": { "md": "16px" }
        }"##,
        )
        .unwrap()
    }

    #[test]
    fn css_contains_custom_properties() {
        let css = emit_tokens_css(&minimal_registry());
        assert!(css.contains("--vox-color-primary: #3a86ff;"), "{}", css);
        assert!(css.contains("--vox-color-background: #ffffff;"), "{}", css);
        assert!(css.contains("--vox-color-text: #1d3557;"), "{}", css);
        assert!(css.contains("--vox-spacing-md: 16px;"), "{}", css);
    }

    #[test]
    fn css_omits_schema_key() {
        let json = r##"{ "$schema": "./contracts/tokens/tokens.v1.json", "color": { "primary": "#3a86ff" } }"##;
        let reg = TokenRegistry::load_from_str(json).unwrap();
        let css = emit_tokens_css(&reg);
        assert!(!css.contains("$schema"), "schema key leaked: {}", css);
        assert!(!css.contains("schema"), "schema key leaked: {}", css);
    }

    #[test]
    fn annotated_token_emits_value_not_object() {
        let css = emit_tokens_css(&minimal_registry());
        assert!(
            css.contains("--vox-color-text: #1d3557;"),
            "annotated token should emit hex value: {}",
            css
        );
        assert!(!css.contains("on:"), "object leaked into CSS: {}", css);
    }

    #[test]
    fn ts_exports_const_and_type() {
        let ts = emit_tokens_ts(&minimal_registry());
        assert!(ts.contains("export const voxTokens"), "{}", ts);
        assert!(ts.contains("as const"), "{}", ts);
        assert!(ts.contains("export type VoxTokenKey"), "{}", ts);
        assert!(
            ts.contains("\"color-primary\": \"var(--vox-color-primary)\""),
            "{}",
            ts
        );
    }

    #[test]
    fn output_is_deterministic() {
        // Load two registries from the same JSON with keys declared in
        // different insertion order to verify sort-based determinism, not
        // just same-instance purity.
        let json_a = r##"{
            "color": { "primary": "#3a86ff", "background": "#ffffff" },
            "spacing": { "sm": "8px", "md": "16px" }
        }"##;
        let json_b = r##"{
            "spacing": { "md": "16px", "sm": "8px" },
            "color": { "background": "#ffffff", "primary": "#3a86ff" }
        }"##;
        let reg_a = TokenRegistry::load_from_str(json_a).unwrap();
        let reg_b = TokenRegistry::load_from_str(json_b).unwrap();
        assert_eq!(
            emit_tokens_css(&reg_a),
            emit_tokens_css(&reg_b),
            "CSS output must be identical regardless of key insertion order"
        );
        assert_eq!(
            emit_tokens_ts(&reg_a),
            emit_tokens_ts(&reg_b),
            "TS output must be identical regardless of key insertion order"
        );
    }
}
