//! Framework-agnostic typed `fetch` client for `@endpoint(kind: query|mutation|server)`.
//!
//! **HTTP SSOT (Rust + TS):** generated Axum wiring uses **`GET`** for `@query` (deterministic
//! JSON-in-query encoding: sorted keys, each value is `JSON.stringify` + `encodeURIComponent`) and
//! **`POST` + JSON body** for `@mutation` / `@server`. Cache-friendly reads use GET as intended.
//!
//! Wire-format rules live in [`vox_compiler::contract_ir`]. This emitter reads
//! [`vox_compiler::contract_ir::ContractEndpoint`] rather than walking HIR directly —
//! so type mappings (Decimal → string, BigInt → string, Option → optional param) are
//! enforced by the same projection that drives Zod and OpenAPI emit.

use vox_compiler::contract_ir::{
    self, ContractEndpointKind, WireType, wire_type_to_ts, wire_type_to_zod,
};
use vox_compiler::hir::HirModule;

/// Stable output filename for the generated client.
pub const VOX_CLIENT_FILENAME: &str = "vox-client.ts";

#[must_use]
pub fn emit_vox_client(hir: &HirModule) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Vox — typed fetch client for @query / @mutation / @server\n");
    out.push_str("// Transport: GET + JSON query values for @query; POST + JSON body for @mutation / @server.\n");
    out.push_str("// Do not edit; regenerate with `vox build`.\n\n");
    out.push_str("import { z } from \"zod\";\n");

    let ir = contract_ir::project(hir);

    let type_names: Vec<String> = ir.types.iter().map(|t| t.name.clone()).collect();
    if !type_names.is_empty() {
        out.push_str(&format!(
            "import type {{ {} }} from \"./types\";\n",
            type_names.join(", ")
        ));
        let zod_imports: Vec<String> = type_names.iter().map(|t| format!("{}Schema", t)).collect();
        out.push_str(&format!(
            "import {{ {} }} from \"./schemas\";\n\n",
            zod_imports.join(", ")
        ));
    }

    out.push_str("export class VoxApiError extends Error {\n  constructor(public readonly status: number, public readonly path: string, public readonly responseText: string) {\n    super(`${path} failed: ${status}${responseText ? ` — ${responseText.slice(0, 200)}` : \"\"}`);\n    this.name = \"VoxApiError\";\n  }\n}\n\n");

    out.push_str(
        "const BASE = ((import.meta as unknown as { env?: { VITE_API_URL?: string } }).env?.VITE_API_URL ?? \"\");\n\n",
    );
    out.push_str(
        r#"/** Build `?a=<json>&b=<json>` with keys sorted lexicographically (matches Axum BTreeMap decode). */
function voxQueryString(query: Record<string, unknown>): string {
  const keys = Object.keys(query).sort();
  if (keys.length === 0) return "";
  const parts = keys.map(
    (k) => `${encodeURIComponent(k)}=${encodeURIComponent(JSON.stringify(query[k]))}`,
  );
  return `?${parts.join("&")}`;
}

async function $get<T>(path: string, schema?: { parse: (x: any) => T }, query?: Record<string, unknown>, init?: RequestInit): Promise<T> {
  const url = BASE ? `${BASE}${path}` : path;
  const qs = query && Object.keys(query).length > 0 ? voxQueryString(query) : "";
  const r = await fetch(`${url}${qs}`, { method: "GET", ...init });
  if (!r.ok) {
    const t = await r.text().catch(() => "");
    throw new VoxApiError(r.status, path, t);
  }
  const data = await r.json();
  return schema ? schema.parse(data) : (data as T);
}

async function $post<T>(path: string, schema?: { parse: (x: any) => T }, body?: unknown, init?: RequestInit): Promise<T> {
  const url = BASE ? `${BASE}${path}` : path;
  const r = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body ?? {}),
    ...init,
  });
  if (!r.ok) {
    const t = await r.text().catch(() => "");
    throw new VoxApiError(r.status, path, t);
  }
  const data = await r.json();
  return schema ? schema.parse(data) : (data as T);
}

"#,
    );

    for ep in &ir.endpoints {
        let is_query = ep.kind == ContractEndpointKind::Query;
        out.push_str(&emit_one_endpoint(ep, is_query));
    }

    out
}

fn emit_one_endpoint(ep: &contract_ir::ContractEndpoint, is_query: bool) -> String {
    let name = &ep.name;
    let path = &ep.path;

    let return_ts = match &ep.response {
        WireType::Unit => "void".to_string(),
        wt => wire_type_to_ts(wt),
    };

    // `undefined` tells $get/$post to skip schema validation (unit returns have
    // no body to parse; callers must not depend on the return value).
    let return_schema = match &ep.response {
        WireType::Unit => "undefined".to_string(),
        wt => wire_type_to_zod(wt),
    };

    if ep.params.is_empty() {
        if is_query {
            return format!(
                "/** @query `{name}` → `{path}` (GET) */\nexport async function {name}(init?: RequestInit): Promise<{return_ts}> {{\n  return $get<{return_ts}>(\"{path}\", {return_schema}, undefined, init);\n}}\n\n"
            );
        }
        return format!(
            "/** Server fn `{name}` → `{path}` (POST) */\nexport async function {name}(init?: RequestInit): Promise<{return_ts}> {{\n  return $post<{return_ts}>(\"{path}\", {return_schema}, {{}}, init);\n}}\n\n"
        );
    }

    let fields: Vec<String> = ep
        .params
        .iter()
        .map(|f| {
            let ts_ty = wire_type_to_ts(&f.ty);
            if f.optional {
                format!("{}?: {}", f.name, ts_ty)
            } else {
                format!("{}: {}", f.name, ts_ty)
            }
        })
        .collect();
    let arg_type = fields.join(", ");
    let body_obj = ep
        .params
        .iter()
        .map(|f| format!("{}: args.{}", f.name, f.name))
        .collect::<Vec<_>>()
        .join(", ");

    if is_query {
        format!(
            "/** @query `{name}` → `{path}` (GET) */\nexport async function {name}(args: {{ {arg_type} }}, init?: RequestInit): Promise<{return_ts}> {{\n  return $get<{return_ts}>(\"{path}\", {return_schema}, {{ {body_obj} }}, init);\n}}\n\n"
        )
    } else {
        format!(
            "/** Server fn `{name}` → `{path}` (POST) */\nexport async function {name}(args: {{ {arg_type} }}, init?: RequestInit): Promise<{return_ts}> {{\n  return $post<{return_ts}>(\"{path}\", {return_schema}, {{ {body_obj} }}, init);\n}}\n\n"
        )
    }
}
