use crate::policy::SecretPolicy;
use crate::spec::ids::SecretId;
use crate::spec::types::*;

pub const SPECS_LLM: &[SecretSpec] = &[
    SecretSpec {
        id: SecretId::GeminiApiKey,
        canonical_env: "GEMINI_API_KEY",
        aliases: &["VOX_GEMINI_API_KEY"],
        deprecated_aliases: &["GOOGLE_AI_STUDIO_KEY"],
        backend_key: None,
        auth_registry: Some("google"),
        policy: SecretPolicy::optional_skip(),
        remediation: "Run `vox clavis set google <token>` or set GEMINI_API_KEY. Required if VOX_GEMINI_ROUTE_POLICY=google_direct_only.",
        scope_description: "Google Gemini API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::OpenRouterApiKey,
        canonical_env: "OPENROUTER_API_KEY",
        aliases: &["VOX_OPENROUTER_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: Some("openrouter"),
        policy: SecretPolicy::required_fail(),
        remediation: "Run `vox clavis set openrouter <token>` or set OPENROUTER_API_KEY.",
        scope_description: "OpenRouter API key for unified LLM access.",
    },
    SecretSpec {
        id: SecretId::OpenRouterModel,
        canonical_env: "OPENROUTER_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "OpenRouter model identifier (e.g. anthropic/claude-3.5-sonnet).",
        scope_description: "Default model identifier for OpenRouter.",
    },
    SecretSpec {
        id: SecretId::OpenaiApiKey,
        canonical_env: "OPENAI_API_KEY",
        aliases: &["VOX_OPENAI_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set OPENAI_API_KEY when OpenAI routes are enabled.",
        scope_description: "OpenAI API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::AnthropicApiKey,
        canonical_env: "ANTHROPIC_API_KEY",
        aliases: &["VOX_ANTHROPIC_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set ANTHROPIC_API_KEY when Anthropic routes are enabled.",
        scope_description: "Anthropic API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::GroqApiKey,
        canonical_env: "GROQ_API_KEY",
        aliases: &["VOX_GROQ_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set GROQ_API_KEY when Groq routes are enabled.",
        scope_description: "Groq API key for LPU-accelerated inference.",
    },
    SecretSpec {
        id: SecretId::MistralApiKey,
        canonical_env: "MISTRAL_API_KEY",
        aliases: &["VOX_MISTRAL_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set MISTRAL_API_KEY when Mistral routes are enabled.",
        scope_description: "Mistral API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::DeepSeekApiKey,
        canonical_env: "DEEPSEEK_API_KEY",
        aliases: &["VOX_DEEPSEEK_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set DEEPSEEK_API_KEY when DeepSeek routes are enabled.",
        scope_description: "DeepSeek API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::SambaNovaApiKey,
        canonical_env: "SAMBANOVA_API_KEY",
        aliases: &["VOX_SAMBANOVA_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set SAMBANOVA_API_KEY when SambaNova routes are enabled.",
        scope_description: "SambaNova API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::HuggingFaceToken,
        canonical_env: "HF_TOKEN",
        aliases: &["VOX_HF_TOKEN"],
        deprecated_aliases: &["HUGGING_FACE_HUB_TOKEN"],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set HF_TOKEN if Hugging Face routes are needed.",
        scope_description: "Hugging Face Hub token for private model access.",
    },
    SecretSpec {
        id: SecretId::OllamaUrl,
        canonical_env: "OLLAMA_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Ollama instance root URL.",
        scope_description: "URL for local Ollama API.",
    },
    SecretSpec {
        id: SecretId::OllamaModel,
        canonical_env: "OLLAMA_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Ollama model tag (e.g. codellama).",
        scope_description: "Default model tag for Ollama.",
    },
    SecretSpec {
        id: SecretId::TogetherApiKey,
        canonical_env: "TOGETHER_API_KEY",
        aliases: &["VOX_TOGETHER_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set TOGETHER_API_KEY for Together training flows.",
        scope_description: "Together AI API key for training and inference.",
    },
    SecretSpec {
        id: SecretId::CustomOpenaiApiKey,
        canonical_env: "CUSTOM_OPENAI_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set CUSTOM_OPENAI_API_KEY for custom OpenAI endpoints.",
        scope_description: "Custom OpenAI API key.",
    },
    SecretSpec {
        id: SecretId::V0ApiKey,
        canonical_env: "V0_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set V0_API_KEY for v0.dev access.",
        scope_description: "v0 API key.",
    },
    SecretSpec {
        id: SecretId::OpenClawToken,
        canonical_env: "OPENCLAW_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set OPENCLAW_TOKEN for OpenClaw access.",
        scope_description: "OpenClaw token.",
    },
    SecretSpec {
        id: SecretId::VoxRunpodApiKey,
        canonical_env: "RUNPOD_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set RUNPOD_API_KEY for RunPod GPU access.",
        scope_description: "RunPod API key.",
    },
    SecretSpec {
        id: SecretId::VoxVastApiKey,
        canonical_env: "VAST_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VAST_API_KEY for Vast.ai GPU access.",
        scope_description: "Vast.ai API key.",
    },
    SecretSpec {
        id: SecretId::CerebrasApiKey,
        canonical_env: "CEREBRAS_API_KEY",
        aliases: &["VOX_CEREBRAS_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set CEREBRAS_API_KEY for Cerebras inference.",
        scope_description: "Cerebras API key.",
    },
    SecretSpec {
        id: SecretId::VoxAnthropicDirect,
        canonical_env: "VOX_ANTHROPIC_DIRECT",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Force direct Anthropic API usage bypassing OpenRouter.",
        scope_description: "Anthropic direct mode flag.",
    },
    SecretSpec {
        id: SecretId::VoxOpenrouterHttpReferer,
        canonical_env: "OPENROUTER_HTTP_REFERER",
        aliases: &["VOX_OPENROUTER_HTTP_REFERER"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "HTTP Referer for OpenRouter ranking.",
        scope_description: "OpenRouter referer.",
    },
    SecretSpec {
        id: SecretId::VoxOpenrouterAppTitle,
        canonical_env: "OPENROUTER_APP_TITLE",
        aliases: &["VOX_OPENROUTER_APP_TITLE"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "App Title for OpenRouter ranking.",
        scope_description: "OpenRouter app title.",
    },
    SecretSpec {
        id: SecretId::VoxOpenrouterRouteHint,
        canonical_env: "OPENROUTER_ROUTE_HINT",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Route preference hint for OpenRouter.",
        scope_description: "OpenRouter route hint.",
    },
    SecretSpec {
        id: SecretId::VoxOllamaHost,
        canonical_env: "OLLAMA_HOST",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override Ollama host address.",
        scope_description: "Ollama host override.",
    },
    SecretSpec {
        id: SecretId::VoxGroqChatCompletionsUrl,
        canonical_env: "VOX_GROQ_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override Groq chat completions URL.",
        scope_description: "Groq API URL.",
    },
    SecretSpec {
        id: SecretId::VoxCerebrasChatCompletionsUrl,
        canonical_env: "VOX_CEREBRAS_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override Cerebras chat completions URL.",
        scope_description: "Cerebras API URL.",
    },
    SecretSpec {
        id: SecretId::VoxMistralChatCompletionsUrl,
        canonical_env: "VOX_MISTRAL_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override Mistral chat completions URL.",
        scope_description: "Mistral API URL.",
    },
    SecretSpec {
        id: SecretId::VoxDeepseekChatCompletionsUrl,
        canonical_env: "VOX_DEEPSEEK_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override DeepSeek chat completions URL.",
        scope_description: "DeepSeek API URL.",
    },
    SecretSpec {
        id: SecretId::VoxSambanovaChatCompletionsUrl,
        canonical_env: "VOX_SAMBANOVA_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override SambaNova chat completions URL.",
        scope_description: "SambaNova API URL.",
    },
    SecretSpec {
        id: SecretId::VoxAnthropicChatCompletionsUrl,
        canonical_env: "VOX_ANTHROPIC_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override Anthropic chat completions URL.",
        scope_description: "Anthropic API URL.",
    },
];
