use crate::spec::types::*;
use crate::spec::ids::SecretId;
use crate::policy::SecretPolicy;

pub const SPECS_MESH: &[SecretSpec] = &[
    SecretSpec {
        id: SecretId::VoxMeshToken,
        canonical_env: "VOX_MESH_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Run `vox populi up` or set VOX_MESH_TOKEN for mesh auth.",
        scope_description: "General-purpose bearer token for mesh operations.",
    },
    SecretSpec {
        id: SecretId::VoxMeshJwtHmacSecret,
        canonical_env: "VOX_MESH_JWT_HMAC_SECRET",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::required_fail(),
        remediation: "Required API secret for JWT mesh bearer tokens.",
        scope_description: "HMAC secret for signing and verifying mesh JWTs.",
    },
    SecretSpec {
        id: SecretId::VoxMeshWorkerToken,
        canonical_env: "VOX_MESH_WORKER_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Worker token for mesh authentication.",
        scope_description: "Mesh worker token.",
    },
    SecretSpec {
        id: SecretId::VoxMeshSubmitterToken,
        canonical_env: "VOX_MESH_SUBMITTER_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Submitter token for mesh authentication.",
        scope_description: "Mesh submitter token.",
    },
    SecretSpec {
        id: SecretId::VoxMeshAdminToken,
        canonical_env: "VOX_MESH_ADMIN_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Admin token for mesh authentication.",
        scope_description: "Mesh admin token.",
    },
    SecretSpec {
        id: SecretId::VoxMeshWorkerResultVerifyKey,
        canonical_env: "VOX_MESH_WORKER_RESULT_VERIFY_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Verification key for mesh worker results.",
        scope_description: "Mesh worker result verify key.",
    },
    SecretSpec {
        id: SecretId::VoxMeshHttpJoin,
        canonical_env: "VOX_MESH_HTTP_JOIN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Join mesh via HTTP.",
        scope_description: "Mesh HTTP join flag.",
    },
    SecretSpec {
        id: SecretId::VoxMeshHttpHeartbeatSecs,
        canonical_env: "VOX_MESH_HTTP_HEARTBEAT_SECS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Heartbeat interval for HTTP mesh.",
        scope_description: "Mesh HTTP heartbeat interval.",
    },
];
