use crate::spec::types::*;
use crate::spec::ids::SecretId;
use crate::policy::SecretPolicy;

pub const SPECS_PLATFORM: &[SecretSpec] = &[
    SecretSpec {
        id: SecretId::VoxCostPreference,
        canonical_env: "VOX_COST_PREFERENCE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_COST_PREFERENCE.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxDogfoodTracePath,
        canonical_env: "VOX_DOGFOOD_TRACE_PATH",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_DOGFOOD_TRACE_PATH.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::ForgeToken,
        canonical_env: "FORGE_TOKEN",
        aliases: &["VOX_FORGE_TOKEN", "GITHUB_TOKEN", "GITLAB_TOKEN"],
        deprecated_aliases: &["GH_TOKEN", "GL_TOKEN"],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set FORGE_TOKEN (or GITHUB_TOKEN/GITLAB_TOKEN, matched in that order) for forge API flows.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::V0ApiKey,
        canonical_env: "V0_API_KEY",
        aliases: &["VOX_V0_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set V0_API_KEY for island generation against v0.dev.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::OpenClawToken,
        canonical_env: "VOX_OPENCLAW_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_OPENCLAW_TOKEN for protected OpenClaw gateway operations.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxOpenClawUrl,
        canonical_env: "VOX_OPENCLAW_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "HTTP gateway URL for the OpenClaw skill registry.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxOpenClawWsUrl,
        canonical_env: "VOX_OPENCLAW_WS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "WebSocket gateway URL for OpenClaw control plane.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxApiKey,
        canonical_env: "VOX_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_API_KEY to require API key auth on runtime servers.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxBearerToken,
        canonical_env: "VOX_BEARER_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_BEARER_TOKEN to require bearer auth on runtime servers.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxDbUrl,
        canonical_env: "VOX_DB_URL",
        aliases: &[],
        deprecated_aliases: &["VOX_TURSO_URL", "TURSO_URL"],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_DB_URL for remote DB use.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxDbToken,
        canonical_env: "VOX_DB_TOKEN",
        aliases: &[],
        deprecated_aliases: &["VOX_TURSO_TOKEN", "TURSO_AUTH_TOKEN"],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_DB_TOKEN for remote DB use.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::WebhookIngressToken,
        canonical_env: "VOX_WEBHOOK_INGRESS_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_WEBHOOK_INGRESS_TOKEN to require bearer auth on the webhook ingress server.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::WebhookSigningSecret,
        canonical_env: "VOX_WEBHOOK_SIGNING_SECRET",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::required_fail(),
        remediation: "Set VOX_WEBHOOK_SIGNING_SECRET to enable HMAC verification for generic inbound webhook sources.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::TavilyApiKey,
        canonical_env: "TAVILY_API_KEY",
        aliases: &["VOX_TAVILY_API_KEY"],
        deprecated_aliases: &["X_TAVILY_API_KEY"],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Tavily web search API key (https://tavily.com)",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::TavilyProject,
        canonical_env: "TAVILY_PROJECT",
        aliases: &["VOX_TAVILY_PROJECT"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Optional Tavily project ID for usage tracking (X-Project-ID header)",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxSyndicationTemplateProfileEnabled,
        canonical_env: "VOX_SYNDICATION_TEMPLATE_PROFILE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable use of template_profile keys in syndication metadata.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::TavilyProject,
        canonical_env: "TAVILY_PROJECT_ID",
        aliases: &["VOX_TAVILY_PROJECT_ID"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set TAVILY_PROJECT_ID for usage tracking.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxGenericApiKey,
        canonical_env: "API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Generic legacy API_KEY credential.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxProviderDailyLimitDefault,
        canonical_env: "VOX_PROVIDER_DAILY_LIMIT_DEFAULT",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Default daily USD limit for all providers.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxProviderLimitProviders,
        canonical_env: "VOX_PROVIDER_LIMIT_PROVIDERS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Comma-separated list of providers subject to hard limits.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxProviderDailyLimitsFile,
        canonical_env: "VOX_PROVIDER_DAILY_LIMITS_FILE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Path to a JSON file containing per-provider daily limits.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxProviderDailyLimitsJson,
        canonical_env: "VOX_PROVIDER_DAILY_LIMITS_JSON",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Inline JSON string containing per-provider daily limits.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxWorkspaceRoot,
        canonical_env: "VOX_WORKSPACE_ROOT",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Path to the vox workspace root (ADR-001).",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxMensExperimentalOptimizer,
        canonical_env: "VOX_MENS_EXPERIMENTAL_OPTIMIZER",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable experimental optimizer features in MENS.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxCloudPriceTtl,
        canonical_env: "VOX_CLOUD_PRICE_TTL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Time-to-live for cached cloud provider price data.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxCloudImage,
        canonical_env: "VOX_CLOUD_IMAGE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Default container image for cloud-based jobs.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxCloudMaxRuntime,
        canonical_env: "VOX_CLOUD_MAX_RUNTIME",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Maximum runtime for cloud-based jobs.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxGpuModel,
        canonical_env: "VOX_GPU_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Target GPU model for capacity selection.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxGpuVramMb,
        canonical_env: "VOX_GPU_VRAM_MB",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Target GPU VRAM in megabytes.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxBaseModel,
        canonical_env: "VOX_BASE_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Canonical model name to use as base for training.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxTrainProfile,
        canonical_env: "VOX_TRAIN_PROFILE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Training profile (e.g. low-vram, performance).",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxQwen35NativeCutover,
        canonical_env: "VOX_QWEN35_NATIVE_CUTOVER",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable native cutover for Qwen 3.5 models (default: enforced).",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxAllowQwen2Native,
        canonical_env: "VOX_ALLOW_QWEN2_NATIVE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Allow native execution for Qwen 2 models (DEPRECATED: use qwen35 instead).",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxMensTrainJsonlStrict,
        canonical_env: "VOX_MENS_TRAIN_JSON_STRICT",
        aliases: &["VOX_MENS_TRAIN_JSONL_STRICT"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Require strict JSONL validation for training data.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxVramOverrideGb,
        canonical_env: "VOX_VRAM_OVERRIDE_GB",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Manual override for GPU VRAM availability in gigabytes.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxCandleDevice,
        canonical_env: "VOX_CANDLE_DEVICE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Force training backend device (candle_qlora: cpu, cuda, metal).",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxRepositoryRoot,
        canonical_env: "VOX_REPOSITORY_ROOT",
        aliases: &["VOX_REPO_ROOT"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Root directory of the active Vox repository.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxReviewRepositoryId,
        canonical_env: "VOX_REVIEW_REPOSITORY_ID",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Repository ID for review grounding.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxRegistryToken,
        canonical_env: "VOX_REGISTRY_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Bearer token for private registry access.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxPmAllowGitUnverified,
        canonical_env: "VOX_PM_ALLOW_GIT_UNVERIFIED",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Allow unverified git modules in PM.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxCoderabbitGithubPerPage,
        canonical_env: "CODERABBIT_GITHUB_PER_PAGE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Items per page for CodeRabbit GitHub API.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxScriptCacheMaxEntries,
        canonical_env: "VOX_SCRIPT_CACHE_MAX_ENTRIES",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Max entries in runtime script cache.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxScriptCacheMaxSizeMb,
        canonical_env: "VOX_SCRIPT_CACHE_MAX_SIZE_MB",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Max size of runtime script cache in MB.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxOpenclawSidecarDisable,
        canonical_env: "VOX_OPENCLAW_SIDECAR_DISABLE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Disable OpenClaw sidecar installation.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxWebTanstackStart,
        canonical_env: "VOX_WEB_TANSTACK_START",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable TanStack Start integration in local web server.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxSyndicationTemplateProfile,
        canonical_env: "VOX_SYNDICATION_TEMPLATE_PROFILE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable syndication template profile (1/true to enable).",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxGithubSha,
        canonical_env: "GITHUB_SHA",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Standard GitHub SHA environment variable.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxEmitExpressServer,
        canonical_env: "VOX_EMIT_EXPRESS_SERVER",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable optional Express server emission in TypeScript codegen.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxJsonOutput,
        canonical_env: "VOX_JSON_OUTPUT",
        aliases: &["VOX_CLI_JSON"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Force CLI to emit JSON instead of human-readable text.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxMensScorecardMaxTokens,
        canonical_env: "VOX_MENS_SCORECARD_MAX_TOKENS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Max tokens for scorecard evaluation.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxOpenclawSidecarExpectVersion,
        canonical_env: "VOX_OPENCLAW_SIDECAR_EXPECT_VERSION",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Expected version of OpenClaw sidecar.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxCliGlobalJson,
        canonical_env: "VOX_CLI_GLOBAL_JSON",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable global JSON output for CLI commands.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxScriptRelease,
        canonical_env: "VOX_SCRIPT_RELEASE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Compile scripts in release mode.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxCargoBin,
        canonical_env: "VOX_CARGO_BIN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Path to cargo binary for script compilation.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::SkipCudaFeatureCheck,
        canonical_env: "SKIP_CUDA_FEATURE_CHECK",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Bypass CUDA feature availability check.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxSecretGuardGitRef,
        canonical_env: "VOX_SECRET_GUARD_GIT_REF",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Git ref for CI secret-env-guard to check against.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxTelemetryUploadUrl,
        canonical_env: "VOX_TELEMETRY_UPLOAD_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Telemetry upload URL.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxTelemetryUploadToken,
        canonical_env: "VOX_TELEMETRY_UPLOAD_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Telemetry upload token.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxSearchQdrantApiKey,
        canonical_env: "VOX_SEARCH_QDRANT_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Qdrant API key for search.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxMcpHttpBearerToken,
        canonical_env: "VOX_MCP_HTTP_BEARER_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Bearer token for MCP HTTP server.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxMcpHttpReadBearerToken,
        canonical_env: "VOX_MCP_HTTP_READ_BEARER_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Read-only bearer token for MCP HTTP server.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxGithubSha,
        canonical_env: "GITHUB_SHA",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "GitHub SHA.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::SkipCudaFeatureCheck,
        canonical_env: "SKIP_CUDA_FEATURE_CHECK",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Skip CUDA feature check.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxCargoBin,
        canonical_env: "VOX_CARGO_BIN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Path to vox-cargo binary.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxCliGlobalJson,
        canonical_env: "VOX_CLI_GLOBAL_JSON",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Global JSON output flag for CLI.",
        scope_description: "",
    },
];
