use crate::spec::types::*;
use crate::spec::ids::SecretId;
use crate::policy::SecretPolicy;

pub const SPECS_SOCIAL: &[SecretSpec] = &[
    SecretSpec {
        id: SecretId::VoxNewsTwitterBearer,
        canonical_env: "VOX_NEWS_TWITTER_TOKEN",
        aliases: &["VOX_SOCIAL_TWITTER_TOKEN"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Twitter API bearer token (v2).",
        scope_description: "Twitter token.",
    },
    SecretSpec {
        id: SecretId::VoxSocialDiscordWebhook,
        canonical_env: "VOX_SOCIAL_DISCORD_WEBHOOK",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Discord webhook URL for news announcements.",
        scope_description: "Discord webhook for news.",
    },
    SecretSpec {
        id: SecretId::VoxSocialBlueskyHandle,
        canonical_env: "VOX_SOCIAL_BLUESKY_HANDLE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Bluesky handle for syndication.",
        scope_description: "Bluesky handle.",
    },
    SecretSpec {
        id: SecretId::VoxSocialBlueskyPassword,
        canonical_env: "VOX_SOCIAL_BLUESKY_PASSWORD",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Bluesky password/app-password.",
        scope_description: "Bluesky password.",
    },
    SecretSpec {
        id: SecretId::VoxSocialRedditClientId,
        canonical_env: "VOX_SOCIAL_REDDIT_CLIENT_ID",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Reddit API client ID.",
        scope_description: "Reddit client id.",
    },
    SecretSpec {
        id: SecretId::VoxSocialRedditClientSecret,
        canonical_env: "VOX_SOCIAL_REDDIT_CLIENT_SECRET",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Reddit API client secret.",
        scope_description: "Reddit secret.",
    },
    SecretSpec {
        id: SecretId::VoxSocialRedditRefreshToken,
        canonical_env: "VOX_SOCIAL_REDDIT_REFRESH_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Reddit API refresh token.",
        scope_description: "Reddit refresh token.",
    },
    SecretSpec {
        id: SecretId::VoxSocialRedditUserAgent,
        canonical_env: "VOX_SOCIAL_REDDIT_USER_AGENT",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Reddit API user agent string.",
        scope_description: "Reddit user agent.",
    },
    SecretSpec {
        id: SecretId::VoxSocialYoutubeClientId,
        canonical_env: "VOX_SOCIAL_YOUTUBE_CLIENT_ID",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "YouTube API client ID.",
        scope_description: "YouTube client id.",
    },
    SecretSpec {
        id: SecretId::VoxSocialYoutubeClientSecret,
        canonical_env: "VOX_SOCIAL_YOUTUBE_CLIENT_SECRET",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "YouTube API client secret.",
        scope_description: "YouTube secret.",
    },
    SecretSpec {
        id: SecretId::VoxSocialYoutubeRefreshToken,
        canonical_env: "VOX_SOCIAL_YOUTUBE_REFRESH_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "YouTube API refresh token.",
        scope_description: "YouTube refresh token.",
    },
    SecretSpec {
        id: SecretId::VoxSocialMastodonToken,
        canonical_env: "VOX_SOCIAL_MASTODON_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Mastodon access token.",
        scope_description: "Mastodon token.",
    },
    SecretSpec {
        id: SecretId::VoxSocialMastodonDomain,
        canonical_env: "VOX_SOCIAL_MASTODON_DOMAIN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Mastodon instance domain.",
        scope_description: "Mastodon domain.",
    },
    SecretSpec {
        id: SecretId::VoxSocialLinkedinAccessToken,
        canonical_env: "VOX_SOCIAL_LINKEDIN_ACCESS_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "LinkedIn API access token.",
        scope_description: "LinkedIn token.",
    },
    SecretSpec {
        id: SecretId::VoxNewsOpenCollectiveToken,
        canonical_env: "VOX_NEWS_OPENCOLLECTIVE_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "OpenCollective API token.",
        scope_description: "OpenCollective token.",
    },
    SecretSpec {
        id: SecretId::VoxSocialTwitterApiBase,
        canonical_env: "VOX_SOCIAL_TWITTER_API_BASE",
        aliases: &["VOX_NEWS_TWITTER_API_BASE"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Twitter API base URL override.",
        scope_description: "Twitter API base.",
    },
    SecretSpec {
        id: SecretId::VoxSocialLinkedinApiBase,
        canonical_env: "VOX_SOCIAL_LINKEDIN_API_BASE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "LinkedIn API base URL override.",
        scope_description: "LinkedIn API base.",
    },
    SecretSpec {
        id: SecretId::VoxSocialRedditApiBase,
        canonical_env: "VOX_SOCIAL_REDDIT_API_BASE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Reddit API base URL override.",
        scope_description: "Reddit API base.",
    },
    SecretSpec {
        id: SecretId::VoxNewsTwitterTextChunkMax,
        canonical_env: "VOX_NEWS_TWITTER_TEXT_CHUNK_MAX",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Maximum characters per Twitter chunk.",
        scope_description: "Twitter chunk max.",
    },
    SecretSpec {
        id: SecretId::VoxNewsTwitterTruncationSuffix,
        canonical_env: "VOX_NEWS_TWITTER_TRUNCATION_SUFFIX",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Suffix for truncated tweets.",
        scope_description: "Twitter truncation suffix.",
    },
    SecretSpec {
        id: SecretId::VoxSocialTwitterSummaryMarginChars,
        canonical_env: "VOX_SOCIAL_TWITTER_SUMMARY_MARGIN_CHARS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Twitter summary margin characters.",
        scope_description: "Twitter summary margin.",
    },
    SecretSpec {
        id: SecretId::VoxSocialRedditSelfpostSummaryMax,
        canonical_env: "VOX_SOCIAL_REDDIT_SELFPOST_SUMMARY_MAX",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Reddit self-post summary character limit.",
        scope_description: "Reddit self-post summary max.",
    },
    SecretSpec {
        id: SecretId::VoxSocialHnMode,
        canonical_env: "VOX_SOCIAL_HN_MODE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Hacker News submission mode.",
        scope_description: "HN mode.",
    },
    SecretSpec {
        id: SecretId::VoxSocialYoutubeDefaultCategoryId,
        canonical_env: "VOX_SOCIAL_YOUTUBE_DEFAULT_CATEGORY_ID",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "YouTube default category ID.",
        scope_description: "YouTube category ID.",
    },
];
