use std::fs;
use std::path::PathBuf;
use sha2::{Digest, Sha256};

fn generate_code() -> String {
    r#"// DO NOT EDIT. This file is generated by `vox-jsonschema-util/examples/emit_agent_harness.rs`.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AgentHarnessSpec {
    pub schema_version: i64,
    pub harness_id: String,
    pub description: Option<String>,
    pub task_family: Option<String>,
    pub runtime_charter: String,
    pub subject: Subject,
    pub roles: Vec<Role>,
    pub stages: Vec<Stage>,
    pub contracts: Contracts,
    pub adapters: Option<Vec<Adapter>>,
    pub state: State,
    pub failure_taxonomy: Vec<FailureTaxonomy>,
    pub metadata: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Subject {
    pub repository_id: String,
    pub session_id: Option<String>,
    pub thread_id: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Role {
    pub role_id: String,
    pub prompt_purpose: String,
    pub responsibilities: Vec<String>,
    pub permission_mode: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Stage {
    pub stage_id: String,
    pub role_id: String,
    pub summary: String,
    pub input_artifacts: Option<Vec<String>>,
    pub output_artifacts: Option<Vec<String>>,
    pub completion_gate_ids: Option<Vec<String>>,
    pub failure_mode_codes: Option<Vec<String>>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Contracts {
    pub required_outputs: Vec<RequiredOutput>,
    pub completion_gates: Vec<CompletionGate>,
    pub max_attempts: Option<i64>,
    pub requires_artifact_backed_completion: bool,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RequiredOutput {
    pub artifact_id: String,
    pub kind: String,
    pub path_hint: Option<String>,
    pub required: bool,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CompletionGate {
    pub gate_id: String,
    pub description: String,
    pub evidence_required: Option<bool>,
    pub independent_verification: Option<bool>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Adapter {
    pub adapter_id: String,
    pub kind: String,
    pub description: String,
    pub target_ref: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct State {
    pub state_root: String,
    pub child_workspace_root: Option<String>,
    pub task_history_path: Option<String>,
    pub artifact_manifest_path: Option<String>,
    pub path_addressable: bool,
    pub compaction_stable: bool,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct FailureTaxonomy {
    pub code: String,
    pub description: String,
    pub retryable: Option<bool>,
    pub recovery_stage_id: Option<String>,
}
"#.to_string()
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let dry_run = args.iter().any(|a| a == "--dry-run");

    let code = generate_code();

    // Assuming we run from workspace root
    let root = std::env::current_dir().unwrap();
    let target_dir = root.join("crates/vox-orchestrator/src/generated");
    let target_file = target_dir.join("agent_harness.rs");

    if dry_run {
        println!("Dry run. Would write to {}:\n{}", target_file.display(), code);
        return;
    }

    fs::create_dir_all(&target_dir).unwrap();
    fs::write(&target_file, &code).unwrap();
    
    // Also create mod.rs
    let mod_file = target_dir.join("mod.rs");
    if !mod_file.exists() {
        fs::write(&mod_file, "pub mod agent_harness;\n").unwrap();
    }
    
    // Also update generated.manifest.sha256
    let sha256_file = target_dir.join("generated.manifest.sha256");
    let mut hasher = Sha256::new();
    hasher.update(code.as_bytes());
    let hash = format!("{:x}", hasher.finalize());
    fs::write(&sha256_file, format!("{}  agent_harness.rs\n", hash)).unwrap();
    
    println!("Wrote {}", target_file.display());
}
