//! TanStack Start / router embedded sources.

/// TanStack Start root route (`src/routes/__root.tsx`).
pub fn tanstack_start_root_tsx() -> &'static str {
    r#"/// <reference types="vite/client" />
import "../index.css";
import type { ReactNode } from "react";
import {
  HeadContent,
  Outlet,
  Scripts,
  createRootRoute,
} from "@tanstack/react-router";
import { VoxQueryProvider } from "../generated/vox-tanstack-query";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1, viewport-fit=cover" },
      { name: "color-scheme", content: "dark light" },
      { title: "Vox App" },
    ],
  }),
  component: RootComponent,
});

function RootComponent() {
  return (
    <VoxQueryProvider>
      <RootDocument>
        <Outlet />
      </RootDocument>
    </VoxQueryProvider>
  );
}

function RootDocument({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}
"#
}

/// Index file route when generated output included **`App.tsx`** (legacy smoke fixtures only).
///
/// Default codegen emits **`routes.manifest.ts`** and component TSX; the Start scaffold still seeds
/// a `/` file route that mounts `generated/App` when that file is present.
pub fn tanstack_start_index_for_app() -> &'static str {
    r#"import { createFileRoute } from "@tanstack/react-router";
import App from "../generated/App";

export const Route = createFileRoute("/")({
  component: App,
});
"#
}

/// Index file route when there is no `App.tsx` — mount the primary `@component` export.
pub fn tanstack_start_index_for_component(component_name: &str) -> String {
    format!(
        r#"import {{ createFileRoute }} from "@tanstack/react-router";
import {{ {component_name} }} from "../generated/{component_name}";

export const Route = createFileRoute("/")({{
  component: {component_name},
}});
"#
    )
}

/// `src/router.tsx` for TanStack Start (imports generated `routeTree.gen.ts`).
pub fn tanstack_start_router_tsx() -> &'static str {
    r#"import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

export function getRouter() {
  return createRouter({
    routeTree,
    scrollRestoration: true,
  });
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
"#
}

/// Seed `routeTree.gen.ts` for a single `/` file route before **`pnpm run routes:gen`** refreshes it.
pub fn tanstack_start_route_tree_gen() -> &'static str {
    r#"/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// After editing `src/routes/**`, run `pnpm run routes:gen` (`tsr` from `@tanstack/router-cli`) to regenerate.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/";
  id: "__root__" | "/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes();

import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
"#
}

/// Strict `tsconfig.json` suitable for Vite + React.
pub fn tsconfig_json() -> &'static str {
    r#"{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noFallthroughCasesInSwitch": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["src"]
}
"#
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tsconfig_json_includes_at_alias_to_src() {
        let t = tsconfig_json();
        assert!(t.contains("\"baseUrl\": \".\""), "{t}");
        assert!(t.contains("\"@/*\": [\"./src/*\"]"), "{t}");
    }

    #[test]
    fn tanstack_start_root_includes_mobile_viewport_contract() {
        let root = tanstack_start_root_tsx();
        assert!(root.contains("{ name: \"viewport\""));
        assert!(root.contains("width=device-width, initial-scale=1, viewport-fit=cover"));
        assert!(root.contains("{ name: \"color-scheme\", content: \"dark light\" }"));
    }
}
