#![allow(clippy::new_without_default)]
#![allow(clippy::should_implement_trait)]

use crate::resolver::SemVer;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

/// Represents the `vox.lock` lockfile.
/// Records exact resolved versions and content hashes for reproducible installs.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Lockfile {
    /// Lockfile format version for forward compatibility.
    pub version: u32,
    /// Resolved packages, keyed by name.
    pub packages: BTreeMap<String, LockedPackage>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedPackage {
    pub version: String,
    pub content_hash: String,
    #[serde(default)]
    pub source: PackageSource,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub skills: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum PackageSource {
    #[default]
    Registry,
    Path(String),
    Git {
        url: String,
        #[serde(default)]
        rev: Option<String>,
    },
}

fn parse_lockfile_source(v: &toml::Value) -> PackageSource {
    match v {
        toml::Value::String(s) if s == "registry" => PackageSource::Registry,
        toml::Value::Table(t) => {
            if let Some(p) = t.get("path").and_then(|x| x.as_str()) {
                return PackageSource::Path(p.replace('\\', "/"));
            }
            if let Some(url) = t.get("git").and_then(|x| x.as_str()) {
                let rev = t.get("rev").and_then(|x| x.as_str()).map(str::to_string);
                return PackageSource::Git {
                    url: url.to_string(),
                    rev,
                };
            }
            PackageSource::Registry
        }
        _ => PackageSource::Registry,
    }
}

impl Lockfile {
    /// Create a new empty lockfile.
    pub fn new() -> Self {
        Self {
            version: 1,
            packages: BTreeMap::new(),
        }
    }

    /// Add or update a resolved package.
    pub fn add(
        &mut self,
        name: &str,
        version: &SemVer,
        content_hash: &str,
        source: PackageSource,
        dependencies: Vec<String>,
        skills: Vec<String>,
    ) {
        self.packages.insert(
            name.to_string(),
            LockedPackage {
                version: version.to_string(),
                content_hash: content_hash.to_string(),
                source,
                dependencies,
                skills,
            },
        );
    }

    /// Check if a package is locked at a specific version.
    pub fn is_locked(&self, name: &str, version: &SemVer) -> bool {
        self.packages
            .get(name)
            .map(|p| p.version == version.to_string())
            .unwrap_or(false)
    }

    /// Get the locked version of a package.
    pub fn get_locked_version(&self, name: &str) -> Option<SemVer> {
        self.packages
            .get(name)
            .and_then(|p| SemVer::parse(&p.version).ok())
    }

    /// Remove a package from the lockfile.
    pub fn remove(&mut self, name: &str) -> bool {
        self.packages.remove(name).is_some()
    }

    /// Serialize to TOML string.
    pub fn to_toml_string(&self) -> Result<String, LockfileError> {
        let mut output = String::new();
        output.push_str("# This file is auto-generated by VoxPM. Do not edit manually.\n\n");
        output.push_str(&format!("version = {}\n\n", self.version));

        for (name, pkg) in &self.packages {
            output.push_str("[[package]]\n");
            output.push_str(&format!("name = \"{name}\"\n"));
            output.push_str(&format!("version = \"{}\"\n", pkg.version));
            output.push_str(&format!("content_hash = \"{}\"\n", pkg.content_hash));

            match &pkg.source {
                PackageSource::Registry => {
                    output.push_str("source = \"registry\"\n");
                }
                PackageSource::Path(p) => {
                    output.push_str(&format!("source = {{ path = \"{}\" }}\n", p));
                }
                PackageSource::Git { url, rev } => {
                    if let Some(rev) = rev {
                        output.push_str(&format!(
                            "source = {{ git = \"{}\", rev = \"{}\" }}\n",
                            url, rev
                        ));
                    } else {
                        output.push_str(&format!("source = {{ git = \"{}\" }}\n", url));
                    }
                }
            }

            if !pkg.dependencies.is_empty() {
                output.push_str(&format!(
                    "dependencies = [{}]\n",
                    pkg.dependencies
                        .iter()
                        .map(|d| format!("\"{d}\""))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            if !pkg.skills.is_empty() {
                output.push_str(&format!(
                    "skills = [{}]\n",
                    pkg.skills
                        .iter()
                        .map(|s| format!("\"{s}\""))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            output.push('\n');
        }

        Ok(output)
    }

    /// Load from a lockfile path.
    pub fn load(path: &Path) -> Result<Self, LockfileError> {
        let content = std::fs::read_to_string(path).map_err(LockfileError::Io)?;
        Self::from_str(&content)
    }

    /// Parse from a TOML string. For simplicity, uses serde_json round-trip.
    pub fn from_str(content: &str) -> Result<Self, LockfileError> {
        // Parse the TOML as a toml::Value, then reconstruct the lockfile.
        let table: toml::Value = content.parse().map_err(LockfileError::Parse)?;

        let version = table
            .get("version")
            .and_then(|v| v.as_integer())
            .unwrap_or(1) as u32;

        let mut packages = BTreeMap::new();
        if let Some(pkg_array) = table.get("package").and_then(|v| v.as_array()) {
            for pkg_val in pkg_array {
                let name = pkg_val
                    .get("name")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                let pkg_version = pkg_val
                    .get("version")
                    .and_then(|v| v.as_str())
                    .unwrap_or("0.0.0")
                    .to_string();
                let content_hash = pkg_val
                    .get("content_hash")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                let deps: Vec<String> = pkg_val
                    .get("dependencies")
                    .and_then(|v| v.as_array())
                    .map(|arr| {
                        arr.iter()
                            .filter_map(|v| v.as_str().map(|s| s.to_string()))
                            .collect()
                    })
                    .unwrap_or_default();

                let skills: Vec<String> = pkg_val
                    .get("skills")
                    .and_then(|v| v.as_array())
                    .map(|arr| {
                        arr.iter()
                            .filter_map(|v| v.as_str().map(|s| s.to_string()))
                            .collect()
                    })
                    .unwrap_or_default();

                let source = pkg_val
                    .get("source")
                    .map(parse_lockfile_source)
                    .unwrap_or(PackageSource::Registry);

                packages.insert(
                    name,
                    LockedPackage {
                        version: pkg_version,
                        content_hash,
                        source,
                        dependencies: deps,
                        skills,
                    },
                );
            }
        }

        Ok(Self { version, packages })
    }

    /// Save to a file path.
    pub fn save(&self, path: &Path) -> Result<(), LockfileError> {
        let content = self.to_toml_string()?;
        std::fs::write(path, content).map_err(LockfileError::Io)
    }
}

#[derive(Debug)]
pub enum LockfileError {
    Io(std::io::Error),
    Parse(toml::de::Error),
}

impl std::fmt::Display for LockfileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(e) => write!(f, "I/O error: {e}"),
            Self::Parse(e) => write!(f, "Parse error: {e}"),
        }
    }
}

impl std::error::Error for LockfileError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lockfile_add_and_query() {
        let mut lf = Lockfile::new();
        let v = SemVer::parse("1.2.3").unwrap();
        lf.add("foo", &v, "abc123", PackageSource::Registry, vec![], vec![]);

        assert!(lf.is_locked("foo", &v));
        assert!(!lf.is_locked("foo", &SemVer::parse("1.2.4").unwrap()));
        assert!(!lf.is_locked("bar", &v));
    }

    #[test]
    fn test_lockfile_get_version() {
        let mut lf = Lockfile::new();
        let v = SemVer::parse("2.0.0").unwrap();
        lf.add(
            "core",
            &v,
            "hash",
            PackageSource::Registry,
            vec!["utils".into()],
            vec![],
        );

        let locked = lf.get_locked_version("core").unwrap();
        assert_eq!(locked, v);
        assert!(lf.get_locked_version("missing").is_none());
    }

    #[test]
    fn test_lockfile_remove() {
        let mut lf = Lockfile::new();
        let v = SemVer::parse("1.0.0").unwrap();
        lf.add("foo", &v, "hash", PackageSource::Registry, vec![], vec![]);

        assert!(lf.remove("foo"));
        assert!(!lf.remove("foo"));
        assert!(lf.packages.is_empty());
    }

    #[test]
    fn test_lockfile_serialize() {
        let mut lf = Lockfile::new();
        let v = SemVer::parse("1.0.0").unwrap();
        lf.add(
            "foo",
            &v,
            "abc",
            PackageSource::Registry,
            vec!["bar".into()],
            vec![],
        );
        lf.add(
            "bar",
            &SemVer::parse("0.5.0").unwrap(),
            "def",
            PackageSource::Registry,
            vec![],
            vec![],
        );

        let toml_str = lf.to_toml_string().unwrap();
        assert!(toml_str.contains("name = \"foo\""));
        assert!(toml_str.contains("name = \"bar\""));
        assert!(toml_str.contains("content_hash = \"abc\""));
        assert!(toml_str.contains("\"bar\""));
    }

    #[test]
    fn test_lockfile_path_source_round_trips_through_toml() {
        let mut lf = Lockfile::new();
        let v = SemVer::parse("0.1.0").unwrap();
        lf.add(
            "sidecar",
            &v,
            "deadbeef",
            PackageSource::Path("../sidecar".into()),
            vec![],
            vec![],
        );
        let s = lf.to_toml_string().unwrap();
        let again = Lockfile::from_str(&s).unwrap();
        match again.packages.get("sidecar").map(|p| &p.source) {
            Some(PackageSource::Path(p)) => assert_eq!(p, "../sidecar"),
            other => panic!("expected path source, got {other:?}"),
        }
    }
}
