//! Dockerfile and Compose file generation from environment specifications.
//!
//! This module replaces the hardcoded generation that previously lived in
//! `vox-codegen-ts/src/emitter/infra.rs`, making it reusable across both
//! TS and Rust codegen backends.

use serde::{Deserialize, Serialize};

/// Declarative specification for a container environment.
///
/// Maps directly to Vox `environment` declarations in user source code.
/// The codegen layer constructs an `EnvironmentSpec` from the AST node
/// and passes it here to generate a Dockerfile.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct EnvironmentSpec {
    /// Base image, e.g. `"node:22-alpine"`.
    pub base_image: String,
    /// System packages to install via the distro package manager.
    pub packages: Vec<String>,
    /// Environment variable key-value pairs.
    pub env_vars: Vec<(String, String)>,
    /// Ports to expose.
    pub exposed_ports: Vec<u16>,
    /// Volume mount points inside the container.
    pub volumes: Vec<String>,
    /// Working directory inside the container.
    pub workdir: Option<String>,
    /// Files/directories to copy into the container as `(src, dest)`.
    pub copy_instructions: Vec<(String, String)>,
    /// RUN commands to execute during build.
    pub run_commands: Vec<String>,
    /// Default CMD for the container.
    pub cmd: Vec<String>,
    /// Default ENTRYPOINT for the container.
    pub entrypoint: Vec<String>,
}

/// Generate a Dockerfile string from an [`EnvironmentSpec`].
///
/// Produces an OCI-compatible Dockerfile that works with both Docker and
/// Podman.
pub fn generate_dockerfile_from_spec(spec: &EnvironmentSpec) -> String {
    let mut lines: Vec<String> = Vec::new();

    // Header
    lines.push("# Generated by Vox — OCI-compatible Dockerfile".to_string());
    lines.push(format!("FROM {}", spec.base_image));

    // Working directory
    if let Some(ref wd) = spec.workdir {
        lines.push(format!("WORKDIR {wd}"));
    }

    // System packages
    if !spec.packages.is_empty() {
        let pkg_list = spec.packages.join(" ");
        // Auto-detect package manager based on common base images
        if spec.base_image.contains("alpine") {
            lines.push(format!("RUN apk add --no-cache {pkg_list}"));
        } else {
            lines.push(format!(
                "RUN apt-get update && apt-get install -y {pkg_list} && rm -rf /var/lib/apt/lists/*"
            ));
        }
    }

    // Environment variables
    for (key, val) in &spec.env_vars {
        lines.push(format!("ENV {key}={val}"));
    }

    // Copy instructions
    for (src, dest) in &spec.copy_instructions {
        lines.push(format!("COPY {src} {dest}"));
    }

    // Run commands
    for cmd in &spec.run_commands {
        lines.push(format!("RUN {cmd}"));
    }

    // Volumes
    for vol in &spec.volumes {
        lines.push(format!("VOLUME [\"{vol}\"]"));
    }

    // Exposed ports
    for port in &spec.exposed_ports {
        lines.push(format!("EXPOSE {port}"));
    }

    // Entrypoint
    if !spec.entrypoint.is_empty() {
        let parts: Vec<String> = spec.entrypoint.iter().map(|s| format!("\"{s}\"")).collect();
        lines.push(format!("ENTRYPOINT [{}]", parts.join(", ")));
    }

    // CMD
    if !spec.cmd.is_empty() {
        let parts: Vec<String> = spec.cmd.iter().map(|s| format!("\"{s}\"")).collect();
        lines.push(format!("CMD [{}]", parts.join(", ")));
    }

    lines.join("\n") + "\n"
}

/// Generate a default Dockerfile for a **Rust-first** Vox deployment.
///
/// Expects a **release binary** in the build context named **`vox-app`** (e.g. from `vox bundle` or
/// `cargo build --release` in `target/generated`). For the legacy **Node + `npx tsx server.ts`** lane,
/// use an explicit `@environment` block or a hand-authored Dockerfile; see repository docs.
pub fn generate_default_dockerfile() -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push("# Generated by Vox — OCI-compatible Dockerfile (Rust binary; see docs for Node lane)".to_string());
    lines.push("FROM debian:bookworm-slim".to_string());
    lines.push("WORKDIR /app".to_string());
    lines.push(
        "RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \\"
            .to_string(),
    );
    lines.push("    && rm -rf /var/lib/apt/lists/*".to_string());
    lines.push("COPY vox-app /app/vox-app".to_string());
    lines.push("RUN chmod +x /app/vox-app".to_string());
    lines.push("ENV VOX_PORT=3000".to_string());
    lines.push("EXPOSE 3000".to_string());
    lines.push("CMD [\"/app/vox-app\"]".to_string());
    lines.join("\n") + "\n"
}

const COMPOSE_OPTIONAL_MESH_ENV: &str =
    include_str!("../../../docker/vox-compose-mesh-environment.block.yaml");

/// Generate a docker-compose.yml that works with both Docker Compose and
/// Podman Compose.
///
/// Omits the deprecated `version` field for OCI compatibility.
///
/// Optional mesh-related `environment` entries are loaded from
/// `docker/vox-compose-mesh-environment.block.yaml` (SSOT shared with docs).
pub fn generate_compose_file() -> String {
    format!(
        r#"# Generated by Vox — compatible with Docker Compose and Podman Compose
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VOX_API_KEY=${{VOX_API_KEY:-}}
      - VOX_BEARER_TOKEN=${{VOX_BEARER_TOKEN:-}}
{mesh_env}    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
"#,
        mesh_env = COMPOSE_OPTIONAL_MESH_ENV
    )
}

/// Generate basic Kubernetes manifests (Deployment and Service) for a Vox app.
pub fn generate_kubernetes_manifests(
    app_name: &str,
    image_tag: &str,
    namespace: &str,
    spec: &EnvironmentSpec,
) -> String {
    let mut env_snippets = Vec::new();
    for (key, val) in &spec.env_vars {
        env_snippets.push(format!(
            "            - name: {}\n              value: \"{}\"",
            key, val
        ));
    }
    let env_block = if env_snippets.is_empty() {
        "".to_string()
    } else {
        format!("          env:\n{}", env_snippets.join("\n"))
    };

    let container_ports = if spec.exposed_ports.is_empty() {
        "            - containerPort: 3000".to_string()
    } else {
        spec.exposed_ports
            .iter()
            .map(|p| format!("            - containerPort: {}", p))
            .collect::<Vec<_>>()
            .join("\n")
    };

    let service_ports = if spec.exposed_ports.is_empty() {
        "    - port: 80\n      targetPort: 3000".to_string()
    } else {
        spec.exposed_ports
            .iter()
            .map(|p| {
                format!(
                    "    - name: port-{}\n      port: {}\n      targetPort: {}",
                    p, p, p
                )
            })
            .collect::<Vec<_>>()
            .join("\n")
    };

    format!(
        r#"apiVersion: apps/v1
kind: Deployment
metadata:
  name: {app_name}
  namespace: {namespace}
  labels:
    app: {app_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {app_name}
  template:
    metadata:
      labels:
        app: {app_name}
    spec:
      containers:
        - name: {app_name}
          image: {image_tag}
          ports:
{container_ports}
{env_block}
---
apiVersion: v1
kind: Service
metadata:
  name: {app_name}
  namespace: {namespace}
spec:
  type: ClusterIP
  ports:
{service_ports}
  selector:
    app: {app_name}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_dockerfile_rust_binary_layout() {
        let df = generate_default_dockerfile();
        assert!(
            df.contains("FROM debian:bookworm-slim"),
            "Should use Debian slim runtime"
        );
        assert!(df.contains("WORKDIR /app"), "Should set workdir");
        assert!(df.contains("COPY vox-app /app/vox-app"), "Should copy release binary");
        assert!(df.contains("EXPOSE 3000"), "Should expose port 3000");
        assert!(df.contains("CMD [\"/app/vox-app\"]"), "Should run Rust binary");
    }

    #[test]
    fn spec_dockerfile_alpine_uses_apk() {
        let spec = EnvironmentSpec {
            base_image: "alpine:3.19".to_string(),
            packages: vec!["curl".to_string(), "git".to_string()],
            ..Default::default()
        };
        let df = generate_dockerfile_from_spec(&spec);
        assert!(
            df.contains("apk add --no-cache curl git"),
            "Alpine should use apk"
        );
    }

    #[test]
    fn spec_dockerfile_debian_uses_apt() {
        let spec = EnvironmentSpec {
            base_image: "debian:bookworm".to_string(),
            packages: vec!["curl".to_string()],
            ..Default::default()
        };
        let df = generate_dockerfile_from_spec(&spec);
        assert!(
            df.contains("apt-get install -y curl"),
            "Debian should use apt-get"
        );
    }

    #[test]
    fn spec_dockerfile_env_vars() {
        let spec = EnvironmentSpec {
            base_image: "node:22".to_string(),
            env_vars: vec![
                ("NODE_ENV".to_string(), "production".to_string()),
                ("PORT".to_string(), "8080".to_string()),
            ],
            ..Default::default()
        };
        let df = generate_dockerfile_from_spec(&spec);
        assert!(
            df.contains("ENV NODE_ENV=production"),
            "Should set NODE_ENV"
        );
        assert!(df.contains("ENV PORT=8080"), "Should set PORT");
    }

    #[test]
    fn spec_dockerfile_volumes_and_ports() {
        let spec = EnvironmentSpec {
            base_image: "node:22".to_string(),
            volumes: vec!["/data".to_string()],
            exposed_ports: vec![3000, 8080],
            ..Default::default()
        };
        let df = generate_dockerfile_from_spec(&spec);
        assert!(df.contains("VOLUME [\"/data\"]"), "Should declare volume");
        assert!(df.contains("EXPOSE 3000"), "Should expose 3000");
        assert!(df.contains("EXPOSE 8080"), "Should expose 8080");
    }

    #[test]
    fn compose_file_omits_version() {
        let compose = generate_compose_file();
        assert!(
            !compose.contains("version:"),
            "Modern compose should not have version field"
        );
        assert!(
            compose.contains("services:"),
            "Should have services section"
        );
        assert!(
            compose.contains("VOX_MESH_TOKEN"),
            "Compose template should wire optional mesh bearer token"
        );
        assert!(
            compose.contains("VOX_MESH_SCOPE_ID"),
            "Compose template should wire optional mesh scope id"
        );
        assert!(compose.contains("VOX_ORCHESTRATOR_MESH_CONTROL_URL"));
        assert!(compose.contains("VOX_MESH_MAX_STALE_MS"));
        assert!(compose.contains("VOX_MESH_HTTP_JOIN"));
        assert!(compose.contains("VOX_MESH_HTTP_HEARTBEAT_SECS"));
        assert!(compose.contains("VOX_MESH_ADVERTISE_VULKAN"));
        assert!(compose.contains("VOX_MESH_ADVERTISE_WEBGPU"));
        assert!(compose.contains("VOX_MESH_ADVERTISE_NPU"));
        assert!(compose.contains("VOX_MESH_DEVICE_CLASS"));
    }

    #[test]
    fn kubernetes_manifests_basic() {
        let spec = EnvironmentSpec {
            env_vars: vec![("NODE_ENV".into(), "production".into())],
            exposed_ports: vec![3000],
            ..Default::default()
        };
        let manifest = generate_kubernetes_manifests("myapp", "myapp:latest", "prod", &spec);
        assert!(
            manifest.contains("name: myapp"),
            "Missing app name in kubernetes manifest"
        );
        assert!(
            manifest.contains("image: myapp:latest"),
            "Missing image tag in kubernetes manifest"
        );
        assert!(
            manifest.contains("namespace: prod"),
            "Missing namespace in kubernetes manifest"
        );
        assert!(manifest.contains("kind: Deployment"), "Missing deployment");
        assert!(manifest.contains("kind: Service"), "Missing service");
        assert!(manifest.contains("containerPort: 3000"), "Missing port");
        assert!(manifest.contains("name: NODE_ENV"), "Missing env var");
    }
}
