//! Generate `pyproject.toml` from Vox `@py.import` declarations.
//!
//! When a `.vox` source file contains `@py.import` declarations, Vox
//! generates a `pyproject.toml` in the output directory that can be used
//! with `uv sync` to install the required Python packages.

use crate::env::PythonEnv;

/// A Python dependency (package name + optional version constraint).
#[derive(Debug, Clone)]
pub struct PyDep {
    /// Package name as it appears on PyPI, e.g. `"torch"` or `"numpy"`.
    pub name: String,
    /// Optional PEP 440 version specifier, e.g. `">=2.0"`.
    pub version: Option<String>,
}

impl PyDep {
    /// Infer the correct PyPI package name from a Python import module name.
    ///
    /// Maps common Vox `@py.import` module names to their PyPI package names,
    /// e.g. `torch.nn` → `torch`, `sklearn` → `scikit-learn`.
    pub fn from_import_module(module: &str) -> Self {
        // Take the top-level module name.
        let top = module.split('.').next().unwrap_or(module);
        let pypi_name = canonical_pypi_name(top);
        PyDep {
            name: pypi_name.to_string(),
            version: None,
        }
    }

    /// Format as a PEP 621 dependency string, e.g. `"torch>=2.0"`.
    pub fn as_pep621(&self) -> String {
        match &self.version {
            Some(v) => format!("{}{}", self.name, v),
            None => self.name.clone(),
        }
    }
}

/// Map common import names to canonical PyPI names.
fn canonical_pypi_name(module: &str) -> &str {
    match module {
        "cv2" => "opencv-python",
        "sklearn" => "scikit-learn",
        "PIL" => "Pillow",
        "pil" => "Pillow",
        "yaml" => "PyYAML",
        "bs4" => "beautifulsoup4",
        "dateutil" => "python-dateutil",
        "dotenv" => "python-dotenv",
        "jwt" => "PyJWT",
        "attr" | "attrs" => "attrs",
        other => other,
    }
}

/// Generate a `pyproject.toml` file content from a list of Python imports.
///
/// Produces a minimal PEP 621-compliant `pyproject.toml` that can be used
/// directly with `uv sync`.
///
/// # Arguments
/// * `project_name` — Vox project name, used as the `[project].name`.
/// * `imports` — Module names from `@py.import` declarations.
/// * `env` — Detected Python environment (for CUDA-aware source selection).
pub fn generate_pyproject_toml(project_name: &str, imports: &[String], env: &PythonEnv) -> String {
    // Deduplicate by top-level module.
    let mut deps: Vec<PyDep> = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for module in imports {
        let dep = PyDep::from_import_module(module);
        if seen.insert(dep.name.clone()) {
            deps.push(dep);
        }
    }

    let torch_index = env.pytorch_index_url();
    let has_torch = deps.iter().any(|d| d.name == "torch");

    let mut out = String::new();

    out.push_str("# Generated by Vox — do not edit manually.\n");
    out.push_str("# Re-generated from @py.import declarations in your .vox source files.\n\n");

    out.push_str("[project]\n");
    out.push_str(&format!("name = \"{}\"\n", project_name));
    out.push_str("version = \"0.1.0\"\n");
    out.push_str("requires-python = \">=3.12\"\n");

    if deps.is_empty() {
        out.push_str("dependencies = []\n");
    } else {
        out.push_str("dependencies = [\n");
        for dep in &deps {
            out.push_str(&format!("    \"{}\",\n", dep.as_pep621()));
        }
        out.push_str("]\n");
    }

    // Only add the torch-specific index when torch is in the dependency list.
    if has_torch {
        out.push('\n');
        out.push_str("# PyTorch wheel source — CPU or CUDA-specific build\n");
        out.push_str("# (auto-detected from nvcc/nvidia-smi at vox container init time)\n");
        out.push_str("[tool.uv.sources]\n");

        // Only add a custom source for torch if we need GPU wheels.
        // For CPU-only, PyPI default is fine.
        if torch_index != "https://download.pytorch.org/whl/cpu" {
            out.push_str(&format!(
                "torch = {{ index = \"pytorch-{gpu}\" }}\n",
                gpu = if torch_index.contains("cu130") {
                    "cu130"
                } else if torch_index.contains("cu124") {
                    "cu124"
                } else if torch_index.contains("cu121") {
                    "cu121"
                } else {
                    "cu118"
                }
            ));
            out.push('\n');
            out.push_str("[[tool.uv.index]]\n");
            out.push_str(&format!(
                "name = \"pytorch-{gpu}\"\n",
                gpu = if torch_index.contains("cu130") {
                    "cu130"
                } else if torch_index.contains("cu124") {
                    "cu124"
                } else if torch_index.contains("cu121") {
                    "cu121"
                } else {
                    "cu118"
                }
            ));
            out.push_str(&format!("url = \"{}\"\n", torch_index));
            out.push_str("explicit = true\n");
        }
    }

    out.push('\n');
    out.push_str("[build-system]\n");
    out.push_str("requires = [\"hatchling\"]\n");
    out.push_str("build-backend = \"hatchling.build\"\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::env::PythonEnv;

    fn cpu_env() -> PythonEnv {
        PythonEnv {
            uv_available: true,
            uv_version: None,
            python_version: None,
            cuda_version: None,
            has_gpu: false,
        }
    }

    fn gpu_env() -> PythonEnv {
        PythonEnv {
            uv_available: true,
            uv_version: None,
            python_version: None,
            cuda_version: Some("12.4".to_string()),
            has_gpu: true,
        }
    }

    #[test]
    fn generates_project_block() {
        let toml = generate_pyproject_toml("my-app", &["torch".to_string()], &cpu_env());
        assert!(toml.contains("[project]"));
        assert!(toml.contains("name = \"my-app\""));
        assert!(toml.contains("requires-python = \">=3.12\""));
    }

    #[test]
    fn torch_cpu_no_custom_index() {
        let toml = generate_pyproject_toml("app", &["torch".to_string()], &cpu_env());
        // CPU wheels come from PyPI default — no custom index needed
        assert!(!toml.contains("[[tool.uv.index]]"));
    }

    #[test]
    fn torch_cuda_adds_custom_index() {
        let toml = generate_pyproject_toml("app", &["torch".to_string()], &gpu_env());
        assert!(toml.contains("[[tool.uv.index]]"));
        assert!(toml.contains("cu124"));
    }

    #[test]
    fn canonical_opencv() {
        let dep = PyDep::from_import_module("cv2");
        assert_eq!(dep.name, "opencv-python");
    }

    #[test]
    fn canonical_sklearn() {
        let dep = PyDep::from_import_module("sklearn");
        assert_eq!(dep.name, "scikit-learn");
    }

    #[test]
    fn deduplicates_torch_nn() {
        let imports = vec![
            "torch".to_string(),
            "torch.nn".to_string(),
            "torch.nn.functional".to_string(),
        ];
        let toml = generate_pyproject_toml("app", &imports, &cpu_env());
        // Should only list "torch" once
        let count = toml.matches("\"torch\"").count();
        assert_eq!(count, 1, "torch should appear exactly once: {toml}");
    }
}
