//! Python-capable Dockerfile generator.
//!
//! Generates a CUDA-aware Dockerfile that:
//! - Uses the official PyTorch CUDA base image when GPU is detected.
//! - Falls back to a slim Python 3.12 base for CPU-only workloads.
//! - Installs `uv` for fast, reproducible Python dependency management.
//! - Copies the generated `pyproject.toml` and runs `uv sync`.

use crate::env::PythonEnv;

/// Generate a production-ready Dockerfile for a Vox app that uses Python.
///
/// Automatically selects the correct base image based on CUDA availability.
pub fn generate_python_dockerfile(
    project_name: &str,
    env: &PythonEnv,
    py_imports: &[String],
) -> String {
    let has_torch = py_imports
        .iter()
        .any(|m| m == "torch" || m.starts_with("torch."));

    let (base_image, cuda_extra) = pick_base_image(env, has_torch);

    let mut lines = Vec::new();

    lines.push("# Generated by Vox — Python/CUDA-aware Dockerfile".to_string());
    lines.push("# Compatible with Docker and Podman.".to_string());
    lines.push(format!("FROM {base_image}"));
    lines.push(String::new());

    // CUDA-specific env vars
    if let Some(extra) = cuda_extra {
        lines.push(extra);
        lines.push(String::new());
    }

    lines.push("WORKDIR /app".to_string());
    lines.push(String::new());

    // Install uv using the official standalone installer (faster than pip in containers)
    lines.push("# Install uv for fast Python dependency management".to_string());
    lines.push("RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \\".to_string());
    lines.push("    mv /root/.local/bin/uv /usr/local/bin/uv".to_string());
    lines.push(String::new());

    // Copy and install Python deps first (good layer-caching practice)
    lines.push("# Install Python dependencies".to_string());
    lines.push("COPY pyproject.toml ./".to_string());

    // Add torch index if CUDA
    if has_torch && env.pytorch_index_url() != "https://download.pytorch.org/whl/cpu" {
        lines.push(format!(
            "RUN uv sync --extra-index-url {}",
            env.pytorch_index_url()
        ));
    } else {
        lines.push("RUN uv sync".to_string());
    }
    lines.push(String::new());

    // Copy the Vox-compiled binary / app code
    lines.push("# Copy compiled application".to_string());
    lines.push("COPY . .".to_string());
    lines.push(String::new());

    // Expose standard port
    lines.push("EXPOSE 3000".to_string());
    lines.push(String::new());

    // Default entrypoint — runs the compiled Vox binary
    lines.push(format!("CMD [\"./{project_name}\"]"));

    lines.join("\n") + "\n"
}

/// Pick the best base Docker image for the given environment.
///
/// Returns `(base_image, optional_env_line)`.
fn pick_base_image(env: &PythonEnv, needs_torch: bool) -> (String, Option<String>) {
    if needs_torch && env.has_gpu {
        // Use the official PyTorch CUDA image — includes everything needed
        // for GPU inference without manual CUDA toolkit installation.
        let cuda_tag = match env.cuda_version.as_deref() {
            Some(v) if v.starts_with("13.") => "pytorch/pytorch:2.6.0-cuda13.0-cudnn9-runtime",
            Some(v) if v.starts_with("12.4") || v.starts_with("12.5") || v.starts_with("12.6") => {
                "pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime"
            }
            Some(v) if v.starts_with("12.1") || v.starts_with("12.2") || v.starts_with("12.3") => {
                "pytorch/pytorch:2.4.1-cuda12.1-cudnn9-runtime"
            }
            Some(v) if v.starts_with("11.8") => "pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime",
            _ => {
                // Unknown CUDA version — fall back to latest stable GPU build
                "pytorch/pytorch:2.6.0-cuda13.0-cudnn9-runtime"
            }
        };

        let env_line = Some(
            "ENV NVIDIA_VISIBLE_DEVICES=all NVIDIA_DRIVER_CAPABILITIES=compute,utility".to_string(),
        );
        (cuda_tag.to_string(), env_line)
    } else if needs_torch {
        // CPU-only PyTorch — use slim Python to keep image small
        ("python:3.12-slim".to_string(), None)
    } else {
        // No PyTorch — minimal Python base
        ("python:3.12-slim".to_string(), None)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::env::PythonEnv;

    fn make_env(cuda: Option<&str>) -> PythonEnv {
        PythonEnv {
            uv_available: true,
            uv_version: None,
            python_version: None,
            cuda_version: cuda.map(String::from),
            has_gpu: cuda.is_some(),
        }
    }

    #[test]
    fn cpu_uses_python_slim() {
        let env = make_env(None);
        let df = generate_python_dockerfile("myapp", &env, &["torch".to_string()]);
        assert!(df.contains("python:3.12-slim"), "CPU should use slim: {df}");
    }

    #[test]
    fn cuda_130_uses_pytorch_130_image() {
        let env = make_env(Some("13.0"));
        let df = generate_python_dockerfile("myapp", &env, &["torch".to_string()]);
        assert!(df.contains("cuda13.0"), "Should use 13.0 image: {df}");
    }

    #[test]
    fn cuda_124_uses_pytorch_image() {
        let env = make_env(Some("12.4"));
        let df = generate_python_dockerfile("myapp", &env, &["torch".to_string()]);
        assert!(
            df.contains("pytorch/pytorch:2.5.1-cuda12.4"),
            "Should use PyTorch CUDA image: {df}"
        );
    }

    #[test]
    fn cuda_118_uses_pytorch_118_image() {
        let env = make_env(Some("11.8"));
        let df = generate_python_dockerfile("myapp", &env, &["torch".to_string()]);
        assert!(df.contains("cuda11.8"), "Should use 11.8 image: {df}");
    }

    #[test]
    fn contains_uv_install() {
        let env = make_env(None);
        let df = generate_python_dockerfile("myapp", &env, &["torch".to_string()]);
        assert!(
            df.contains("astral.sh/uv/install.sh"),
            "Should install uv via official installer"
        );
    }

    #[test]
    fn contains_expose_and_cmd() {
        let env = make_env(None);
        let df = generate_python_dockerfile("myapp", &env, &[]);
        assert!(df.contains("EXPOSE 3000"));
        assert!(df.contains("CMD [\"./myapp\"]"));
    }
}
