import React, { useMemo } from 'react';
import { useVoxQuery } from '../../../hooks/useVoxQuery';
import { voxTransport } from '../../../transport';
import { Button } from '../../ui/Button';
import { EmpiricalVerificationBadge } from './EmpiricalVerificationBadge';

interface DocReaderProps {
  path: string;
  onNavigateToResearch?: (sessionId: number) => void;
}

const PROVENANCE_REGEX =
  />\s*\*\*Empirical Provenance:\*\*\s*Generated by Vox Deep Research\s*\(Session\s*#(\d+),\s*Stability\s*\$?S\s*=\s*([\d.]+)\$?.*?\)/i;

export function DocReader({ path, onNavigateToResearch }: DocReaderProps) {
  const q = useVoxQuery(['doc', path], () => voxTransport.readDocMarkdown(path), {
    enabled: path.length > 0,
  });

  const provenance = useMemo(() => {
    if (!q.data) return null;
    const match = q.data.match(PROVENANCE_REGEX);
    if (!match) return null;
    const sessionId = parseInt(match[1], 10);
    const stabilityScore = parseFloat(match[2]);
    if (isNaN(sessionId) || isNaN(stabilityScore)) return null;
    return { sessionId, stabilityScore };
  }, [q.data]);

  if (q.isLoading) {
    return (
      <article className="p-6 text-text-muted font-display text-sm" data-testid="doc-reader">
        Loading documentation…
      </article>
    );
  }

  if (q.isError) {
    return (
      <article className="p-6 text-amber-400 font-mono text-sm" data-testid="doc-reader" role="alert">
        Failed to load doc: {q.error.message}
      </article>
    );
  }

  return (
    <article className="max-w-none p-4" data-testid="doc-reader">
      <header className="mb-4 border-b border-border-subtle pb-3 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="font-display text-lg text-text-primary">{path.split('/').pop()}</h1>
          <p className="mt-1 font-mono text-[11px] text-text-muted">{path}</p>
        </div>
        {provenance && (
          <EmpiricalVerificationBadge
            sessionId={provenance.sessionId}
            stabilityScore={provenance.stabilityScore}
            onNavigateToResearch={onNavigateToResearch}
          />
        )}
      </header>
      <pre className="whitespace-pre-wrap font-mono text-[12px] leading-relaxed text-text-secondary">
        {q.data ?? ''}
      </pre>
      <div className="mt-4">
        <Button
          className="text-[11px]"
          onClick={() => {
            voxTransport.openLocator({ kind: 'file', value: path }).catch(() => {});
          }}
        >
          Open in editor
        </Button>
      </div>
    </article>
  );
}

