// @vitest-environment jsdom
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import React from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

vi.mock('../../../transport', () => ({
  voxTransport: {
    openLocator: vi.fn().mockResolvedValue({ action: 'opened' }),
    readDocMarkdown: vi.fn(),
  },
}));

import { voxTransport } from '../../../transport';
import { DocReader } from './DocReader';

function renderDocReader(path: string) {
  const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(
    <QueryClientProvider client={qc}>
      <DocReader path={path} />
    </QueryClientProvider>,
  );
}

describe('DocReader', () => {
  beforeEach(() => {
    vi.mocked(voxTransport.readDocMarkdown).mockReset();
    vi.mocked(voxTransport.readDocMarkdown).mockResolvedValue('# Title\n\nBody text');
  });

  it('loads and renders markdown for a doc path', async () => {
    renderDocReader('docs/src/reference/cli.md');
    await waitFor(() => {
      expect(screen.getByTestId('doc-reader')).toBeDefined();
      expect(screen.getByText(/Body text/)).toBeDefined();
    });
    expect(voxTransport.readDocMarkdown).toHaveBeenCalledWith('docs/src/reference/cli.md');
    expect(screen.queryByText(/Verified by Deep Research/i)).toBeNull();
  });

  it('renders EmpiricalVerificationBadge when document contains empirical provenance block', async () => {
    vi.mocked(voxTransport.readDocMarkdown).mockResolvedValue(
      '# Architecture Doc\n\n> **Empirical Provenance:** Generated by Vox Deep Research (Session #101, Stability $S = 0.95$).\n\nVerified findings.',
    );

    renderDocReader('docs/src/architecture/metal-optimization-2026.md');
    await waitFor(() => {
      expect(screen.getByText(/Verified by Deep Research/i)).toBeDefined();
      expect(screen.getByText(/\(S = 0.95\)/)).toBeDefined();
    });
  });

  it('forwards onNavigateToResearch when navigating from provenance drawer', async () => {
    vi.mocked(voxTransport.readDocMarkdown).mockResolvedValue(
      '# Architecture Doc\n\n> **Empirical Provenance:** Generated by Vox Deep Research (Session #101, Stability $S = 0.95$).\n\nVerified findings.',
    );
    const onNavigate = vi.fn();
    const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } });
    render(
      <QueryClientProvider client={qc}>
        <DocReader
          path="docs/src/architecture/metal-optimization-2026.md"
          onNavigateToResearch={onNavigate}
        />
      </QueryClientProvider>,
    );

    await waitFor(() => {
      expect(screen.getByText(/Verified by Deep Research/i)).toBeDefined();
    });

    screen.getByRole('button', { name: /Verified by Deep Research/i }).click();
    await waitFor(() => {
      expect(screen.getByText(/Open Full Research Session #101/i)).toBeDefined();
    });

    screen.getByRole('button', { name: /Open Full Research Session #101/i }).click();
    expect(onNavigate).toHaveBeenCalledWith(101);
  });
});


