use crate::spec::types::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, strum::Display)]
pub enum SecretId {
    GeminiApiKey,
    OpenRouterApiKey,
    OpenRouterModel,
    OpenaiApiKey,
    OpenaiModel,
    OpenaiBaseUrl,
    GeminiModel,
    TogetherFinetuneModel,
    GeminiDirectModel,
    OpenRouterGeminiModel,
    VoxPopuliLocalOllamaUrl,
    AnthropicApiKey,
    OllamaUrl,
    OllamaModel,
    HuggingFaceToken,
    ForgeToken,
    GroqApiKey,
    CerebrasApiKey,
    MistralApiKey,
    DeepSeekApiKey,
    SambaNovaApiKey,
    CustomOpenaiApiKey,
    V0ApiKey,
    OpenClawToken,
    /// API key for publishing skills to OpenClaw / ClawHub gateways.
    OpenClawApiKey,
    VoxOpenClawUrl,
    VoxOpenClawWsUrl,
    TogetherApiKey,
    VoxRunpodApiKey,
    VoxVastApiKey,
    VoxApiKey,
    VoxBearerToken,
    VoxDbUrl,
    VoxDbToken,
    VoxMeshToken,
    VoxMeshWorkerToken,
    VoxMeshSubmitterToken,
    VoxMeshAdminToken,
    VoxMeshJwtHmacSecret,
    VoxMeshWorkerResultVerifyKey,
    VoxNewsTwitterBearer,
    VoxSocialBlueskyHandle,
    VoxSocialBlueskyPassword,
    VoxNewsOpenCollectiveToken,
    VoxSocialRedditClientId,
    VoxSocialRedditClientSecret,
    VoxSocialRedditRefreshToken,
    VoxSocialRedditUserAgent,
    VoxSocialYoutubeClientId,
    VoxSocialYoutubeClientSecret,
    VoxSocialYoutubeRefreshToken,
    VoxSocialMastodonToken,
    VoxSocialMastodonDomain,
    VoxSocialLinkedinAccessToken,
    VoxSocialLinkedinAuthorUrn,
    VoxSocialBlueskyPdsUrl,
    VoxNewsOpenCollectiveSlug,
    VoxSocialDiscordWebhook,
    VoxSocialTwitterApiBase,
    VoxSocialLinkedinApiBase,
    VoxSocialRedditApiBase,
    VoxZenodoAccessToken,
    VoxOpenReviewEmail,
    VoxOpenReviewAccessToken,
    VoxOpenReviewPassword,
    VoxCrossrefPlusApiKey,
    VoxArxivAssistHandoffSecret,
    VoxSearchQdrantApiKey,
    PopuliApiKey,
    VoxTelemetryUploadUrl,
    VoxTelemetryUploadToken,
    WebhookIngressToken,
    VoxMcpHttpBearerToken,
    VoxMcpHttpReadBearerToken,
    WebhookSigningSecret,
    VoxOrcidClientId,
    VoxOrcidClientSecret,
    VoxDataCiteRepository,
    VoxDataCitePassword,
    TavilyApiKey,
    VoxScholarlyAdapter,
    VoxScholarlyDisable,
    VoxScholarlyDisableLive,
    VoxScholarlyDisableZenodo,
    VoxScholarlyDisableOpenReview,
    VoxOpenReviewApiBase,
    VoxOpenReviewInvitation,
    VoxOpenReviewSignature,
    VoxZenodoSandbox,
    VoxZenodoApiBase,
    VoxNewsTwitterTextChunkMax,
    VoxNewsTwitterTruncationSuffix,
    VoxSocialTwitterSummaryMarginChars,
    VoxSocialRedditSelfpostSummaryMax,
    VoxSocialHnMode,
    VoxSocialYoutubeDefaultCategoryId,
    VoxSyndicationTemplateProfileEnabled,
    TavilyProject,
    VoxNewsSiteBaseUrl,
    VoxNewsRssFeedPath,
    VoxNewsPublishArmed,
    VoxZenodoAttachManifestBody,
    VoxZenodoPublishDeposition,
    VoxZenodoDraftOnly,
    VoxZenodoPublishNow,
    VoxZenodoStagingDir,
    VoxZenodoUploadAllowlist,
    VoxZenodoVerifyStagingChecksums,
    VoxZenodoRequireMetadataParity,
    VoxMcpAgentFleet,
    VoxZenodoHttpMaxAttempts,
    VoxOpenReviewHttpMaxAttempts,
    VoxScholarlyJobLockOwner,
    VoxScientiaCrossrefMailto,
    VoxMeshBootstrapToken,
    VoxMeshBootstrapExpiresUnixMs,
    VoxIdentityKeyPath,
    VoxIdentityMasterPwd,
    VoxGithubClientId,
    VoxGithubOauthToken,
    CoolifyWebhookUrl,
    CoolifyBaseUrl,
    CoolifyToken,
    CoolifyAppUuid,
    VoxMeshEnabled,
    VoxMeshMode,
    VoxMeshNodeId,
    VoxMeshLabels,
    VoxMeshControlAddr,
    VoxMeshRegistryPath,
    VoxMeshAdvertiseGpu,
    VoxMeshScopeId,
    VoxMeshServerStalePruneMs,
    VoxMeshA2aMaxMessages,
    VoxMeshA2aLeaseMs,
    VoxMeshHttpRateLimit,
    VoxMeshVisibility,
    VoxMeshDonationPolicyJson,
    VoxOrchestratorEnabled,
    VoxOrchestratorMaxAgents,
    VoxOrchestratorLockTimeoutMs,
    VoxOrchestratorToestubGate,
    VoxOrchestratorMaxDebugIterations,
    VoxOrchestratorMaxToestubDebugIterations,
    VoxOrchestratorMaxSocratesDebugIterations,
    VoxOrchestratorLogLevel,
    VoxOrchestratorFallbackSingle,
    VoxOrchestratorMinAgents,
    VoxOrchestratorScalingThreshold,
    VoxOrchestratorIdleRetirementMs,
    VoxOrchestratorScalingEnabled,
    VoxOrchestratorCostPreference,
    VoxOrchestratorScalingLookback,
    VoxOrchestratorResourceWeight,
    VoxOrchestratorResourceCpuMult,
    VoxOrchestratorResourceMemMult,
    VoxOrchestratorResourceExponent,
    VoxOrchestratorScalingProfile,
    VoxOrchestratorMaxSpawnPerTick,
    VoxOrchestratorScalingCooldownMs,
    VoxOrchestratorUrgentRebalanceThreshold,
    VoxOrchestratorSocratesGateShadow,
    VoxOrchestratorSocratesGateEnforce,
    VoxOrchestratorSocratesReputationRouting,
    VoxOrchestratorSocratesReputationWeight,
    VoxOrchestratorTrustGateRelaxEnabled,
    VoxOrchestratorTrustGateRelaxMinReliability,
    VoxOrchestratorTrustEwmaAlpha,
    VoxOrchestratorTrustProvisionalThreshold,
    VoxOrchestratorTrustTrustedThreshold,
    VoxOrchestratorTrustAutoApproveMin,
    VoxOrchestratorMigrationV2Enabled,
    VoxOrchestratorMigrationLegacyFallback,
    VoxOrchestratorMeshControlUrl,
    VoxOrchestratorPopuliInferenceBaseUrl,
    VoxOrchestratorMeshPollIntervalSecs,
    VoxOrchestratorMeshHttpTimeoutMs,
    VoxOrchestratorMeshRoutingExperimental,
    VoxOrchestratorMeshRebalanceOnRemoteSchedulableDrop,
    VoxOrchestratorMeshReplayQueuedRoutesOnRemoteSchedulableDrop,
    VoxOrchestratorMeshTrainingRoutingExperimental,
    VoxOrchestratorMeshTrainingBudgetPressure,
    VoxOrchestratorMeshRemoteExecuteExperimental,
    VoxOrchestratorMeshRemoteExecuteReceiverAgent,
    VoxOrchestratorMeshRemoteExecuteSenderAgent,
    VoxOrchestratorMeshRemoteResultPollIntervalSecs,
    VoxOrchestratorMeshRemoteResultMaxMessagesPerPoll,
    VoxOrchestratorMeshRemoteWorkerPollIntervalSecs,
    VoxOrchestratorMeshRemoteLeaseGatingEnabled,
    VoxOrchestratorMeshRemoteLeaseGatedRoles,
    VoxOrchestratorChatmlStrict,
    VoxOrchestratorCompletionGroundingShadow,
    VoxOrchestratorCompletionGroundingEnforce,
    VoxOrchestratorPlanningLlmSynthesisEnabled,
    VoxOrchestratorPlanningLlmSynthesisModel,
    VoxOrchestratorPlanningEnabled,
    VoxOrchestratorPlanningRouterEnabled,
    VoxOrchestratorPlanningReplanEnabled,
    VoxOrchestratorPlanningWorkflowHandoffEnabled,
    VoxOrchestratorPlanningShadowMode,
    VoxOrchestratorResearchModelEnabled,
    VoxOrchestratorPlanningAutoModeEnabled,
    VoxOrchestratorPlanningRolloutPercent,
    VoxOrchestratorPlanAdequacyShadow,
    VoxOrchestratorPlanAdequacyEnforce,
    VoxOrchestratorContextLifecycleShadow,
    VoxOrchestratorContextLifecycleEnforce,
    VoxOrchestratorSocratesGateAutoMode,
    VoxOrchestratorSocratesGateThreshold,
    VoxOrchestratorAttentionEnabled,
    VoxOrchestratorAttentionBudgetMs,
    VoxOrchestratorAttentionAlertThreshold,
    VoxOrchestratorAttentionInterruptCostMs,
    VoxOrchestratorTlxMental,
    VoxOrchestratorTlxTemporal,
    VoxOrchestratorTlxFrustration,
    VoxOrchestratorTlxTrustDiscount,
    VoxOrchestratorTierGateEntropyThreshold,
    VoxOrchestratorTierGateMinObservations,
    VoxOrchestratorInterruptionCalPlanGain,
    VoxOrchestratorInterruptionCalA2AGain,
    VoxOrchestratorInterruptionCalBacklogPenalty,
    VoxOrchestratorAttentionTrustRoutingWeight,
    VoxOrchestratorRepoShardSpecializationWeight,
    VoxOrchestratorRepoShardValidationFailurePenalty,
    VoxOrchestratorRepoReduceConflictCooldownPenalty,
    VoxOrchestratorRepoReduceConflictCooldownMs,
    VoxOrchestratorExecTimeBudgetEnabled,
    VoxOrchestratorExecTimeSafetyMultiplier,
    VoxOrchestratorExecTimeTimeoutRateAlert,
    VoxOrchestratorExecTimeDefaultBudgetMs,
    VoxOrchestratorExecTimeHistoryWindowDays,
    VoxOrchestratorCampaignId,
    VoxRepositoryRoot,
    VoxProviderDailyLimitDefault,
    VoxProviderLimitProviders,
    VoxProviderDailyLimitsFile,
    VoxProviderDailyLimitsJson,
    PopuliModel,
    VoxOpenRouterCatalogMinRefreshIntervalSecs,
    VoxOpenRouterCatalogRefreshJitterMs,
    VoxOrchestratorHarnessCompletionGuard,
    VoxOrchestratorMeshExecLeaseReconcile,
    VoxOrchestratorMeshExecLeaseAutoRevoke,
    VoxWorkspaceRoot,
    VoxOrchestratorDaemonSocket,
    VoxModel,
    VoxBudgetUsd,
    VoxDataDir,
    VoxMcpBinary,
    VoxGamifyEnabled,
    VoxGamifyMode,
    VoxWebRunMode,
    VoxOpenRouterClassifierEnabled,
    VoxSocialWorthinessScoreMin,
    VoxSocialChannelWorthinessFloors,
    VoxSyndicationTemplateProfile,
    VoxNewsScanRecursive,
    VoxGenericApiKey,
    VoxMeshHttpJoin,
    VoxMeshHttpHeartbeatSecs,
    VoxMeshExecPolicy,
    VoxMeshA2aStorePath,
    VoxMeshExecLeaseStorePath,
    VoxMeshDispatchStorePath,
    VoxMeshHttpMaxBodyBytes,
    VoxMeshReplayPersist,
    VoxMeshReplayStatePath,
    VoxMensExperimentalOptimizer,
    VoxCloudMaxBudget,
    VoxCloudPriceTtl,
    VoxCloudImage,
    VoxCloudMaxRuntime,
    VoxGpuModel,
    VoxGpuVramMb,
    VoxMeshTrain,
    VoxMeshRank,
    VoxBaseModel,
    VoxTrainProfile,
    VoxQwen35NativeCutover,
    VoxAllowQwen2Native,
    VoxMensTrainJsonlStrict,
    VoxVramOverrideGb,
    VoxCandleDevice,
    VoxQuestioningMirrorGlobalAttention,
    VoxMcpOrchestratorDaemonRepositoryIdStrict,

    VoxQuestioningMaxAttentionMs,
    VoxOratioLogitBiasStrength,
    VoxOratioLogitBiasMaxTokens,
    VoxOratioLogitForbidTokens,
    VoxOratioConstrainedTrie,
    VoxOratioConstrainedPhrases,
    VoxOratioTrieStuckSteps,
    VoxOratioSpeechLexiconPath,
    VoxOratioSessionHotwords,
    VoxOratioMaxBiasPhrases,
    VoxOratioContextualBias,
    VoxOratioAcousticPreprocessBudgetMs,
    VoxOratioModel,
    VoxOratioRevision,
    VoxOratioCuda,
    VoxOratioLanguage,
    VoxOratioChunkSec,
    VoxOratioChunkOverlapSec,
    VoxOratioEmitPartialPath,
    VoxOratioStreamTokens,
    VoxOratioSeed,
    VoxOratioVerbose,
    VoxOratioTask,
    VoxOratioNoSpeechThreshold,
    VoxPopuliModel,
    VoxPopuliTemperature,
    VoxPopuliMaxTokens,
    VoxSearchBm25K1,
    VoxSearchBm25B,
    VoxSearchRrfK,
    VoxSearchQdrantUrl,
    VoxSearchQdrantCollection,
    VoxSearchQdrantVectorName,
    VoxSearchTantivyRoot,
    VoxSearchPreferRrf,
    VoxSearchTavilyEnabled,
    VoxSearchTavilyDepth,
    VoxSearchTavilyMaxResults,
    VoxSearchTavilyOnEmpty,
    VoxSearchTavilyOnWeak,
    VoxSearchTavilyBudget,
    VoxSearchSearxngUrl,
    VoxSearchSearxngMaxResults,
    VoxSearchSearxngMaxScrape,
    VoxSearchSearxngEngines,
    VoxSearchSearxngLanguage,
    VoxSearchDdgFallbackDisabled,
    VoxSearchScraperTimeout,
    VoxSearchScraperRobotsRespect,
    VoxSearchScraperMinDensity,
    VoxSearchMaxHops,
    VoxSocialWorthinessEnforce,
    VoxReviewRepositoryId,
    VoxRegistryToken,
    VoxPmAllowGitUnverified,
    VoxCoderabbitGithubPerPage,
    VoxScriptCacheMaxEntries,
    VoxScriptCacheMaxSizeMb,
    VoxEvalMinParseRate,
    VoxEvalMinCoverage,
    VoxEvalStrict,
    VoxBenchmarkTelemetry,
    VoxSyntaxKTelemetry,
    VoxOpenclawSidecarDisable,
    VoxMeshCodexTelemetry,
    VoxOratioBackend,
    VoxOratioAcousticPreprocess,
    VoxOratioRmsTargetDbfs,
    VoxOratioRoutingSessionCap,
    VoxOratioRoutingSessionTtlSecs,
    VoxOratioStreamPartialQuietMs,
    VoxOratioStreamMaxWaitMs,
    VoxOratioConfig,
    VoxOratioToolRouteMinConfidence,
    VoxOratioVad,
    VoxOratioVadEnergyThreshold,
    VoxOratioVadMergeGapMs,
    VoxOratioSherpaModelDir,
    VoxOratioSherpaHfModel,
    VoxOratioSherpaModel,
    VoxMcpHttpHost,
    VoxMcpHttpPort,
    VoxMcpHttpRateLimitPerMinute,
    VoxMcpHttpAllowedTools,
    VoxMcpHttpReadRoleAllowedTools,
    VoxMcpHttpEnabled,
    VoxMcpHttpAllowUnauthenticated,
    VoxMcpHttpRequireForwardedHttps,
    VoxMcpHttpHealthAuth,
    VoxMcpHttpTrustXForwardedFor,
    VoxMcpHttpPublicEvalEnabled,
    VoxMeshMaxStaleMs,
    VoxMcpLlmCostEvents,
    VoxMcpGrammarMask,
    VoxMcpDecodePolicy,
    VoxAnthropicDirect,
    VoxOpenrouterHttpReferer,
    VoxOpenrouterAppTitle,
    VoxOpenrouterRouteHint,
    VoxCostPreference,
    VoxDogfoodTracePath,
    VoxBrowserLlmContextChars,
    VoxOllamaHost,
    VoxDashHost,
    VoxDashPort,
    VoxDashboardEnabled,
    VoxDashboardPort,
    VoxDashboardAutoOpen,
    VoxSubmitTaskBypassQuestioningGate,
    VoxWebTanstackStart,
    VoxLudusExperiment,
    VoxGroqChatCompletionsUrl,
    VoxCerebrasChatCompletionsUrl,
    VoxMistralChatCompletionsUrl,
    VoxDeepseekChatCompletionsUrl,
    VoxSambanovaChatCompletionsUrl,
    VoxAnthropicChatCompletionsUrl,
    VoxSearchPolicyVersion,
    VoxSearchMemoryVectorWeight,
    VoxSearchVerificationQualityThreshold,
    VoxSearchRepoMaxFiles,
    VoxSearchRepoSkipDirs,
    VoxGithubSha,
    VoxEmitExpressServer,
    VoxOrchestratorEventLog,
    VoxJsonOutput,
    VoxBenchmarkDir,
    VoxWebViteSmoke,
    VoxGuiPlaywright,
    VoxLineEndingsHead,
    VoxLineEndingsBase,
    VoxMensScorecardMaxTokens,
    VoxOpenclawSidecarExpectVersion,
    VoxCliGlobalJson,
    VoxToestubMaxRustParseFailures,
    VoxBuildTimingsBudgetWarn,
    VoxBuildTimingsBudgetFail,
    VoxScriptRelease,
    VoxCargoBin,
    SkipCudaFeatureCheck,
    VoxLudusChannel,
    VoxLudusMcpToolArgs,
    VoxLudusEmergencyOff,
    VoxLudusSessionEnabled,
    VoxLudusSessionMode,
    VoxLudusExperimentRewardMult,
    VoxSecretGuardGitRef,
    VoxMeshFederationSigningKey,
    VoxRoutingPreferMesh,
    TogetherTuningTemperature,
    TogetherTuningTopP,
    GeminiTuningTemperature,
    GeminiTuningTopP,
    OllamaTuningTemperature,
    OllamaTuningTopP,
    OllamaTuningNumCtx,
    OpenaiTuningTemperature,
    OpenaiTuningTopP,
    AnthropicTuningTemperature,
    AnthropicTuningTopP,
}

pub const ALL_CHAT_OPTIONALS: &[SecretId] = &[
    SecretId::GeminiApiKey,
    SecretId::OpenaiApiKey,
    SecretId::AnthropicApiKey,
    SecretId::HuggingFaceToken,
    SecretId::GroqApiKey,
    SecretId::CerebrasApiKey,
    SecretId::MistralApiKey,
    SecretId::DeepSeekApiKey,
    SecretId::SambaNovaApiKey,
    SecretId::CustomOpenaiApiKey,
];

pub const CHAT_CLOUD_PRIMARY: &[SecretId] = &[SecretId::OpenRouterApiKey];

impl std::str::FromStr for SecretId {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let clean = s.trim().to_uppercase();
        for reg in crate::spec::ALL_REGISTRIES {
            for spec in *reg {
                if spec.canonical_env.to_uppercase() == clean {
                    return Ok(spec.id);
                }
                for alias in spec.aliases {
                    if alias.to_uppercase() == clean {
                        return Ok(spec.id);
                    }
                }
                if format!("{:?}", spec.id).to_uppercase() == clean {
                    return Ok(spec.id);
                }
            }
        }
        Err(format!("Unknown SecretId: {}", s))
    }
}

impl SecretId {
    #[must_use]
    pub const fn metadata(self) -> SecretMetadata {
        match self {
            SecretId::GeminiApiKey
            | SecretId::OpenRouterApiKey
            | SecretId::OpenaiApiKey
            | SecretId::AnthropicApiKey
            | SecretId::HuggingFaceToken
            | SecretId::GroqApiKey
            | SecretId::CerebrasApiKey
            | SecretId::MistralApiKey
            | SecretId::DeepSeekApiKey
            | SecretId::SambaNovaApiKey
            | SecretId::CustomOpenaiApiKey
            | SecretId::TogetherApiKey
            | SecretId::VoxRunpodApiKey
            | SecretId::VoxVastApiKey
            | SecretId::PopuliApiKey
            | SecretId::V0ApiKey
            | SecretId::OpenClawToken
            | SecretId::OpenClawApiKey
            | SecretId::VoxSearchQdrantApiKey
            | SecretId::VoxCrossrefPlusApiKey
            | SecretId::VoxZenodoAccessToken
            | SecretId::VoxOrcidClientId
            | SecretId::VoxOrcidClientSecret
            | SecretId::VoxDataCiteRepository
            | SecretId::TavilyApiKey
            | SecretId::TavilyProject
            | SecretId::VoxDataCitePassword
            | SecretId::VoxIdentityKeyPath
            | SecretId::VoxGithubClientId
            | SecretId::VoxGithubOauthToken
            | SecretId::CoolifyToken
            | SecretId::TogetherTuningTemperature
            | SecretId::TogetherTuningTopP
            | SecretId::GeminiTuningTemperature
            | SecretId::GeminiTuningTopP
            | SecretId::OllamaTuningTemperature
            | SecretId::OllamaTuningTopP
            | SecretId::OllamaTuningNumCtx
            | SecretId::OpenaiTuningTemperature
            | SecretId::OpenaiTuningTopP
            | SecretId::AnthropicTuningTemperature
            | SecretId::AnthropicTuningTopP
            | SecretId::VoxIdentityMasterPwd => SecretMetadata {
                class: SecretClass::Integration,
                material_kind: SecretMaterialKind::ApiKey,
                persistable_account_secret: true,
                shareable: true,
                device_local_only: false,
                allow_env_in_strict: true,
                allow_compat_sources_in_strict: true,
                rotation_policy: RotationPolicy::Periodic,
                taxonomy_class: TaxonomyClass::AuxTooling,
                lifecycle: LifecycleMeta::MANUAL,
            },
            SecretId::WebhookSigningSecret
            | SecretId::VoxOpenReviewAccessToken
            | SecretId::VoxOpenReviewPassword
            | SecretId::VoxOpenReviewEmail
            | SecretId::VoxSocialRedditClientId
            | SecretId::VoxSocialRedditClientSecret
            | SecretId::VoxSocialRedditRefreshToken
            | SecretId::VoxSocialRedditUserAgent => SecretMetadata {
                class: SecretClass::Integration,
                material_kind: SecretMaterialKind::ApiKey,
                persistable_account_secret: true,
                shareable: true,
                device_local_only: false,
                allow_env_in_strict: false,
                allow_compat_sources_in_strict: false,
                rotation_policy: RotationPolicy::Periodic,
                taxonomy_class: TaxonomyClass::AuxTooling,
                lifecycle: LifecycleMeta::MANUAL,
            },
            _ => SecretMetadata {
                class: SecretClass::Operator,
                material_kind: SecretMaterialKind::ApiKey,
                persistable_account_secret: false,
                shareable: false,
                device_local_only: true,
                allow_env_in_strict: true,
                allow_compat_sources_in_strict: true,
                rotation_policy: RotationPolicy::Manual,
                taxonomy_class: TaxonomyClass::AuxTooling,
                lifecycle: LifecycleMeta::MANUAL,
            },
        }
    }

    #[must_use]
    pub const fn spec(self) -> &'static SecretSpec {
        let mut i = 0;
        while i < super::ALL_REGISTRIES.len() {
            let reg = super::ALL_REGISTRIES[i];
            let mut j = 0;
            while j < reg.len() {
                if reg[j].id as u32 == self as u32 {
                    return &reg[j];
                }
                j += 1;
            }
            i += 1;
        }
        panic!("SecretId must exist in SPECS")
    }
}
