use std::collections::HashMap;

use vox_ast::scalar_mapping::VoxScalar;
use vox_hir::{
    HirActivity, HirActor, HirBinOp, HirExpr, HirFn, HirHttpMethod, HirIndex, HirModule,
    HirPattern, HirRoute, HirServerFn, HirStmt, HirTable, HirType, HirWorkflow,
};

/// Output of [`generate`]: synthetic Cargo project files plus optional TS client source.
pub struct CodegenOutput {
    /// Relative path → file contents (e.g. `Cargo.toml`, `src/main.rs`).
    pub files: HashMap<String, String>,
    /// TypeScript API client for server functions (empty if no server fns)
    pub api_client_ts: String,
}

/// Emit a minimal Axum + Turso backend crate from `module` (paths relative to generated root).
pub fn generate(module: &HirModule, package_name: &str) -> Result<CodegenOutput, miette::Error> {
    let mut files = HashMap::new();

    // Cargo.toml
    files.insert("Cargo.toml".to_string(), emit_cargo_toml(package_name));

    // src/main.rs (Entry point + Routes)
    files.insert("src/main.rs".to_string(), emit_main(module, package_name));

    // src/lib.rs (Types, Actors, Workflows, Functions)
    files.insert("src/lib.rs".to_string(), emit_lib(module));

    // TypeScript API client
    let api_client_ts = emit_api_client(module);

    // MCP server (if @mcp.tool declarations are present)
    if !module.mcp_tools.is_empty() {
        files.insert(
            "src/mcp_server.rs".to_string(),
            emit_mcp_server(module, package_name),
        );
    }

    Ok(CodegenOutput {
        files,
        api_client_ts,
    })
}

/// `Cargo.toml` body for the generated Rust package `name`.
pub fn emit_cargo_toml(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "{edition}"

[workspace]

[dependencies]
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
axum = "0.7"
tower = "0.4"
rust-embed = "8"
mime_guess = "2"
reqwest = {{ version = "0.12", default-features = false, features = ["rustls-tls"] }}
tracing = "0.1"
tracing-subscriber = "0.3"
turso = {{ version = "0.4", default-features = false }}
vox-db = {{ path = "../../crates/vox-db" }}
vox-runtime = {{ path = "../../crates/vox-runtime" }}
vox-oratio = {{ path = "../../crates/vox-oratio" }}
"#,
        edition = crate::GENERATED_CARGO_EDITION,
    )
}

/// `src/main.rs`: Axum router, static assets, optional MCP server wiring.
pub fn emit_main(module: &HirModule, package_name: &str) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Vox Compiler\n");

    let has_tables = !module.tables.is_empty();

    // Collect which routing methods are actually used
    let mut needs_get = false;
    let mut needs_post = false;
    let mut needs_put = false;
    let mut needs_delete = false;
    for route in &module.routes {
        match route.method {
            HirHttpMethod::Get => needs_get = true,
            HirHttpMethod::Post => needs_post = true,
            HirHttpMethod::Put => needs_put = true,
            HirHttpMethod::Delete => needs_delete = true,
        }
    }
    // Server functions always use post
    if !module.server_fns.is_empty() {
        needs_post = true;
    }

    let mut routing_methods = Vec::new();
    if needs_get {
        routing_methods.push("get");
    }
    if needs_post {
        routing_methods.push("post");
    }
    if needs_put {
        routing_methods.push("put");
    }
    if needs_delete {
        routing_methods.push("delete");
    }

    if routing_methods.is_empty() {
        out.push_str("use axum::Router;\n");
    } else {
        out.push_str(&format!(
            "use axum::{{Router, routing::{{{}}}, Json}};\n",
            routing_methods.join(", ")
        ));
    }
    out.push_str("use axum::response::{Response, IntoResponse};\n");
    out.push_str("use axum::body::Body;\n");
    out.push_str("use axum::http::{StatusCode, header};\n");
    out.push_str("use std::net::SocketAddr;\n");
    out.push_str("use rust_embed::Embed;\n");
    if has_tables {
        out.push_str("use std::sync::Arc;\n");
        out.push_str("use axum::extract::Extension;\n");
        out.push_str("use vox_db::Codex;\n");
    }

    // Use the library crate by name (avoids `mod lib;` warning)
    let crate_name = package_name.replace('-', "_");
    out.push_str(&format!("use {}::*;\n\n", crate_name));

    // Embedded static assets
    out.push_str("#[derive(Embed)]\n");
    out.push_str("#[folder = \"public/\"]\n");
    out.push_str("struct Assets;\n\n");

    // Fallback handler for embedded assets
    out.push_str("async fn serve_embedded(uri: axum::http::Uri) -> Response {\n");
    out.push_str("    let path = uri.path().trim_start_matches('/');\n");
    out.push_str("    let path = if path.is_empty() { \"index.html\" } else { path };\n");
    out.push_str("    match Assets::get(path) {\n");
    out.push_str("        Some(file) => {\n");
    out.push_str("            let mime = mime_guess::from_path(path).first_or_octet_stream();\n");
    out.push_str("            (StatusCode::OK, [(header::CONTENT_TYPE, mime.as_ref().to_string())], file.data.to_vec()).into_response()\n");
    out.push_str("        }\n");
    out.push_str("        None => {\n");
    out.push_str("            // SPA fallback: serve index.html for client-side routing\n");
    out.push_str("            match Assets::get(\"index.html\") {\n");
    out.push_str("                Some(file) => (StatusCode::OK, [(header::CONTENT_TYPE, \"text/html\".to_string())], file.data.to_vec()).into_response(),\n");
    out.push_str(
        "                None => (StatusCode::NOT_FOUND, \"Not Found\").into_response(),\n",
    );
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str(
        "async fn serve_dispatch(req: axum::http::Request<Body>) -> Response {\n",
    );
    out.push_str("    let uri = req.uri().clone();\n");
    out.push_str("    if *req.method() == axum::http::Method::GET {\n");
    out.push_str("        if let Ok(base) = std::env::var(\"VOX_SSR_DEV_URL\") {\n");
    out.push_str("            let base = base.trim();\n");
    out.push_str("            if !base.is_empty() {\n");
    out.push_str("                let p = uri.path();\n");
    out.push_str("                if !p.starts_with(\"/api\") {\n");
    out.push_str(
        "                    let target = format!(\"{}{}\", base.trim_end_matches('/'), uri);\n",
    );
    out.push_str("                    if let Ok(client) = reqwest::Client::builder()\n");
    out.push_str("                        .timeout(std::time::Duration::from_secs(60))\n");
    out.push_str("                        .build()\n");
    out.push_str("                    {\n");
    out.push_str("                        if let Ok(resp) = client.get(target).send().await {\n");
    out.push_str("                            let status = resp.status();\n");
    out.push_str("                            let ct = resp.headers().get(reqwest::header::CONTENT_TYPE).cloned();\n");
    out.push_str("                            let bytes = resp.bytes().await.unwrap_or_default();\n");
    out.push_str("                            let code = axum::http::StatusCode::from_u16(status.as_u16())\n");
    out.push_str("                                .unwrap_or(axum::http::StatusCode::BAD_GATEWAY);\n");
    out.push_str("                            let mut builder = Response::builder().status(code);\n");
    out.push_str("                            if let Some(ct) = ct {\n");
    out.push_str("                                if let Ok(v) = ct.to_str() {\n");
    out.push_str("                                    builder = builder.header(header::CONTENT_TYPE, v);\n");
    out.push_str("                                }\n");
    out.push_str("                            }\n");
    out.push_str("                            if let Ok(out) = builder.body(Body::from(bytes)) {\n");
    out.push_str("                                return out;\n");
    out.push_str("                            }\n");
    out.push_str("                        }\n");
    out.push_str("                    }\n");
    out.push_str("                }\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    serve_embedded(uri).await\n");
    out.push_str("}\n\n");

    out.push_str("#[tokio::main]\n");
    out.push_str("async fn main() {\n");
    out.push_str("    tracing_subscriber::fmt::init();\n");

    // Database setup
    if has_tables {
        out.push_str(&emit_db_setup(module));
    }

    let has_routes = !module.routes.is_empty() || !module.server_fns.is_empty();

    // Setup routes
    if has_routes {
        out.push_str("    let app = Router::new()\n");
        // Manual routes
        for route in &module.routes {
            let method = match route.method {
                HirHttpMethod::Get => "get",
                HirHttpMethod::Post => "post",
                HirHttpMethod::Put => "put",
                HirHttpMethod::Delete => "delete",
            };
            out.push_str(&format!(
                "        .route(\"{}\", {}({}))\n",
                route.path,
                method,
                route_handler_name(&route.path, &route.method)
            ));
        }
        // Auto-generated server function routes
        for sf in &module.server_fns {
            out.push_str(&format!(
                "        .route(\"{}\", post(handle_sf_{}))\n",
                sf.route_path, sf.name
            ));
        }
        out.push_str("        .fallback(serve_dispatch);\n\n");

        if has_tables {
            out.push_str("    let app = app.layer(Extension(db.clone()));\n");
        }

        out.push_str("    let port: u16 = std::env::var(\"VOX_PORT\")\n");
        out.push_str("        .ok()\n");
        out.push_str("        .and_then(|s| s.parse().ok())\n");
        out.push_str("        .unwrap_or(3000);\n");
        out.push_str("    let addr = SocketAddr::from(([127, 0, 0, 1], port));\n");
        out.push_str("    println!(\"Listening on {}\", addr);\n");
        out.push_str(
            "    let listener = tokio::net::TcpListener::bind(addr).await.expect(\"Failed to bind TCP listener\");\n",
        );
        out.push_str(
            "    axum::serve(listener, app).await.expect(\"Server exited with error\");\n",
        );
    } else {
        out.push_str("    println!(\"No routes defined. Exiting.\");\n");
    }
    out.push_str("}\n\n");

    // Generate route handlers
    for route in &module.routes {
        out.push_str(&emit_route_handler(route, has_tables));
    }

    // Generate server function handlers
    for sf in &module.server_fns {
        out.push_str(&emit_server_fn_handler(sf, has_tables));
    }

    out
}

fn route_handler_name(path: &str, method: &HirHttpMethod) -> String {
    let clean_path = path.replace('/', "_").replace(['{', '}'], "");
    let m = match method {
        HirHttpMethod::Get => "get",
        HirHttpMethod::Post => "post",
        HirHttpMethod::Put => "put",
        HirHttpMethod::Delete => "delete",
    };
    format!("handle_{}{}", m, clean_path)
}

fn emit_route_handler(route: &HirRoute, has_tables: bool) -> String {
    let handler_name = route_handler_name(&route.path, &route.method);
    let mut out = String::new();
    out.push_str(&format!("async fn {handler_name}("));
    if has_tables {
        out.push_str("Extension(db): Extension<Arc<Codex>>, ");
    }
    out.push_str("Json(request): Json<serde_json::Value>) -> Json<serde_json::Value> {\n");

    let mut has_return = false;
    for stmt in &route.body {
        let emitted = emit_stmt(stmt, 1, true, false);
        if emitted.contains("return Json(") {
            has_return = true;
        }
        out.push_str(&emitted);
    }
    if !has_return {
        out.push_str("    Json(serde_json::Value::Null)\n");
    }
    out.push_str("}\n\n");
    out
}

/// Generate an Axum handler for a server function.
fn emit_server_fn_handler(sf: &HirServerFn, has_tables: bool) -> String {
    let mut out = String::new();
    out.push_str(&format!("async fn handle_sf_{}(", sf.name));
    if has_tables {
        out.push_str("Extension(db): Extension<Arc<Codex>>, ");
    }
    out.push_str("Json(request): Json<serde_json::Value>) -> Json<serde_json::Value> {\n");

    // Extract params from request JSON
    for param in &sf.params {
        out.push_str(&format!(
            "    let {} = request[\"{}\"].clone();\n",
            param.name, param.name
        ));
    }

    let mut has_return = false;
    for stmt in &sf.body {
        let emitted = emit_stmt(stmt, 1, true, false);
        if emitted.contains("return Json(") {
            has_return = true;
        }
        out.push_str(&emitted);
    }
    if !has_return {
        out.push_str("    Json(serde_json::Value::Null)\n");
    }
    out.push_str("}\n\n");
    out
}

/// `src/lib.rs`: types, actors, workflows, routes glue, tables, server fns, tests.
pub fn emit_lib(module: &HirModule) -> String {
    let mut out = String::new();
    out.push_str("use serde::{Serialize, Deserialize};\n");

    // Only import runtime types when actors are present
    if !module.actors.is_empty() {
        out.push_str(
            "use vox_runtime::{ProcessContext, Envelope, MessagePayload, Pid, Message};\n",
        );
    }

    if !module.tables.is_empty() {
        out.push_str("use vox_db::Codex;\n");
    }

    out.push('\n');

    // Helper for casts
    out.push_str("pub fn as_string<T: serde::Serialize>(v: &T) -> String {\n");
    out.push_str("    let val = serde_json::to_value(v).expect(\"vox codegen: serde_json::to_value failed\");\n");
    out.push_str("    if let Some(s) = val.as_str() { s.to_string() } else { val.to_string() }\n");
    out.push_str("}\n\n");

    // Only emit append helper when actors are present (used for list operations in handlers)
    if !module.actors.is_empty() {
        out.push_str("pub fn append(list: &Vec<serde_json::Value>, item: &serde_json::Value) -> Vec<serde_json::Value> {\n");
        out.push_str("    let mut new_list = list.clone();\n");
        out.push_str("    new_list.push(item.clone());\n");
        out.push_str("    new_list\n");
        out.push_str("}\n\n");
    }

    // Re-export variants
    for typedef in &module.types {
        out.push_str(&format!("pub use self::{}::*;\n", typedef.name));
    }

    // Types
    for typedef in &module.types {
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str(&format!("pub enum {} {{\n", typedef.name));
        for variant in &typedef.variants {
            if variant.fields.is_empty() {
                out.push_str(&format!("    {},\n", variant.name));
            } else {
                out.push_str(&format!("    {}(", variant.name));
                for (_fname, ftype) in &variant.fields {
                    out.push_str(&format!("{}, ", emit_type(ftype)));
                }
                out.push_str("),\n");
            }
        }
        out.push_str("}\n\n");
    }

    // Table structs
    for table in &module.tables {
        out.push_str(&emit_table_struct(table));
    }

    // Functions (skip components)
    for func in &module.functions {
        if !func.is_component {
            out.push_str(&emit_fn(func));
        }
    }

    // Workflows (async functions with durable execution semantics)
    for workflow in &module.workflows {
        out.push_str(&emit_workflow(workflow));
    }

    // Activities (async functions with retry/timeout support)
    for activity in &module.activities {
        out.push_str(&emit_activity(activity));
    }

    // Actors
    for actor in &module.actors {
        out.push_str(&emit_actor(actor));
    }

    // Tests
    for test in &module.tests {
        if test.is_async {
            out.push_str("#[tokio::test]\n");
        } else {
            out.push_str("#[test]\n");
        }
        out.push_str(&emit_fn(test));
    }

    out
}

/// Emit a single HIR function (or test) as Rust source.
pub fn emit_fn(func: &HirFn) -> String {
    let mut out = String::new();
    let pub_kw = if func.is_pub { "pub " } else { "" };
    let async_kw = if func.is_async { "async " } else { "" };
    out.push_str(&format!("{}{}fn {}(", pub_kw, async_kw, func.name));
    for param in &func.params {
        out.push_str(&format!(
            "{}: {}, ",
            param.name,
            emit_type(
                param
                    .type_ann
                    .as_ref()
                    .unwrap_or(&HirType::Named("serde_json::Value".into()))
            )
        ));
    }
    out.push_str(") ");
    if let Some(ret) = &func.return_type {
        out.push_str(&format!("-> {} ", emit_type(ret)));
    }
    out.push_str("{\n");
    for stmt in &func.body {
        out.push_str(&emit_stmt(stmt, 1, false, false));
    }
    out.push_str("}\n\n");
    out
}

fn emit_activity(func: &HirActivity) -> String {
    let mut out = String::new();
    // Activities are always async public functions in the library crate
    out.push_str(&format!("pub async fn {}(", func.name));
    for param in &func.params {
        out.push_str(&format!(
            "{}: {}, ",
            param.name,
            emit_type(
                param
                    .type_ann
                    .as_ref()
                    .unwrap_or(&HirType::Named("serde_json::Value".into()))
            )
        ));
    }
    out.push_str(") ");
    if let Some(ret) = &func.return_type {
        out.push_str(&format!("-> {} ", emit_type(ret)));
    }
    out.push_str("{\n");
    for stmt in &func.body {
        out.push_str(&emit_stmt(stmt, 1, false, false));
    }
    out.push_str("}\n\n");
    out
}

fn emit_workflow(wf: &HirWorkflow) -> String {
    let mut out = String::new();
    // Workflows are async public functions (orchestrators of activities)
    out.push_str(&format!("pub async fn {}(", wf.name));
    for param in &wf.params {
        out.push_str(&format!(
            "{}: {}, ",
            param.name,
            emit_type(
                param
                    .type_ann
                    .as_ref()
                    .unwrap_or(&HirType::Named("serde_json::Value".into()))
            )
        ));
    }
    out.push_str(") ");
    if let Some(ret) = &wf.return_type {
        out.push_str(&format!("-> {} ", emit_type(ret)));
    }
    out.push_str("{\n");
    for stmt in &wf.body {
        out.push_str(&emit_stmt(stmt, 1, false, false));
    }
    out.push_str("}\n\n");
    out
}

fn emit_actor(actor: &HirActor) -> String {
    let mut out = String::new();
    let msg_enum = format!("{}Message", actor.name);

    // Actor Message Enum
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub enum {} {{\n", msg_enum));
    for handler in &actor.handlers {
        out.push_str(&format!("    {} {{ ", capitalize(&handler.event_name)));
        for param in &handler.params {
            out.push_str(&format!(
                "{}: {}, ",
                param.name,
                emit_type(
                    param
                        .type_ann
                        .as_ref()
                        .unwrap_or(&HirType::Named("serde_json::Value".into()))
                )
            ));
        }
        out.push_str("},\n");
    }
    out.push_str("}\n\n");

    // Actor Logic — handles Request envelopes with reply channels
    out.push_str(&format!("pub struct {};\n", actor.name));
    out.push_str(&format!("impl {} {{\n", actor.name));
    out.push_str("    pub async fn run(mut ctx: ProcessContext) {\n");
    out.push_str("        while let Some(envelope) = ctx.receive().await {\n");
    out.push_str("            match envelope {\n");
    out.push_str("                vox_runtime::Envelope::Request(req) => {\n");
    out.push_str(
        "                    if let vox_runtime::MessagePayload::Json(json_str) = &req.payload {\n",
    );
    out.push_str(&format!(
        "                        if let Ok(actor_msg) = serde_json::from_str::<{}>(&json_str) {{\n",
        msg_enum
    ));
    out.push_str("                            let reply_str = match actor_msg {\n");

    for handler in &actor.handlers {
        out.push_str(&format!(
            "                                {}::{} {{ ",
            msg_enum,
            capitalize(&handler.event_name)
        ));
        for param in &handler.params {
            out.push_str(&format!("{}, ", param.name));
        }
        out.push_str("} => {\n");
        // Emit handler body statements. The last expression is the reply value.
        // Must produce a String — serialize if needed.
        if handler.body.is_empty() {
            out.push_str("                                    String::new()\n");
        } else {
            // Emit all statements except the last as regular statements
            for stmt in &handler.body[..handler.body.len().saturating_sub(1)] {
                out.push_str(&emit_stmt(stmt, 10, false, true));
            }
            // For the last statement, extract the value and serialize to String
            if let Some(last) = handler.body.last() {
                match last {
                    HirStmt::Return {
                        value: Some(val), ..
                    } => {
                        let val_str = emit_expr(val);
                        out.push_str(&format!("                                    serde_json::to_string(&({})).unwrap_or_default()\n", val_str));
                    }
                    HirStmt::Expr { expr, .. } => {
                        let val_str = emit_expr(expr);
                        out.push_str(&format!("                                    serde_json::to_string(&({})).unwrap_or_default()\n", val_str));
                    }
                    _ => {
                        out.push_str(&emit_stmt(last, 10, false, true));
                        out.push_str("                                    String::new()\n");
                    }
                }
            }
        }
        out.push_str("                                }\n");
    }

    out.push_str("                            };\n");
    out.push_str("                            ProcessContext::reply(req, reply_str);\n");
    out.push_str("                        }\n");
    out.push_str("                    }\n");
    out.push_str("                }\n");
    out.push_str("                vox_runtime::Envelope::Message(msg) => {\n");
    out.push_str("                    // Fire-and-forget: process but don't reply\n");
    out.push_str(
        "                    if let vox_runtime::MessagePayload::Json(json_str) = msg.payload {\n",
    );
    out.push_str(&format!(
        "                        if let Ok(actor_msg) = serde_json::from_str::<{}>(&json_str) {{\n",
        msg_enum
    ));
    out.push_str("                            let _ = actor_msg; // processed\n");
    out.push_str("                        }\n");
    out.push_str("                    }\n");
    out.push_str("                }\n");
    out.push_str("                _ => {}\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Typed Handle — uses call() for request-response
    out.push_str(&format!(
        "#[derive(Clone)]\npub struct {}Handle {{\n",
        actor.name
    ));
    out.push_str("    handle: vox_runtime::ProcessHandle,\n");
    out.push_str("}\n");
    out.push_str(&format!("impl {}Handle {{\n", actor.name));
    out.push_str(
        "    pub fn new(handle: vox_runtime::ProcessHandle) -> Self { Self { handle } }\n",
    );
    out.push_str("    pub fn spawn() -> Self {\n");
    out.push_str(&format!(
        "        let handle = vox_runtime::spawn_process({}::run);\n",
        actor.name
    ));
    out.push_str("        Self::new(handle)\n");
    out.push_str("    }\n");

    for handler in &actor.handlers {
        out.push_str(&format!("    pub async fn {}(&self, ", handler.event_name));
        for param in &handler.params {
            out.push_str(&format!(
                "{}: {}, ",
                param.name,
                emit_type(
                    param
                        .type_ann
                        .as_ref()
                        .unwrap_or(&HirType::Named("serde_json::Value".into()))
                )
            ));
        }
        out.push_str(") -> String {\n");
        out.push_str(&format!(
            "        let msg = {}::{} {{ ",
            msg_enum,
            capitalize(&handler.event_name)
        ));
        for param in &handler.params {
            out.push_str(&format!("{}, ", param.name));
        }
        out.push_str("};\n");
        out.push_str("        let payload = vox_runtime::MessagePayload::Json(serde_json::to_string(&msg).expect(\"vox codegen: actor message JSON\"));\n");
        out.push_str("        self.handle.call(payload).await.unwrap_or_else(|e| format!(\"Actor error: {}\", e))\n");
        out.push_str("    }\n");
    }
    out.push_str("}\n\n");

    out
}

fn emit_type(ty: &HirType) -> String {
    match ty {
        HirType::Named(n) => match n.as_str() {
            "int" => "i64".into(),
            "float" => "f64".into(),
            "bool" => "bool".into(),
            "str" => "String".into(),
            "Element" | "Result" | "Any" => "serde_json::Value".into(),
            other => other.to_string(),
        },
        HirType::Generic(n, args) => {
            let args_str: Vec<_> = args.iter().map(emit_type).collect();
            match n.as_str() {
                // Id[Task] → i64 (SQLite rowid)
                "Id" => "i64".into(),
                "List" | "list" => format!(
                    "Vec<{}>",
                    args_str.first().unwrap_or(&"serde_json::Value".to_string())
                ),
                "Option" => format!(
                    "Option<{}>",
                    args_str.first().unwrap_or(&"serde_json::Value".to_string())
                ),
                _ => format!("{}<{}>", n, args_str.join(", ")),
            }
        }
        HirType::Unit => "()".into(),
        _ => "serde_json::Value".into(),
    }
}

/// Map a Vox HIR type to a SQLite column type.
fn hir_type_to_sql(ty: &HirType) -> &'static str {
    match ty {
        HirType::Named(n) => {
            if let Some(s) = VoxScalar::parse(n) {
                s.as_sqlite_affinity()
            } else {
                "TEXT" // Fallback: serialize as JSON text
            }
        }
        HirType::Generic(n, _) => match n.as_str() {
            "Id" => "INTEGER",  // Foreign key reference
            "Option" => "TEXT", // Nullable, type handled at Rust level
            _ => "TEXT",        // Complex types serialized as JSON
        },
        _ => "TEXT",
    }
}

/// Generate a Rust struct for a @table type w/ methods (tests and tooling).
pub fn emit_table_struct(table: &HirTable) -> String {
    let mut out = String::new();
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", table.name));
    out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
    out.push_str("    pub _id: Option<i64>,\n");
    for field in &table.fields {
        out.push_str(&format!(
            "    pub {}: {},\n",
            field.name,
            emit_type(&field.type_ann)
        ));
    }
    out.push_str("}\n\n");

    // Helper to check if a type needs JSON serialization for SQL
    let is_json = |ty: &HirType| -> bool {
        match ty {
            HirType::Named(n) => VoxScalar::parse(n).is_none(),
            HirType::Generic(n, args) => {
                if n == "Option" {
                    // Option<T>: if T is simple, it's simple. If T is complex, it's JSON.
                    match &args[0] {
                        HirType::Named(sub) => VoxScalar::parse(sub).is_none(),
                        _ => true,
                    }
                } else if n == "Id" {
                    false
                } else {
                    true // List, etc.
                }
            }
            _ => true, // Unit, tuple etc.
        }
    };

    out.push_str(&format!("impl {} {{\n", table.name));

    let col_names: Vec<&String> = table.fields.iter().map(|f| &f.name).collect();
    let placeholders: Vec<String> = (1..=col_names.len()).map(|i| format!("?{}", i)).collect();
    let tn = table.name.to_lowercase();

    // -- insert
    out.push_str(
        "    pub async fn insert(db: &Codex, item: &Self) -> Result<i64, turso::Error> {\n",
    );
    for field in &table.fields {
        if is_json(&field.type_ann) {
            out.push_str(&format!(
                "        let {}_json = serde_json::to_string(&item.{}).map_err(|e| turso::Error::ConversionFailure(format!(\"serde_json: {{}}\", e)))?;\n",
                field.name, field.name
            ));
        }
    }
    out.push_str(&format!(
        "        db.store().conn.execute(\n            \"INSERT INTO {} ({}) VALUES ({})\",\n            turso::params![",
        tn,
        col_names
            .iter()
            .map(|s| s.as_str())
            .collect::<Vec<_>>()
            .join(", "),
        placeholders.join(", ")
    ));
    for (i, field) in table.fields.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        if is_json(&field.type_ann) {
            out.push_str(&format!("{}_json", field.name));
        } else {
            out.push_str(&format!("item.{}.clone()", field.name));
        }
    }
    out.push_str("],\n        ).await?;\n");
    out.push_str("        Ok(db.store().conn.last_insert_rowid())\n");
    out.push_str("    }\n\n");

    // -- get
    out.push_str(
        "    pub async fn get(db: &Codex, id: i64) -> Result<Option<Self>, turso::Error> {\n",
    );
    out.push_str(&format!(
        "        let mut rows = db.store().conn.query(\"SELECT * FROM {} WHERE _id = ?1\", turso::params![id]).await?;\n",
        tn
    ));
    out.push_str("        Ok(match rows.next().await? {\n");
    out.push_str("            Some(row) => Some(Self::from_row(&row)?),\n");
    out.push_str("            None => None,\n");
    out.push_str("        })\n");
    out.push_str("    }\n\n");

    // -- query (clause appended to SELECT * FROM table …)
    out.push_str(
        "    pub async fn query(db: &Codex, clause: &str) -> Result<Vec<Self>, turso::Error> {\n",
    );
    out.push_str(&format!(
        "        let sql = format!(\"SELECT * FROM {} {{}}\", clause);\n",
        tn
    ));
    out.push_str(
        "        let mut rows = db.store().conn.query(&sql, ()).await?;\n        let mut out = Vec::new();\n        while let Some(row) = rows.next().await? {\n            out.push(Self::from_row(&row)?);\n        }\n        Ok(out)\n",
    );
    out.push_str("    }\n\n");

    // -- delete
    out.push_str("    pub async fn delete(db: &Codex, id: i64) -> Result<usize, turso::Error> {\n");
    out.push_str(&format!(
        "        let n = db.store().conn.execute(\"DELETE FROM {} WHERE _id = ?1\", turso::params![id]).await?;\n",
        tn
    ));
    out.push_str("        Ok(n as usize)\n");
    out.push_str("    }\n\n");

    // -- from_row (column order: _id, then fields in declaration order)
    out.push_str("    fn from_row(row: &turso::Row) -> Result<Self, turso::Error> {\n");
    out.push_str("        let _id_val: i64 = row.get(0)?;\n");
    let mut col_idx: usize = 1;
    out.push_str("        Ok(Self {\n");
    out.push_str("            _id: Some(_id_val),\n");
    for field in &table.fields {
        if is_json(&field.type_ann) {
            out.push_str(&format!(
                "            {}: {{\n                let s: String = row.get({})?;\n                serde_json::from_str(&s).map_err(|e| turso::Error::ConversionFailure(format!(\"JSON decode on {}.{} row _id {{}}: {{}}\", _id_val, e)))?\n            }},\n",
                field.name, col_idx, tn, field.name
            ));
        } else {
            out.push_str(&format!(
                "            {}: row.get({})?,\n",
                field.name, col_idx
            ));
        }
        col_idx += 1;
    }
    out.push_str("        })\n");
    out.push_str("    }\n");

    out.push_str("}\n\n");
    out
}

/// Generate `CREATE TABLE IF NOT EXISTS` DDL for a @table.
pub fn emit_table_ddl(table: &HirTable) -> String {
    let table_name = table.name.to_lowercase();
    let mut cols = vec!["_id INTEGER PRIMARY KEY AUTOINCREMENT".to_string()];
    for field in &table.fields {
        let sql_type = hir_type_to_sql(&field.type_ann);
        let not_null = if matches!(&field.type_ann, HirType::Generic(n, _) if n == "Option") {
            ""
        } else {
            " NOT NULL"
        };
        cols.push(format!("    {} {}{}", field.name, sql_type, not_null));
    }
    format!(
        "CREATE TABLE IF NOT EXISTS {} (\n{}\n);",
        table_name,
        cols.join(",\n")
    )
}

/// Generate `CREATE INDEX IF NOT EXISTS` DDL for a @index.
pub fn emit_index_ddl(index: &HirIndex) -> String {
    let table_name = index.table_name.to_lowercase();
    format!(
        "CREATE INDEX IF NOT EXISTS idx_{table}_{name} ON {table} ({cols});",
        table = table_name,
        name = index.index_name,
        cols = index.columns.join(", "),
    )
}

/// Generate the DB initialization code for `main()` (Turso / libSQL).
///
/// Opens **Codex** via `vox_db::DbConfig::resolve_standalone` (VOX_DB_*, legacy TURSO_*, or local file).
fn emit_db_setup(module: &HirModule) -> String {
    let mut out = String::new();
    out.push_str("    // ── Database setup (Codex / vox_db) ──\n");
    out.push_str(
        "    let cfg = vox_db::DbConfig::resolve_standalone().expect(\"resolve Codex DB config (VOX_DB_URL+TOKEN, VOX_DB_PATH, or TURSO_URL+TURSO_AUTH_TOKEN)\");\n",
    );
    out.push_str(
        "    let codex = vox_db::Codex::connect(cfg).await.expect(\"Failed to open Codex database\");\n",
    );
    out.push_str(
        "    codex.store().conn.execute_batch(\"PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;\").await.expect(\"PRAGMA failed\");\n",
    );
    out.push_str("    codex.store().conn.execute_batch(r#\"\n");
    for table in &module.tables {
        out.push_str(&emit_table_ddl(table));
        out.push('\n');
    }
    for index in &module.indexes {
        out.push_str(&emit_index_ddl(index));
        out.push('\n');
    }
    out.push_str("#\"#).await.expect(\"schema migration failed\");\n");
    out.push_str("    let db = Arc::new(codex);\n\n");
    out
}

fn emit_stmt(stmt: &HirStmt, indent: usize, is_route: bool, is_actor: bool) -> String {
    let pad = " ".repeat(indent * 4);
    match stmt {
        HirStmt::Let {
            pattern,
            value,
            mutable,
            ..
        } => {
            let mut_kw = if *mutable { "mut " } else { "" };
            format!(
                "{pad}let {}{} = {};\n",
                mut_kw,
                emit_pattern(pattern),
                emit_expr(value)
            )
        }
        HirStmt::Assign { target, value, .. } => {
            format!("{pad}{} = {};\n", emit_expr(target), emit_expr(value))
        }
        HirStmt::Return { value, .. } => {
            if is_actor {
                if let Some(v) = value {
                    format!(
                        "{pad}let _ = {}; // return ignored in actor; scaffolding only\n",
                        emit_expr(v)
                    )
                } else {
                    format!("{pad}// return ignored in actor; scaffolding only\n")
                }
            } else if let Some(v) = value {
                let expr_str = emit_expr(v);
                if is_route {
                    format!(
                        "{pad}return Json(serde_json::to_value({}).expect(\"vox codegen: route return JSON\"));\n",
                        expr_str
                    )
                } else {
                    format!("{pad}return {};\n", expr_str)
                }
            } else if is_route {
                format!("{pad}return Json(serde_json::Value::Null);\n")
            } else {
                format!("{pad}return;\n")
            }
        }
        HirStmt::Expr { expr, .. } => {
            format!("{pad}{};\n", emit_expr(expr))
        }
    }
}

/// Emit one statement for script-mode `main` (no route/actor return wrapping).
pub fn emit_main_stmt(stmt: &HirStmt, indent: usize) -> String {
    emit_stmt(stmt, indent, false, false)
}

fn emit_pattern(pat: &HirPattern) -> String {
    match pat {
        HirPattern::Ident(n, _) => n.clone(),
        HirPattern::Wildcard(_) => "_".into(),
        HirPattern::Literal(lit, _) => emit_expr(lit),
        HirPattern::Tuple(pats, _) => format!(
            "({})",
            pats.iter().map(emit_pattern).collect::<Vec<_>>().join(", ")
        ),
        HirPattern::Constructor(n, pats, _) => {
            // Rust struct variant syntax: Name { field: val }
            // HirPattern::Constructor has positional args?
            // "Ok(text: str)" -> Constructor("Ok", [Ident("text")])
            // Rust enum: Ok { text: ... } or Ok(...) depending on def.
            // Vox ADTs use named fields. So we matched on Struct names.
            // Wait, parse_typedef uses named fields.
            // But pattern matching? "Ok(r) -> r". This is positional.
            // My ADT generator emitted named fields: `Variant { field: Type }`.
            // Rust requires named matching if defined with names.
            // Or use tuple variants if positional.
            // Vox defines `| Ok(text: str)`. This is named.
            // So `Ok(t)` in match needs to be `Ok { text: t }`.
            // BUT the parser/HIR doesn't resolve positional match to named fields yet.
            // This is a semantic gap.
            // Workaround: Use tuple variants in Rust if possible, or assume names match?
            // "Ok(r)" -> pattern is Constructor("Ok", [Ident("r")]).
            // We don't know the field name "text" here without looking up the definition.
            // For now, emit as tuple style `Ok(p1, p2)` and hope the ADT generation uses tuple variants?
            // In emit_lib: `variant.fields` are named.
            // If I change emit_lib to use tuple variants if fields are present?
            // Or structs?
            // Vox syntax `Ok(text: str)` looks like named.
            // But usage `Ok("hi")` looks positional.
            // Let's generate Tuple variants in Rust for simplicity: `Ok(String)`.
            // And ignore field names in TypeDef?
            // Or use the names?
            format!(
                "{}({})",
                n,
                pats.iter().map(emit_pattern).collect::<Vec<_>>().join(", ")
            )
        }
    }
}

/// Emit one HIR expression as a Rust expression string (for nested codegen / tools).
pub fn emit_expr(expr: &HirExpr) -> String {
    match expr {
        HirExpr::IntLit(v, _) => v.to_string(),
        HirExpr::FloatLit(v, _) => v.to_string(),
        HirExpr::StringLit(v, _) => format!("\"{}\".to_string()", v),
        HirExpr::BoolLit(v, _) => v.to_string(),
        HirExpr::Ident(n, _) => {
            if n == "request" {
                "request".into()
            } else if n.chars().next().map(|c| c.is_uppercase()).unwrap_or(false) {
                n.clone()
            } else {
                format!("{}.clone()", n)
            }
        }
        HirExpr::Binary(op, l, r, _) => {
            let op_str = match op {
                HirBinOp::Add => "+",
                HirBinOp::Sub => "-",
                HirBinOp::Mul => "*",
                HirBinOp::Div => "/",
                HirBinOp::Lt => "<",
                HirBinOp::Gt => ">",
                HirBinOp::Lte => "<=",
                HirBinOp::Gte => ">=",
                HirBinOp::And => "&&",
                HirBinOp::Or => "||",
                HirBinOp::Is => "==",
                HirBinOp::Isnt => "!=",
                HirBinOp::Pipe => return format!("{}({})", emit_expr(r), emit_expr(l)),
            };
            if matches!(
                op,
                HirBinOp::Add | HirBinOp::Sub | HirBinOp::Mul | HirBinOp::Div
            ) {
                format!("({} {} &{})", emit_expr(l), op_str, emit_expr(r))
            } else {
                format!("({} {} {})", emit_expr(l), op_str, emit_expr(r))
            }
        }
        HirExpr::Call(callee, args, is_await, _) => {
            if let HirExpr::Ident(n, _) = &**callee {
                if n == "str" && args.len() == 1 {
                    return format!("as_string(&{})", emit_expr(&args[0].value));
                }
                if n == "assert" && args.len() == 1 {
                    if let HirExpr::Binary(HirBinOp::Is, l, r, _) = &args[0].value {
                        return format!("assert_eq!({}, {})", emit_expr(l), emit_expr(r));
                    }
                    return format!("assert!({})", emit_expr(&args[0].value));
                }
                if n == "assert_eq" && args.len() >= 2 {
                    return format!(
                        "assert_eq!({}, {})",
                        emit_expr(&args[0].value),
                        emit_expr(&args[1].value)
                    );
                }
                if n == "assert_ne" && args.len() >= 2 {
                    return format!(
                        "assert_ne!({}, {})",
                        emit_expr(&args[0].value),
                        emit_expr(&args[1].value)
                    );
                }
                if n == "print" && args.len() == 1 {
                    return format!("println!(\"{{}}\", {})", emit_expr(&args[0].value));
                }
            }
            // std.* call forms: std.fs.read(path) → FieldAccess(FieldAccess(Ident("std"), "fs"), "read")
            if let HirExpr::FieldAccess(namespace_expr, fn_name, _) = &**callee {
                if let HirExpr::Ident(std_kw, _) = &**namespace_expr {
                    if std_kw == "std" {
                        let a: Vec<_> = args.iter().map(|arg| emit_expr(&arg.value)).collect();
                        let builtin: Option<String> = match fn_name.as_str() {
                            "uuid" => Some("vox_runtime::builtins::vox_uuid()".to_string()),
                            "now_ms" => Some("vox_runtime::builtins::vox_now_ms()".to_string()),
                            "hash_fast" if !a.is_empty() => {
                                Some(format!("vox_runtime::builtins::vox_hash_fast(&{})", a[0]))
                            }
                            "hash_secure" if !a.is_empty() => {
                                Some(format!("vox_runtime::builtins::vox_hash_secure(&{})", a[0]))
                            }
                            _ => None,
                        };
                        if let Some(b) = builtin {
                            return if *is_await { format!("{}.await", b) } else { b };
                        }
                    }
                }
                if let HirExpr::FieldAccess(std_expr, ns_name, _) = &**namespace_expr {
                    if let HirExpr::Ident(std_kw, _) = &**std_expr {
                        if std_kw == "std" {
                            let a: Vec<_> = args.iter().map(|arg| emit_expr(&arg.value)).collect();
                            let builtin: Option<String> = match (ns_name.as_str(), fn_name.as_str())
                            {
                                ("crypto", "hash_fast") if !a.is_empty() => {
                                    Some(format!("vox_runtime::builtins::vox_hash_fast(&{})", a[0]))
                                }
                                ("crypto", "hash_secure") if !a.is_empty() => Some(format!(
                                    "vox_runtime::builtins::vox_hash_secure(&{})",
                                    a[0]
                                )),
                                ("crypto", "uuid") => {
                                    Some("vox_runtime::builtins::vox_uuid()".to_string())
                                }
                                ("time", "now_ms") => {
                                    Some("vox_runtime::builtins::vox_now_ms()".to_string())
                                }
                                ("fs", "read") if !a.is_empty() => Some(format!(
                                    "std::fs::read_to_string({}).map_err(|e| Box::new(e) as Box<dyn std::error::Error>)?",
                                    a[0]
                                )),
                                ("fs", "write") if a.len() >= 2 => Some(format!(
                                    "std::fs::write({}, {}).map_err(|e| Box::new(e) as Box<dyn std::error::Error>)?",
                                    a[0], a[1]
                                )),
                                ("fs", "exists") if !a.is_empty() => {
                                    Some(format!("std::path::Path::new(&{}).exists()", a[0]))
                                }
                                ("fs", "remove") if !a.is_empty() => Some(format!(
                                    "std::fs::remove_file({}).map_err(|e| Box::new(e) as Box<dyn std::error::Error>)?",
                                    a[0]
                                )),
                                ("fs", "read_bytes") if !a.is_empty() => Some(format!(
                                    "std::fs::read({}).map_err(|e| Box::new(e) as Box<dyn std::error::Error>)?",
                                    a[0]
                                )),
                                ("fs", "mkdir") if !a.is_empty() => Some(format!(
                                    "std::fs::create_dir_all({}).map_err(|e| Box::new(e) as Box<dyn std::error::Error>)?",
                                    a[0]
                                )),
                                ("path", "join") if a.len() >= 2 => Some(format!(
                                    "std::path::Path::new(&{}).join(&{}).to_string_lossy().to_string()",
                                    a[0], a[1]
                                )),
                                ("path", "basename") if !a.is_empty() => Some(format!(
                                    "std::path::Path::new(&{}).file_name().unwrap_or_default().to_string_lossy().to_string()",
                                    a[0]
                                )),
                                ("path", "dirname") if !a.is_empty() => Some(format!(
                                    "std::path::Path::new(&{}).parent().unwrap_or(std::path::Path::new(\".\")).to_string_lossy().to_string()",
                                    a[0]
                                )),
                                ("path", "extension") if !a.is_empty() => Some(format!(
                                    "std::path::Path::new(&{}).extension().unwrap_or_default().to_string_lossy().to_string()",
                                    a[0]
                                )),
                                ("env", "get") if !a.is_empty() => Some(format!(
                                    "(vox_runtime::builtins::vox_env_get(({}).as_str()))",
                                    a[0]
                                )),
                                ("process", "run") if a.len() >= 2 => Some(format!(
                                    "(match vox_runtime::builtins::vox_process_run(({}).as_str(), {}.as_slice()) {{ Ok(c) => Ok(c as i64), Err(m) => Error(m) }})",
                                    a[0], a[1]
                                )),
                                ("process", "run_ex") if a.len() >= 4 => Some(format!(
                                    "(match vox_runtime::builtins::vox_process_run_ex(({}).as_str(), {}.as_slice(), ({}).as_str(), {}.as_slice()) {{ Ok(c) => Ok(c as i64), Err(m) => Error(m) }})",
                                    a[0], a[1], a[2], a[3]
                                )),
                                ("process", "run_capture") if a.len() >= 2 => Some(format!(
                                    "(match vox_runtime::builtins::vox_process_run_capture(({}).as_str(), {}.as_slice()) {{ Ok(p) => Ok(serde_json::json!({{ \"exit\": p.exit as i64, \"stdout\": p.stdout, \"stderr\": p.stderr }})), Err(m) => Error(m) }})",
                                    a[0], a[1]
                                )),
                                ("process", "run_capture_ex") if a.len() >= 4 => Some(format!(
                                    "(match vox_runtime::builtins::vox_process_run_capture_ex(({}).as_str(), {}.as_slice(), ({}).as_str(), {}.as_slice()) {{ Ok(p) => Ok(serde_json::json!({{ \"exit\": p.exit as i64, \"stdout\": p.stdout, \"stderr\": p.stderr }})), Err(m) => Error(m) }})",
                                    a[0], a[1], a[2], a[3]
                                )),
                                ("process", "exit") if !a.is_empty() => {
                                    Some(format!("{{ std::process::exit({} as i32) }}", a[0]))
                                }
                                ("fs", "list_dir") if !a.is_empty() => Some(format!(
                                    "(match vox_runtime::builtins::vox_list_dir(({}).as_str()) {{ Ok(v) => Ok(v), Err(m) => Error(m) }})",
                                    a[0]
                                )),
                                ("fs", "glob") if !a.is_empty() => Some(format!(
                                    "(match vox_runtime::builtins::vox_fs_glob(({}).as_str()) {{ Ok(v) => Ok(v), Err(m) => Error(m) }})",
                                    a[0]
                                )),
                                ("fs", "remove_dir_all") if !a.is_empty() => Some(format!(
                                    "(match vox_runtime::builtins::vox_fs_remove_dir_all(({}).as_str()) {{ Ok(()) => Ok(()), Err(m) => Error(m) }})",
                                    a[0]
                                )),
                                ("fs", "copy") if a.len() >= 2 => Some(format!(
                                    "(match vox_runtime::builtins::vox_fs_copy(({}).as_str(), ({}).as_str()) {{ Ok(()) => Ok(()), Err(m) => Error(m) }})",
                                    a[0], a[1]
                                )),
                                ("path", "join_many") if !a.is_empty() => Some(format!(
                                    "vox_runtime::builtins::vox_path_join_many({}.as_slice())",
                                    a[0]
                                )),
                                ("json", "read_str") if a.len() >= 2 => Some(format!(
                                    "(match vox_runtime::builtins::vox_json_read_str(({}).as_str(), ({}).as_str()) {{ Ok(s) => Ok(s), Err(m) => Error(m) }})",
                                    a[0], a[1]
                                )),
                                ("json", "read_f64") if a.len() >= 2 => Some(format!(
                                    "(match vox_runtime::builtins::vox_json_read_f64(({}).as_str(), ({}).as_str()) {{ Ok(v) => Ok(v), Err(m) => Error(m) }})",
                                    a[0], a[1]
                                )),
                                ("json", "quote") if !a.is_empty() => Some(format!(
                                    "vox_runtime::builtins::vox_json_quote(({}).as_str())",
                                    a[0]
                                )),
                                _ => None,
                            };
                            if let Some(b) = builtin {
                                return if *is_await { format!("{}.await", b) } else { b };
                            }
                            let call = format!("std::{}::{}({})", ns_name, fn_name, a.join(", "));
                            return if *is_await {
                                format!("{}.await", call)
                            } else {
                                call
                            };
                        }
                    }
                }
            }
            let c = emit_expr(callee);
            let a: Vec<_> = args.iter().map(|arg| emit_expr(&arg.value)).collect();
            if *is_await {
                format!("{}({}).await", c, a.join(", "))
            } else {
                format!("{}({})", c, a.join(", "))
            }
        }
        HirExpr::ObjectLit(fields, _) => {
            let props: Vec<String> = fields
                .iter()
                .map(|(k, v)| format!("\"{}\": {}", k, emit_expr(v)))
                .collect();
            format!("serde_json::json!({{ {} }})", props.join(", "))
        }
        HirExpr::MethodCall(obj, method, args, _) => {
            if let HirExpr::Ident(obj_name, _) = &**obj {
                if obj_name == "Speech" && method.as_str() == "transcribe" && args.len() == 1 {
                    let p = emit_expr(&args[0].value);
                    return format!(
                        "(match vox_oratio::transcribe_path(std::path::Path::new(({}).as_str())) {{ Ok(t) => Ok(t.display_text().to_string()), Err(e) => Error(format!(\"{{}}\", e)) }})",
                        p
                    );
                }
                if obj_name == "log" && !args.is_empty() {
                    let mut args_iter = args.iter();
                    if let Some(first_arg) = args_iter.next() {
                        let fmt = match &first_arg.value {
                            HirExpr::StringLit(s, _) => format!("\"{}\"", s),
                            other => emit_expr(other),
                        };
                        let remaining: Vec<String> =
                            args_iter.map(|a| emit_expr(&a.value)).collect();
                        let macro_name = match method.as_str() {
                            "info" => "info",
                            "warn" => "warn",
                            "error" => "error",
                            "debug" => "debug",
                            _ => "info",
                        };
                        if remaining.is_empty() {
                            return format!("tracing::{}!(\"{{:?}}\", {})", macro_name, fmt);
                        }
                        return format!(
                            "tracing::{}!({}, {})",
                            macro_name,
                            fmt,
                            remaining.join(", ")
                        );
                    }
                }
            }
            // Check for db.Table.method pattern
            // obj must be FieldAccess(inner="db", field=TableName)
            if let HirExpr::FieldAccess(inner, table_name, _) = &**obj {
                if let HirExpr::Ident(n, _) = &**inner {
                    if n == "db" {
                        let args_str: Vec<String> =
                            args.iter().map(|a| emit_expr(&a.value)).collect();
                        return match method.as_str() {
                            "insert" => {
                                format!(
                                    "{{ let item: {} = serde_json::from_value({}).expect(\"vox codegen: db insert from_value\"); {}::insert(&*db, &item).await.expect(\"vox codegen: db insert\") }}",
                                    table_name,
                                    args_str
                                        .first()
                                        .unwrap_or(&"serde_json::json!({})".to_string()),
                                    table_name
                                )
                            }
                            "get" => {
                                format!(
                                    "{}::get(&*db, {}).await.expect(\"vox codegen: db get\")",
                                    table_name,
                                    args_str.first().unwrap_or(&"0".to_string())
                                )
                            }
                            "delete" => {
                                format!(
                                    "{}::delete(&*db, {}).await.expect(\"vox codegen: db delete\")",
                                    table_name,
                                    args_str.first().unwrap_or(&"0".to_string())
                                )
                            }
                            "query" => {
                                format!(
                                    "{}::query(&*db, {}).await.expect(\"vox codegen: db query\")",
                                    table_name,
                                    args_str.first().unwrap_or(&"\"\"".to_string())
                                )
                            }
                            _ => format!("/* unsupported db method {} */", method),
                        };
                    }
                }
            }

            let o = emit_expr(obj);
            if method == "json" && o == "request" {
                "request.clone()".into()
            } else {
                let call = format!(
                    "{}.{}({})",
                    o,
                    method,
                    args.iter()
                        .map(|a| emit_expr(&a.value))
                        .collect::<Vec<_>>()
                        .join(", ")
                );
                if method == "send" {
                    format!("{}.await", call)
                } else {
                    call
                }
            }
        }
        HirExpr::Spawn(target, _) => {
            if let HirExpr::Ident(n, _) = &**target {
                format!("{}Handle::spawn()", n)
            } else {
                "/* error: spawn target must be actor name */".into()
            }
        }
        HirExpr::If(cond, then_b, else_b, _) => {
            let mut s = format!("if {} {{\n", emit_expr(cond));
            for stmt in then_b {
                s.push_str(&emit_stmt(stmt, 1, false, false));
            }
            s.push('}');
            if let Some(else_stmts) = else_b {
                s.push_str(" else {\n");
                for stmt in else_stmts {
                    s.push_str(&emit_stmt(stmt, 1, false, false));
                }
                s.push('}');
            }
            s
        }
        HirExpr::FieldAccess(obj, field, _) => {
            if let HirExpr::Ident(root, _) = obj.as_ref() {
                if root == "std" && field == "args" {
                    return "std::env::args().skip(1).map(|s| s.to_string()).collect::<Vec<String>>()"
                        .to_string();
                }
            }
            format!("{}[\"{}\"].clone()", emit_expr(obj), field)
        }
        HirExpr::Block(stmts, _) => {
            let mut s = String::from("{\n");
            for stmt in stmts {
                s.push_str(&emit_stmt(stmt, 1, false, false));
            }
            s.push('}');
            s
        }
        HirExpr::With(operand, options, _) => {
            // Build ActivityOptions from the record literal
            let mut opts_builder = String::from("vox_runtime::ActivityOptions::new()");

            if let HirExpr::ObjectLit(fields, _) = options.as_ref() {
                for (key, value) in fields {
                    match key.as_str() {
                        "retries" => {
                            opts_builder
                                .push_str(&format!(".with_retries({} as u32)", emit_expr(value)));
                        }
                        "timeout" => {
                            // timeout can be a string like "10s" or an int (seconds)
                            match value {
                                HirExpr::StringLit(s, _) => {
                                    opts_builder.push_str(&format!(
                                        ".with_timeout(vox_runtime::ActivityOptions::parse_duration(\"{}\").expect(\"vox codegen: activity timeout duration\"))",
                                        s
                                    ));
                                }
                                _ => {
                                    opts_builder.push_str(&format!(
                                        ".with_timeout_secs({} as u64)",
                                        emit_expr(value)
                                    ));
                                }
                            }
                        }
                        "initial_backoff" => {
                            if let HirExpr::StringLit(s, _) = value {
                                opts_builder.push_str(&format!(
                                    ".with_initial_backoff(vox_runtime::ActivityOptions::parse_duration(\"{}\").expect(\"vox codegen: initial_backoff duration\"))",
                                    s
                                ));
                            }
                        }
                        "max_backoff" => {
                            if let HirExpr::StringLit(s, _) = value {
                                opts_builder.push_str(&format!(
                                    ".with_max_backoff(vox_runtime::ActivityOptions::parse_duration(\"{}\").expect(\"vox codegen: max_backoff duration\"))",
                                    s
                                ));
                            }
                        }
                        "backoff_multiplier" => {
                            opts_builder.push_str(&format!(
                                ".with_backoff_multiplier({} as f64)",
                                emit_expr(value)
                            ));
                        }
                        "activity_id" => {
                            if let HirExpr::StringLit(s, _) = value {
                                opts_builder
                                    .push_str(&format!(".with_activity_id(\"{}\".to_string())", s));
                            }
                        }
                        _ => {} // unknown options ignored at codegen (warned at typecheck)
                    }
                }
            }

            // Wrap the operand call in execute_activity
            let operand_str = emit_expr(operand);
            format!(
                "match vox_runtime::execute_activity(\"activity\", &{opts}, || async {{ {call} }}).await {{ \
                    vox_runtime::ActivityResult::Ok(v) => v, \
                    vox_runtime::ActivityResult::Failed(e) => panic!(\"Activity failed: {{}}\", e), \
                    vox_runtime::ActivityResult::Cancelled => panic!(\"Activity cancelled\"), \
                }}",
                opts = opts_builder,
                call = operand_str,
            )
        }
        HirExpr::Lambda(params, _ret_ty, body, _) => {
            let mut s = String::new();
            s.push('|');
            let param_strs: Vec<String> = params.iter().map(|p| p.name.clone()).collect();
            s.push_str(&param_strs.join(", "));
            s.push_str("| ");
            s.push_str(&emit_expr(body));
            s
        }
        HirExpr::Pipe(left, right, _) => {
            format!("({})({})", emit_expr(right), emit_expr(left))
        }
        HirExpr::For(name, iter, body, _) => {
            let mut s = format!("for {} in {} {{\n", name, emit_expr(iter));
            if let HirExpr::Block(stmts, _) = &**body {
                for stmt in stmts {
                    s.push_str(&emit_stmt(stmt, 1, false, false));
                }
            } else {
                s.push_str(&format!("  {};\n", emit_expr(body)));
            }
            s.push_str("}\n");
            s
        }
        HirExpr::Jsx(_) | HirExpr::JsxSelfClosing(_) => {
            "panic!(\"JSX cannot be rendered via the Rust backend yet\")".into()
        }
        HirExpr::ListLit(items, _) => {
            let item_strs: Vec<String> = items.iter().map(emit_expr).collect();
            format!("vec![{}]", item_strs.join(", "))
        }
        HirExpr::Unary(op, expr, _) => {
            let op_str = match op {
                vox_hir::HirUnOp::Not => "!",
                vox_hir::HirUnOp::Neg => "-",
            };
            format!("{}({})", op_str, emit_expr(expr))
        }
        HirExpr::Match(obj, arms, _) => {
            let mut s = format!("match {} {{\n", emit_expr(obj));
            for arm in arms {
                s.push_str(&format!("    {} => {{\n", emit_pattern(&arm.pattern)));
                s.push_str(&emit_expr(&arm.body));
                s.push_str("\n    }\n");
            }
            s.push('}');
            s
        }
    }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

/// Generate a TypeScript API client file with typed `fetch()` wrappers for server functions.
pub fn emit_api_client(module: &HirModule) -> String {
    if module.server_fns.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("// Auto-generated API client for Vox server functions\n");
    out.push_str("// Do not edit manually — regenerated on each build.\n\n");

    out.push_str("const API_BASE = '';\n\n");

    for sf in &module.server_fns {
        // Generate TypeScript function signature
        let params: Vec<String> = sf
            .params
            .iter()
            .map(|p| {
                let ts_type = p
                    .type_ann
                    .as_ref()
                    .map_or("any".to_string(), hir_type_to_ts);
                format!("{}: {}", p.name, ts_type)
            })
            .collect();

        let return_ts = sf
            .return_type
            .as_ref()
            .map_or("any".to_string(), hir_type_to_ts);

        out.push_str(&format!(
            "export async function {}({}): Promise<{}> {{\n",
            sf.name,
            params.join(", "),
            return_ts,
        ));
        out.push_str(&format!(
            "  const response = await fetch(`${{API_BASE}}{}`, {{\n",
            sf.route_path,
        ));
        out.push_str("    method: 'POST',\n");
        out.push_str("    headers: { 'Content-Type': 'application/json' },\n");

        // Build body from params
        let body_fields: Vec<String> = sf.params.iter().map(|p| p.name.clone()).collect();
        out.push_str(&format!(
            "    body: JSON.stringify({{ {} }}),\n",
            body_fields.join(", ")
        ));
        out.push_str("  });\n");
        out.push_str("  if (!response.ok) throw new Error(`Server error: ${response.status}`);\n");
        out.push_str("  return response.json();\n");
        out.push_str("}\n\n");
    }

    out
}

fn hir_type_to_ts(ty: &HirType) -> String {
    match ty {
        HirType::Named(name) => {
            if let Some(s) = VoxScalar::parse(name) {
                s.as_ts_primitive().to_string()
            } else {
                match name.as_str() {
                    "Unit" => "void".to_string(),
                    other => other.to_string(),
                }
            }
        }
        HirType::Generic(name, args) => {
            let args_str: Vec<String> = args.iter().map(hir_type_to_ts).collect();
            match name.as_str() {
                "list" | "List" => format!("{}[]", args_str.first().unwrap_or(&"any".to_string())),
                _ => format!("{}<{}>", name, args_str.join(", ")),
            }
        }
        HirType::Function(params, ret) => {
            let params_str: Vec<String> = params
                .iter()
                .enumerate()
                .map(|(i, p)| format!("arg{}: {}", i, hir_type_to_ts(p)))
                .collect();
            format!("({}) => {}", params_str.join(", "), hir_type_to_ts(ret))
        }
        HirType::Tuple(elems) => {
            let elems_str: Vec<String> = elems.iter().map(hir_type_to_ts).collect();
            format!("[{}]", elems_str.join(", "))
        }
        HirType::Unit => "void".to_string(),
    }
}

/// Generate the MCP (Model Context Protocol) JSON-RPC server binary.
/// Communicates over stdio: reads JSON-RPC requests from stdin, writes responses to stdout.
pub fn emit_mcp_server(module: &HirModule, package_name: &str) -> String {
    let crate_name = package_name.replace('-', "_");
    let mut out = String::new();

    out.push_str("// MCP Server — Generated by Vox Compiler\n");
    out.push_str("// Implements the Model Context Protocol (JSON-RPC 2.0 over stdio)\n\n");
    out.push_str("use serde_json::{json, Value};\n");
    out.push_str("use std::io::{self, BufRead, Write};\n");
    out.push_str(&format!("use {}::*;\n\n", crate_name));

    // Tool dispatch function
    out.push_str("fn dispatch_tool(name: &str, args: &Value) -> Result<Value, String> {\n");
    out.push_str("    match name {\n");
    for tool in &module.mcp_tools {
        let fn_name = &tool.func.name;
        out.push_str(&format!("        \"{}\" => {{\n", fn_name));
        // Extract args
        for param in &tool.func.params {
            let p = &param.name;
            out.push_str(&format!(
                "            let {p} = args.get(\"{p}\").cloned().unwrap_or(Value::Null);\n"
            ));
        }
        // Call function — for now, wrap result in Ok(json)
        let arg_list: Vec<String> = tool
            .func
            .params
            .iter()
            .map(|p| {
                // Convert from serde_json::Value to the appropriate type
                let name = &p.name;
                match p.type_ann.as_ref() {
                    Some(HirType::Named(t)) if t == "String" || t == "str" => {
                        format!("{name}.as_str().unwrap_or_default().to_string()")
                    }
                    Some(HirType::Named(t)) if t == "i64" || t == "int" => {
                        format!("{name}.as_i64().unwrap_or(0)")
                    }
                    Some(HirType::Named(t)) if t == "f64" || t == "float" => {
                        format!("{name}.as_f64().unwrap_or(0.0)")
                    }
                    Some(HirType::Named(t)) if t == "bool" => {
                        format!("{name}.as_bool().unwrap_or(false)")
                    }
                    _ => name.to_string(),
                }
            })
            .collect();
        out.push_str(&format!(
            "            let result = {}({});\n",
            fn_name,
            arg_list.join(", ")
        ));
        out.push_str("            Ok(serde_json::to_value(result).unwrap_or(Value::Null))\n");
        out.push_str("        }\n");
    }
    out.push_str("        _ => Err(format!(\"Unknown tool: {}\", name)),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Build tool list JSON
    out.push_str("fn tool_list() -> Value {\n");
    out.push_str("    json!({\n");
    out.push_str("        \"tools\": [\n");
    for (i, tool) in module.mcp_tools.iter().enumerate() {
        let trailing = if i + 1 < module.mcp_tools.len() {
            ","
        } else {
            ""
        };
        out.push_str("            {\n");
        out.push_str(&format!(
            "                \"name\": \"{}\",\n",
            tool.func.name
        ));
        out.push_str(&format!(
            "                \"description\": \"{}\",\n",
            tool.description.replace('"', "\\\"")
        ));
        // Build inputSchema from params
        out.push_str("                \"inputSchema\": {\n");
        out.push_str("                    \"type\": \"object\",\n");
        out.push_str("                    \"properties\": {\n");
        for (j, param) in tool.func.params.iter().enumerate() {
            let json_type = match param.type_ann.as_ref() {
                Some(HirType::Named(t)) if t == "String" || t == "str" => "string",
                Some(HirType::Named(t)) if t == "i64" || t == "int" => "integer",
                Some(HirType::Named(t)) if t == "f64" || t == "float" => "number",
                Some(HirType::Named(t)) if t == "bool" => "boolean",
                _ => "string",
            };
            let param_trailing = if j + 1 < tool.func.params.len() {
                ","
            } else {
                ""
            };
            out.push_str(&format!(
                "                        \"{}\": {{ \"type\": \"{}\" }}{}",
                param.name, json_type, param_trailing
            ));
            out.push('\n');
        }
        out.push_str("                    },\n");
        // All params required
        let required: Vec<String> = tool
            .func
            .params
            .iter()
            .map(|p| format!("\"{}\"", p.name))
            .collect();
        out.push_str(&format!(
            "                    \"required\": [{}]\n",
            required.join(", ")
        ));
        out.push_str("                }\n");
        out.push_str(&format!("            }}{}\n", trailing));
    }
    out.push_str("        ]\n");
    out.push_str("    })\n");
    out.push_str("}\n\n");

    // Main loop — JSON-RPC over stdio
    out.push_str("fn main() {\n");
    out.push_str("    let stdin = io::stdin();\n");
    out.push_str("    let mut stdout = io::stdout();\n");
    out.push_str("    for line in stdin.lock().lines() {\n");
    out.push_str("        let line = match line {\n");
    out.push_str("            Ok(l) => l,\n");
    out.push_str("            Err(_) => break,\n");
    out.push_str("        };\n");
    out.push_str("        if line.trim().is_empty() { continue; }\n");
    out.push_str("        let request: Value = match serde_json::from_str(&line) {\n");
    out.push_str("            Ok(v) => v,\n");
    out.push_str("            Err(e) => {\n");
    out.push_str("                let err = json!({\n");
    out.push_str("                    \"jsonrpc\": \"2.0\",\n");
    out.push_str("                    \"error\": { \"code\": -32700, \"message\": format!(\"Parse error: {e}\") },\n");
    out.push_str("                    \"id\": null\n");
    out.push_str("                });\n");
    out.push_str("                writeln!(stdout, \"{}\", err).ok();\n");
    out.push_str("                stdout.flush().ok();\n");
    out.push_str("                continue;\n");
    out.push_str("            }\n");
    out.push_str("        };\n");
    out.push_str("        let id = request.get(\"id\").cloned().unwrap_or(Value::Null);\n");
    out.push_str(
        "        let method = request.get(\"method\").and_then(|m| m.as_str()).unwrap_or(\"\");\n",
    );
    out.push_str("        let params = request.get(\"params\").cloned().unwrap_or(json!({}));\n\n");

    out.push_str("        let response = match method {\n");
    // initialize
    out.push_str("            \"initialize\" => json!({\n");
    out.push_str("                \"jsonrpc\": \"2.0\",\n");
    out.push_str("                \"id\": id,\n");
    out.push_str("                \"result\": {\n");
    out.push_str("                    \"protocolVersion\": \"2024-11-05\",\n");
    out.push_str("                    \"capabilities\": { \"tools\": {} },\n");
    out.push_str(&format!(
        "                    \"serverInfo\": {{ \"name\": \"{}\", \"version\": \"0.1.0\" }}\n",
        package_name
    ));
    out.push_str("                }\n");
    out.push_str("            }),\n");
    // tools/list
    out.push_str("            \"tools/list\" => {\n");
    out.push_str("                let tools = tool_list();\n");
    out.push_str("                json!({\n");
    out.push_str("                    \"jsonrpc\": \"2.0\",\n");
    out.push_str("                    \"id\": id,\n");
    out.push_str("                    \"result\": tools\n");
    out.push_str("                })\n");
    out.push_str("            }\n");
    // tools/call
    out.push_str("            \"tools/call\" => {\n");
    out.push_str("                let tool_name = params.get(\"name\").and_then(|n| n.as_str()).unwrap_or(\"\");\n");
    out.push_str("                let tool_args = params.get(\"arguments\").cloned().unwrap_or(json!({}));\n");
    out.push_str("                match dispatch_tool(tool_name, &tool_args) {\n");
    out.push_str("                    Ok(result) => json!({\n");
    out.push_str("                        \"jsonrpc\": \"2.0\",\n");
    out.push_str("                        \"id\": id,\n");
    out.push_str("                        \"result\": {\n");
    out.push_str("                            \"content\": [{ \"type\": \"text\", \"text\": serde_json::to_string(&result).unwrap_or_default() }]\n");
    out.push_str("                        }\n");
    out.push_str("                    }),\n");
    out.push_str("                    Err(e) => json!({\n");
    out.push_str("                        \"jsonrpc\": \"2.0\",\n");
    out.push_str("                        \"id\": id,\n");
    out.push_str("                        \"result\": {\n");
    out.push_str("                            \"isError\": true,\n");
    out.push_str(
        "                            \"content\": [{ \"type\": \"text\", \"text\": e }]\n",
    );
    out.push_str("                        }\n");
    out.push_str("                    }),\n");
    out.push_str("                }\n");
    out.push_str("            }\n");
    // notifications (no-ops)
    out.push_str(
        "            \"notifications/initialized\" | \"notifications/cancelled\" => continue,\n",
    );
    // unknown method
    out.push_str("            _ => json!({\n");
    out.push_str("                \"jsonrpc\": \"2.0\",\n");
    out.push_str("                \"id\": id,\n");
    out.push_str("                \"error\": { \"code\": -32601, \"message\": format!(\"Method not found: {}\", method) }\n");
    out.push_str("            }),\n");
    out.push_str("        };\n\n");

    out.push_str("        writeln!(stdout, \"{}\", response).ok();\n");
    out.push_str("        stdout.flush().ok();\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}
