// Mirrors docs/src/ into the Starlight content collection directory.
// docsLoader() hardcodes src/content/docs/ as its base and has no exclude
// option, so src/content/docs/ is a directory of per-entry symlinks into
// docs/src/ that leaves out the tombstoned archive (P20-D8) and generated
// artifacts. The directory carries a marker file; it is only ever deleted
// when the marker is present, and links inside it are unlinked, never followed.
import {
  copyFileSync,
  cpSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readlinkSync,
  realpathSync,
  rmdirSync,
  rmSync,
  statSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { join, dirname } from 'node:path';

export const MIRROR_MARKER = '.vox-docs-mirror';
/** Top-level docs/src entries that are never mirrored (never opened either). */
export const MIRROR_EXCLUDED = ['archive', '.well-known', 'SUMMARY.md'];

const type = process.platform === 'win32' ? 'junction' : 'dir';

/**
 * Empties `mirrorPath` for a rebuild: a symlink there is unlinked, a directory
 * is removed only if it holds MIRROR_MARKER, anything else is an error. Then
 * recreates it as an empty directory holding only the marker.
 */
export function prepareMirrorDir(mirrorPath) {
  let stat;
  try {
    stat = lstatSync(mirrorPath);
  } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }
  if (stat?.isSymbolicLink()) {
    unlinkSync(mirrorPath);
  } else if (stat?.isDirectory()) {
    if (!existsSync(join(mirrorPath, MIRROR_MARKER))) {
      throw new Error(
        `[setup-content] ${mirrorPath} is a directory without the ${MIRROR_MARKER} marker; refusing to delete it. Move its contents out and re-run.`
      );
    }
    for (const name of readdirSync(mirrorPath)) {
      const entry = join(mirrorPath, name);
      if (lstatSync(entry).isSymbolicLink()) unlinkSync(entry);
      else rmSync(entry, { recursive: true });
    }
    rmdirSync(mirrorPath);
  } else if (stat) {
    throw new Error(`[setup-content] ${mirrorPath} exists but is not a directory or symlink. Remove it manually and re-run.`);
  }
  mkdirSync(mirrorPath, { recursive: true });
  writeFileSync(
    join(mirrorPath, MIRROR_MARKER),
    'Generated by docs-astro/scripts/setup-content.mjs; safe to delete the whole directory.\n'
  );
}

/** Rebuilds `mirrorPath` as per-entry links to `sourceDir`, minus MIRROR_EXCLUDED. */
export function buildMirror(sourceDir, mirrorPath) {
  prepareMirrorDir(mirrorPath);
  const names = readdirSync(sourceDir).filter((name) => !MIRROR_EXCLUDED.includes(name));
  const copied = [];
  for (const name of names) {
    const from = join(sourceDir, name);
    const to = join(mirrorPath, name);
    const isDir = statSync(from).isDirectory();
    try {
      symlinkSync(from, to, isDir ? type : 'file');
    } catch (err) {
      if (err.code !== 'EPERM') throw err;
      cpSync(from, to, { recursive: true });
      copied.push(name);
    }
  }
  if (copied.length > 0) {
    console.log(`[setup-content] No symlink permission; copied instead: ${copied.join(', ')}`);
  }
  console.log(
    `[setup-content] Mirrored ${names.length} docs/src entries into docs-astro/src/content/docs (excluded: ${MIRROR_EXCLUDED.join(', ')})`
  );
  return { mirrored: names.length, copied };
}

function main() {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const repoRoot = join(scriptDir, '..', '..');

  buildMirror(join(repoRoot, 'docs', 'src'), join(repoRoot, 'docs-astro', 'src', 'content', 'docs'));

  // Second link: expose repo-root examples/ so remark-vox-include can resolve
  // {{#include ../../../examples/golden/X.vox}} from any docs section subdirectory.
  // From docs-astro/src/content/docs/<section>/, going up 3 levels reaches
  // docs-astro/src/, so the plugin looks for docs-astro/src/examples/golden/X.vox.
  const examplesTarget = join(repoRoot, 'examples');
  const examplesLink = join(repoRoot, 'docs-astro', 'src', 'examples');

  function createExamplesLink() {
    mkdirSync(join(repoRoot, 'docs-astro', 'src'), { recursive: true });
    symlinkSync(examplesTarget, examplesLink, type);
    console.log(`[setup-content] Created ${type}: docs-astro/src/examples → examples`);
  }

  if (!existsSync(examplesLink)) {
    createExamplesLink();
  } else {
    const stat = lstatSync(examplesLink);
    if (!stat.isSymbolicLink()) {
      throw new Error(
        `[setup-content] docs-astro/src/examples exists but is not a symlink (is a ${stat.isDirectory() ? 'directory' : 'file'}). Remove it manually and re-run.`
      );
    }
    const actual = readlinkSync(examplesLink);
    if (actual !== examplesTarget) {
      console.log(`[setup-content] Stale examples link (${actual} → ${examplesTarget}), recreating...`);
      rmSync(examplesLink, { recursive: true });
      createExamplesLink();
    } else {
      console.log('[setup-content] docs-astro/src/examples already points to examples, skipping.');
    }
  }

  // Copy agent discovery files so CF Pages serves /.well-known/* (Starlight
  // excludes that directory from the content collection).
  const wellKnownSrc = join(repoRoot, 'docs', 'src', '.well-known');
  const wellKnownDest = join(repoRoot, 'docs-astro', 'public', '.well-known');
  if (existsSync(wellKnownSrc)) {
    mkdirSync(wellKnownDest, { recursive: true });
    for (const name of readdirSync(wellKnownSrc)) {
      copyFileSync(join(wellKnownSrc, name), join(wellKnownDest, name));
    }
    console.log('[setup-content] Copied docs/src/.well-known → docs-astro/public/.well-known');
  }

  // Origin robots.txt (Cloudflare may prepend managed signals). Keep the
  // sitemap host on voxlang.org, not the retired vox.foundation domain.
  const robotsSrc = join(repoRoot, 'docs', 'src', 'robots.txt');
  const robotsDest = join(repoRoot, 'docs-astro', 'public', 'robots.txt');
  if (existsSync(robotsSrc)) {
    copyFileSync(robotsSrc, robotsDest);
    console.log('[setup-content] Copied docs/src/robots.txt → docs-astro/public/robots.txt');
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  main();
}
