use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

pub fn run(repo_root: &Path) -> Result<()> {
    let readme_path = repo_root.join("README.md");
    let content = fs::read_to_string(&readme_path)
        .with_context(|| format!("Failed to read {}", readme_path.display()))?;

    let start_marker = "<!-- ANCHOR: tier_table -->";
    let end_marker = "<!-- ANCHOR_END: tier_table -->";

    let start_idx = content
        .find(start_marker)
        .context("Could not find start marker for tier_table in README.md")?;
    let end_idx = content
        .find(end_marker)
        .context("Could not find end marker for tier_table in README.md")?;

    let table_content = &content[start_idx + start_marker.len()..end_idx].trim();

    let output_content = format!(
        "# What's Shipped Today\n\nThis file is auto-generated by `vox ci capability-snapshot` from the README.md.\n\n## Domain Matrix\n\n{}\n",
        table_content
    );

    let docs_dir = repo_root.join("docs/src/reference");
    fs::create_dir_all(&docs_dir).ok();

    let output_path = docs_dir.join("shipped-v0.4.md");
    fs::write(&output_path, output_content)
        .with_context(|| format!("Failed to write {}", output_path.display()))?;

    println!("capability-snapshot OK (wrote {})", output_path.display());
    Ok(())
}
