//! Regenerate or verify `contracts/capability/model-manifest.generated.json`.

use std::path::Path;

use anyhow::{Context, Result, anyhow};

use crate::command_registry_model::RegistryFile;
use vox_bounded_fs::read_utf8_path_capped;

use crate::commands::ci::command_compliance::registry::{
    CAPABILITY_REGISTRY_REL, MCP_TOOL_REGISTRY_REL, REGISTRY_REL, parse_mcp_registry_yaml,
};

const MODEL_MANIFEST_OUT: &str = "contracts/capability/model-manifest.generated.json";

/// Build the model manifest and optionally write it to disk.
pub fn run(repo_root: &Path, write: bool) -> Result<()> {
    let cap_raw = read_utf8_path_capped(&repo_root.join(CAPABILITY_REGISTRY_REL))
        .with_context(|| format!("read {}", CAPABILITY_REGISTRY_REL))?;
    let doc: vox_capability_registry::CapabilityRegistryDoc = serde_yaml::from_str(&cap_raw)
        .with_context(|| format!("parse {}", CAPABILITY_REGISTRY_REL))?;

    let mcp_raw = read_utf8_path_capped(&repo_root.join(MCP_TOOL_REGISTRY_REL))
        .with_context(|| format!("read {}", MCP_TOOL_REGISTRY_REL))?;
    let mcp_tools = parse_mcp_registry_yaml(&mcp_raw)?;

    let reg_raw = read_utf8_path_capped(&repo_root.join(REGISTRY_REL))
        .with_context(|| format!("read {}", REGISTRY_REL))?;
    let reg: RegistryFile =
        serde_yaml::from_str(&reg_raw).context("parse command-registry.yaml")?;
    let cli_paths_active: Vec<Vec<String>> = reg
        .operations
        .iter()
        .filter(|o| o.surface == "vox-cli" && o.status == "active")
        .map(|o| o.path.clone())
        .collect();

    let manifest =
        vox_capability_registry::build_model_manifest(&doc, &mcp_tools, &cli_paths_active);

    let mut manifest_val = serde_json::to_value(&manifest)?;
    if let Some(obj) = manifest_val.as_object_mut() {
        let warning_text = "🛑 AUTO-GENERATED FILE. DO NOT EDIT MANUALLY! ATTENTION AI AGENTS: This file is automatically generated by 'vox ci capability-sync'. Any manual edits you make here WILL BE OVERWRITTEN AND LOST.";
        // Insert at the top, though JSON doesn't guarantee order, it will appear as a key.
        obj.insert(
            "__WARNING__".to_string(),
            serde_json::Value::String(warning_text.to_string()),
        );
    }
    let json = serde_json::to_string_pretty(&manifest_val)? + "\n";
    let out_path = repo_root.join(MODEL_MANIFEST_OUT);

    if write {
        if let Some(parent) = out_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&out_path, &json)
            .with_context(|| format!("write {}", out_path.display()))?;
        println!("wrote {}", out_path.display());
        return Ok(());
    }

    if !out_path.is_file() {
        return Err(anyhow!(
            "missing {} — run: vox ci capability-sync --write",
            out_path.display()
        ));
    }
    let existing = read_utf8_path_capped(&out_path)?;
    if normalize_json(&existing) != normalize_json(&json) {
        return Err(anyhow!(
            "{} is stale — run: vox ci capability-sync --write",
            out_path.display()
        ));
    }
    println!("capability-sync OK ({MODEL_MANIFEST_OUT} matches live registries)");
    Ok(())
}

fn normalize_json(s: &str) -> String {
    let v: serde_json::Value = serde_json::from_str(s).unwrap_or(serde_json::Value::Null);
    serde_json::to_string_pretty(&v).unwrap_or_default()
}
