//! `vox ci command-sync` — regenerate or verify generated CLI/reference docs.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result, anyhow};

use vox_bounded_fs::read_utf8_path_capped;
use crate::command_registry_model::RegistryFile;

const REGISTRY_REL: &str = "contracts/cli/command-registry.yaml";

const GENERATED_REL: &str = "docs/src/reference/cli-command-surface.generated.md";
const GENERATED_MENS_DEFAULTS_REL: &str = "docs/src/reference/mens-train-defaults.generated.md";

fn normalize_lf(s: &str) -> String {
    s.replace("\r\n", "\n").replace('\r', "\n")
}

const WARNING_BLOCK: &str = r#"<!--
  ========================================================================
  🛑 🛑 🛑 AUTO-GENERATED FILE. DO NOT EDIT THIS FILE MANUALLY! 🛑 🛑 🛑
  ========================================================================
  
  ATTENTION AI AGENTS, LLMs, AND BOTS:
  This file is automatically generated by `vox ci command-sync`.
  Any manual edits you make here WILL BE OVERWRITTEN AND LOST.
  
  DO NOT USE `replace_file_content` or similar tools on this file.
  ========================================================================
-->"#;

fn render_generated_md(reg: &RegistryFile) -> String {
    let mut out = String::new();
    // Docs lint (`vox-doc-pipeline`) requires YAML frontmatter on every `.md` under `docs/src/`.
    out.push_str("---\n");
    out.push_str("title: \"CLI command surface (generated)\"\n");
    out.push_str("description: \"Auto-generated table of vox command paths and metadata; CLI rows are generated from contracts/operations/catalog.v1.yaml into command-registry.yaml — use vox ci operations-sync --target cli --write then vox ci command-sync --write.\"\n");
    out.push_str("category: \"reference\"\n");
    out.push_str("---\n\n");
    out.push_str(WARNING_BLOCK);
    out.push_str("\n\n# CLI command surface (generated)\n\n");
    out.push_str("Machine-derived from [`contracts/cli/command-registry.yaml`](../../../contracts/cli/command-registry.yaml) (itself projected from [`contracts/operations/catalog.v1.yaml`](../../../contracts/operations/catalog.v1.yaml)).\n\n");
    out.push_str(&format!(
        "**schema_version:** `{}` · **vox-cli operations:** {}\n\n",
        reg.schema_version,
        reg.operations
            .iter()
            .filter(|o| o.surface == "vox-cli")
            .count()
    ));
    out.push_str("| Path | Status | Feature gate | Latin ns | Product lane | Catalog group |\n");
    out.push_str("|------|--------|--------------|----------|--------------|----------------|\n");
    let mut ops: Vec<_> = reg
        .operations
        .iter()
        .filter(|o| o.surface == "vox-cli")
        .collect();
    ops.sort_by(|a, b| a.path.cmp(&b.path));
    for op in ops {
        let path = op.path.join(" ");
        let gate = op.feature_gate.as_deref().unwrap_or("—");
        let latin = op.latin_ns.as_deref().unwrap_or("—");
        let lane = op.product_lane.as_deref().unwrap_or("—");
        let cg = op.catalog_group.as_deref().unwrap_or("—");
        out.push_str(&format!(
            "| `vox {}` | {} | {} | {} | {} | {} |\n",
            path, op.status, gate, latin, lane, cg
        ));
    }
    out
}

fn render_mens_train_defaults_md(default_base_model: &str) -> String {
    let mut out = String::new();
    out.push_str("---\n");
    out.push_str("title: \"Mens train defaults (generated)\"\n");
    out.push_str("description: \"Auto-generated defaults snapshot for vox mens train from Rust constants and canonical command defaults.\"\n");
    out.push_str("category: \"reference\"\n");
    out.push_str("---\n\n");
    out.push_str(WARNING_BLOCK);
    out.push_str("\n\n# Mens train defaults (generated)\n\n");
    out.push_str(
        "This snapshot is generated from code-level constants and canonical CLI defaults.\n\n",
    );
    out.push_str("| Setting | Value | Source |\n");
    out.push_str("|---|---|---|\n");
    out.push_str(&format!(
        "| Default model id | `{}` | `contracts/mens/training-presets.v1.yaml::default_base_model` |\n",
        default_base_model
    ));
    out.push_str(&format!(
        "| Canonical train data dir | `{}` | `vox_corpus::training::CANONICAL_TRAIN_DATA_DIR` |\n",
        vox_corpus::training::CANONICAL_TRAIN_DATA_DIR
    ));
    out.push_str("| Canonical backend | `qlora` | `vox mens train` command defaults |\n");
    out.push_str("| Canonical tokenizer | `hf` | `vox mens train` command defaults |\n");
    out.push_str(
        "| Canonical output dir | `mens/runs/latest` | `vox mens train` command defaults |\n",
    );
    out
}

fn write_or_verify_generated_file(
    repo_root: &Path,
    rel_path: &str,
    rendered: &str,
    write: bool,
) -> Result<()> {
    let out_path = repo_root.join(rel_path);
    if write {
        fs::write(&out_path, normalize_lf(rendered))
            .with_context(|| format!("write {}", out_path.display()))?;
        println!("Wrote {}", out_path.display());
        return Ok(());
    }
    if !out_path.is_file() {
        return Err(anyhow!(
            "missing {}; run `vox ci command-sync --write`",
            out_path.display()
        ));
    }
    let existing =
        read_utf8_path_capped(&out_path).with_context(|| format!("read {}", out_path.display()))?;
    if normalize_lf(&existing) != normalize_lf(rendered) {
        return Err(anyhow!(
            "{} is stale; run `vox ci command-sync --write` from the repo root",
            out_path.display()
        ));
    }
    Ok(())
}

/// Write or verify the generated Markdown fragment.
pub fn run(repo_root: &Path, write: bool) -> Result<()> {
    let reg_path = repo_root.join(REGISTRY_REL);
    let raw =
        read_utf8_path_capped(&reg_path).with_context(|| format!("read {}", reg_path.display()))?;
    let reg: RegistryFile = serde_yaml::from_str(&raw).context("parse command-registry.yaml")?;
    let preset_path = repo_root.join("contracts/mens/training-presets.v1.yaml");
    let preset_raw = read_utf8_path_capped(&preset_path)
        .with_context(|| format!("read {}", preset_path.display()))?;
    let preset_yaml: serde_yaml::Value =
        serde_yaml::from_str(&preset_raw).context("parse training-presets.v1.yaml")?;
    let default_base_model = preset_yaml
        .get("default_base_model")
        .and_then(|v| v.as_str())
        .unwrap_or("Qwen/Qwen3.5-4B");
    write_or_verify_generated_file(repo_root, GENERATED_REL, &render_generated_md(&reg), write)?;
    write_or_verify_generated_file(
        repo_root,
        GENERATED_MENS_DEFAULTS_REL,
        &render_mens_train_defaults_md(default_base_model),
        write,
    )?;
    let cap_path = repo_root.join("contracts/capability/capability-registry.yaml");
    if cap_path.exists() {
        let cap_raw = read_utf8_path_capped(&cap_path).context("read capability-registry.yaml")?;
        let cap_yaml: serde_yaml::Value =
            serde_yaml::from_str(&cap_raw).context("parse capability-registry")?;
        if let Some(curated) = cap_yaml.get("curated").and_then(|v| v.as_sequence()) {
            for entry in curated {
                if let Some(id) = entry.get("id").and_then(|v| v.as_str()) {
                    if id == "cli.build" && entry.get("parameters").is_none() {
                        return Err(anyhow!(
                            "CLI arg schema missing. `vox build` has no parameters entry in contracts/capability/capability-registry.yaml"
                        ));
                    }
                }
            }
        }
    }

    println!(
        "command-sync OK ({}, {})",
        GENERATED_REL, GENERATED_MENS_DEFAULTS_REL
    );
    Ok(())
}

/// Verify the generated file (used from `command-compliance`).
pub(crate) fn verify(repo_root: &Path) -> Result<()> {
    run(repo_root, false)
}
