//! `vox ci command-sync` — regenerate or verify `docs/src/reference/cli-command-surface.generated.md`.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result, anyhow};

use super::bounded_read::read_utf8_path_capped;
use crate::command_registry_model::RegistryFile;

const REGISTRY_REL: &str = "contracts/cli/command-registry.yaml";

const GENERATED_REL: &str = "docs/src/reference/cli-command-surface.generated.md";

fn normalize_lf(s: &str) -> String {
    s.replace("\r\n", "\n").replace('\r', "\n")
}

fn render_generated_md(reg: &RegistryFile) -> String {
    let mut out = String::new();
    // Docs lint (`vox-doc-pipeline`) requires YAML frontmatter on every `.md` under `docs/src/`.
    out.push_str("---\n");
    out.push_str("title: \"CLI command surface (generated)\"\n");
    out.push_str("description: \"Auto-generated table of vox command paths and metadata; CLI rows are generated from contracts/operations/catalog.v1.yaml into command-registry.yaml — use vox ci operations-sync --target cli --write then vox ci command-sync --write.\"\n");
    out.push_str("category: \"reference\"\n");
    out.push_str("---\n\n");
    out.push_str("<!-- GENERATED BY `vox ci command-sync --write`. Do not hand-edit. -->\n\n");
    out.push_str("# CLI command surface (generated)\n\n");
    out.push_str("Machine-derived from [`contracts/cli/command-registry.yaml`](../../contracts/cli/command-registry.yaml) (itself projected from [`contracts/operations/catalog.v1.yaml`](../../contracts/operations/catalog.v1.yaml)).\n\n");
    out.push_str(&format!(
        "**schema_version:** `{}` · **vox-cli operations:** {}\n\n",
        reg.schema_version,
        reg.operations
            .iter()
            .filter(|o| o.surface == "vox-cli")
            .count()
    ));
    out.push_str("| Path | Status | Feature gate | Latin ns | Product lane | Catalog group |\n");
    out.push_str("|------|--------|--------------|----------|--------------|----------------|\n");
    let mut ops: Vec<_> = reg
        .operations
        .iter()
        .filter(|o| o.surface == "vox-cli")
        .collect();
    ops.sort_by(|a, b| a.path.cmp(&b.path));
    for op in ops {
        let path = op.path.join(" ");
        let gate = op.feature_gate.as_deref().unwrap_or("—");
        let latin = op.latin_ns.as_deref().unwrap_or("—");
        let lane = op.product_lane.as_deref().unwrap_or("—");
        let cg = op.catalog_group.as_deref().unwrap_or("—");
        out.push_str(&format!(
            "| `vox {}` | {} | {} | {} | {} | {} |\n",
            path, op.status, gate, latin, lane, cg
        ));
    }
    out
}

/// Write or verify the generated Markdown fragment.
pub fn run(repo_root: &Path, write: bool) -> Result<()> {
    let reg_path = repo_root.join(REGISTRY_REL);
    let raw =
        read_utf8_path_capped(&reg_path).with_context(|| format!("read {}", reg_path.display()))?;
    let reg: RegistryFile = serde_yaml::from_str(&raw).context("parse command-registry.yaml")?;
    let rendered = render_generated_md(&reg);
    let out_path = repo_root.join(GENERATED_REL);
    if write {
        fs::write(&out_path, normalize_lf(&rendered))
            .with_context(|| format!("write {}", out_path.display()))?;
        println!("Wrote {}", out_path.display());
        return Ok(());
    }
    if !out_path.is_file() {
        return Err(anyhow!(
            "missing {}; run `vox ci command-sync --write`",
            out_path.display()
        ));
    }
    let existing =
        read_utf8_path_capped(&out_path).with_context(|| format!("read {}", out_path.display()))?;
    if normalize_lf(&existing) != normalize_lf(&rendered) {
        return Err(anyhow!(
            "{} is stale; run `vox ci command-sync --write` from the repo root",
            out_path.display()
        ));
    }
    println!("command-sync OK ({})", out_path.display());
    Ok(())
}

/// Verify the generated file (used from `command-compliance`).
pub(crate) fn verify(repo_root: &Path) -> Result<()> {
    run(repo_root, false)
}
