//! Static path lists and feature matrix lanes for CI guards.

pub(crate) const DOCS_SSOT_FILES: &[&str] = &[
    "docs/src/architecture/forward-migration-charter.md",
    "docs/src/architecture/codex-arca-compatibility-boundaries.md",
    "docs/src/architecture/codex-arca-import-policy.md",
    "docs/src/architecture/codex-turso-allowlist.md",
    "docs/src/architecture/cli-scope-policy.md",
    "docs/src/architecture/compatibility-deprecation-windows.md",
    "docs/src/architecture/doc-to-code-acceptance-checklist.md",
    "docs/src/architecture/cli-reachability-ssot.md",
    "docs/src/architecture/cli-design-rules-ssot.md",
    "docs/src/architecture/trim-build-defer-policy.md",
    "docs/src/architecture/vox-cli-build-feature-inventory.md",
    "docs/src/architecture/crate-build-lanes-migration.md",
    "docs/src/architecture/crate-topology-buckets.md",
    "docs/src/architecture/deployment-compose-ssot.md",
    "docs/src/architecture/mens-training-ssot.md",
    "docs/src/how-to/how-to-train-mens-4080.md",
    "docs/src/architecture/phase0-migration-signoff.md",
    "docs/src/architecture/migration-script-dashboard.md",
    "docs/src/architecture/vox-automation-primitives.md",
    "docs/src/architecture/typescript-migration-boundary.md",
    "docs/src/architecture/vox-web-stack-ssot.md",
    "docs/src/architecture/external-scripts-boundary-archive.md",
    "docs/src/ci/runner-contract.md",
    "docs/src/ci/command-surface-duals.md",
    "docs/src/ci/command-compliance-ssot.md",
    "docs/src/ci/doc-inventory-ssot.md",
    "docs/src/ci/crate-hardening-matrix.md",
    "docs/src/ci/github-hosted-exceptions.md",
    "docs/src/ci/workflow-enumeration.md",
    "docs/src/ci/binary-release-contract.md",
    "docs/src/ci/cli-baseline-metrics.md",
];

pub(crate) const CODEX_SSOT_FILES: &[&str] = &[
    "contracts/index.yaml",
    "contracts/index.schema.json",
    "contracts/db/baseline-version-policy.yaml",
    "contracts/reports/evidence-snapshot-rev-c.json",
    "contracts/codex-api.openapi.yaml",
    "docs/src/adr/004-codex-arca-turso-ssot.md",
    "docs/src/architecture/codex-vnext-schema.md",
    "docs/src/architecture/codex-baas.md",
    "docs/src/architecture/orphan-surface-inventory.md",
    "docs/src/architecture/codex-legacy-migration.md",
    "docs/src/architecture/forward-migration-charter.md",
    "docs/src/architecture/codex-arca-import-policy.md",
    "docs/src/architecture/codex-arca-compatibility-boundaries.md",
    "infra/coolify/docker-compose.yml",
    "scripts/check_codex_ssot.sh",
    "scripts/check_codex_ssot.ps1",
];

pub(crate) const OPENAPI_SUBSTRINGS: &[&str] = &[
    "openapi:",
    "/api/codex/research-session",
    "/api/codex/conversations/{conv_id}/versions",
    "/api/codex/conversation-edges",
    "/api/codex/topics/{topic_id}/evolution-events",
];

pub(crate) const MANIFEST_SNIPPETS: &[&str] = &[
    "BASELINE_VERSION",
    "SCHEMA_FRAGMENTS",
    "schema_baseline_digest_hex",
];

pub(crate) const FEATURE_SETS: &[&str] = &[
    "",
    "codex",
    "stub-check",
    "codex,stub-check",
    "live",
    "mens-dei",
    "oratio",
    "dashboard",
    "ars",
    "extras-ludus",
    "ludus-hud",
    "gpu,mens-qlora,stub-check",
    "island",
    "island,mens-base",
    "script-execution",
    "script-execution,stub-check",
    "mens",
    "script-execution,mens",
    "workflow-runtime",
];
