use anyhow::{Context, Result, anyhow};
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

const REGISTRY_PATH: &str = "contracts/gui/surface-registry.v1.yaml";
const SCHEMA_PATH: &str = "contracts/gui/surface-registry.v1.schema.json";
const REPORT_PATH: &str = "contracts/reports/gui-surface-registry.v1.json";
const GENERATED_TS: &str = "crates/vox-gui/ui/src/generated/surfaceRegistry.generated.ts";
const GUI_APP: &str = "crates/vox-gui/ui/src/App.tsx";

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RepresentationTier {
    None,
    GenericForm,
    CuratedDecorator,
    LiveBackend,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SurfaceEntry {
    #[serde(default)]
    pub view_key: Option<String>,
    #[serde(default)]
    pub cli_group: Option<String>,
    pub representation_tier: RepresentationTier,
    #[serde(default)]
    pub nav_label: Option<String>,
    #[serde(default)]
    pub nav_icon: Option<String>,
    #[serde(default)]
    pub nav_group: Option<String>,
    #[serde(default)]
    pub parent_surface: Option<String>,
    #[serde(default)]
    pub notes: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurfaceRegistry {
    pub x_vox_version: u32,
    pub schema_version: u8,
    pub surfaces: Vec<SurfaceEntry>,
}

/// Groups already classified by some entry's `cli_group`.
fn covered_groups(reg: &SurfaceRegistry) -> BTreeSet<String> {
    reg.surfaces
        .iter()
        .filter_map(|e| e.cli_group.clone())
        .collect()
}

/// Top-level clap groups not yet covered by any entry.
pub fn missing_groups(reg: &SurfaceRegistry, top_level: &BTreeSet<String>) -> Vec<String> {
    let covered = covered_groups(reg);
    top_level.difference(&covered).cloned().collect()
}

/// Return a registry with `none`-tier entries appended for every missing group,
/// surfaces sorted by (cli_group, view_key) for deterministic output.
pub fn backfill(mut reg: SurfaceRegistry, missing: &[String]) -> SurfaceRegistry {
    for g in missing {
        reg.surfaces.push(SurfaceEntry {
            view_key: None,
            cli_group: Some(g.clone()),
            representation_tier: RepresentationTier::None,
            nav_label: None,
            nav_icon: None,
            nav_group: None,
            parent_surface: None,
            notes: None,
        });
    }
    reg.surfaces.sort_by(|a, b| {
        let ka = (
            a.cli_group.clone().unwrap_or_default(),
            a.view_key.clone().unwrap_or_default(),
        );
        let kb = (
            b.cli_group.clone().unwrap_or_default(),
            b.view_key.clone().unwrap_or_default(),
        );
        ka.cmp(&kb)
    });
    reg
}

/// Curated/live entries whose `view_key` is absent or not present in App.tsx.
pub fn wiring_violations(reg: &SurfaceRegistry, app_src: &str) -> Vec<String> {
    let mut v = Vec::new();
    for e in &reg.surfaces {
        if matches!(
            e.representation_tier,
            RepresentationTier::CuratedDecorator | RepresentationTier::LiveBackend
        ) {
            match &e.view_key {
                None => v.push(format!(
                    "{:?} surface for cli_group={:?} has no view_key",
                    e.representation_tier, e.cli_group
                )),
                Some(vk) if !app_src.contains(&format!("'{vk}'")) => {
                    v.push(format!("view_key '{vk}' is not referenced in App.tsx"));
                }
                Some(_) => {}
            }
        }
    }
    v
}

/// Deterministic TypeScript projection of the registry.
pub fn generate_ts(reg: &SurfaceRegistry) -> String {
    let opt = |o: &Option<String>| match o {
        Some(s) => format!("'{}'", s.replace('\'', "\\'")),
        None => "null".to_string(),
    };
    let tier = |t: &RepresentationTier| match t {
        RepresentationTier::None => "none",
        RepresentationTier::GenericForm => "generic_form",
        RepresentationTier::CuratedDecorator => "curated_decorator",
        RepresentationTier::LiveBackend => "live_backend",
    };
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by `vox ci gui-surface-registry --write`. DO NOT EDIT.\n");
    out.push_str("export type RepresentationTier = 'none' | 'generic_form' | 'curated_decorator' | 'live_backend';\n");
    out.push_str("export interface SurfaceRegistryEntry {\n");
    out.push_str(
        "  viewKey: string | null;\n  cliGroup: string | null;\n  tier: RepresentationTier;\n",
    );
    out.push_str(
        "  navLabel: string | null;\n  navIcon: string | null;\n  navGroup: string | null;\n  parentSurface: string | null;\n}\n",
    );
    out.push_str("export const SURFACE_REGISTRY: SurfaceRegistryEntry[] = [\n");
    for e in &reg.surfaces {
        out.push_str(&format!(
            "  {{ viewKey: {}, cliGroup: {}, tier: '{}', navLabel: {}, navIcon: {}, navGroup: {}, parentSurface: {} }},\n",
            opt(&e.view_key),
            opt(&e.cli_group),
            tier(&e.representation_tier),
            opt(&e.nav_label),
            opt(&e.nav_icon),
            opt(&e.nav_group),
            opt(&e.parent_surface),
        ));
    }
    out.push_str("];\n");
    out
}

/// Top-level command groups, from `contracts/cli/command-registry.yaml` rather than the
/// compiled clap tree: the tree varies with cargo features, so a feature-built CI binary and
/// a default-built local binary would disagree on the committed report. The registry lists
/// every compiled path in either build (guarded by gui_surface_coverage's
/// `every_compiled_clap_path_is_in_command_registry`).
fn top_level_groups(repo_root: &Path) -> Result<BTreeSet<String>> {
    use vox_cli_core::command_registry_model::RegistryFile;

    let path = repo_root.join("contracts/cli/command-registry.yaml");
    let raw = fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    let reg: RegistryFile =
        serde_yaml::from_str(&raw).with_context(|| format!("parse {}", path.display()))?;
    let mut groups: BTreeSet<String> = reg
        .operations
        .into_iter()
        .filter(|op| op.surface == "vox-cli" && op.status != "retired")
        .filter_map(|op| op.path.into_iter().next())
        .collect();
    // Union feature-gated top-level groups so the gate is not structurally blind to commands that
    // are compiled out of this build (e.g. `dei`/`visus`/`safety`/`attention` behind `--features
    // dei`). Without this, those groups never appear in `missing_groups` and silently escape
    // classification. See A3.
    for (name, _feature) in crate::command_catalog::feature_gated_group_names() {
        groups.insert(name.to_string());
    }
    Ok(groups)
}

fn load_registry(repo_root: &Path) -> Result<SurfaceRegistry> {
    let path = repo_root.join(REGISTRY_PATH);
    let raw = fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    // Validate against the JSON schema first (parse YAML → JSON value).
    let yaml_val: serde_json::Value =
        serde_yaml::from_str(&raw).with_context(|| format!("parse {}", path.display()))?;
    let schema_raw =
        fs::read_to_string(repo_root.join(SCHEMA_PATH)).context("read registry schema")?;
    let schema_val: serde_json::Value =
        serde_json::from_str(&schema_raw).context("parse registry schema")?;
    let validator =
        vox_jsonschema_util::compile_validator(&schema_val, repo_root.join(SCHEMA_PATH).display())
            .context("compile surface-registry schema")?;
    vox_jsonschema_util::validate(&yaml_val, &validator, "surface-registry schema")
        .context("validate surface-registry against schema")?;
    serde_yaml::from_str(&raw).with_context(|| format!("deserialize {}", path.display()))
}

pub fn run(repo_root: &Path, write: bool) -> Result<()> {
    let parsed = load_registry(repo_root)?;
    let top_level = top_level_groups(repo_root)?;
    let missing = missing_groups(&parsed, &top_level);
    let resolved = backfill(parsed, &missing);

    let app_src = fs::read_to_string(repo_root.join(GUI_APP)).context("read App.tsx")?;
    let violations = wiring_violations(&resolved, &app_src);

    let ts = generate_ts(&resolved);
    let report = serde_json::json!({
        "schema_version": 1,
        "top_level_groups": top_level.iter().collect::<Vec<_>>(),
        "surface_count": resolved.surfaces.len(),
        "unclassified_backfilled": missing,
        "wiring_violations": violations,
    });
    let report_str = serde_json::to_string_pretty(&report)? + "\n";

    if write {
        let yaml_out = serde_yaml::to_string(&resolved)?;
        fs::write(repo_root.join(REGISTRY_PATH), yaml_out).context("write registry yaml")?;
        fs::write(repo_root.join(GENERATED_TS), &ts).context("write generated ts")?;
        fs::write(repo_root.join(REPORT_PATH), report_str).context("write report")?;
        println!("gui-surface-registry: wrote registry, generated TS, and report");
        return Ok(());
    }

    if !missing.is_empty() {
        return Err(anyhow!(
            "gui-surface-registry: {} unclassified top-level CLI group(s) [{}] — run `vox ci gui-surface-registry --write`, then set representation_tier in {}",
            missing.len(),
            missing.join(", "),
            REGISTRY_PATH
        ));
    }
    if !violations.is_empty() {
        return Err(anyhow!(
            "gui-surface-registry: wiring violations:\n  - {}",
            violations.join("\n  - ")
        ));
    }
    let existing_ts = fs::read_to_string(repo_root.join(GENERATED_TS)).with_context(|| {
        format!("read {GENERATED_TS} (run `vox ci gui-surface-registry --write`)")
    })?;
    if existing_ts.trim() != ts.trim() {
        return Err(anyhow!(
            "gui-surface-registry: {GENERATED_TS} drift (run `vox ci gui-surface-registry --write`)"
        ));
    }
    println!("gui-surface-registry: registry and generated TS are up to date");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn reg(entries: Vec<SurfaceEntry>) -> SurfaceRegistry {
        SurfaceRegistry {
            x_vox_version: 2,
            schema_version: 1,
            surfaces: entries,
        }
    }

    #[test]
    fn missing_groups_detects_unclassified() {
        let r = reg(vec![SurfaceEntry {
            view_key: Some("scientia".into()),
            cli_group: Some("scientia".into()),
            representation_tier: RepresentationTier::CuratedDecorator,
            nav_label: None,
            nav_icon: None,
            nav_group: None,
            parent_surface: None,
            notes: None,
        }]);
        let top: BTreeSet<String> = ["scientia", "build", "audit"]
            .iter()
            .map(|s| s.to_string())
            .collect();
        let mut got = missing_groups(&r, &top);
        got.sort();
        assert_eq!(got, vec!["audit".to_string(), "build".to_string()]);
    }

    #[test]
    fn backfill_appends_none_entries_sorted() {
        let r = reg(vec![]);
        let out = backfill(r, &["build".into(), "audit".into()]);
        assert_eq!(out.surfaces.len(), 2);
        assert_eq!(out.surfaces[0].cli_group.as_deref(), Some("audit"));
        assert_eq!(
            out.surfaces[0].representation_tier,
            RepresentationTier::None
        );
    }

    #[test]
    fn wiring_violation_when_view_key_absent_from_app() {
        let r = reg(vec![SurfaceEntry {
            view_key: Some("ghost".into()),
            cli_group: Some("ghost".into()),
            representation_tier: RepresentationTier::CuratedDecorator,
            nav_label: None,
            nav_icon: None,
            nav_group: None,
            parent_surface: None,
            notes: None,
        }]);
        let violations = wiring_violations(&r, "switch (activeView) { case 'dashboard': }");
        assert_eq!(violations.len(), 1);
        assert!(violations[0].contains("ghost"));
    }

    fn repo_root() -> std::path::PathBuf {
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("repo root")
    }

    /// The committed report must not depend on build features: CI builds `vox` with
    /// `extras-ludus,ars,...` and the `ssot-autoregen` bot committed the groups those
    /// compile in (`gamify`, `skill`, …), while a default build dropped them, so local
    /// and CI kept overwriting each other. The registry lists them either way.
    #[test]
    fn top_level_groups_are_feature_independent() {
        let groups = top_level_groups(&repo_root()).unwrap();
        for g in ["gamify", "skill", "review", "openclaw", "recensio"] {
            assert!(
                groups.contains(g),
                "expected feature-gated top-level group {g:?} regardless of build features, got {groups:?}"
            );
        }
    }

    #[test]
    fn top_level_groups_include_feature_gated_dei_groups() {
        // Even in a default (non-dei) build, the gate must "see" dei-gated
        // top-level groups so they can be classified with a waiver (A3).
        let groups = top_level_groups(&repo_root()).unwrap();
        for g in ["dei", "visus", "safety", "attention"] {
            assert!(
                groups.contains(g),
                "expected top-level group {g:?} to be present (feature-gate aware), got {groups:?}"
            );
        }
    }

    #[test]
    fn generate_ts_is_deterministic_and_typed() {
        let r = reg(vec![SurfaceEntry {
            view_key: Some("scientia".into()),
            cli_group: Some("scientia".into()),
            representation_tier: RepresentationTier::CuratedDecorator,
            nav_label: Some("Scientia".into()),
            nav_icon: Some("file".into()),
            nav_group: Some("research".into()),
            parent_surface: None,
            notes: None,
        }]);
        let ts = generate_ts(&r);
        assert!(ts.contains("export const SURFACE_REGISTRY"));
        assert!(ts.contains("viewKey: 'scientia'"));
        assert!(ts.contains("tier: 'curated_decorator'"));
    }
}
