use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

const PRE_COMMIT_HOOK: &str = r#"#!/usr/bin/env bash
# File: .git/hooks/pre-commit
# Automatically generated by `vox ci install-hooks`

echo "🦶 Running VoxCI line-endings check..."

# Run the strict line-ending validator, scoping to changed files (--all is not needed here)
cargo run -q -p vox-cli -- ci line-endings

if [ $? -ne 0 ]; then
    echo "❌ Commit aborted: CRLF line-endings detected. Run the formatter or fix them in your IDE, then git add again."
    exit 1
fi

echo "✅ Line endings OK."
exit 0
"#;

pub fn run(root: &Path) -> Result<()> {
    let git_dir = root.join(".git");
    if !git_dir.is_dir() {
        // Just print a warning, no need to fail the CI step if someone isn't inside a git clone.
        println!("Skipping hook installation: {} is not a valid .git directory", git_dir.display());
        return Ok(());
    }

    let hooks_dir = git_dir.join("hooks");
    if !hooks_dir.exists() {
        fs::create_dir_all(&hooks_dir).with_context(|| format!("create {}", hooks_dir.display()))?;
    }

    let pre_commit_path = hooks_dir.join("pre-commit");
    
    fs::write(&pre_commit_path, PRE_COMMIT_HOOK).with_context(|| format!("write {}", pre_commit_path.display()))?;

    // Make the hook executable on Unix systems
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(mut perms) = fs::metadata(&pre_commit_path).map(|m| m.permissions()) {
            perms.set_mode(0o755);
            let _ = fs::set_permissions(&pre_commit_path, perms);
        }
    }

    println!("✅ Installed Git pre-commit line-endings hook to {}", pre_commit_path.display());
    Ok(())
}
