//! Regenerate `examples/PARSE_STATUS.md` from `examples/golden/*.vox` parse results.

use anyhow::{Context, Result};
use std::path::Path;

/// Emit or verify the parse-status matrix markdown at `examples/PARSE_STATUS.md`.
pub fn run(repo_root: &Path, write: bool) -> Result<()> {
    let golden_dir = repo_root.join("examples/golden");
    let mut rows: Vec<(String, &'static str)> = Vec::new();

    for entry in std::fs::read_dir(&golden_dir)
        .with_context(|| format!("read_dir {}", golden_dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("vox") {
            continue;
        }
        let rel = path
            .strip_prefix(repo_root)
            .unwrap_or(&path)
            .to_string_lossy()
            .replace('\\', "/");
        let source =
            std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
        let tokens = vox_compiler::lexer::lex(&source);
        let status = match vox_compiler::parser::parse(tokens) {
            Ok(_) => "✅ PASS",
            Err(_) => "❌ FAIL",
        };
        rows.push((rel, status));
    }

    rows.sort_by(|a, b| a.0.cmp(&b.0));

    let today = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let mut md = String::new();
    md.push_str("# Parse Status Matrix\n\n");
    md.push_str("> Generated by `vox ci parse-status --write`. Do not edit manually.\n");
    md.push_str(&format!("> Last run: {today}\n\n"));
    md.push_str("| File | Status | Syntax Version | Parse Result | Last Validated |\n");
    md.push_str("|------|--------|----------------|--------------|----------------|\n");

    for (rel, status) in &rows {
        let short = rel.strip_prefix("examples/").unwrap_or(rel);
        md.push_str(&format!(
            "| {short} | golden | 0.5.0 | {status} | {today} |\n"
        ));
    }

    let out_path = repo_root.join("examples/PARSE_STATUS.md");
    if write {
        std::fs::write(&out_path, &md).with_context(|| format!("write {}", out_path.display()))?;
        println!("Wrote {}", out_path.display());
        return Ok(());
    }

    let existing = std::fs::read_to_string(&out_path)
        .with_context(|| format!("read {}", out_path.display()))?;
    if existing != md {
        anyhow::bail!(
            "{} is out of date. Run:\n  cargo run -p vox-cli -- ci parse-status --write",
            out_path.display()
        );
    }
    println!(
        "parse-status: {} matches generator output",
        out_path.display()
    );
    Ok(())
}
