//! `vox ci scaling-audit` — validate scaling SSOT and emit per-crate backlog artifacts.

use anyhow::{Context, Result, anyhow};
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use std::fs;
use std::path::{Path, PathBuf};

use super::cargo_bin;
use super::cmd_enums::ScalingAuditCmd;

const POLICY_REL: &str = "contracts/scaling/policy.yaml";
const POLICY_SCHEMA_REL: &str = "contracts/scaling/policy.schema.json";
const TEMPLATES_REL: &str = "contracts/scaling/task-templates.yaml";
const REPORT_ROOT: &str = "contracts/reports/scaling-audit";

#[derive(Debug, Deserialize)]
struct TaskTemplatesFile {
    #[allow(dead_code)]
    schema_version: u32,
    categories: Vec<TaskCategory>,
}

#[derive(Debug, Deserialize)]
struct TaskCategory {
    id: String,
    pattern: String,
    impact: String,
    risk: String,
    title: String,
    verification: String,
}

/// Validate `contracts/scaling/policy.yaml` against `policy.schema.json`.
fn verify_policy_schema(repo_root: &Path) -> Result<()> {
    let policy_path = repo_root.join(POLICY_REL);
    let raw = fs::read_to_string(&policy_path)
        .with_context(|| format!("read {}", policy_path.display()))?;
    let schema_path = repo_root.join(POLICY_SCHEMA_REL);
    if !schema_path.is_file() {
        return Err(anyhow!("missing {}", schema_path.display()));
    }
    let schema_val: JsonValue = serde_json::from_str(
        &fs::read_to_string(&schema_path).with_context(|| format!("read {}", schema_path.display()))?,
    )
    .with_context(|| format!("parse {}", schema_path.display()))?;
    let instance: JsonValue =
        serde_yaml::from_str(&raw).context("parse scaling policy as JSON value")?;
    let validator =
        jsonschema::validator_for(&schema_val).context("compile scaling policy.schema.json")?;
    validator
        .validate(&instance)
        .map_err(|e| anyhow!("scaling policy does not match schema: {e}"))?;
    println!("scaling policy YAML OK (schema validated)");
    Ok(())
}

/// Embedded policy must match on-disk file (vox-scaling-policy `include_str`).
fn verify_embedded_policy_roundtrip(repo_root: &Path) -> Result<()> {
    let policy_path = repo_root.join(POLICY_REL);
    let disk = fs::read_to_string(&policy_path).with_context(|| format!("read {}", policy_path.display()))?;
    let parsed = vox_scaling_policy::ScalingPolicy::from_yaml_str(&disk)
        .context("parse policy with vox-scaling-policy")?;
    if parsed.schema_version < 1 {
        return Err(anyhow!("scaling policy schema_version must be >= 1"));
    }
    println!("vox-scaling-policy parse OK");
    Ok(())
}

fn workspace_crates(repo_root: &Path) -> Result<Vec<String>> {
    let mut out = Vec::new();
    let crates_dir = repo_root.join("crates");
    for e in fs::read_dir(&crates_dir).with_context(|| format!("read_dir {}", crates_dir.display()))? {
        let e = e?;
        if !e.file_type()?.is_dir() {
            continue;
        }
        if e.path().join("Cargo.toml").is_file() {
            out.push(e.file_name().to_string_lossy().into_owned());
        }
    }
    out.sort();
    if out.is_empty() {
        return Err(anyhow!("no crates found under {}", crates_dir.display()));
    }
    Ok(out)
}

fn load_templates(repo_root: &Path) -> Result<TaskTemplatesFile> {
    let p = repo_root.join(TEMPLATES_REL);
    let raw = fs::read_to_string(&p).with_context(|| format!("read {}", p.display()))?;
    serde_yaml::from_str(&raw).context("parse task-templates.yaml")
}

fn emit_per_crate_backlogs(repo_root: &Path, crates: &[String], templates: &TaskTemplatesFile) -> Result<()> {
    let by_crate = PathBuf::from(repo_root).join(REPORT_ROOT).join("by-crate");
    fs::create_dir_all(&by_crate).with_context(|| format!("create {}", by_crate.display()))?;

    for c in crates {
        let mut md = String::new();
        md.push_str(&format!("# Scaling backlog: `{c}`\n\n"));
        md.push_str("Generated by `vox ci scaling-audit emit-reports`. Do not hand-edit IDs; regenerate instead.\n\n");
        for cat in &templates.categories {
            let id = format!("SCALE-{}-{}", c.to_uppercase().replace('-', "_"), cat.id.to_uppercase());
            md.push_str(&format!("## {id}\n"));
            md.push_str(&format!("- **Pattern**: `{}`\n", cat.pattern));
            md.push_str(&format!("- **Impact**: {}\n", cat.impact));
            md.push_str(&format!("- **Risk**: {}\n", cat.risk));
            md.push_str(&format!("- **Task**: {}\n", cat.title.replace("{crate}", c)));
            md.push_str(&format!(
                "- **Verification**: {}\n\n",
                cat.verification.replace("{crate}", c)
            ));
        }
        let dest = by_crate.join(format!("{c}.md"));
        fs::write(&dest, md).with_context(|| format!("write {}", dest.display()))?;
    }
    println!("Wrote {} per-crate backlog files under {}", crates.len(), by_crate.display());
    Ok(())
}

#[derive(Serialize)]
struct RollupEntry {
    id: String,
    #[serde(rename = "crate")]
    krate: String,
    template: String,
    pattern: String,
    file: String,
}

fn emit_rollup_index(repo_root: &Path, crates: &[String], templates: &TaskTemplatesFile) -> Result<()> {
    let rollup_dir = PathBuf::from(repo_root).join(REPORT_ROOT).join("rollup");
    fs::create_dir_all(&rollup_dir).context("create rollup dir")?;
    let mut entries: Vec<RollupEntry> = Vec::new();
    for c in crates {
        for cat in &templates.categories {
            let id = format!("SCALE-{}-{}", c.to_uppercase().replace('-', "_"), cat.id.to_uppercase());
            entries.push(RollupEntry {
                id,
                krate: c.clone(),
                template: cat.id.clone(),
                pattern: cat.pattern.clone(),
                file: format!("by-crate/{c}.md"),
            });
        }
    }
    let header = concat!(
        "# Scaling audit rollup — stable IDs (SSOT)\n",
        "# Generated by `vox ci scaling-audit emit-reports`.\n\n",
    );
    let body = serde_yaml::to_string(&entries).context("serialize rollup INDEX")?;
    let dest = rollup_dir.join("INDEX.yaml");
    fs::write(&dest, format!("{header}{body}")).with_context(|| format!("write {}", dest.display()))?;
    println!("Wrote {}", dest.display());
    Ok(())
}

fn run_toestub_json_snapshot(repo_root: &Path) -> Result<()> {
    let cargo = cargo_bin();
    let out_path = PathBuf::from(repo_root).join(REPORT_ROOT).join("findings-latest.json");
    fs::create_dir_all(out_path.parent().unwrap()).ok();
    let output = std::process::Command::new(&cargo)
        .current_dir(repo_root)
        .args(["run", "-q", "-p", "vox-toestub", "--bin", "toestub", "--"])
        .arg("--mode")
        .arg("audit")
        .arg("--format")
        .arg("json")
        .arg("--min-severity")
        .arg("info")
        .arg("crates")
        .output()
        .context("spawn toestub json")?;
    if !output.status.success() {
        return Err(anyhow!(
            "toestub audit failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    // CLI prints JSON to stdout; capture full stdout (Reporter outputs findings only).
    fs::write(&out_path, &output.stdout).with_context(|| format!("write {}", out_path.display()))?;
    println!("Wrote {}", out_path.display());
    Ok(())
}

/// Run scaling-audit subcommand.
pub fn run(repo_root: &Path, cmd: ScalingAuditCmd) -> Result<()> {
    match cmd {
        ScalingAuditCmd::Verify => {
            verify_policy_schema(repo_root)?;
            verify_embedded_policy_roundtrip(repo_root)?;
            println!("scaling-audit verify OK");
            Ok(())
        }
        ScalingAuditCmd::EmitReports => {
            verify_policy_schema(repo_root)?;
            verify_embedded_policy_roundtrip(repo_root)?;
            let crates = workspace_crates(repo_root)?;
            let templates = load_templates(repo_root)?;
            let n_tasks = crates.len() * templates.categories.len();
            if n_tasks < 300 {
                return Err(anyhow!(
                    "expected at least 300 tasks (crates * templates); got {n_tasks}. Add crates or template rows."
                ));
            }
            emit_per_crate_backlogs(repo_root, &crates, &templates)?;
            emit_rollup_index(repo_root, &crates, &templates)?;
            run_toestub_json_snapshot(repo_root)?;
            println!(
                "scaling-audit emit-reports OK ({} crates × {} categories = {} tasks)",
                crates.len(),
                templates.categories.len(),
                n_tasks
            );
            Ok(())
        }
    }
}
