use crate::ast::scalar_mapping::VoxScalar;
use crate::hir::{HirModule, HirType};

pub fn emit_api_client(module: &HirModule) -> String {
    if module.server_fns.is_empty()
        && module.query_fns.is_empty()
        && module.mutation_fns.is_empty()
    {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("// Auto-generated API client for Vox server functions\n");
    out.push_str("// Do not edit manually — regenerated on each build.\n\n");

    out.push_str("const API_BASE = '';\n\n");

    for sf in module
        .server_fns
        .iter()
        .chain(module.query_fns.iter())
        .chain(module.mutation_fns.iter())
    {
        // Generate TypeScript function signature
        let params: Vec<String> = sf
            .params
            .iter()
            .map(|p| {
                let ts_type = p
                    .type_ann
                    .as_ref()
                    .map_or("any".to_string(), hir_type_to_ts);
                format!("{}: {}", p.name, ts_type)
            })
            .collect();

        let return_ts = sf
            .return_type
            .as_ref()
            .map_or("any".to_string(), hir_type_to_ts);

        out.push_str(&format!(
            "export async function {}({}): Promise<{}> {{\n",
            sf.name,
            params.join(", "),
            return_ts,
        ));
        out.push_str(&format!(
            "  const response = await fetch(`${{API_BASE}}{}`, {{\n",
            sf.route_path,
        ));
        out.push_str("    method: 'POST',\n");
        out.push_str("    headers: { 'Content-Type': 'application/json' },\n");

        // Build body from params
        let body_fields: Vec<String> = sf.params.iter().map(|p| p.name.clone()).collect();
        out.push_str(&format!(
            "    body: JSON.stringify({{ {} }}),\n",
            body_fields.join(", ")
        ));
        out.push_str("  });\n");
        out.push_str("  if (!response.ok) throw new Error(`Server error: ${response.status}`);\n");
        out.push_str("  return response.json();\n");
        out.push_str("}\n\n");
    }

    out
}

fn hir_type_to_ts(ty: &HirType) -> String {
    match ty {
        HirType::Named(name) => {
            if let Some(s) = VoxScalar::parse(name) {
                s.as_ts_primitive().to_string()
            } else {
                match name.as_str() {
                    "Unit" => "void".to_string(),
                    other => other.to_string(),
                }
            }
        }
        HirType::Generic(name, args) => {
            let args_str: Vec<String> = args.iter().map(hir_type_to_ts).collect();
            match name.as_str() {
                "list" | "List" => format!("{}[]", args_str.first().unwrap_or(&"any".to_string())),
                _ => format!("{}<{}>", name, args_str.join(", ")),
            }
        }
        HirType::Function(params, ret) => {
            let params_str: Vec<String> = params
                .iter()
                .enumerate()
                .map(|(i, p)| format!("arg{}: {}", i, hir_type_to_ts(p)))
                .collect();
            format!("({}) => {}", params_str.join(", "), hir_type_to_ts(ret))
        }
        HirType::Tuple(elems) => {
            let elems_str: Vec<String> = elems.iter().map(hir_type_to_ts).collect();
            format!("[{}]", elems_str.join(", "))
        }
        HirType::Unit => "void".to_string(),
    }
}

/// Generate the MCP (Model Context Protocol) JSON-RPC server binary.
/// Communicates over stdio: reads JSON-RPC requests from stdin, writes responses to stdout.
pub fn emit_mcp_server(module: &HirModule, package_name: &str) -> String {
    let crate_name = package_name.replace('-', "_");
    let mut out = String::new();

    out.push_str("// MCP Server — Generated by Vox Compiler\n");
    out.push_str("// Implements the Model Context Protocol (JSON-RPC 2.0 over stdio)\n\n");
    out.push_str("use serde_json::{json, Value};\n");
    out.push_str("use std::io::{self, BufRead, Write};\n");
    out.push_str(&format!("use {}::*;\n\n", crate_name));

    // Tool dispatch function
    out.push_str("fn dispatch_tool(name: &str, args: &Value) -> Result<Value, String> {\n");
    out.push_str("    match name {\n");
    for tool in &module.mcp_tools {
        let fn_name = &tool.func.name;
        out.push_str(&format!("        \"{}\" => {{\n", fn_name));
        // Extract args
        for param in &tool.func.params {
            let p = &param.name;
            out.push_str(&format!(
                "            let {p} = args.get(\"{p}\").cloned().unwrap_or(Value::Null);\n"
            ));
        }
        // Call function — for now, wrap result in Ok(json)
        let arg_list: Vec<String> = tool
            .func
            .params
            .iter()
            .map(|p| {
                // Convert from serde_json::Value to the appropriate type
                let name = &p.name;
                match p.type_ann.as_ref() {
                    Some(HirType::Named(t)) if t == "String" || t == "str" => {
                        format!("{name}.as_str().unwrap_or_default().to_string()")
                    }
                    Some(HirType::Named(t)) if t == "i64" || t == "int" => {
                        format!("{name}.as_i64().unwrap_or(0)")
                    }
                    Some(HirType::Named(t)) if t == "f64" || t == "float" => {
                        format!("{name}.as_f64().unwrap_or(0.0)")
                    }
                    Some(HirType::Named(t)) if t == "bool" => {
                        format!("{name}.as_bool().unwrap_or(false)")
                    }
                    _ => name.to_string(),
                }
            })
            .collect();
        out.push_str(&format!(
            "            let result = {}({});\n",
            fn_name,
            arg_list.join(", ")
        ));
        out.push_str("            Ok(serde_json::to_value(result).unwrap_or(Value::Null))\n");
        out.push_str("        }\n");
    }
    out.push_str("        _ => Err(format!(\"Unknown tool: {}\", name)),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Build tool list JSON
    out.push_str("fn tool_list() -> Value {\n");
    out.push_str("    json!({\n");
    out.push_str("        \"tools\": [\n");
    for (i, tool) in module.mcp_tools.iter().enumerate() {
        let trailing = if i + 1 < module.mcp_tools.len() {
            ","
        } else {
            ""
        };
        out.push_str("            {\n");
        out.push_str(&format!(
            "                \"name\": \"{}\",\n",
            tool.func.name
        ));
        out.push_str(&format!(
            "                \"description\": \"{}\",\n",
            tool.description.replace('"', "\\\"")
        ));
        // Build inputSchema from params
        out.push_str("                \"inputSchema\": {\n");
        out.push_str("                    \"type\": \"object\",\n");
        out.push_str("                    \"properties\": {\n");
        for (j, param) in tool.func.params.iter().enumerate() {
            let json_type = match param.type_ann.as_ref() {
                Some(HirType::Named(t)) if t == "String" || t == "str" => "string",
                Some(HirType::Named(t)) if t == "i64" || t == "int" => "integer",
                Some(HirType::Named(t)) if t == "f64" || t == "float" => "number",
                Some(HirType::Named(t)) if t == "bool" => "boolean",
                _ => "string",
            };
            let param_trailing = if j + 1 < tool.func.params.len() {
                ","
            } else {
                ""
            };
            out.push_str(&format!(
                "                        \"{}\": {{ \"type\": \"{}\" }}{}",
                param.name, json_type, param_trailing
            ));
            out.push('\n');
        }
        out.push_str("                    },\n");
        // All params required
        let required: Vec<String> = tool
            .func
            .params
            .iter()
            .map(|p| format!("\"{}\"", p.name))
            .collect();
        out.push_str(&format!(
            "                    \"required\": [{}]\n",
            required.join(", ")
        ));
        out.push_str("                }\n");
        out.push_str(&format!("            }}{}\n", trailing));
    }
    out.push_str("        ]\n");
    out.push_str("    })\n");
    out.push_str("}\n\n");

    // Main loop — JSON-RPC over stdio
    out.push_str("fn main() {\n");
    out.push_str("    let stdin = io::stdin();\n");
    out.push_str("    let mut stdout = io::stdout();\n");
    out.push_str("    for line in stdin.lock().lines() {\n");
    out.push_str("        let line = match line {\n");
    out.push_str("            Ok(l) => l,\n");
    out.push_str("            Err(_) => break,\n");
    out.push_str("        };\n");
    out.push_str("        if line.trim().is_empty() { continue; }\n");
    out.push_str("        let request: Value = match serde_json::from_str(&line) {\n");
    out.push_str("            Ok(v) => v,\n");
    out.push_str("            Err(e) => {\n");
    out.push_str("                let err = json!({\n");
    out.push_str("                    \"jsonrpc\": \"2.0\",\n");
    out.push_str("                    \"error\": { \"code\": -32700, \"message\": format!(\"Parse error: {e}\") },\n");
    out.push_str("                    \"id\": null\n");
    out.push_str("                });\n");
    out.push_str("                writeln!(stdout, \"{}\", err).ok();\n");
    out.push_str("                stdout.flush().ok();\n");
    out.push_str("                continue;\n");
    out.push_str("            }\n");
    out.push_str("        };\n");
    out.push_str("        let id = request.get(\"id\").cloned().unwrap_or(Value::Null);\n");
    out.push_str(
        "        let method = request.get(\"method\").and_then(|m| m.as_str()).unwrap_or(\"\");\n",
    );
    out.push_str("        let params = request.get(\"params\").cloned().unwrap_or(json!({}));\n\n");

    out.push_str("        let response = match method {\n");
    // initialize
    out.push_str("            \"initialize\" => json!({\n");
    out.push_str("                \"jsonrpc\": \"2.0\",\n");
    out.push_str("                \"id\": id,\n");
    out.push_str("                \"result\": {\n");
    out.push_str("                    \"protocolVersion\": \"2024-11-05\",\n");
    out.push_str("                    \"capabilities\": { \"tools\": {} },\n");
    out.push_str(&format!(
        "                    \"serverInfo\": {{ \"name\": \"{}\", \"version\": \"0.1.0\" }}\n",
        package_name
    ));
    out.push_str("                }\n");
    out.push_str("            }),\n");
    // tools/list
    out.push_str("            \"tools/list\" => {\n");
    out.push_str("                let tools = tool_list();\n");
    out.push_str("                json!({\n");
    out.push_str("                    \"jsonrpc\": \"2.0\",\n");
    out.push_str("                    \"id\": id,\n");
    out.push_str("                    \"result\": tools\n");
    out.push_str("                })\n");
    out.push_str("            }\n");
    // tools/call
    out.push_str("            \"tools/call\" => {\n");
    out.push_str("                let tool_name = params.get(\"name\").and_then(|n| n.as_str()).unwrap_or(\"\");\n");
    out.push_str("                let tool_args = params.get(\"arguments\").cloned().unwrap_or(json!({}));\n");
    out.push_str("                match dispatch_tool(tool_name, &tool_args) {\n");
    out.push_str("                    Ok(result) => json!({\n");
    out.push_str("                        \"jsonrpc\": \"2.0\",\n");
    out.push_str("                        \"id\": id,\n");
    out.push_str("                        \"result\": {\n");
    out.push_str("                            \"content\": [{ \"type\": \"text\", \"text\": serde_json::to_string(&result).unwrap_or_default() }]\n");
    out.push_str("                        }\n");
    out.push_str("                    }),\n");
    out.push_str("                    Err(e) => json!({\n");
    out.push_str("                        \"jsonrpc\": \"2.0\",\n");
    out.push_str("                        \"id\": id,\n");
    out.push_str("                        \"result\": {\n");
    out.push_str("                            \"isError\": true,\n");
    out.push_str(
        "                            \"content\": [{ \"type\": \"text\", \"text\": e }]\n",
    );
    out.push_str("                        }\n");
    out.push_str("                    }),\n");
    out.push_str("                }\n");
    out.push_str("            }\n");
    // notifications (no-ops)
    out.push_str(
        "            \"notifications/initialized\" | \"notifications/cancelled\" => continue,\n",
    );
    // unknown method
    out.push_str("            _ => json!({\n");
    out.push_str("                \"jsonrpc\": \"2.0\",\n");
    out.push_str("                \"id\": id,\n");
    out.push_str("                \"error\": { \"code\": -32601, \"message\": format!(\"Method not found: {}\", method) }\n");
    out.push_str("            }),\n");
    out.push_str("        };\n\n");

    out.push_str("        writeln!(stdout, \"{}\", response).ok();\n");
    out.push_str("        stdout.flush().ok();\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}
