//! Differential gate (spec §3.3): a golden that declares `// EXPECT:` prints the same
//! bytes under interp and a native `[[bin]]` from one generated crate. `// EXPECT-EXIT:
//! nonzero-both` exits non-zero on both and EXPECT lines are a prefix of each stdout.
//! `// EXPECT-TIER-ASYMMETRY: <reason>` fails when the tiers start agreeing.

use std::path::{Path, PathBuf};
use std::process::Command;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

fn vox_binary() -> PathBuf {
    if let Ok(p) = std::env::var("VOX_BIN") {
        return PathBuf::from(p);
    }
    let root = repo_root();
    let exe = root
        .join("target/debug")
        .join(if cfg!(windows) { "vox.exe" } else { "vox" });
    if !exe.exists() {
        let st = Command::new(env!("CARGO"))
            .current_dir(&root)
            .args(["build", "-q", "-p", "vox-cli", "--bin", "vox"])
            .status()
            .expect("spawn cargo");
        assert!(
            st.success(),
            "could not build the vox binary the gate spawns"
        );
    }
    exe
}

fn collect_vox_recursive(dir: &Path, out: &mut Vec<PathBuf>) {
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_dir() {
                collect_vox_recursive(&p, out);
            } else if p.extension().is_some_and(|e| e == "vox") {
                out.push(p);
            }
        }
    }
}

fn directive_lines(src: &str, key: &str) -> Vec<String> {
    src.lines()
        .filter_map(|l| {
            l.trim_start()
                .strip_prefix(key)
                .map(|r| r.strip_prefix(' ').unwrap_or(r).to_string())
        })
        .collect()
}

fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n").trim_end().to_string()
}

fn golden_stem(path: &Path) -> &str {
    path.file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or_else(|| panic!("non-UTF8 golden filename: {}", path.display()))
}

fn native_bin_path(native_dir: &Path, stem: &str) -> PathBuf {
    native_dir.join(if cfg!(windows) {
        format!("{stem}.exe")
    } else {
        stem.to_string()
    })
}

struct Run {
    code: Option<i32>,
    stdout: String,
    stderr: String,
}

fn run_interp(vox: &Path, file: &Path, cwd: &Path) -> Run {
    let out = Command::new(vox)
        .current_dir(cwd)
        .args(["run", "--mode", "interp"])
        .arg(file)
        .output()
        .unwrap_or_else(|e| panic!("spawn `{}` failed: {e}", vox.display()));
    Run {
        code: out.status.code(),
        stdout: String::from_utf8_lossy(&out.stdout).into_owned(),
        stderr: String::from_utf8_lossy(&out.stderr).into_owned(),
    }
}

/// Cross-platform-safe `path = "..."` value for a generated `Cargo.toml` (forward
/// slashes even on Windows, so cargo doesn't choke on `\` escapes in the TOML string).
/// vox:defactored-from vox-codegen 2026-09-06 — mirrors the private
/// `manifest_dependency_path` helper in `crates/vox-codegen/src/codegen_rust/manifest.rs`;
/// not worth a crate edge for one string transform.
fn manifest_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

/// Mirrors the private `module_needs_workflow_runtime` predicate in
/// `crates/vox-codegen/src/codegen_rust/pipeline.rs` (not `pub`, so it can't be called
/// directly from an integration test). vox:defactored-from vox-codegen 2026-09-06.
fn module_needs_workflow_runtime(module: &vox_compiler::hir::HirModule) -> bool {
    use vox_compiler::hir::{DurabilityKind, HirFn};
    let scan = |f: &HirFn| {
        matches!(
            f.durability,
            Some(DurabilityKind::Workflow | DurabilityKind::Activity)
        )
    };
    module.functions.iter().any(scan)
        || module.tests.iter().any(scan)
        || module.mcp_tools.iter().any(|t| scan(&t.func))
        || module.mcp_resources.iter().any(|r| scan(&r.func))
        || module.foralls.iter().any(|forall| scan(&forall.func))
        || module
            .functions
            .iter()
            .any(|f| f.schedule_interval.is_some())
}

/// Strip the script-mode `main.rs` boilerplate (the `// Generated by ...` comment,
/// `#![allow(unused)]`, and `use {crate}::*;`), rewriting the glob import to the nested
/// `lib_impl` module `merge_lib_and_main` wraps the golden's `lib.rs` in.
fn strip_main_header(main_rs: &str, crate_name: &str) -> String {
    let use_line = format!("use {crate_name}::*;");
    let mut body = String::new();
    for line in main_rs.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("// Generated by Vox Compiler") || trimmed == "#![allow(unused)]" {
            continue;
        }
        if trimmed == use_line {
            body.push_str("use lib_impl::*;\n");
            continue;
        }
        body.push_str(line);
        body.push('\n');
    }
    body.trim_start_matches('\n').to_string()
}

/// Fold one golden's generated `src/lib.rs` + `src/main.rs` into a single
/// `[[bin]]`-crate-root file.
///
/// Script-mode codegen emits a *pub* `fn main` into the lib (so the normal two-crate
/// `cargo run` shape works via `use {crate}::*;`) as well as the bin's own `fn main`.
/// Concatenating both files verbatim at the same scope would be `error[E0428]: the name
/// `main` is defined multiple times`. Nesting the lib in `mod lib_impl { .. }` and
/// glob-importing it avoids that: a local `fn main` silently shadows a glob-imported
/// `lib_impl::main` (Rust gives local items priority over glob imports), exactly like the
/// bin crate shadows the lib crate in the unmerged two-crate shape.
fn merge_lib_and_main(lib_rs: &str, main_rs: &str, crate_name: &str) -> String {
    let body = strip_main_header(main_rs, crate_name);
    format!(
        "#![allow(unused)]\n\nmod lib_impl {{\n{}\n}}\n\n{}",
        lib_rs.trim_end(),
        body
    )
}

/// One generated crate, N [[bin]] targets, `serde_json` with `preserve_order`.
/// Implementation: write a temp crate whose bins are the native-compiled goldens
/// produced by invoking the existing native codegen once per golden *into the same
/// `CARGO_TARGET_DIR`*, then `cargo build --bins` once. Do **not** call
/// `vox run --mode script` per golden — that path discards the shared target dir.
fn build_native_bins(vox: &Path, files: &[PathBuf], bundle: &Path) -> PathBuf {
    let _ = vox;
    let root = repo_root();
    let runtime_path = root.join("crates").join("vox-actor-runtime");
    assert!(
        runtime_path.is_dir(),
        "vox-actor-runtime not found at {}",
        runtime_path.display()
    );

    std::fs::create_dir_all(bundle.join("src/bin")).expect("create bundle src/bin dir");

    let mut bin_names: Vec<String> = Vec::new();
    let mut needs_db = false;
    let mut needs_traced = false;
    let mut needs_workflow = false;

    for f in files {
        let bin_name = golden_stem(f).to_string();
        let crate_name = bin_name.replace('-', "_");

        let src =
            std::fs::read_to_string(f).unwrap_or_else(|e| panic!("read {}: {e}", f.display()));
        let opts = vox_compiler::pipeline::PipelineOptions {
            script_mode: true,
            ..Default::default()
        };
        let frontend = vox_compiler::pipeline::run_frontend_str_with_options(
            &src,
            f.to_str()
                .unwrap_or_else(|| panic!("non-UTF8 path: {}", f.display())),
            &opts,
        )
        .unwrap_or_else(|e| panic!("frontend pipeline failed for {}: {e}", f.display()));
        assert!(
            !frontend.has_errors(),
            "golden {} fails frontend checks ({} error(s)): {:?}",
            f.display(),
            frontend.error_count(),
            frontend.diagnostics
        );
        assert!(
            frontend.module.has_entrypoint(),
            "golden {} has no main() — not runnable as a script",
            f.display()
        );
        assert!(
            frontend.hir.rust_imports.is_empty(),
            "golden {} declares a custom rust_import; build_native_bins doesn't merge \
             per-golden rust_imports into the shared bundle Cargo.toml yet",
            f.display()
        );

        needs_db |= !frontend.hir.tables.is_empty();
        needs_traced |= frontend.hir.functions.iter().any(|fun| fun.is_traced)
            || frontend.hir.tests.iter().any(|fun| fun.is_traced);
        needs_workflow |= module_needs_workflow_runtime(&frontend.hir);

        let output = vox_codegen::codegen_rust::generate_script(
            &frontend.hir,
            &crate_name,
            Some(&runtime_path),
        )
        .unwrap_or_else(|e| panic!("codegen failed for {}: {e}", f.display()));

        let lib_rs = output.files.get("src/lib.rs").cloned().unwrap_or_default();
        let main_rs = output
            .files
            .get("src/main.rs")
            .cloned()
            .unwrap_or_else(|| panic!("codegen produced no src/main.rs for {}", f.display()));

        let merged = merge_lib_and_main(&lib_rs, &main_rs, &crate_name);
        std::fs::write(
            bundle.join("src/bin").join(format!("{bin_name}.rs")),
            merged,
        )
        .unwrap_or_else(|e| panic!("write bin source for {}: {e}", f.display()));
        bin_names.push(bin_name);
    }

    // Additive deps beyond the always-on baseline below — mirrors the conditional
    // sections of `generate_script`'s own Cargo.toml template (pipeline.rs) so the
    // shared bundle keeps parity if a future golden needs tables/tracing/durability.
    let mut extra_deps = String::new();
    if needs_traced {
        extra_deps.push_str(&format!(
            "vox-telemetry = {{ path = \"{}\" }}\n",
            manifest_path(&root.join("crates/vox-telemetry"))
        ));
    }
    if needs_workflow {
        extra_deps.push_str(&format!(
            "vox-workflow-runtime = {{ path = \"{}\", default-features = false }}\nanyhow = \"1\"\n",
            manifest_path(&root.join("crates/vox-workflow-runtime"))
        ));
    }
    if needs_db {
        extra_deps.push_str(&format!(
            "vox-db = {{ path = \"{}\" }}\n",
            manifest_path(&root.join("crates/vox-db"))
        ));
        // Must match workspace `[workspace.dependencies].turso` (vox-db uses 0.6).
        extra_deps.push_str(
            "turso = { version = \"0.6\", default-features = false, features = [\"sync\"] }\n",
        );
    }

    let bin_entries: String = bin_names
        .iter()
        .map(|name| format!("[[bin]]\nname = \"{name}\"\npath = \"src/bin/{name}.rs\"\n\n"))
        .collect();

    // vox-actor-runtime -> vox-openclaw-runtime -> vox-db -> turso -> aegis is an
    // unconditional (non-optional) chain, so every generated crate that depends on
    // vox-actor-runtime needs this patch, exactly like `generate_script`'s own template
    // (pipeline.rs `aegis_patch_section`) unconditionally includes it too.
    let aegis_patch_path = manifest_path(&root.join("patches/aegis-0.9.8"));

    let cargo_toml = format!(
        r#"[workspace]

[package]
name = "golden-differential-bundle"
version = "0.0.0"
edition = "{edition}"
publish = false

{bin_entries}[dependencies]
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = {{ version = "1", features = ["preserve_order"] }}
tracing = "0.1"
rust_decimal = "1.36"
regex = "1"
vox-actor-runtime = {{ path = "{runtime_path}" }}
{extra_deps}
[patch.crates-io]
aegis = {{ path = "{aegis_patch_path}" }}
"#,
        edition = vox_codegen::codegen_rust::GENERATED_CARGO_EDITION,
        bin_entries = bin_entries,
        runtime_path = manifest_path(&runtime_path),
        extra_deps = extra_deps,
        aegis_patch_path = aegis_patch_path,
    );
    std::fs::write(bundle.join("Cargo.toml"), cargo_toml).expect("write bundle Cargo.toml");

    let target_dir = bundle.join("target");
    let build = Command::new("cargo")
        .current_dir(bundle)
        .env("CARGO_TARGET_DIR", &target_dir)
        .args(["build", "--quiet", "--bins"])
        .output()
        .expect("spawn cargo build for the golden differential bundle");
    assert!(
        build.status.success(),
        "native bundle build failed:\n{}",
        String::from_utf8_lossy(&build.stderr)
    );

    target_dir.join("debug")
}

#[test]
#[ignore = "owner:mesh sunset:2026-12-31 slow: one native crate for every EXPECT golden; nightly lane"]
fn golden_expect_blocks_match_on_both_tiers() {
    let root = repo_root();
    let vox = vox_binary();
    assert!(
        which::which("cargo").is_ok(),
        "the native half needs cargo on PATH; this gate must not pass silently"
    );

    let cache = vox_config::paths::script_cache_dir(false);
    let _ = std::fs::remove_dir_all(&cache);

    let mut files = Vec::new();
    collect_vox_recursive(&root.join("examples/golden"), &mut files);
    files.sort();

    let tmp = tempfile::tempdir().unwrap();
    let bundle = tmp.path().join("golden-bundle");
    let expect_files: Vec<PathBuf> = files
        .iter()
        .filter(|f| {
            let src = std::fs::read_to_string(f).unwrap();
            !directive_lines(&src, "// EXPECT:").is_empty()
                || !directive_lines(&src, "// EXPECT-EXIT:").is_empty()
                || !directive_lines(&src, "// EXPECT-TIER-ASYMMETRY:").is_empty()
        })
        .cloned()
        .collect();
    let native_dir = build_native_bins(&vox, &expect_files, &bundle);

    let mut checked = 0usize;
    let mut failures = Vec::new();
    for f in &expect_files {
        let src = std::fs::read_to_string(f).unwrap();
        let expect = directive_lines(&src, "// EXPECT:");
        let expect_exit = directive_lines(&src, "// EXPECT-EXIT:");
        let asymmetry = directive_lines(&src, "// EXPECT-TIER-ASYMMETRY:");
        checked += 1;
        let expected = normalize(&expect.join("\n"));
        let i = run_interp(&vox, f, &root);
        let bin = native_bin_path(&native_dir, golden_stem(f));
        let n_out = Command::new(&bin)
            .current_dir(&root)
            .output()
            .expect("native bin");
        let n = Run {
            code: n_out.status.code(),
            stdout: String::from_utf8_lossy(&n_out.stdout).into_owned(),
            stderr: String::from_utf8_lossy(&n_out.stderr).into_owned(),
        };
        let (io, no) = (normalize(&i.stdout), normalize(&n.stdout));
        if !asymmetry.is_empty() {
            if io == no && i.code == n.code {
                failures.push(format!(
                    "{} declared EXPECT-TIER-ASYMMETRY ({}) but the tiers now agree — remove the directive",
                    f.display(),
                    asymmetry.join("; ")
                ));
            }
            continue;
        }
        let fault_expected = expect_exit.iter().any(|d| d == "nonzero-both");
        let ok = if fault_expected {
            i.code != Some(0)
                && n.code != Some(0)
                && io.starts_with(&expected)
                && no.starts_with(&expected)
        } else {
            i.code == Some(0) && n.code == Some(0) && io == expected && no == expected
        };
        if !ok {
            failures.push(format!(
                "{}\n  expected: {expected:?} (fault_expected={fault_expected})\n  interp:   code={:?} {io:?}\n    stderr: {}\n  native:   code={:?} {no:?}\n    stderr: {}",
                f.display(), i.code, i.stderr.trim(), n.code, n.stderr.trim()
            ));
        }
    }
    assert!(
        checked > 0,
        "no golden declares EXPECT / EXPECT-EXIT — the gate has no corpus"
    );
    assert!(
        failures.is_empty(),
        "tiers disagree on {} golden(s):\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}
