//! `CONFIG_KEYS`: the general federated config registry. Seed it with the knobs
//! that already have constants + a clear home. Domains migrate their
//! `operator_registry` rows here over time (Phase 2A.3). The
//! `vox ci config-registry-parity` gate (Phase 2B) enforces env coverage.

use crate::config_key::{ConfigKey, ConfigKind, DefaultValue, Group, GuiSurface, Home, Status};
use crate::operator_registry::ConfigClass;

/// The general config registry. ADD a row here for every new operational knob.
pub const CONFIG_KEYS: &[ConfigKey] = &[
    ConfigKey {
        key: "VOX_WASM_SKILL_FUEL",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("1000000000"),
        bound: Some((1_000_000.0, 100_000_000_000.0)),
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: Some(GuiSurface {
            section: "Runtime & Sandbox",
            options: &[],
        }),
        secret: false,
        status: Status::Active,
        label: "WASM skill fuel",
        hint: "Wasmtime instruction budget for skill execution.",
    },
    ConfigKey {
        key: "VOX_GAMIFY_ECONOMY_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Computed("embedded gamify economy contract"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::NodeLocal,
        home: Home::Contract("contracts/gamify/economy.v1.yaml"),
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Gamify economy contract override",
        hint: "Path to an override economy.v1.yaml; defaults to the embedded contract.",
    },
    ConfigKey {
        key: "VOX_CIRCUIT_BREAKER_CONTRACT",
        kind: ConfigKind::Path,
        default: DefaultValue::Computed("embedded circuit-breaker contract"),
        bound: None,
        group: Group::Orchestrator,
        class: ConfigClass::NodeLocal,
        home: Home::Contract("contracts/orchestration/circuit-breaker.v1.yaml"),
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Circuit-breaker contract override",
        hint: "Path to an override circuit-breaker.v1.yaml; defaults to the embedded contract.",
    },
    // --- 2A.3 Wave 1: SEARCH (VOX_SEARCH_*) migrated from operator_registry ---
    ConfigKey {
        key: "VOX_SEARCH_BM25_K1",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("1.2"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Bm25 K1",
        hint: "BM25 ranking saturation parameter k1.",
    },
    ConfigKey {
        key: "VOX_SEARCH_BM25_B",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("0.75"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Bm25 B",
        hint: "BM25 ranking document length normalization parameter b.",
    },
    ConfigKey {
        key: "VOX_SEARCH_RRF_K",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("60"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Rrf K",
        hint: "Reciprocal Rank Fusion constant k.",
    },
    ConfigKey {
        key: "VOX_SEARCH_VERIFICATION_QUALITY_THRESHOLD",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("0.7"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Verification Quality Threshold",
        hint: "Min confidence for search hit verification.",
    },
    ConfigKey {
        key: "VOX_SEARCH_POLICY_VERSION",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("1"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Policy Version",
        hint: "Enforce a specific search policy version.",
    },
    ConfigKey {
        key: "VOX_SEARCH_MEMORY_VECTOR_WEIGHT",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("0.55"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Memory Vector Weight",
        hint: "Vector weight in hybrid search fusion.",
    },
    ConfigKey {
        key: "VOX_SEARCH_REPO_MAX_FILES",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("20000"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Repo Max Files",
        hint: "Max files to scan for repo inventory.",
    },
    ConfigKey {
        key: "VOX_SEARCH_REPO_SKIP_DIRS",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(".git,target,node_modules"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Repo Skip Dirs",
        hint: "Comma-separated list of directories to skip in repo scan.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_ENABLED",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily Enabled",
        hint: "Master switch for Tavily web search.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_DEPTH",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("basic"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily Depth",
        hint: "Tavily search depth (basic/advanced).",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_MAX_RESULTS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("5"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily Max Results",
        hint: "Max results per Tavily search.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_ON_EMPTY",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("true"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily On Empty",
        hint: "Auto-fire Tavily when local search is empty.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_ON_WEAK",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily On Weak",
        hint: "Auto-fire Tavily when local evidence is weak.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_BUDGET",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("50"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily Budget",
        hint: "Safety budget for Tavily credits per session.",
    },
    ConfigKey {
        key: "VOX_TAVILY_RESEARCH",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Tavily research tier",
        hint: "When truthy, enable Tavily /research deep-research tier in web gather.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SEARXNG_URL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Searxng Url",
        hint: "SearXNG instance URL.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SEARXNG_MAX_RESULTS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("5"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Searxng Max Results",
        hint: "Max results from SearXNG.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SEARXNG_MAX_SCRAPE",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("3"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Searxng Max Scrape",
        hint: "Max URLs to deep-scrape from SearXNG results.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SEARXNG_ENGINES",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Searxng Engines",
        hint: "Engines for SearXNG query.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SEARXNG_LANGUAGE",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Searxng Language",
        hint: "Language for SearXNG query.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SCRAPER_TIMEOUT",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("5000"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Scraper Timeout",
        hint: "Timeout for web scraper in ms.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SCRAPER_ROBOTS_RESPECT",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Scraper Robots Respect",
        hint: "Respect robots.txt in scraper.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SCRAPER_MIN_DENSITY",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("0.15"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Scraper Min Density",
        hint: "Min text density for scraped content.",
    },
    ConfigKey {
        key: "VOX_SEARCH_MAX_HOPS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("3"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Max Hops",
        hint: "Max iterative search hops.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TANTIVY_ROOT",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tantivy Root",
        hint: "Root path for Tantivy indices.",
    },
    ConfigKey {
        key: "VOX_SEARCH_PREFER_RRF",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Prefer Rrf",
        hint: "Prefer RRF for search fusion.",
    },
    ConfigKey {
        key: "VOX_SEARCH_QDRANT_URL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Qdrant Url",
        hint: "Qdrant API base URL.",
    },
    ConfigKey {
        key: "VOX_SEARCH_QDRANT_COLLECTION",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("vox_docs"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Qdrant Collection",
        hint: "Qdrant collection name.",
    },
    ConfigKey {
        key: "VOX_SEARCH_QDRANT_VECTOR_NAME",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Qdrant Vector Name",
        hint: "Named vector in Qdrant collection.",
    },
    ConfigKey {
        key: "VOX_SEARCH_DDG_FALLBACK_DISABLED",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Ddg Fallback Disabled",
        hint: "Disable DuckDuckGo fallback when SearXNG fails.",
    },
    // --- 2A.3 Wave 1: MESH (VOX_MESH_*) migrated from operator_registry ---
    ConfigKey {
        key: "VOX_MESH_DEVICE_CLASS",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("workstation"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Device Class",
        hint: "Device tier for mesh coordination (mobile, workstation, cluster).",
    },
    ConfigKey {
        key: "VOX_MESH_EXEC_LEASE_STORE_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/mesh_leases.db"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Exec Lease Store Path",
        hint: "Path to the mesh execution lease store.",
    },
    ConfigKey {
        key: "VOX_MESH_CODEX_TELEMETRY",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Codex Telemetry",
        hint: "Enable mesh telemetry recording to Codex (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_MESH_A2A_MAX_MESSAGES",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("1000"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh A2A Max Messages",
        hint: "Max A2A messages retained in memory per peer.",
    },
    ConfigKey {
        key: "VOX_MESH_BOOTSTRAP_EXPIRES_UNIX_MS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("0"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Bootstrap Expires Unix Ms",
        hint: "Expiration timestamp for bootstrap tokens.",
    },
    ConfigKey {
        key: "VOX_MESH_SCOPE_ID",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("global"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Scope Id",
        hint: "Isolation scope ID for the mesh network.",
    },
    ConfigKey {
        key: "VOX_MESH_SERVER_STALE_PRUNE_MS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("300000"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Server Stale Prune Ms",
        hint: "Interval for pruning stale mesh servers.",
    },
    ConfigKey {
        key: "VOX_MESH_MAX_STALE_MS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("600000"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Max Stale Ms",
        hint: "Maximum staleness for mesh nodes in monitoring.",
    },
    // Surviving VOX_MESH_EXEC_POLICY is task *placement* (local_only /
    // prefer_remote / remote_only). The SecretId::VoxMeshExecPolicy exec-ladder
    // (no-exec / source-only / permissive) was deleted with the bundle lane.
    ConfigKey {
        key: "VOX_MESH_EXEC_POLICY",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("local_only"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Exec Policy",
        hint: "Execution policy for mesh TASK PLACEMENT across mesh nodes only \
            (local_only, prefer_remote, remote_only) — NOT an LLM inference privacy \
            control. Setting this to local_only does not stop cloud model calls; see \
            VOX_INFERENCE_PRIVACY for that.",
    },
    ConfigKey {
        key: "VOX_INFERENCE_PRIVACY",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("any"),
        bound: None,
        group: Group::Security,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Inference Privacy",
        hint: "Hard filter on which models may be selected for chat/inference calls \
            (any [default] | local_only). local_only excludes every cloud-provider \
            model from candidates, genuinely, not just as a ranking preference. This \
            is UNRELATED to VOX_MESH_EXEC_POLICY, which governs mesh task placement \
            across physical nodes, not inference privacy — do not confuse the two.",
    },
    ConfigKey {
        key: "VOX_MESH_NODE_ID",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("default_node"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Node Id",
        hint: "Unique identifier for this mesh node.",
    },
    ConfigKey {
        key: "VOX_MESH_REPLAY_PERSIST",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Replay Persist",
        hint: "Enable persistence for mesh message replay (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_MESH_REPLAY_STATE_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/mesh_replay.bin"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Replay State Path",
        hint: "Path to mesh replay state file.",
    },
    ConfigKey {
        key: "VOX_MESH_A2A_LEASE_MS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("30000"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh A2A Lease Ms",
        hint: "Lease duration for A2A message locks.",
    },
    ConfigKey {
        key: "VOX_MESH_HTTP_MAX_BODY_BYTES",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("104857600"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Http Max Body Bytes",
        hint: "Max body size for mesh HTTP transport.",
    },
    ConfigKey {
        key: "VOX_MESH_A2A_STORE_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/mesh_a2a.db"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh A2A Store Path",
        hint: "Path to the A2A message store.",
    },
    ConfigKey {
        key: "VOX_MESH_DISPATCH_STORE_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/mesh_dispatch.db"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Dispatch Store Path",
        hint: "Path to the task dispatch store.",
    },
    ConfigKey {
        key: "VOX_MESH_RANK",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("0"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Rank",
        hint: "Rank of this node in a distributed training mesh.",
    },
    ConfigKey {
        key: "VOX_MESH_TRAIN",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Train",
        hint: "Enable distributed mesh training (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_MESH_REGISTRY_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/mesh_nodes.json"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Registry Path",
        hint: "Path to the mesh node registry file.",
    },
    // --- 2A.3 Wave 2: remaining operator_registry rows (migration complete) ---
    // Non-VOX_-prefixed env names are homed as VoxToml (settable via config) to
    // honor the env-homed-keys-are-VOX-prefixed invariant; VOX_* keys stay Home::Env.
    ConfigKey {
        key: "VOX_DB_CIRCUIT_BREAKER",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Storage,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Db Circuit Breaker",
        hint: "Gate workflow durability writes under DB stress (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_ORCH_LINEAGE_OFF",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Orchestrator,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Orch Lineage Off",
        hint: "Disable orchestration lineage persistence (1/true to disable).",
    },
    ConfigKey {
        key: "VOX_WORKFLOW_JOURNAL_CODEX_OFF",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Workflow Journal Codex Off",
        hint: "Disable Codex workflow journal append (1/true to disable).",
    },
    ConfigKey {
        key: "VOX_DB_SYNC_INTEGRATION",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("0"),
        bound: None,
        group: Group::Storage,
        class: ConfigClass::CiGate,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Db Sync Integration",
        hint: "Opt-in to remote sync_for test gate (1/true only).",
    },
    ConfigKey {
        key: "VOX_DB_EMBEDDED_REPLICA_INTEGRATION",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("0"),
        bound: None,
        group: Group::Storage,
        class: ConfigClass::CiGate,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Db Embedded Replica Integration",
        hint: "Opt-in to embedded-replica test gate (1/true only).",
    },
    ConfigKey {
        key: "POPULI_URL",
        kind: ConfigKind::Url,
        default: DefaultValue::Literal("http://localhost:11434"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Populi Url",
        hint: "Local Populi base URL.",
    },
    ConfigKey {
        key: "OLLAMA_URL",
        kind: ConfigKind::Url,
        default: DefaultValue::Literal("http://localhost:11434"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Ollama Url",
        hint: "Ollama base URL (fallback for POPULI_URL).",
    },
    ConfigKey {
        key: "HF_CHAT_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Hf Chat Model",
        hint: "Preferred HF router model ID.",
    },
    ConfigKey {
        key: "OPENROUTER_CHAT_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("auto"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Openrouter Chat Model",
        hint: "Preferred OpenRouter model ID.",
    },
    ConfigKey {
        key: "HF_DEDICATED_CHAT_URL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Hf Dedicated Chat Url",
        hint: "Pinned HF Inference Endpoint URL.",
    },
    ConfigKey {
        key: "HF_DEDICATED_CHAT_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Hf Dedicated Chat Model",
        hint: "Model ID for dedicated HF endpoint.",
    },
    ConfigKey {
        key: "VOX_SECRETS_PROFILE",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("dev"),
        bound: None,
        group: Group::Security,
        class: ConfigClass::Bootstrap,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Secrets Profile",
        hint: "Secrets resolution profile (ci, prod, hardcut, dev).",
    },
    ConfigKey {
        key: "VOX_SECRETS_AUTO_PREFER_VAULT",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Security,
        class: ConfigClass::Bootstrap,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Secrets Auto Prefer Vault",
        hint: "Prefer vault over Infisical/env in Auto mode.",
    },
    ConfigKey {
        key: "VOX_SECRETS_AUTO_VAULT",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Security,
        class: ConfigClass::Bootstrap,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Secrets Auto Vault",
        hint: "Mirror signal for secrets vault presence.",
    },
    ConfigKey {
        key: "VOX_SECRETS_VAULT_URL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Security,
        class: ConfigClass::Bootstrap,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Secrets Vault Url",
        hint: "Cloudless vault URL.",
    },
    ConfigKey {
        key: "VOX_SECRETS_VAULT_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/clavis_vault.db"),
        bound: None,
        group: Group::Security,
        class: ConfigClass::Bootstrap,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Secrets Vault Path",
        hint: "Cloudless vault file path.",
    },
    ConfigKey {
        key: "VOX_SECRETS_BACKEND",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("auto"),
        bound: None,
        group: Group::Security,
        class: ConfigClass::Bootstrap,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Secrets Backend",
        hint: "Explicit secrets backend (env_only, infisical, vault, vox_cloud, auto).",
    },
    ConfigKey {
        key: "VOX_SCHOLARLY_ADAPTER",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("zenodo"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Scholarly Adapter",
        hint: "Selects scholarly publisher backend (zenodo, openreview, arxiv_assist).",
    },
    ConfigKey {
        key: "VOX_SCHOLARLY_JOB_LOCK_OWNER",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("local"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Scholarly Job Lock Owner",
        hint: "Owner ID for distributed scholarly ingestion locks.",
    },
    ConfigKey {
        key: "VOX_SCIENTIA_CROSSREF_MAILTO",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Scientia Crossref Mailto",
        hint: "Email for Crossref API polite pool (required).",
    },
    ConfigKey {
        key: "VOX_ACCOUNT_ID",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("default_dev"),
        bound: None,
        group: Group::General,
        class: ConfigClass::Bootstrap,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Account Id",
        hint: "Vox account ID (used for cost attribution and mesh identity).",
    },
    ConfigKey {
        key: "VOX_NEWS_SITE_BASE_URL",
        kind: ConfigKind::Url,
        default: DefaultValue::Literal("http://localhost:3000"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "News Site Base Url",
        hint: "Base URL for syndication site generation.",
    },
    ConfigKey {
        key: "VOX_NEWS_RSS_FEED_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal("public/rss.xml"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "News Rss Feed Path",
        hint: "Path to output generated RSS feed.",
    },
    ConfigKey {
        key: "VOX_NEWS_PUBLISH_ARMED",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "News Publish Armed",
        hint: "Gate for actually pushing news to remote endpoints (1/true to arm).",
    },
    ConfigKey {
        key: "VOX_SYNDICATION_TEMPLATE_PROFILE",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("default"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Syndication Template Profile",
        hint: "Profile name for syndication template selection.",
    },
    ConfigKey {
        key: "VOX_ZENODO_STAGING_DIR",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal("tmp/zenodo_staging"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Zenodo Staging Dir",
        hint: "Local staging directory for Zenodo uploads.",
    },
    ConfigKey {
        key: "VOX_ZENODO_UPLOAD_ALLOWLIST",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("pdf,zip,json"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Zenodo Upload Allowlist",
        hint: "Comma-separated extensions allowed for Zenodo upload.",
    },
    ConfigKey {
        key: "VOX_ZENODO_API_BASE",
        kind: ConfigKind::Url,
        default: DefaultValue::Literal("https://sandbox.zenodo.org/api"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Zenodo Api Base",
        hint: "Zenodo API base URL (e.g. sandbox vs prod).",
    },
    ConfigKey {
        key: "VOX_ZENODO_HTTP_MAX_ATTEMPTS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("3"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Zenodo Http Max Attempts",
        hint: "Zenodo API retry limit.",
    },
    ConfigKey {
        key: "VOX_OPENREVIEW_HTTP_MAX_ATTEMPTS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("5"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Openreview Http Max Attempts",
        hint: "OpenReview API retry limit.",
    },
    ConfigKey {
        key: "VOX_ORCH_METRICS_SINK",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Orchestrator,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Orch Metrics Sink",
        hint: "Metrics ingestion endpoint for orchestrator telemetry.",
    },
    ConfigKey {
        key: "VOX_PUBLISHER_DRY_RUN",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Publisher Dry Run",
        hint: "Disable actual publication side-effects (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_BENCHMARK_TELEMETRY",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::General,
        class: ConfigClass::CiGate,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Benchmark Telemetry",
        hint: "Enable benchmark event recording (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_SYNTAX_K_TELEMETRY",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::General,
        class: ConfigClass::CiGate,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Syntax K Telemetry",
        hint: "Enable syntax-k benchmark recording (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_RUNTIME_LLM_MAX_RETRY",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("3"),
        bound: None,
        group: Group::Runtime,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Runtime Llm Max Retry",
        hint: "Max retries for LLM inference failures.",
    },
    ConfigKey {
        key: "VOX_OPENCLAW_URL",
        kind: ConfigKind::Url,
        default: DefaultValue::Literal("http://localhost:8000"),
        bound: None,
        group: Group::Orchestrator,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Openclaw Url",
        hint: "OpenClaw API base URL.",
    },
    ConfigKey {
        key: "VOX_OPENCLAW_WS_URL",
        kind: ConfigKind::Url,
        default: DefaultValue::Literal("ws://localhost:8000/ws"),
        bound: None,
        group: Group::Orchestrator,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Openclaw Ws Url",
        hint: "OpenClaw WebSocket endpoint.",
    },
    ConfigKey {
        key: "VOX_OPENCLAW_SIDECAR_DISABLE",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Orchestrator,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Openclaw Sidecar Disable",
        hint: "Disable OpenClaw sidecar installation.",
    },
    // --- MCP (VOX_MCP_*): launcher-set operational knobs ---
    ConfigKey {
        key: "VOX_MCP_CALLER_ROLE",
        kind: ConfigKind::Enum,
        default: DefaultValue::Literal("agent"),
        bound: None,
        group: Group::Orchestrator,
        class: ConfigClass::Bootstrap,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "MCP caller role",
        hint: "Trusted MCP process role: human (privileged) or agent (default). Set by the launcher, not tool request bodies.",
    },
    ConfigKey {
        key: "GEMINI_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("gemini-1.5-pro"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Gemini Model",
        hint: "Default model for Gemini provider.",
    },
    ConfigKey {
        key: "OLLAMA_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("llama3"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Ollama Model",
        hint: "Default model for Ollama provider.",
    },
    ConfigKey {
        key: "OPENAI_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("gpt-4o"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Openai Model",
        hint: "Default model for OpenAI provider.",
    },
    ConfigKey {
        key: "OPENROUTER_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("auto"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Openrouter Model",
        hint: "Default model for OpenRouter provider.",
    },
    ConfigKey {
        key: "VOX_OPENAI_BASE_URL",
        kind: ConfigKind::Url,
        default: DefaultValue::Literal("https://api.openai.com/v1"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Openai Base Url",
        hint: "Custom base URL for OpenAI-compatible providers.",
    },
    ConfigKey {
        key: "VOX_MENS_TRAIN_JSONL_STRICT",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::General,
        class: ConfigClass::CiGate,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mens Train Jsonl Strict",
        hint: "Enforce strict compiler recheck for training corpora.",
    },
    ConfigKey {
        key: "VOX_RATE_LIMIT_MAX_REQUESTS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("100"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Rate Limit Max Requests",
        hint: "Max requests per rate-limit window.",
    },
    ConfigKey {
        key: "VOX_RATE_LIMIT_WINDOW_SECONDS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("60"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Rate Limit Window Seconds",
        hint: "Duration of rate-limit window in seconds.",
    },
    ConfigKey {
        key: "VOX_UNIFIED_ROUTING",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Unified Routing",
        hint: "Enable experimental unified routing across agents.",
    },
    ConfigKey {
        key: "VOX_EXE",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("vox"),
        bound: None,
        group: Group::General,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Exe",
        hint: "Path to the vox executable for self-forwarding.",
    },
    ConfigKey {
        key: "VOX_SCHOLA_FORWARD",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Schola Forward",
        hint: "Enable SCHOLA training forwarding.",
    },
    ConfigKey {
        key: "VOX_SCHOLA_TRAIN_IN_PROCESS",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("true"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Schola Train In Process",
        hint: "Run SCHOLA training in the main process.",
    },
    ConfigKey {
        key: "VOX_EMBEDDING_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("text-embedding-3-small"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Embedding Model",
        hint: "Default model for text embeddings.",
    },
    ConfigKey {
        key: "OPENAI_BASE_URL",
        kind: ConfigKind::Url,
        default: DefaultValue::Literal("https://api.openai.com/v1"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Openai Base Url",
        hint: "Custom base URL for OpenAI-compatible providers (legacy).",
    },
    ConfigKey {
        key: "RUST_LOG",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("info"),
        bound: None,
        group: Group::General,
        class: ConfigClass::Bootstrap,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Rust Log",
        hint: "Standard Rust logging filter.",
    },
    ConfigKey {
        key: "HOSTNAME",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("localhost"),
        bound: None,
        group: Group::General,
        class: ConfigClass::NodeLocal,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Hostname",
        hint: "System hostname (auto-detected).",
    },
    ConfigKey {
        key: "VOX_ALLOW_UNAUTHENTICATED",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::General,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Allow Unauthenticated",
        hint: "Gate for allowing unauthenticated runtime requests (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_CHROME_EXECUTABLE",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::General,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Chrome Executable",
        hint: "Path to Chrome/Chromium executable for scraping.",
    },
    ConfigKey {
        key: "VOX_SECRETS_CLOUDLESS_DB_PATH",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Security,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Secrets Cloudless Db Path",
        hint: "Mirror signal for vault path.",
    },
    ConfigKey {
        key: "POPULI_MAX_TOKENS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("4096"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Populi Max Tokens",
        hint: "Max tokens for Populi local inference.",
    },
    ConfigKey {
        key: "POPULI_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("llama3"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Populi Model",
        hint: "Model ID for Populi local inference.",
    },
    ConfigKey {
        key: "POPULI_TEMPERATURE",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("0.7"),
        bound: None,
        group: Group::General,
        class: ConfigClass::UserPreference,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Populi Temperature",
        hint: "Temperature for Populi local inference.",
    },
    ConfigKey {
        key: "COMPUTERNAME",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("localhost"),
        bound: None,
        group: Group::General,
        class: ConfigClass::NodeLocal,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Computername",
        hint: "Windows system computer name (auto-detected).",
    },
    ConfigKey {
        key: "VOX_GPU_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Gpu Model",
        hint: "Manually specify the GPU model for training (e.g. RTX4080).",
    },
    ConfigKey {
        key: "VOX_GPU_VRAM_MB",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("0"),
        bound: None,
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Gpu Vram Mb",
        hint: "Manually specify available VRAM in MB.",
    },
    ConfigKey {
        key: "VOX_BASE_MODEL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::General,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Base Model",
        hint: "Path or ID of the base model for training/fine-tuning.",
    },
    ConfigKey {
        key: "VOX_TRAIN_PROFILE",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("default"),
        bound: None,
        group: Group::Training,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Train Profile",
        hint: "Configuration profile for ML training (e.g. qlora_v1).",
    },
    ConfigKey {
        key: "VOX_VRAM_OVERRIDE_GB",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("0"),
        bound: None,
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Vram Override Gb",
        hint: "Override detected VRAM for memory-intensive ops (GB).",
    },
    ConfigKey {
        key: "CARGO_HOME",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal("~/.cargo"),
        bound: None,
        group: Group::General,
        class: ConfigClass::NodeLocal,
        home: Home::VoxToml,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Cargo Home",
        hint: "Standard Cargo home directory.",
    },
    ConfigKey {
        key: "VOX_SECRETS_CUTOVER_PHASE",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("shadow"),
        bound: None,
        group: Group::Security,
        class: ConfigClass::Bootstrap,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Secrets Cutover Phase",
        hint: "Secrets cutover phase controls (shadow, enforce, decommission).",
    },
    ConfigKey {
        key: "VOX_SECRETS_MIGRATION_PHASE",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("legacy_pre"),
        bound: None,
        group: Group::Security,
        class: ConfigClass::Bootstrap,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Secrets Migration Phase",
        hint: "Secrets migration phase controls (legacy_pre, shadow, dual).",
    },
    ConfigKey {
        key: "VOX_DB_MVCC",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Storage,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Db Mvcc",
        hint: "Enable experimental MVCC for SQLite (1/true to enable).",
    },
    // --- P6-2: graphify cache disk-footprint knobs (VOX_GRAPHIFY_TTL_DAYS was already
    // read in code but not yet a CONFIG_KEYS row; registering all three together). ---
    ConfigKey {
        key: "VOX_GRAPHIFY_CACHE_DIR",
        kind: ConfigKind::Path,
        default: DefaultValue::Computed("<repo>/.vox/cache/graphify"),
        bound: None,
        group: Group::Storage,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        // NOT wired to the real cache writer today (crates/vox-cli/src/commands/
        // graphify/mod.rs::primary_cache_dir builds its path from
        // REPO_VOX_GRAPH_CACHE_DIR directly and never calls this resolver) —
        // the doctor check's GRAPHIFY_ENV_NOT_WIRED_NOTE already says so;
        // Status::Declared makes the registry say the same thing.
        status: Status::Declared,
        label: "Graphify Cache Dir",
        hint: "Base dir for graphify's Tier D cache (per-corpus subdir kept underneath). \
               NOT YET WIRED to the real writer -- setting this has no effect today.",
    },
    ConfigKey {
        key: "VOX_GRAPHIFY_DISABLE",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Storage,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        // See VOX_GRAPHIFY_CACHE_DIR above: same gap, same reason.
        status: Status::Declared,
        label: "Graphify Disable",
        hint: "Disable the graphify cache outright (no corpus graph reads or writes). \
               NOT YET WIRED to the real writer -- setting this has no effect today.",
    },
    ConfigKey {
        key: "VOX_GRAPHIFY_TTL_DAYS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("30"),
        bound: Some((1.0, 3650.0)),
        group: Group::Storage,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Graphify Ttl Days",
        hint: "Freshness TTL in days for all graphify corpora, overriding the contract default.",
    },
    // --- P6-3: explicit opt-out for the Sherpa-ONNX speech-model download,
    // so a user or CI job can guarantee nothing large is fetched. ---
    ConfigKey {
        key: "VOX_ORATIO_SHERPA_NO_DOWNLOAD",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Storage,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Sherpa No Download",
        hint: "Refuse to download Sherpa-ONNX speech models; point VOX_ORATIO_SHERPA_MODEL_DIR at a local copy instead.",
    },
    // --- P6-7: explicit opt-out for the vox-populi Mens training-weight
    // download (the actual `download_model` HF Hub downloader, ~16 GB for
    // the default model), so a user or CI job can guarantee nothing large
    // is fetched. ---
    ConfigKey {
        key: "VOX_MENS_NO_DOWNLOAD",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Storage,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mens No Download",
        hint: "Refuse to download Mens training-weight models from Hugging Face Hub; there is no local-directory alternative today.",
    },
    // --- P3P6: broker/home knobs surfaced by the config-registry-parity gate ---
    ConfigKey {
        key: "VOX_HOME",
        kind: ConfigKind::Path,
        default: DefaultValue::Computed("<home>/.vox"),
        bound: None,
        group: Group::General,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Vox Home",
        hint: "Overrides the root vox_config::paths::dot_vox_user_dir() resolves under; a \
            partial relocation only (see that function's doc comment for what it does not move).",
    },
    ConfigKey {
        key: "VOX_BROKER_RESERVED_SLOTS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("0"),
        bound: None,
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Broker Reserved Slots",
        hint: "Slots reserved for a build domain the broker's filesystem semaphore can't see \
            (e.g. a containerised CI runner sharing this host's CPU but not its mount namespace).",
    },
    ConfigKey {
        key: "VOX_GUI_DRIVE",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Axis Drive live plane",
        hint: "Set by vox gui drive start on the dedicated debug Axis (never the token).",
    },
    ConfigKey {
        key: "VOX_GUI_DRIVE_SHOW",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Axis Drive show window",
        hint: "Reveal the dedicated debug Axis window (otherwise hidden, no Dock icon).",
    },
    ConfigKey {
        key: "VOX_GUI_DRIVE_SESSION_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Computed("$VOX_HOME/run/gui-drive.json"),
        bound: None,
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Axis Drive session path",
        hint: "Where the dedicated Axis writes gui-drive.json (port/pid/token_path).",
    },
    ConfigKey {
        key: "VOX_GUI_DRIVE_STORE_ROOT",
        kind: ConfigKind::Path,
        default: DefaultValue::Computed("$VOX_HOME/gui-drive/<profile>"),
        bound: None,
        group: Group::Storage,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Axis Drive store root",
        hint: "Overrides the journey store so drive chat_turn cannot append to the user transcript.",
    },
    ConfigKey {
        key: "VOX_GUI_DRIVE_PROFILE",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("default"),
        bound: None,
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Axis Drive profile",
        hint: "Isolates ~/.vox/gui-drive/<profile>/store.db for a debug Axis session.",
    },
    ConfigKey {
        key: "VOX_GUI_DRIVE_TOKEN_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Computed("$VOX_HOME/run/gui-drive.token"),
        bound: None,
        group: Group::Security,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Axis Drive token path",
        hint: "Path to the 0600 bearer file. Never set VOX_GUI_DRIVE_TOKEN (ps leak).",
    },
    ConfigKey {
        key: "VOX_GUI_DRIVE_ALLOW_STORE_RESET",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Axis Drive allow store reset",
        hint: "With VOX_GUI_DRIVE=1, wipe LegacySchemaChain store.db under VOX_GUI_DRIVE_STORE_ROOT only.",
    },
];

/// All registered keys (for the parity gate).
pub fn registered_keys() -> impl Iterator<Item = &'static str> {
    CONFIG_KEYS.iter().map(|k| k.key)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wave1_search_mesh_rows_migrated() {
        let keys: std::collections::BTreeSet<&str> = CONFIG_KEYS.iter().map(|k| k.key).collect();
        assert!(keys.contains("VOX_SEARCH_BM25_K1"));
        assert!(keys.contains("VOX_SEARCH_TAVILY_ENABLED"));
        assert!(keys.contains("VOX_MESH_DEVICE_CLASS"));
        assert!(
            CONFIG_KEYS.len() >= 3 + 40,
            "expected ~48 SEARCH+MESH rows added"
        );
    }

    #[test]
    fn every_operator_env_is_in_config_keys() {
        use crate::operator_registry::OPERATOR_TUNING_ENVS;
        let registered: std::collections::BTreeSet<&str> =
            CONFIG_KEYS.iter().map(|k| k.key).collect();
        for spec in OPERATOR_TUNING_ENVS {
            assert!(
                registered.contains(spec.name),
                "operator env {} not migrated to CONFIG_KEYS",
                spec.name
            );
        }
    }

    #[test]
    fn keys_are_unique() {
        let mut seen = std::collections::BTreeSet::new();
        for k in CONFIG_KEYS {
            assert!(seen.insert(k.key), "duplicate ConfigKey: {}", k.key);
        }
    }

    #[test]
    fn env_homed_keys_are_vox_prefixed() {
        for k in CONFIG_KEYS {
            if matches!(k.home, Home::Env) {
                assert!(
                    k.key.starts_with("VOX_"),
                    "env knob must be VOX_*: {}",
                    k.key
                );
            }
        }
    }

    #[test]
    fn vox_mcp_caller_role_is_registered() {
        let row = CONFIG_KEYS
            .iter()
            .find(|k| k.key == "VOX_MCP_CALLER_ROLE")
            .expect("VOX_MCP_CALLER_ROLE must be in CONFIG_KEYS");
        assert_eq!(row.kind, ConfigKind::Enum);
        assert_eq!(row.default, DefaultValue::Literal("agent"));
        assert_eq!(row.group, Group::Orchestrator);
        assert_eq!(row.class, ConfigClass::Bootstrap);
        assert!(!row.secret);
        assert_eq!(row.status, Status::Active);
    }

    #[test]
    fn vox_tavily_research_is_registered() {
        let row = CONFIG_KEYS
            .iter()
            .find(|k| k.key == "VOX_TAVILY_RESEARCH")
            .expect("VOX_TAVILY_RESEARCH must be in CONFIG_KEYS");
        assert_eq!(row.kind, ConfigKind::Bool);
        assert_eq!(row.default, DefaultValue::Literal("false"));
        assert_eq!(row.group, Group::Tuning);
        assert!(!row.secret);
        assert_eq!(row.status, Status::Active);
    }
}
