//! TypeScript emission for `state_machine` declarations (TASK-4.1).
//!
//! For each state machine emits:
//! 1. A discriminated union type for states.
//! 2. A discriminated union type for events.
//! 3. A typed reducer function stub.
//!
//! Output file: `state_machines.ts`.

use crate::hir::{HirModule, HirStateMachineDecl, HirType};

/// Emit `state_machines.ts` content for all state machines in the module.
/// Returns an empty string if the module has no state machines.
pub fn emit_state_machine_decls(hir: &HirModule) -> String {
    if hir.state_machines.is_empty() {
        return String::new();
    }

    let mut out = String::from("// Generated by vox-compiler — do not edit.\n");

    for sm in &hir.state_machines {
        emit_one(sm, &mut out);
        out.push('\n');
    }

    out
}

fn emit_one(sm: &HirStateMachineDecl, out: &mut String) {
    let name = &sm.name;

    // ── State type ─────────────────────────────────────────────────────────
    out.push_str(&format!("export type {name} =\n"));
    for (i, st) in sm.states.iter().enumerate() {
        let sep = if i + 1 < sm.states.len() { " |" } else { "  " };
        out.push_str(&format!("  {sep} {{ readonly _tag: {:?}", st.name));
        for field in &st.fields {
            let ty_str = field
                .ty
                .as_ref()
                .map(|t| hir_type_to_ts(t))
                .unwrap_or_else(|| "unknown".to_string());
            out.push_str(&format!("; readonly {}: {ty_str}", field.name));
        }
        out.push_str(" }");
        if i + 1 < sm.states.len() {
            out.push('\n');
        }
    }
    out.push_str(";\n\n");

    // ── Event type ─────────────────────────────────────────────────────────
    // Collect unique events (in declaration order of first occurrence).
    let mut seen_events: Vec<String> = Vec::new();
    for tr in &sm.transitions {
        if !seen_events.contains(&tr.event_name) {
            seen_events.push(tr.event_name.clone());
        }
    }

    if !seen_events.is_empty() {
        out.push_str(&format!("export type {name}Event =\n"));
        for (i, event) in seen_events.iter().enumerate() {
            let sep = if i + 1 < seen_events.len() { " |" } else { "  " };
            // Collect params for this event from the first matching transition.
            let params: Vec<&str> = sm
                .transitions
                .iter()
                .find(|tr| &tr.event_name == event)
                .map(|tr| tr.event_params.iter().map(String::as_str).collect())
                .unwrap_or_default();

            out.push_str(&format!("  {sep} {{ readonly _type: {:?}", event));
            for param in &params {
                out.push_str(&format!("; readonly {param}: unknown"));
            }
            out.push_str(" }");
            if i + 1 < seen_events.len() {
                out.push('\n');
            }
        }
        out.push_str(";\n\n");

        // ── Reducer stub ───────────────────────────────────────────────────
        let reducer_name = to_camel_case(name);
        out.push_str(&format!(
            "export function {reducer_name}Reducer(\n  state: {name},\n  event: {name}Event,\n): {name} {{\n"
        ));
        out.push_str("  switch (state._tag) {\n");
        for st in &sm.states {
            if st.is_terminal {
                continue; // terminal states have no transitions
            }
            out.push_str(&format!("    case {:?}:\n", st.name));
            out.push_str("      switch (event._type) {\n");
            let state_transitions: Vec<_> = sm
                .transitions
                .iter()
                .filter(|tr| matches!(&tr.from, crate::hir::HirSmFrom::Named(n) if n == &st.name)
                    || matches!(&tr.from, crate::hir::HirSmFrom::Any))
                .collect();
            for tr in &state_transitions {
                out.push_str(&format!("        case {:?}:\n", tr.event_name));
                out.push_str(&format!("          return {{ _tag: {:?} }};\n", tr.to_state));
            }
            out.push_str("        default: return state;\n");
            out.push_str("      }\n");
        }
        out.push_str("    default: return state;\n");
        out.push_str("  }\n");
        out.push_str("}\n");
    }
}

fn to_camel_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
    }
}

fn hir_type_to_ts(ty: &HirType) -> String {
    match ty {
        HirType::Named(n) => match n.as_str() {
            "str" | "string" => "string".to_string(),
            "int" | "i32" | "i64" | "u32" | "u64" => "number".to_string(),
            "float" | "f32" | "f64" => "number".to_string(),
            "bool" => "boolean".to_string(),
            other => other.to_string(),
        },
        HirType::Generic(outer, args) if outer == "option" && args.len() == 1 => {
            format!("{} | undefined", hir_type_to_ts(&args[0]))
        }
        HirType::Generic(outer, args) if outer == "list" && args.len() == 1 => {
            format!("ReadonlyArray<{}>", hir_type_to_ts(&args[0]))
        }
        HirType::Generic(outer, args) => {
            let inner: Vec<_> = args.iter().map(hir_type_to_ts).collect();
            format!("{}<{}>", outer, inner.join(", "))
        }
        HirType::Tuple(parts) => {
            let inner: Vec<_> = parts.iter().map(hir_type_to_ts).collect();
            format!("[{}]", inner.join(", "))
        }
        HirType::Unit => "void".to_string(),
        HirType::Function(params, ret) => {
            let ps: Vec<_> = params.iter().map(hir_type_to_ts).collect();
            format!("({}) => {}", ps.join(", "), hir_type_to_ts(ret))
        }
        HirType::Decimal => "string".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hir::lower::lower_module;
    use crate::lexer::lex;
    use crate::parser::parse;

    fn emit(src: &str) -> String {
        let tokens = lex(src);
        let module = parse(tokens).expect("parse error");
        let hir = lower_module(&module);
        emit_state_machine_decls(&hir)
    }

    #[test]
    fn test_emit_empty_when_no_state_machines() {
        let out = emit("fn f() to int { 1 }");
        assert!(out.is_empty());
    }

    #[test]
    fn test_emit_state_type_discriminated_union() {
        let out = emit("state_machine Light { state On\nstate Off\non Toggle from On -> Off\non Toggle from Off -> On\n}");
        assert!(out.contains("export type Light ="));
        assert!(out.contains("\"On\""));
        assert!(out.contains("\"Off\""));
    }

    #[test]
    fn test_emit_event_type() {
        let out = emit("state_machine Light { state On\nstate Off\non Toggle from On -> Off\non Toggle from Off -> On\n}");
        assert!(out.contains("export type LightEvent ="));
        assert!(out.contains("\"Toggle\""));
    }

    #[test]
    fn test_emit_reducer() {
        let out = emit("state_machine Light { state On\nstate Off\non Toggle from On -> Off\non Toggle from Off -> On\n}");
        assert!(out.contains("export function lightReducer("));
        assert!(out.contains("state: Light"));
        assert!(out.contains("event: LightEvent"));
    }
}
