//! Generated `vox-tanstack-query.tsx` — TanStack Query client + narrow `useVoxServerQuery` helper.
//!
//! **Pairing:** wrap **`@query`** / server-fn clients with **`useVoxServerQuery(['name'], () => name(...args))`**
//! (stable keys + async `queryFn`). Route-level suspense UI uses **`@loading`** → TanStack
//! **`pendingComponent`** wiring aligns with [`route_manifest`](./route_manifest.rs) (`globalPendingComponent` / per-route `pending:`).

/// React Query wiring emitted into `dist/**/generated/` for Vox web apps.
#[must_use]
pub fn vox_tanstack_query_tsx() -> String {
    r#"/**
 * TanStack Query helpers — generated by Vox (`vox-compiler`).
 * Wrap async data (e.g. `vox-client` / `fetch`) with `useVoxServerQuery`.
 */
import { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query";
import type { ReactElement, ReactNode } from "react";

export const voxQueryClient = new QueryClient({
  defaultOptions: {
    queries: { staleTime: 30_000 },
  },
});

export function VoxQueryProvider({
  children,
}: Readonly<{ children: ReactNode }>): ReactElement {
  return <QueryClientProvider client={voxQueryClient}>{children}</QueryClientProvider>;
}

/** Narrow mapping: stable `queryKey` + promise `queryFn` (pairs with generated server fns). */
export function useVoxServerQuery<TData>(
  queryKey: readonly unknown[],
  queryFn: () => Promise<TData>,
) {
  return useQuery<TData>({ queryKey, queryFn });
}
"#
    .to_string()
}
