//! Emit CSS and TypeScript artifacts from a loaded [`TokenRegistry`].
//!
//! Called from [`super::emitter`] when `vox.tokens.json` is present.

use crate::tokens::TokenRegistry;

/// Emit `:root { --vox-* }` CSS custom properties from the registry.
///
/// Entries are sorted for deterministic output. Annotated tokens emit their
/// resolved hex value (not the raw JSON object).
pub fn emit_tokens_css(registry: &TokenRegistry) -> String {
    let mut entries: Vec<(&str, &str)> = registry
        .by_css_var
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();
    entries.sort_by_key(|(k, _)| *k);

    let mut out = String::from(":root {\n");
    for (key, value) in entries {
        out.push_str(&format!("  --vox-{}: {};\n", key, value));
    }
    out.push_str("}\n");
    out
}

/// Emit a typed `voxTokens` constant for TypeScript consumers.
///
/// Keys match the CSS custom property suffix: `"color-primary"` maps to
/// `"var(--vox-color-primary)"`. The object is `as const` so property-level
/// types are preserved.
pub fn emit_tokens_ts(registry: &TokenRegistry) -> String {
    let mut entries: Vec<(&str, &str)> = registry
        .by_css_var
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();
    entries.sort_by_key(|(k, _)| *k);

    let mut out =
        String::from("// Generated by Vox compiler from vox.tokens.json. Do not edit.\n\n");
    out.push_str("export const voxTokens = {\n");
    for (key, _) in &entries {
        out.push_str(&format!(
            "  \"{key}\": \"var(--vox-{key})\",\n",
            key = key
        ));
    }
    out.push_str("} as const;\n\n");
    out.push_str("export type VoxTokenKey = keyof typeof voxTokens;\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn minimal_registry() -> TokenRegistry {
        TokenRegistry::load_from_str(
            r##"{
            "color": {
                "primary": "#3a86ff",
                "background": "#ffffff",
                "text": {
                    "value": "#1d3557",
                    "on": "color.background",
                    "text_role": "body"
                }
            },
            "spacing": { "md": "16px" }
        }"##,
        )
        .unwrap()
    }

    #[test]
    fn css_contains_custom_properties() {
        let css = emit_tokens_css(&minimal_registry());
        assert!(css.contains("--vox-color-primary: #3a86ff;"), "{}", css);
        assert!(css.contains("--vox-color-background: #ffffff;"), "{}", css);
        assert!(css.contains("--vox-color-text: #1d3557;"), "{}", css);
        assert!(css.contains("--vox-spacing-md: 16px;"), "{}", css);
    }

    #[test]
    fn css_omits_schema_key() {
        let json = r##"{ "$schema": "./contracts/tokens/tokens.v1.json", "color": { "primary": "#3a86ff" } }"##;
        let reg = TokenRegistry::load_from_str(json).unwrap();
        let css = emit_tokens_css(&reg);
        assert!(!css.contains("$schema"), "schema key leaked: {}", css);
        assert!(!css.contains("schema"), "schema key leaked: {}", css);
    }

    #[test]
    fn annotated_token_emits_value_not_object() {
        let css = emit_tokens_css(&minimal_registry());
        assert!(
            css.contains("--vox-color-text: #1d3557;"),
            "annotated token should emit hex value: {}",
            css
        );
        assert!(!css.contains("on:"), "object leaked into CSS: {}", css);
    }

    #[test]
    fn ts_exports_const_and_type() {
        let ts = emit_tokens_ts(&minimal_registry());
        assert!(ts.contains("export const voxTokens"), "{}", ts);
        assert!(ts.contains("as const"), "{}", ts);
        assert!(ts.contains("export type VoxTokenKey"), "{}", ts);
        assert!(
            ts.contains("\"color-primary\": \"var(--vox-color-primary)\""),
            "{}",
            ts
        );
    }

    #[test]
    fn output_is_deterministic() {
        let reg = minimal_registry();
        assert_eq!(emit_tokens_css(&reg), emit_tokens_css(&reg));
        assert_eq!(emit_tokens_ts(&reg), emit_tokens_ts(&reg));
    }
}
