//! Framework-agnostic typed `fetch` client for `@server` / `@query` / `@mutation`.
//!
//! **HTTP SSOT (Rust + TS):** generated Axum wiring uses **`GET`** for `@query` (deterministic
//! JSON-in-query encoding: sorted keys, each value is `JSON.stringify` + `encodeURIComponent`) and
//! **`POST` + JSON body** for `@mutation` / `@server`. Cache-friendly reads use GET as intended.

use crate::hir::{HirModule, HirEndpointFn, HirEndpointKind};

/// Stable output filename for the generated client.
pub const VOX_CLIENT_FILENAME: &str = "vox-client.ts";

#[must_use]
pub fn emit_vox_client(hir: &HirModule) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Vox — typed fetch client for @query / @mutation / @server\n");
    out.push_str("// Transport: GET + JSON query values for @query; POST + JSON body for @mutation / @server.\n");
    out.push_str("// Do not edit; regenerate with `vox build`.\n\n");
    out.push_str("import { z } from \"zod\";\n");
    let type_names: Vec<String> = hir.types.iter().map(|t| t.name.clone()).collect();
    if !type_names.is_empty() {
        out.push_str(&format!(
            "import type {{ {} }} from \"./types\";\n",
            type_names.join(", ")
        ));
        let zod_imports: Vec<String> = type_names.iter().map(|t| format!("{}Schema", t)).collect();
        out.push_str(&format!(
            "import {{ {} }} from \"./schemas\";\n\n",
            zod_imports.join(", ")
        ));
    }

    out.push_str("export class VoxApiError extends Error {\n  constructor(public readonly status: number, public readonly path: string, public readonly responseText: string) {\n    super(`${path} failed: ${status}${responseText ? ` — ${responseText.slice(0, 200)}` : \"\"}`);\n    this.name = \"VoxApiError\";\n  }\n}\n\n");

    out.push_str(
        "const BASE = ((import.meta as unknown as { env?: { VITE_API_URL?: string } }).env?.VITE_API_URL ?? \"\");\n\n",
    );
    out.push_str(
        r#"/** Build `?a=<json>&b=<json>` with keys sorted lexicographically (matches Axum BTreeMap decode). */
function voxQueryString(query: Record<string, unknown>): string {
  const keys = Object.keys(query).sort();
  if (keys.length === 0) return "";
  const parts = keys.map(
    (k) => `${encodeURIComponent(k)}=${encodeURIComponent(JSON.stringify(query[k]))}`,
  );
  return `?${parts.join("&")}`;
}

async function $get<T>(path: string, schema?: { parse: (x: any) => T }, query?: Record<string, unknown>, init?: RequestInit): Promise<T> {
  const url = BASE ? `${BASE}${path}` : path;
  const qs = query && Object.keys(query).length > 0 ? voxQueryString(query) : "";
  const r = await fetch(`${url}${qs}`, { method: "GET", ...init });
  if (!r.ok) {
    const t = await r.text().catch(() => "");
    throw new VoxApiError(r.status, path, t);
  }
  const data = await r.json();
  return schema ? schema.parse(data) : (data as T);
}

async function $post<T>(path: string, schema?: { parse: (x: any) => T }, body?: unknown, init?: RequestInit): Promise<T> {
  const url = BASE ? `${BASE}${path}` : path;
  const r = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body ?? {}),
    ...init,
  });
  if (!r.ok) {
    const t = await r.text().catch(() => "");
    throw new VoxApiError(r.status, path, t);
  }
  const data = await r.json();
  return schema ? schema.parse(data) : (data as T);
}

"#,
    );

    for sf in &hir.endpoint_fns {
        out.push_str(&emit_one_fn(sf, sf.kind == HirEndpointKind::Query));
    }

    out
}

fn emit_one_fn(sf: &HirEndpointFn, is_query: bool) -> String {
    let name = &sf.name;
    let return_type = sf.return_type.as_ref().map_or(
        "unknown".to_string(),
        crate::codegen_ts::hir_emit::map_hir_type_to_ts,
    );
    let path = &sf.route_path;

    let return_schema = sf.return_type.as_ref().map_or(
        "undefined".to_string(),
        crate::codegen_ts::zod_emit::map_type_to_zod,
    );

    if sf.params.is_empty() {
        if is_query {
            return format!(
                "/** @query `{name}` → `{path}` (GET) */\nexport async function {name}(init?: RequestInit): Promise<{return_type}> {{\n  return $get<{return_type}>(\"{path}\", {return_schema}, undefined, init);\n}}\n\n"
            );
        }
        return format!(
            "/** Server fn `{name}` → `{path}` (POST) */\nexport async function {name}(init?: RequestInit): Promise<{return_type}> {{\n  return $post<{return_type}>(\"{path}\", {return_schema}, {{}}, init);\n}}\n\n"
        );
    }

    let mut fields = Vec::new();
    for p in &sf.params {
        let ty = p.type_ann.as_ref().map_or(
            "unknown".to_string(),
            crate::codegen_ts::hir_emit::map_hir_type_to_ts,
        );
        fields.push(format!("{}: {}", p.name, ty));
    }
    let arg_type = fields.join(", ");
    let body_obj = sf
        .params
        .iter()
        .map(|p| format!("{}: args.{}", p.name, p.name))
        .collect::<Vec<_>>()
        .join(", ");

    if is_query {
        format!(
            "/** @query `{name}` → `{path}` (GET) */\nexport async function {name}(args: {{ {arg_type} }}, init?: RequestInit): Promise<{return_type}> {{\n  return $get<{return_type}>(\"{path}\", {return_schema}, {{ {body_obj} }}, init);\n}}\n\n"
        )
    } else {
        format!(
            "/** Server fn `{name}` → `{path}` (POST) */\nexport async function {name}(args: {{ {arg_type} }}, init?: RequestInit): Promise<{return_type}> {{\n  return $post<{return_type}>(\"{path}\", {return_schema}, {{ {body_obj} }}, init);\n}}\n\n"
        )
    }
}
