//! Framework-agnostic typed `fetch` client for `@server` / `@query` / `@mutation`.
//!
//! **HTTP SSOT (Rust + TS):** generated Axum wiring uses **`GET`** for `@query` (deterministic
//! JSON-in-query encoding: sorted keys, each value is `JSON.stringify` + `encodeURIComponent`) and
//! **`POST` + JSON body** for `@mutation` / `@server`. Cache-friendly reads use GET as intended.

use crate::hir::{HirModule, HirServerFn};

/// Stable output filename for the generated client.
pub const VOX_CLIENT_FILENAME: &str = "vox-client.ts";

#[must_use]
pub fn emit_vox_client(hir: &HirModule) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Vox — typed fetch client for @query / @mutation / @server\n");
    out.push_str("// Transport: GET + JSON query values for @query; POST + JSON body for @mutation / @server.\n");
    out.push_str("// Do not edit; regenerate with `vox build`.\n\n");
    out.push_str(
        "const BASE = ((import.meta as unknown as { env?: { VITE_API_URL?: string } }).env?.VITE_API_URL ?? \"\");\n\n",
    );
    out.push_str(
        r#"/** Build `?a=<json>&b=<json>` with keys sorted lexicographically (matches Axum BTreeMap decode). */
function voxQueryString(query: Record<string, unknown>): string {
  const keys = Object.keys(query).sort();
  if (keys.length === 0) return "";
  const parts = keys.map(
    (k) => `${encodeURIComponent(k)}=${encodeURIComponent(JSON.stringify(query[k]))}`,
  );
  return `?${parts.join("&")}`;
}

async function $get<T>(path: string, query?: Record<string, unknown>): Promise<T> {
  const url = BASE ? `${BASE}${path}` : path;
  const qs = query && Object.keys(query).length > 0 ? voxQueryString(query) : "";
  const r = await fetch(`${url}${qs}`, { method: "GET" });
  if (!r.ok) {
    const t = await r.text().catch(() => "");
    throw new Error(`${path} failed: ${r.status}${t ? ` — ${t.slice(0, 200)}` : ""}`);
  }
  return r.json() as Promise<T>;
}

async function $post<T>(path: string, body: unknown): Promise<T> {
  const url = BASE ? `${BASE}${path}` : path;
  const r = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body ?? {}),
  });
  if (!r.ok) {
    const t = await r.text().catch(() => "");
    throw new Error(`${path} failed: ${r.status}${t ? ` — ${t.slice(0, 200)}` : ""}`);
  }
  return r.json() as Promise<T>;
}

"#,
    );

    for sf in &hir.server_fns {
        out.push_str(&emit_one_fn(sf, false));
    }
    for qf in &hir.query_fns {
        out.push_str(&emit_one_fn(qf, true));
    }
    for mf in &hir.mutation_fns {
        out.push_str(&emit_one_fn(mf, false));
    }

    out
}

fn emit_one_fn(sf: &HirServerFn, is_query: bool) -> String {
    let name = &sf.name;
    let return_type = sf.return_type.as_ref().map_or(
        "unknown".to_string(),
        crate::codegen_ts::hir_emit::map_hir_type_to_ts,
    );
    let path = &sf.route_path;

    if sf.params.is_empty() {
        if is_query {
            return format!(
                "/** @query `{name}` → `{path}` (GET) */\nexport async function {name}(): Promise<{return_type}> {{\n  return $get<{return_type}>(\"{path}\");\n}}\n\n"
            );
        }
        return format!(
            "/** Server fn `{name}` → `{path}` (POST) */\nexport async function {name}(): Promise<{return_type}> {{\n  return $post<{return_type}>(\"{path}\", {{}});\n}}\n\n"
        );
    }

    let mut fields = Vec::new();
    for p in &sf.params {
        let ty = p.type_ann.as_ref().map_or(
            "unknown".to_string(),
            crate::codegen_ts::hir_emit::map_hir_type_to_ts,
        );
        fields.push(format!("{}: {}", p.name, ty));
    }
    let arg_type = fields.join(", ");
    let body_obj = sf
        .params
        .iter()
        .map(|p| format!("{}: args.{}", p.name, p.name))
        .collect::<Vec<_>>()
        .join(", ");

    if is_query {
        format!(
            "/** @query `{name}` → `{path}` (GET) */\nexport async function {name}(args: {{ {arg_type} }}): Promise<{return_type}> {{\n  return $get<{return_type}>(\"{path}\", {{ {body_obj} }});\n}}\n\n"
        )
    } else {
        format!(
            "/** Server fn `{name}` → `{path}` (POST) */\nexport async function {name}(args: {{ {arg_type} }}): Promise<{return_type}> {{\n  return $post<{return_type}>(\"{path}\", {{ {body_obj} }});\n}}\n\n"
        )
    }
}
