//! Shared constants for CLI defaults.

pub const PUBLICATION_EXTERNAL_JOBS_DEFAULT_LIMIT: i64 = 50;
pub const PUBLICATION_EXTERNAL_JOBS_TICK_DEFAULT_LIMIT: i64 = 10;
pub const PUBLICATION_EXTERNAL_JOBS_TICK_DEFAULT_LOCK_TTL_MS: i64 = 120_000;
pub const PUBLICATION_EXTERNAL_METRICS_DEFAULT_SINCE_HOURS: i64 = 168;
pub const PUBLICATION_SYNC_BATCH_DEFAULT_LIMIT: i64 = 25;
pub const PUBLICATION_WORKER_DEFAULT_INTERVAL_SECS: u64 = 0;
pub const PUBLICATION_WORKER_DEFAULT_ITERATIONS: u32 = 1;
pub const PUBLICATION_WORKER_DEFAULT_JITTER_SECS: u64 = 0;
