//! Behavioral Learning Engine for VoxDB.
//!
//! The `BehavioralLearner` observes user actions, detects usage patterns,
//! infers preferences, and generates suggestions for improving the user
//! experience. It sits on top of the `CodeStore` CRUD layer and provides
//! higher-level analytics.

use std::collections::HashMap;
use crate::arca_store::{LearnedPatternEntry, StoreError};
use crate::CodeStore;

/// Minimum number of observations before a pattern is considered confident.
const MIN_EVIDENCE_FOR_PATTERN: i64 = 3;
/// Default confidence for newly observed patterns.
const DEFAULT_INITIAL_CONFIDENCE: f64 = 0.5;
/// Factor by which existing confidence changes on reinforcement.
const CONFIDENCE_REINFORCEMENT: f64 = 0.1;
/// Maximum confidence value.
const MAX_CONFIDENCE: f64 = 0.99;

/// High-level behavioral learning engine.
///
/// Records user actions, automatically detects patterns, and generates
/// suggestions for improving the development workflow.
pub struct BehavioralLearner<'a> {
    store: &'a CodeStore,
}

/// A suggestion generated by the learning engine.
#[derive(Debug, Clone)]
pub struct Suggestion {
    /// High-level grouping (e.g. `workflow`, `error`).
    pub category: String,
    /// Short headline for UI or logs.
    pub title: String,
    /// Longer explanation for the user.
    pub description: String,
    /// Model confidence in `[0, 1]`.
    pub confidence: f64,
    /// Optional recommended CLI or UI action.
    pub action: Option<String>,
}

/// A frequency analysis result.
#[derive(Debug, Clone)]
pub struct FrequencyItem {
    /// Item key (command name, path, etc.).
    pub item: String,
    /// Observation count.
    pub count: i64,
    /// Mean duration when timestamps are available.
    pub avg_duration_ms: Option<f64>,
    /// Fraction of attempts that succeeded (caller-defined).
    pub success_rate: f64,
}

/// A time-of-day usage bucket.
#[derive(Debug, Clone)]
pub struct TimeUsageBucket {
    /// Hour `0..=23` (local or UTC per ingest).
    pub hour: u32,
    /// Events in this hour bucket.
    pub count: i64,
}

/// Error pattern with details.
#[derive(Debug, Clone)]
pub struct ErrorPattern {
    /// Normalized error class or message stem.
    pub error_type: String,
    /// Occurrence count.
    pub count: i64,
    /// Last seen error context or stack snippet, if captured.
    pub recent_context: Option<String>,
}

/// A detected action sequence (workflow).
#[derive(Debug, Clone)]
pub struct ActionSequence {
    /// Ordered step labels.
    pub actions: Vec<String>,
    /// How often this sequence was observed.
    pub frequency: i64,
    /// Mean gap between steps in milliseconds, if known.
    pub avg_gap_ms: Option<f64>,
}

impl<'a> BehavioralLearner<'a> {
    /// Create a new learning engine backed by the given `CodeStore`.
    pub fn new(store: &'a CodeStore) -> Self {
        Self { store }
    }

    // ── Observation ─────────────────────────────────────

    /// Record a user action as a behavior event and check for pattern matches.
    pub async fn observe(
        &self,
        user_id: &str,
        event_type: &str,
        context: Option<&str>,
        metadata: Option<&str>,
        vcs_snapshot_id: Option<&str>,
    ) -> Result<Vec<Suggestion>, StoreError> {
        // 1. Record the event
        self.store
            .record_behavior_event(user_id, event_type, context, metadata)
            .await?;

        // 2. Check if this event reinforces known patterns
        let patterns = self.get_learned_patterns(user_id, 100).await?;
        let mut suggestions = Vec::new();

        for pattern in &patterns {
            if pattern.pattern_type == event_type || pattern.category == event_type {
                // Reinforce existing pattern
                let new_confidence =
                    (pattern.confidence + CONFIDENCE_REINFORCEMENT).min(MAX_CONFIDENCE);
                self.store
                    .update_pattern_confidence(pattern.id, new_confidence)
                    .await?;
            }
        }

        // 3. Run lightweight analysis to see if new patterns emerge
        let new_patterns = self.detect_frequency_patterns(user_id, event_type).await?;
        for (category, description) in &new_patterns {
            let already_known = patterns
                .iter()
                .any(|p| p.category == *category && p.description == *description);
            if !already_known {
                self.store
                    .store_learned_pattern(
                        user_id,
                        event_type,
                        category,
                        description,
                        DEFAULT_INITIAL_CONFIDENCE,
                        vcs_snapshot_id,
                    )
                    .await?;
                suggestions.push(Suggestion {
                    category: category.clone(),
                    title: format!("Detected pattern: {category}"),
                    description: description.clone(),
                    confidence: DEFAULT_INITIAL_CONFIDENCE,
                    action: None,
                });
            }
        }

        Ok(suggestions)
    }

    // ── Analysis ────────────────────────────────────────

    /// Analyze all behavior events and detect high-confidence patterns.
    pub async fn analyze(
        &self,
        user_id: &str,
        vcs_snapshot_id: Option<&str>,
    ) -> Result<Vec<LearnedPatternEntry>, StoreError> {
        // Get event type distribution
        let summary = self.get_behavior_summary(user_id).await?;

        // For each event type with enough observations, create or reinforce a pattern
        for (event_type, count) in &summary {
            if *count >= MIN_EVIDENCE_FOR_PATTERN {
                let confidence = (*count as f64 / (count + 10) as f64).min(MAX_CONFIDENCE);
                let category = "frequency".to_string();
                let description = format!("User frequently uses '{event_type}' ({count} times)");

                // Check if already known
                let existing = self
                    .store
                    .get_patterns_by_category(user_id, &category)
                    .await?;
                let already = existing.iter().find(|p| p.pattern_type == *event_type);

                match already {
                    Some(p) => {
                        self.store
                            .update_pattern_confidence(p.id, confidence)
                            .await?;
                    }
                    None => {
                        self.store
                            .store_learned_pattern(
                                user_id,
                                event_type,
                                &category,
                                &description,
                                confidence,
                                vcs_snapshot_id,
                            )
                            .await?;
                    }
                }
            }
        }

        // Return all patterns sorted by confidence
        self.get_learned_patterns(user_id, 100).await
    }

    /// Generate suggestions from high-confidence patterns.
    pub async fn suggest(&self, user_id: &str) -> Result<Vec<Suggestion>, StoreError> {
        let patterns = self.get_learned_patterns(user_id, 50).await?;
        let mut suggestions = Vec::new();

        for pattern in &patterns {
            if pattern.confidence >= 0.7 {
                suggestions.push(Suggestion {
                    category: pattern.category.clone(),
                    title: format!("Suggestion based on: {}", pattern.pattern_type),
                    description: pattern.description.clone(),
                    confidence: pattern.confidence,
                    action: Some(format!("Review pattern: {}", pattern.pattern_type)),
                });
            }
        }

        // Sort by confidence descending
        suggestions.sort_by(|a, b| {
            b.confidence
                .partial_cmp(&a.confidence)
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        Ok(suggestions)
    }

    /// Frequency analysis: identify most-used and least-used features.
    pub async fn frequency_analysis(
        &self,
        user_id: &str,
        limit: i64,
    ) -> Result<Vec<FrequencyItem>, StoreError> {
        let commands = self.get_command_frequency(user_id, limit).await?;
        Ok(commands
            .into_iter()
            .map(|c| FrequencyItem {
                success_rate: if c.count > 0 {
                    c.success_count as f64 / c.count as f64
                } else {
                    0.0
                },
                item: c.command,
                count: c.count,
                avg_duration_ms: c.avg_duration_ms,
            })
            .collect())
    }

    /// Time analysis: identify peak usage hours (bucketed by hour-of-day).
    pub async fn time_analysis(&self, user_id: &str) -> Result<Vec<TimeUsageBucket>, StoreError> {
        let events = self.get_behavior_events(user_id, None, 1000).await?;
        let mut hour_counts: HashMap<u32, i64> = HashMap::new();

        for event in &events {
            // Parse hour from ISO datetime (e.g. "2026-02-27 14:30:00")
            if let Some(hour_str) = event.created_at.get(11..13) {
                if let Ok(hour) = hour_str.parse::<u32>() {
                    *hour_counts.entry(hour).or_insert(0) += 1;
                }
            }
        }

        let mut buckets: Vec<TimeUsageBucket> = hour_counts
            .into_iter()
            .map(|(hour, count)| TimeUsageBucket { hour, count })
            .collect();
        buckets.sort_by_key(|b| b.hour);
        Ok(buckets)
    }

    /// Error analysis: identify common error patterns from behavior events.
    pub async fn error_analysis(&self, user_id: &str) -> Result<Vec<ErrorPattern>, StoreError> {
        let events = self
            .store
            .get_behavior_events(user_id, Some("error"), 500)
            .await?;
        let mut error_counts: HashMap<String, (i64, Option<String>)> = HashMap::new();

        for event in &events {
            let key = event.metadata.as_deref().unwrap_or("unknown").to_string();
            let entry = error_counts.entry(key).or_insert((0, None));
            entry.0 += 1;
            entry.1 = event.context.clone();
        }

        let mut patterns: Vec<ErrorPattern> = error_counts
            .into_iter()
            .map(|(error_type, (count, ctx))| ErrorPattern {
                error_type,
                count,
                recent_context: ctx,
            })
            .collect();
        patterns.sort_by(|a, b| b.count.cmp(&a.count));
        Ok(patterns)
    }

    /// Workflow analysis: identify common action sequences from recent events.
    pub async fn workflow_analysis(
        &self,
        user_id: &str,
    ) -> Result<Vec<ActionSequence>, StoreError> {
        let events = self.get_behavior_events(user_id, None, 500).await?;

        if events.len() < 2 {
            return Ok(Vec::new());
        }

        // Build bigrams from consecutive events
        let mut bigram_counts: HashMap<(String, String), i64> = HashMap::new();
        for window in events.windows(2) {
            let key = (window[0].event_type.clone(), window[1].event_type.clone());
            *bigram_counts.entry(key).or_insert(0) += 1;
        }

        let mut sequences: Vec<ActionSequence> = bigram_counts
            .into_iter()
            .filter(|(_k, v)| *v >= MIN_EVIDENCE_FOR_PATTERN)
            .map(|((a, b), freq)| ActionSequence {
                actions: vec![a, b],
                frequency: freq,
                avg_gap_ms: None,
            })
            .collect();
        sequences.sort_by(|a, b| b.frequency.cmp(&a.frequency));
        Ok(sequences)
    }

    /// Infer user preferences from behavior patterns.
    pub async fn preference_inference(
        &self,
        user_id: &str,
    ) -> Result<Vec<(String, String)>, StoreError> {
        let patterns = self.get_learned_patterns(user_id, 50).await?;
        let mut prefs = Vec::new();

        for pattern in &patterns {
            if pattern.confidence >= 0.6 {
                let key = format!("inferred.{}", pattern.category);
                let value = pattern.description.clone();

                // Persist as a preference
                self.store
                    .set_user_preference(user_id, &key, &value)
                    .await?;
                prefs.push((key, value));
            }
        }
        Ok(prefs)
    }

    /// Integrate LLM feedback into learning. Updates patterns based on
    pub async fn feedback_loop(
        &self,
        user_id: &str,
        vcs_snapshot_id: Option<&str>,
    ) -> Result<u64, StoreError> {
        // Get training pairs with feedback
        let pairs = self.get_training_data(100).await?;
        let mut updates = 0u64;

        for pair in &pairs {
            if let Some(rating) = pair.rating {
                let event_type = "llm_feedback";
                let category = "model_preference";
                let description = if rating >= 4 {
                    format!(
                        "User prefers responses like: {}",
                        &pair.response.chars().take(60).collect::<String>()
                    )
                } else {
                    format!(
                        "User dislikes responses like: {}",
                        &pair.response.chars().take(60).collect::<String>()
                    )
                };

                let existing = self
                    .store
                    .get_patterns_by_category(user_id, category)
                    .await?;
                let already = existing.iter().find(|p| p.description == description);

                match already {
                    Some(p) => {
                        let boost = if rating >= 4 {
                            CONFIDENCE_REINFORCEMENT
                        } else {
                            -CONFIDENCE_REINFORCEMENT
                        };
                        let new_conf = (p.confidence + boost).clamp(0.01, MAX_CONFIDENCE);
                        self.update_pattern_confidence(p.id, new_conf).await?;
                    }
                    None => {
                        let conf = if rating >= 4 { 0.6 } else { 0.4 };
                        self.store
                            .store_learned_pattern(
                                user_id,
                                event_type,
                                category,
                                &description,
                                conf,
                                vcs_snapshot_id,
                            )
                            .await?;
                    }
                }
                updates += 1;
            }
        }
        Ok(updates)
    }

    /// Export training data pairs for RLHF pipelines.
    pub async fn export_training_data(
        &self,
        limit: i64,
    ) -> Result<Vec<crate::arca_store::TrainingPair>, StoreError> {
        self.get_training_data(limit).await
    }

    // ── Private helpers ─────────────────────────────────

    /// Detect frequency-based patterns for a specific event type.
    async fn detect_frequency_patterns(
        &self,
        user_id: &str,
        event_type: &str,
    ) -> Result<Vec<(String, String)>, StoreError> {
        let events = self
            .store
            .get_behavior_events(user_id, Some(event_type), 100)
            .await?;

        let mut patterns = Vec::new();

        // Pattern: high frequency (> 10 in recent history)
        if events.len() >= 10 {
            patterns.push((
                "high_usage".to_string(),
                format!(
                    "'{event_type}' used {len} times recently",
                    len = events.len()
                ),
            ));
        }

        Ok(patterns)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn suggestion_debug() {
        let s = Suggestion {
            category: "test".into(),
            title: "title".into(),
            description: "desc".into(),
            confidence: 0.5,
            action: None,
        };
        assert!(format!("{:?}", s).contains("test"));
    }

    #[test]
    fn frequency_item_success_rate() {
        let item = FrequencyItem {
            item: "build".into(),
            count: 10,
            avg_duration_ms: Some(500.0),
            success_rate: 0.8,
        };
        assert_eq!(item.success_rate, 0.8);
    }
}
