// Generated by Vox — typed fetch client for @query / @mutation / @server
// Transport: GET + JSON query values for @query; POST + JSON body for @mutation / @server.
// Do not edit; regenerate with `vox build`.

import { z } from "zod";
export class VoxApiError extends Error {
  constructor(public readonly status: number, public readonly path: string, public readonly responseText: string) {
    super(`${path} failed: ${status}${responseText ? ` — ${responseText.slice(0, 200)}` : ""}`);
    this.name = "VoxApiError";
  }
}

const BASE = ((import.meta as unknown as { env?: { VITE_API_URL?: string } }).env?.VITE_API_URL ?? "");

/** Build `?a=<json>&b=<json>` with keys sorted lexicographically (matches Axum BTreeMap decode). */
function voxQueryString(query: Record<string, unknown>): string {
  const keys = Object.keys(query).sort();
  if (keys.length === 0) return "";
  const parts = keys.map(
    (k) => `${encodeURIComponent(k)}=${encodeURIComponent(JSON.stringify(query[k]))}`,
  );
  return `?${parts.join("&")}`;
}

async function $get<T>(path: string, schema?: { parse: (x: any) => T }, query?: Record<string, unknown>, init?: RequestInit): Promise<T> {
  const url = BASE ? `${BASE}${path}` : path;
  const qs = query && Object.keys(query).length > 0 ? voxQueryString(query) : "";
  const r = await fetch(`${url}${qs}`, { method: "GET", ...init });
  if (!r.ok) {
    const t = await r.text().catch(() => "");
    throw new VoxApiError(r.status, path, t);
  }
  const data = await r.json();
  return schema ? schema.parse(data) : (data as T);
}

async function $post<T>(path: string, schema?: { parse: (x: any) => T }, body?: unknown, init?: RequestInit): Promise<T> {
  const url = BASE ? `${BASE}${path}` : path;
  const r = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body ?? {}),
    ...init,
  });
  if (!r.ok) {
    const t = await r.text().catch(() => "");
    throw new VoxApiError(r.status, path, t);
  }
  const data = await r.json();
  return schema ? schema.parse(data) : (data as T);
}

/** @query `list_items` → `/api/query/list_items` (GET) */
export async function list_items(init?: RequestInit): Promise<list<Item>> {
  return $get<list<Item>>("/api/query/list_items", z.array(ItemSchema), undefined, init);
}

/** Server fn `add_item` → `/api/mutation/add_item` (POST) */
export async function add_item(args: { name: string, value: number }, init?: RequestInit): Promise<Result<string>> {
  return $post<Result<string>>("/api/mutation/add_item", z.any(), { name: args.name, value: args.value }, init);
}

