//! Typed-href, sitemap, and analytics-slug emit (GA-09a).
//!
//! Single declaration drives three derivations:
//! - typed `RouteId` value at runtime;
//! - `sitemap.xml` build artifact;
//! - analytics-event slug per route.
//!
//! Per the design memo, `<a href={…}>` only accepts a `RouteId`; passing a
//! string literal warns `vox/route/stringly-typed`.

use vox_compiler::hir::nodes::boilerplate_grafts::HirRouteId;

/// Emit a typed-route TS module: one `RouteId` per declared route.
///
/// The TS shape is:
/// ```ts
/// export type RouteId =
///   | { _route: "UserProfile"; id: string }
///   | { _route: "Home" };
/// export const Route = {
///   UserProfile: (params: { id: string }): RouteId =>
///     ({ _route: "UserProfile", ...params }),
///   Home: (): RouteId => ({ _route: "Home" }),
/// };
/// export function hrefOf(r: RouteId): string { /* lookup table */ }
/// ```
#[must_use]
pub fn emit_route_id_module(routes: &[HirRouteId]) -> String {
    let mut out = String::from("// Generated by Vox. Typed routes (GA-09a). Do not edit.\n\n");

    out.push_str("export type RouteId =\n");
    if routes.is_empty() {
        out.push_str("  never;\n\n");
    } else {
        for r in routes.iter() {
            // Every variant uses the same prefix; the leading `|` keeps the
            // generated TS readable even on the first line.
            let prefix = "  | ";
            if r.params.is_empty() {
                out.push_str(&format!("{prefix}{{ _route: \"{}\" }}\n", r.name));
            } else {
                let param_block: Vec<String> =
                    r.params.iter().map(|(n, t)| format!("{n}: {t}")).collect();
                out.push_str(&format!(
                    "{prefix}{{ _route: \"{}\"; {} }}\n",
                    r.name,
                    param_block.join("; ")
                ));
            }
        }
        out.push_str(";\n\n");
    }

    out.push_str("export const Route = {\n");
    for r in routes {
        if r.params.is_empty() {
            out.push_str(&format!(
                "  {}: (): RouteId => ({{ _route: \"{}\" }}),\n",
                r.name, r.name
            ));
        } else {
            let arg_type: Vec<String> = r.params.iter().map(|(n, t)| format!("{n}: {t}")).collect();
            out.push_str(&format!(
                "  {}: (params: {{ {} }}): RouteId => ({{ _route: \"{}\", ...params }}),\n",
                r.name,
                arg_type.join("; "),
                r.name
            ));
        }
    }
    out.push_str("} as const;\n\n");

    out.push_str("export function hrefOf(r: RouteId): string {\n");
    out.push_str("  switch (r._route) {\n");
    for r in routes {
        if r.params.is_empty() {
            out.push_str(&format!(
                "    case \"{}\": return \"{}\";\n",
                r.name, r.url_pattern
            ));
        } else {
            let mut body = r.url_pattern.clone();
            for (pname, _) in &r.params {
                body = body.replace(&format!(":{pname}"), &format!("${{(r as any).{pname}}}"));
            }
            out.push_str(&format!("    case \"{}\": return `{body}`;\n", r.name));
        }
    }
    out.push_str("  }\n}\n\n");

    out.push_str("export function analyticsSlugOf(r: RouteId): string {\n");
    out.push_str("  switch (r._route) {\n");
    for r in routes {
        out.push_str(&format!(
            "    case \"{}\": return \"{}\";\n",
            r.name, r.analytics_slug
        ));
    }
    out.push_str("  }\n}\n");
    out
}

/// Emit a sitemap.xml from public routes.
///
/// `base_url` is the canonical origin (e.g., `"https://example.com"`); routes
/// with parameters are emitted with literal `{param}` placeholders so the
/// downstream build pipeline can substitute real values when crawling.
#[must_use]
pub fn emit_sitemap_xml(base_url: &str, routes: &[HirRouteId]) -> String {
    let mut out = String::from(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
"#,
    );
    for r in routes {
        let url = format!("{base_url}{}", r.url_pattern);
        out.push_str(&format!("  <url>\n    <loc>{url}</loc>\n  </url>\n"));
    }
    out.push_str("</urlset>\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use vox_compiler::ast::span::Span;

    fn span() -> Span {
        Span { start: 0, end: 0 }
    }

    fn home() -> HirRouteId {
        HirRouteId {
            name: "Home".into(),
            url_pattern: "/".into(),
            params: vec![],
            analytics_slug: "home".into(),
            span: span(),
        }
    }

    fn user_profile() -> HirRouteId {
        HirRouteId {
            name: "UserProfile".into(),
            url_pattern: "/users/:id".into(),
            params: vec![("id".into(), "string".into())],
            analytics_slug: "user_profile".into(),
            span: span(),
        }
    }

    #[test]
    fn route_id_module_emits_constructors() {
        let ts = emit_route_id_module(&[home(), user_profile()]);
        assert!(ts.contains("Home: (): RouteId =>"));
        assert!(ts.contains("UserProfile: (params: { id: string })"));
        assert!(ts.contains("export type RouteId"));
        assert!(ts.contains("export function hrefOf"));
        assert!(ts.contains("export function analyticsSlugOf"));
    }

    #[test]
    fn href_substitutes_params() {
        let ts = emit_route_id_module(&[user_profile()]);
        // Parameter substitution should produce a template literal expression.
        assert!(ts.contains("${(r as any).id}"));
    }

    #[test]
    fn sitemap_includes_all_routes() {
        let xml = emit_sitemap_xml("https://example.com", &[home(), user_profile()]);
        assert!(xml.contains("<loc>https://example.com/</loc>"));
        assert!(xml.contains("<loc>https://example.com/users/:id</loc>"));
        assert!(xml.starts_with("<?xml version=\"1.0\""));
    }

    #[test]
    fn empty_routes_emits_never_type() {
        let ts = emit_route_id_module(&[]);
        assert!(ts.contains("never;"));
    }

    #[test]
    fn analytics_slug_per_route_is_distinct() {
        let ts = emit_route_id_module(&[home(), user_profile()]);
        assert!(ts.contains("return \"home\""));
        assert!(ts.contains("return \"user_profile\""));
    }

    #[test]
    fn output_is_deterministic() {
        let a = emit_route_id_module(&[home(), user_profile()]);
        let b = emit_route_id_module(&[home(), user_profile()]);
        assert_eq!(a, b);
    }
}
