//! Emit the seven-tier portal stylesheet and root-level portal containers
//! for VUV's layered layout discipline (GA-26).
//!
//! See [`docs/src/architecture/vuv-layered-layout-discipline-2026.md`](../../../../docs/src/architecture/vuv-layered-layout-discipline-2026.md).
//!
//! Two outputs:
//! - [`emit_layer_stylesheet`] — `:root { … }` CSS with the fixed z-index ladder
//!   and a `[data-vox-layer]` selector per tier. **The ladder is not
//!   user-extensible from `.vox` source** (per C4, one canonical ordering).
//! - [`emit_layer_portal_roots`] — the seven `<div data-vox-layer="…">` portal
//!   roots that the React runtime mounts under `<body>`; surfaces declared at
//!   tier T render through the matching portal.

use vox_compiler::hir::nodes::layer::LayerTier;

/// All seven tiers in canonical order (matches `LayerTier` discriminants).
pub const TIERS: &[LayerTier] = &[
    LayerTier::Background,
    LayerTier::Content,
    LayerTier::Chrome,
    LayerTier::Popover,
    LayerTier::Modal,
    LayerTier::Toast,
    LayerTier::SystemOverlay,
];

/// Z-index step between tiers. Tier N gets `BASE_Z + N * STEP`.
///
/// Step is large enough that no one needs to fit anything between tiers — if
/// you find yourself wanting to, that's a tier-design problem, not a
/// numbering problem.
const Z_STEP: i32 = 100;
const Z_BASE: i32 = 0;

fn tier_z_index(tier: LayerTier) -> i32 {
    Z_BASE + (tier as i32) * Z_STEP
}

/// Emit the canonical seven-tier CSS ladder.
///
/// Output is deterministic (tiers iterated in canonical order). The
/// `[data-vox-layer="…"]` selector matches the portal-root convention used
/// by [`emit_layer_portal_roots`].
#[must_use]
pub fn emit_layer_stylesheet() -> String {
    let mut out = String::new();
    out.push_str("/* Generated by Vox compiler. VUV layered layout discipline (GA-26). */\n");
    out.push_str("/* Do not edit; the seven-tier ladder is fixed by the language contract. */\n\n");
    for &tier in TIERS {
        out.push_str(&format!(
            "[data-vox-layer=\"{}\"] {{\n  position: fixed;\n  inset: 0;\n  pointer-events: none;\n  z-index: {};\n}}\n",
            tier.as_str(),
            tier_z_index(tier)
        ));
        // Surfaces inside the portal re-enable pointer-events on themselves.
        out.push_str(&format!(
            "[data-vox-layer=\"{}\"] > * {{\n  pointer-events: auto;\n}}\n\n",
            tier.as_str()
        ));
    }
    out
}

/// Emit the seven `<div data-vox-layer="…">` portal roots as a TSX fragment.
///
/// Mounted once at the application root by the runtime; `Tooltip`, `Dialog`,
/// `Toast`, etc., render through the matching portal via React's
/// `createPortal`.
#[must_use]
pub fn emit_layer_portal_roots() -> String {
    let mut out = String::new();
    out.push_str("// Generated by Vox. VUV layer portal roots — mount once under <body>.\n");
    out.push_str("export function VoxLayerRoots(): JSX.Element {\n");
    out.push_str("  return (\n    <>\n");
    for &tier in TIERS {
        out.push_str(&format!(
            "      <div data-vox-layer=\"{}\" id=\"vox-layer-{}\" />\n",
            tier.as_str(),
            tier.as_str()
        ));
    }
    out.push_str("    </>\n  );\n}\n");
    out
}

/// Emit a TS helper that returns the portal root element for a given tier.
///
/// `Tooltip`, `Dialog`, etc., call this to find their portal-mount.
#[must_use]
pub fn emit_layer_portal_resolver() -> String {
    let mut out = String::new();
    out.push_str("import type { LayerTier } from \"./vox-layer-types\";\n\n");
    out.push_str(
        "/** Resolve the portal root element for a given tier. Returns null on the server. */\n",
    );
    out.push_str("export function voxResolveLayerRoot(tier: LayerTier): HTMLElement | null {\n");
    out.push_str("  if (typeof document === \"undefined\") return null;\n");
    out.push_str("  return document.getElementById(`vox-layer-${tier}`);\n");
    out.push_str("}\n");
    out
}

/// Emit the TS type alias mirroring the seven canonical tiers.
#[must_use]
pub fn emit_layer_type_alias() -> String {
    let mut out = String::new();
    out.push_str("/** VUV layered layout tiers. Closed enum — language contract. */\n");
    out.push_str("export type LayerTier =\n");
    let mut first = true;
    for &tier in TIERS {
        if first {
            out.push_str(&format!("  | \"{}\"\n", tier.as_str()));
            first = false;
        } else {
            out.push_str(&format!("  | \"{}\"\n", tier.as_str()));
        }
    }
    out.push_str(";\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stylesheet_has_seven_tier_selectors() {
        let css = emit_layer_stylesheet();
        for &tier in TIERS {
            let selector = format!("[data-vox-layer=\"{}\"]", tier.as_str());
            assert!(
                css.contains(&selector),
                "missing selector {selector} in:\n{css}"
            );
        }
    }

    #[test]
    fn z_indexes_are_strictly_ascending() {
        let z_values: Vec<i32> = TIERS.iter().map(|&t| tier_z_index(t)).collect();
        for pair in z_values.windows(2) {
            assert!(
                pair[0] < pair[1],
                "tiers not strictly ascending: {z_values:?}"
            );
        }
    }

    #[test]
    fn portal_roots_emit_seven_divs() {
        let tsx = emit_layer_portal_roots();
        for &tier in TIERS {
            let attr = format!("data-vox-layer=\"{}\"", tier.as_str());
            assert!(tsx.contains(&attr), "portal root missing: {attr}");
        }
    }

    #[test]
    fn type_alias_lists_all_tiers() {
        let ts = emit_layer_type_alias();
        for &tier in TIERS {
            let lit = format!("\"{}\"", tier.as_str());
            assert!(ts.contains(&lit), "type alias missing tier {lit}");
        }
    }

    #[test]
    fn modal_z_strictly_above_popover() {
        // Sanity-check the ladder ordering matches the design memo.
        assert!(tier_z_index(LayerTier::Modal) > tier_z_index(LayerTier::Popover));
        assert!(tier_z_index(LayerTier::Toast) > tier_z_index(LayerTier::Modal));
        assert!(tier_z_index(LayerTier::SystemOverlay) > tier_z_index(LayerTier::Toast));
    }

    #[test]
    fn output_is_deterministic() {
        let a = emit_layer_stylesheet();
        let b = emit_layer_stylesheet();
        assert_eq!(a, b);
    }
}
