//! `Paginated[T]` emit + HMAC-signed cursor codec helper (GA-17).
//!
//! Wire format: a paginated response is `{ items: T[], next_cursor: string|null,
//! prev_cursor?: string|null }`. The cursor is base64url(payload || hmac), so a
//! tampered cursor fails verification at the runtime and returns
//! `vox/pagination/invalid-cursor`. The cursor codec spec is documented in
//! `docs/src/architecture/wire-format-v1-ssot.md` (added under GA-17 design).

use vox_compiler::hir::nodes::boilerplate_grafts::HirPaginatedType;

/// Emit the TS shape for `Paginated[T]` along with `parse` / `mkCursor` helpers.
#[must_use]
pub fn emit_paginated_module(p: &HirPaginatedType) -> String {
    let mut out = String::from("// Generated by Vox. Paginated[T] (GA-17). Do not edit.\n\n");
    out.push_str(&format!(
        "import type {{ {} }} from \"./types\";\n\n",
        p.item_type
    ));
    out.push_str(&format!(
        "export interface Paginated{} {{\n  readonly items: readonly {}[];\n  readonly next_cursor: string | null;\n",
        p.item_type, p.item_type
    ));
    if p.bidirectional {
        out.push_str("  readonly prev_cursor: string | null;\n");
    }
    out.push_str("}\n\n");
    out.push_str(&format!(
        "export const PAGINATED_{}_DEFAULT_SIZE = {};\n",
        p.item_type.to_uppercase(),
        p.default_page_size
    ));
    out
}

/// Emit a server-side Rust HMAC cursor codec module.
///
/// The codec wraps a JSON-encoded payload in base64url + HMAC-SHA256 with a
/// secret loaded from `VOX_CURSOR_SECRET`. Tampered cursors return a typed
/// error rather than panicking.
#[must_use]
pub fn emit_cursor_codec_rs() -> String {
    String::from(
        r#"//! Generated by Vox. HMAC-signed pagination cursor codec (GA-17).
//! Cursors are tamper-evident: payload || HMAC-SHA256(secret, payload), base64url-encoded.

use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use hmac::{Hmac, Mac};
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

#[derive(Debug)]
pub enum CursorError {
    InvalidEncoding,
    InvalidSignature,
    InvalidPayload,
}

pub fn encode_cursor(payload: &[u8], secret: &[u8]) -> String {
    let mut mac = HmacSha256::new_from_slice(secret).expect("HMAC key length");
    mac.update(payload);
    let sig = mac.finalize().into_bytes();
    let mut buf = Vec::with_capacity(payload.len() + sig.len());
    buf.extend_from_slice(payload);
    buf.extend_from_slice(&sig);
    URL_SAFE_NO_PAD.encode(&buf)
}

pub fn decode_cursor(cursor: &str, secret: &[u8]) -> Result<Vec<u8>, CursorError> {
    let raw = URL_SAFE_NO_PAD.decode(cursor.as_bytes()).map_err(|_| CursorError::InvalidEncoding)?;
    if raw.len() < 32 {
        return Err(CursorError::InvalidPayload);
    }
    let (payload, sig) = raw.split_at(raw.len() - 32);
    let mut mac = HmacSha256::new_from_slice(secret).expect("HMAC key length");
    mac.update(payload);
    mac.verify_slice(sig).map_err(|_| CursorError::InvalidSignature)?;
    Ok(payload.to_vec())
}
"#,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use vox_compiler::ast::span::Span;

    fn span() -> Span { Span { start: 0, end: 0 } }

    #[test]
    fn paginated_module_uses_item_type_name() {
        let p = HirPaginatedType {
            item_type: "Order".into(),
            default_page_size: 25,
            bidirectional: false,
            span: span(),
        };
        let ts = emit_paginated_module(&p);
        assert!(ts.contains("export interface PaginatedOrder"));
        assert!(ts.contains("readonly items: readonly Order[]"));
        assert!(ts.contains("PAGINATED_ORDER_DEFAULT_SIZE = 25"));
    }

    #[test]
    fn bidirectional_emits_prev_cursor() {
        let p = HirPaginatedType {
            item_type: "Order".into(),
            default_page_size: 25,
            bidirectional: true,
            span: span(),
        };
        let ts = emit_paginated_module(&p);
        assert!(ts.contains("prev_cursor: string | null"));
    }

    #[test]
    fn unidirectional_omits_prev_cursor() {
        let p = HirPaginatedType {
            item_type: "Order".into(),
            default_page_size: 25,
            bidirectional: false,
            span: span(),
        };
        let ts = emit_paginated_module(&p);
        assert!(!ts.contains("prev_cursor"));
    }

    #[test]
    fn cursor_codec_rs_has_encode_and_decode() {
        let rs = emit_cursor_codec_rs();
        assert!(rs.contains("pub fn encode_cursor"));
        assert!(rs.contains("pub fn decode_cursor"));
        assert!(rs.contains("CursorError::InvalidSignature"));
    }
}
