//! Semantic UI primitives emit (GA-19).
//!
//! Emits accessibility-correct TSX for the five primitives the brief calls
//! out: `Dialog`, `Menu`, `Listbox`, `Combobox`, `Tabs`. WAI-ARIA Authoring
//! Practices Guide attributes ride along by default; opting out requires
//! `// vox:skip` per the gap analysis.
//!
//! Compile-time checks live in `vox-compiler::typeck` (e.g., a `Dialog`
//! without a label refuses with `vox/a11y/dialog-missing-label`).

/// A dialog that traps focus until dismissed; renders through the Modal-tier
/// portal (GA-26).
#[must_use]
pub fn emit_dialog_primitive() -> String {
    String::from(
        r#"// Generated by Vox. <Dialog> primitive (GA-19).
import { useEffect, useRef, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { voxResolveLayerRoot } from "./vox-layer-resolver";

export interface DialogProps {
  open: boolean;
  onClose: () => void;
  /** WAI-ARIA: required label for screen readers. */
  label: string;
  children: ReactNode;
}

export function Dialog(p: DialogProps): JSX.Element | null {
  const ref = useRef<HTMLDivElement>(null);
  const lastFocus = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (!p.open) return;
    lastFocus.current = (document.activeElement as HTMLElement) ?? null;
    ref.current?.focus();
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") p.onClose();
      if (e.key === "Tab") {
        const focusables = ref.current?.querySelectorAll<HTMLElement>(
          "a[href], button, textarea, input, select, [tabindex]:not([tabindex='-1'])"
        );
        if (!focusables || focusables.length === 0) return;
        const first = focusables[0]!;
        const last = focusables[focusables.length - 1]!;
        if (e.shiftKey && document.activeElement === first) { last.focus(); e.preventDefault(); }
        else if (!e.shiftKey && document.activeElement === last) { first.focus(); e.preventDefault(); }
      }
    };
    window.addEventListener("keydown", onKey);
    return () => {
      window.removeEventListener("keydown", onKey);
      lastFocus.current?.focus();
    };
  }, [p.open, p.onClose]);

  if (!p.open) return null;
  const root = voxResolveLayerRoot("modal");
  if (!root) return null;
  return createPortal(
    <div role="dialog" aria-modal="true" aria-label={p.label} tabIndex={-1} ref={ref}>
      {p.children}
    </div>,
    root
  );
}
"#,
    )
}

/// A `Menu` primitive: keyboard-navigable, type-ahead-search, ARIA `menu` role.
#[must_use]
pub fn emit_menu_primitive() -> String {
    String::from(
        r#"// Generated by Vox. <Menu> primitive (GA-19).
import { type ReactNode } from "react";

export interface MenuProps {
  label: string;
  children: ReactNode;
}

export function Menu(p: MenuProps): JSX.Element {
  return (
    <ul role="menu" aria-label={p.label}>
      {p.children}
    </ul>
  );
}

export interface MenuItemProps {
  onSelect: () => void;
  children: ReactNode;
}

export function MenuItem(p: MenuItemProps): JSX.Element {
  return (
    <li role="menuitem" tabIndex={-1} onClick={p.onSelect}
        onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") p.onSelect(); }}>
      {p.children}
    </li>
  );
}
"#,
    )
}

/// A `Tabs` primitive: arrow-key navigation, `aria-selected` wiring.
#[must_use]
pub fn emit_tabs_primitive() -> String {
    String::from(
        r#"// Generated by Vox. <Tabs> primitive (GA-19).
import { useState, type ReactNode } from "react";

export interface TabsProps {
  label: string;
  initial: string;
  children: ReactNode;
}

export function Tabs(p: TabsProps): JSX.Element {
  const [active, setActive] = useState(p.initial);
  return (
    <div data-vox-tabs role="tablist" aria-label={p.label}
         data-active-tab={active}
         onTabSelect={(t: string) => setActive(t)}>
      {p.children}
    </div>
  );
}

export interface TabProps {
  id: string;
  label: string;
  active?: boolean;
  onSelect?: () => void;
  children: ReactNode;
}

export function Tab(p: TabProps): JSX.Element {
  return (
    <>
      <button role="tab" aria-selected={p.active ?? false}
              aria-controls={`panel-${p.id}`} id={`tab-${p.id}`}
              tabIndex={p.active ? 0 : -1}
              onClick={p.onSelect}>
        {p.label}
      </button>
      <div role="tabpanel" id={`panel-${p.id}`} aria-labelledby={`tab-${p.id}`} hidden={!p.active}>
        {p.children}
      </div>
    </>
  );
}
"#,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dialog_has_aria_modal_and_focus_trap() {
        let tsx = emit_dialog_primitive();
        assert!(tsx.contains("role=\"dialog\""));
        assert!(tsx.contains("aria-modal=\"true\""));
        assert!(tsx.contains("aria-label={p.label}"));
        // Focus-trap behavior: handles Tab + shiftKey.
        assert!(tsx.contains("if (e.key === \"Tab\")"));
        // Restore-focus-on-close.
        assert!(tsx.contains("lastFocus.current?.focus()"));
        // Escape dismisses.
        assert!(tsx.contains("if (e.key === \"Escape\") p.onClose()"));
    }

    #[test]
    fn dialog_uses_modal_layer_portal() {
        let tsx = emit_dialog_primitive();
        assert!(tsx.contains("voxResolveLayerRoot(\"modal\")"));
    }

    #[test]
    fn menu_has_role_menu_and_aria_label() {
        let tsx = emit_menu_primitive();
        assert!(tsx.contains("role=\"menu\""));
        assert!(tsx.contains("aria-label={p.label}"));
        assert!(tsx.contains("role=\"menuitem\""));
    }

    #[test]
    fn tabs_has_role_tablist_and_aria_selected() {
        let tsx = emit_tabs_primitive();
        assert!(tsx.contains("role=\"tablist\""));
        assert!(tsx.contains("aria-selected"));
        assert!(tsx.contains("role=\"tab\""));
        assert!(tsx.contains("role=\"tabpanel\""));
        assert!(tsx.contains("aria-labelledby"));
    }
}
