//! Lark grammar emitter for `vox-grammar-export`.
//!
//! Lark is a Python-native parser toolkit used in some bridge integrations.
//! This emitter converts the core Vox grammar surface to Lark's EBNF-like notation.

/// Emit a Lark grammar definition for the Vox language surface.
///
/// Lark uses `?rule: alt` for inline rules, terminals in uppercase, and
/// allows full Python regex in terminal definitions.
pub fn emit_lark() -> String {
    let mut g = String::with_capacity(8192);
    g.push_str("// Lark grammar for Vox 0.4\n");
    g.push_str("// Auto-generated by vox-grammar-export — do not hand-edit.\n\n");

    g.push_str("start: module\n\n");

    // ── Module & Declarations
    g.push_str("module: decl*\n");
    g.push_str("decl: fn_decl | type_def | import | actor | workflow | activity\n");
    g.push_str("    | http_route | table | index | test | forall\n");
    g.push_str("    | server_fn | query_fn | mutation_fn\n");
    g.push_str("    | mcp_tool | mcp_resource\n");
    g.push_str("    | component | reactive_component | v0_component\n");
    g.push_str("    | routes | loading | agent | environment\n");
    g.push_str("    ;\n\n");

    // ── Functions
    g.push_str("fn_decl: [\"pub\"] [\"async\"] \"fn\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n");
    g.push_str("params: param (\",\" param)*\n");
    g.push_str("param: IDENT \":\" type_expr [\"?\"]\n\n");

    // ── Type definitions
    g.push_str("type_def: [\"pub\"] \"type\" IDENT \"=\" type_body\n");
    g.push_str("type_body: adt_variants | struct_body\n");
    g.push_str("adt_variants: \"|\" variant (\"|\" variant)*\n");
    g.push_str("variant: IDENT [\"(\" field_list \")\"]\n");
    g.push_str("struct_body: \"{\" field_def (\",\" field_def)* [\",\"] \"}\"\n");
    g.push_str("field_def: IDENT \":\" type_expr\n\n");

    // ── Imports
    g.push_str("import: \"import\" import_path (\",\" import_path)*\n");
    g.push_str("import_path: symbol_path | rust_crate_import\n");
    g.push_str("symbol_path: IDENT (\".\" IDENT)*\n");
    g.push_str("rust_crate_import: \"rust:\" IDENT\n\n");

    // ── Actors
    g.push_str("actor: \"actor\" IDENT \"{\" actor_handler* \"}\"\n");
    g.push_str("actor_handler: \"on\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n\n");

    // ── Workflows & Activities
    g.push_str("workflow: \"workflow\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n");
    g.push_str("activity: \"activity\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n\n");

    // ── HTTP Routes
    g.push_str("http_route: \"http\" HTTP_METHOD STRING_LIT \"(\" params? \")\" [\"to\" type_expr] block\n");
    g.push_str("HTTP_METHOD: \"get\" | \"post\" | \"put\" | \"delete\"\n\n");

    // ── Tables & Indexes
    g.push_str("table: decorator* \"@table\" [\"type\"] IDENT \"{\" field_def* \"}\"\n");
    g.push_str("index: \"@index\" IDENT \".\" IDENT \"on\" \"(\" IDENT (\",\" IDENT)* \")\"\n\n");

    // ── Server / Query / Mutation
    g.push_str(
        "server_fn: \"@server\" \"fn\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n",
    );
    g.push_str("query_fn: \"@query\" \"fn\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n");
    g.push_str(
        "mutation_fn: \"@mutation\" \"fn\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n\n",
    );

    // ── Tests & PBT
    g.push_str("test: \"@test\" \"fn\" IDENT \"(\" \")\" [\"to\" type_expr] block\n");
    g.push_str("forall: \"@forall\" \"fn\" IDENT \"(\" params \")\" [\"to\" type_expr] block\n\n");

    // ── MCP Tools & Resources
    g.push_str("mcp_tool: \"@mcp.tool\" [STRING_LIT] \"fn\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n");
    g.push_str("mcp_resource: \"@mcp.resource\" [STRING_LIT] \"fn\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n\n");

    // ── Components
    g.push_str(
        "component: \"@component\" \"fn\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n",
    );
    g.push_str("reactive_component: \"component\" IDENT \"(\" params? \")\" reactive_block\n");
    g.push_str("reactive_block: \"{\" reactive_member* [\"view:\" expr] \"}\"\n");
    g.push_str("reactive_member: state_decl | derived_decl | effect_block | mount_block | cleanup_block | stmt\n");
    g.push_str("state_decl: \"state\" IDENT [\":\" type_expr] \"=\" expr\n");
    g.push_str("derived_decl: \"derived\" IDENT [\":\" type_expr] \"=\" expr\n");
    g.push_str("effect_block: \"effect\" block\n");
    g.push_str("mount_block: \"mount\" block\n");
    g.push_str("cleanup_block: \"cleanup\" block\n");
    g.push_str("v0_component: \"@v0\" STRING_LIT \"fn\" IDENT \"(\" \")\" \"to\" type_expr\n\n");

    // ── Routes & Loading
    g.push_str("routes: \"routes\" \"{\" route_entry* \"}\"\n");
    g.push_str("route_entry: STRING_LIT \"to\" IDENT [with_clause]\n");
    g.push_str("with_clause: \"with\" \"{\" (IDENT \":\" expr)* \"}\"\n");
    g.push_str("loading: \"@loading\" \"fn\" IDENT \"(\" \")\" [\"to\" type_expr] block\n\n");

    // ── Agents & Environments
    g.push_str("agent: \"agent\" IDENT \"{\" agent_handler* \"}\"\n");
    g.push_str("agent_handler: \"on\" IDENT \"(\" params? \")\" [\"to\" type_expr] block\n");
    g.push_str("environment: \"environment\" IDENT \"{\" env_field* \"}\"\n");
    g.push_str("env_field: IDENT \":\" type_expr \"=\" expr\n\n");

    // ── Decorators
    g.push_str("decorator: \"@require\" \"(\" expr \")\"\n");
    g.push_str("         | \"@ensure\" \"(\" expr \")\"\n");
    g.push_str("         | \"@invariant\" \"(\" expr \")\"\n");
    g.push_str("         | \"@llm\" [\"(\" \"model\" \"=\" STRING_LIT \")\"]\n");
    g.push_str("         | \"@fuzz\"\n\n");

    // ── Statements
    g.push_str("stmt: let_stmt | assign_stmt | return_stmt | while_stmt | loop_stmt | break_stmt | continue_stmt | expr_stmt\n");
    g.push_str("let_stmt: \"let\" [\"mut\" ] IDENT [\":\" type_expr] \"=\" expr\n");
    g.push_str("assign_stmt: IDENT ASSIGN_OP expr\n");
    g.push_str("ASSIGN_OP: \"=\" | \"+=\" | \"-=\" | \"*=\" | \"/=\"\n");
    g.push_str("return_stmt: ( \"ret\" | \"return\" ) [expr]\n");
    g.push_str("while_stmt: \"while\" expr block\n");
    g.push_str("loop_stmt: \"loop\" block\n");
    g.push_str("break_stmt: \"break\"\n");
    g.push_str("continue_stmt: \"continue\"\n");
    g.push_str("expr_stmt: expr\n");
    g.push_str("block: \"{\" stmt* expr? \"}\"\n\n");

    // ── Expressions
    g.push_str("?expr: primary (BIN_OP primary)* | pipe_expr\n");
    g.push_str("pipe_expr: expr \"|>\" expr\n");
    g.push_str("?primary: literal | IDENT | call_expr | field_access | method_call\n");
    g.push_str("        | match_expr | if_expr | for_expr | lambda | spawn_expr | with_expr\n");
    g.push_str(
        "        | object_lit | list_lit | tuple_lit | jsx_expr | block | \"(\" expr \")\"\n\n",
    );

    g.push_str("match_expr: \"match\" expr \"{\" match_arm* \"}\"\n");
    g.push_str("match_arm: pattern \"->\" expr\n");
    g.push_str("pattern: IDENT | IDENT \"(\" (IDENT (\",\" IDENT)*)? \")\" | \"_\" | literal\n\n");
    g.push_str("if_expr: \"if\" expr block (\"else\" (block | if_expr))?\n");
    g.push_str("for_expr: \"for\" IDENT \"in\" expr block\n");
    g.push_str("lambda: \"fn\" \"(\" params? \")\" (block | expr)\n");
    g.push_str("spawn_expr: \"spawn\" expr\n");
    g.push_str("with_expr: \"with\" expr object_lit\n");
    g.push_str("call_expr: expr \"(\" args? \")\"\n");
    g.push_str("args: expr (\",\" expr)*\n");
    g.push_str("field_access: expr \".\" IDENT\n");
    g.push_str("method_call: expr \".\" IDENT \"(\" args? \")\"\n\n");

    // ── Literals
    g.push_str("?literal: INT_LIT | FLOAT_LIT | STRING_LIT | BOOL_LIT | \"Unit\"\n");
    g.push_str("INT_LIT: [\"-\"] /[0-9]+/\n");
    g.push_str("FLOAT_LIT: [\"-\"] /[0-9]+\\.[0-9]+/\n");
    g.push_str("STRING_LIT: /\"[^\"\\\\]*(\\\\.[^\"\\\\]*)*\"/\n");
    g.push_str("BOOL_LIT: \"true\" | \"false\"\n");
    g.push_str("object_lit: \"{\" (field_init (\",\" field_init)*)? \"}\"\n");
    g.push_str("field_init: IDENT \":\" expr\n");
    g.push_str("list_lit: \"[\" (expr (\",\" expr)*)? \"]\"\n");
    g.push_str("tuple_lit: \"(\" expr \",\" (expr (\",\" expr)*)? \")\"\n\n");

    // ── View-call surface (lowers to JSX-shaped HIR nodes)
    g.push_str("jsx_expr: view_call_expr\n");
    g.push_str("view_call_expr: view_call_block | view_call_self_closing\n");
    g.push_str("view_call_block: IDENT \"(\" view_args? \")\" \"{\" expr* \"}\"\n");
    g.push_str("view_call_self_closing: IDENT \"(\" view_args? \")\"\n");
    g.push_str("view_args: view_arg (\",\" view_arg)*\n");
    g.push_str("view_arg: IDENT \"=\" expr\n");
    g.push_str("// angle-bracket JSX (<tag ...>) is retired at parser entry\n\n");

    // ── Type expressions
    g.push_str("type_expr: simple_type | generic_type | fn_type | tuple_type | \"Unit\"\n");
    g.push_str("simple_type: IDENT\n");
    g.push_str("generic_type: IDENT \"[\" type_expr (\",\" type_expr)* \"]\"\n");
    g.push_str("fn_type: \"fn\" \"(\" (type_expr (\",\" type_expr)*)? \")\" \"to\" type_expr\n");
    g.push_str("tuple_type: \"(\" type_expr \",\" (type_expr (\",\" type_expr)*)? \")\"\n\n");

    // ── Operators
    g.push_str("BIN_OP: \"+\" | \"-\" | \"*\" | \"/\" | \"==\" | \"!=\" | \"<\" | \">\" | \"<=\" | \">=\" | \"and\" | \"or\"\n");
    g.push_str("UNARY_OP: \"not\" | \"-\"\n\n");

    // ── Terminals
    g.push_str("IDENT: /[a-zA-Z_][a-zA-Z0-9_]*/\n");
    g.push_str("field_list: field_def (\",\" field_def)*\n");
    g.push_str("TEXT: /[^<{}]+/\n\n");

    // ── Whitespace / Comments
    g.push_str("%ignore /\\s+/\n");
    g.push_str("%ignore /\\/\\/[^\\n]*/\n");

    g
}
