//! Lark grammar emitter for `vox-grammar-export`.
//!
//! Lark is a Python-native parser toolkit used in some bridge integrations.
//! This emitter converts the core Vox grammar surface to Lark's EBNF-like notation.

/// Emit a Lark grammar definition for the Vox language surface.
///
/// Lark uses `?rule: alt` for inline rules, terminals in uppercase, and
/// allows full Python regex in terminal definitions.
pub fn emit_lark() -> String {
    let mut g = String::new();
    g.push_str("// Lark grammar for Vox 0.4\n");
    g.push_str("// Auto-generated by vox-grammar-export — do not hand-edit.\n\n");

    g.push_str("start: module\n\n");

    // Module-level declarations
    g.push_str("module: decl*\n");
    g.push_str("decl: fn_decl\n");
    g.push_str("    | let_decl\n");
    g.push_str("    | type_decl\n\n");

    // Function declaration
    g.push_str("fn_decl: \"fn\" IDENT \"(\" param_list? \")\" (\"->\" type_expr)? block\n");
    g.push_str("param_list: param (\",\" param)*\n");
    g.push_str("param: IDENT \":\" type_expr\n\n");

    // Let declaration
    g.push_str("let_decl: \"let\" IDENT (\":\" type_expr)? \"=\" expr\n\n");

    // Type declaration
    g.push_str("type_decl: \"type\" IDENT \"=\" type_expr\n\n");

    // Type expressions
    g.push_str("type_expr: IDENT\n");
    g.push_str("         | type_expr \"[\" type_expr \"]\"   // generic\n");
    g.push_str("         | \"(\" type_list? \")\"             // tuple type\n");
    g.push_str("         | \"{\" type_field_list? \"}\"       // record type\n");
    g.push_str("type_list: type_expr (\",\" type_expr)*\n");
    g.push_str("type_field_list: type_field (\",\" type_field)*\n");
    g.push_str("type_field: IDENT \":\" type_expr\n\n");

    // Statements and blocks
    g.push_str("block: \"{\" stmt* expr? \"}\"\n");
    g.push_str("stmt: let_decl\n");
    g.push_str("    | expr\n\n");

    // Expressions
    g.push_str("?expr: literal\n");
    g.push_str("     | record_lit\n");
    g.push_str("     | tuple_lit\n");
    g.push_str("     | array_lit\n");
    g.push_str("     | IDENT\n");
    g.push_str("     | call_expr\n");
    g.push_str("     | field_access\n");
    g.push_str("     | binary_expr\n");
    g.push_str("     | if_expr\n");
    g.push_str("     | block\n\n");

    g.push_str("call_expr: expr \"(\" expr_list? \")\"\n");
    g.push_str("field_access: expr \".\" IDENT\n");
    g.push_str("binary_expr: expr BIN_OP expr\n");
    g.push_str("if_expr: \"if\" expr block (\"else\" block)?\n");
    g.push_str("expr_list: expr (\",\" expr)*\n\n");

    // Literals
    g.push_str("?literal: INT_LIT\n");
    g.push_str("        | FLOAT_LIT\n");
    g.push_str("        | STRING_LIT\n");
    g.push_str("        | BOOL_LIT\n\n");

    // Composite literals
    g.push_str("record_lit: \"{\" (field_init (\",\" field_init)*)? \"}\"\n");
    g.push_str("field_init: IDENT \":\" expr\n");
    g.push_str("tuple_lit: \"(\" (expr (\",\" expr)*)? \")\"\n");
    g.push_str("array_lit: \"[\" (expr (\",\" expr)*)? \"]\"\n\n");

    // Terminals
    g.push_str("IDENT: /[a-zA-Z_][a-zA-Z0-9_]*/\n");
    g.push_str("INT_LIT: /[0-9]+/\n");
    g.push_str("FLOAT_LIT: /[0-9]+\\.[0-9]+/\n");
    g.push_str("STRING_LIT: /\"[^\"]*\"/\n");
    g.push_str("BOOL_LIT: \"true\" | \"false\"\n");
    g.push_str("BIN_OP: \"+\" | \"-\" | \"*\" | \"/\" | \"==\" | \"!=\" | \"<\" | \">\" | \"<=\" | \">=\"\n\n");

    // Whitespace / comments
    g.push_str("%ignore /\\s+/\n");
    g.push_str("%ignore /\\/\\/[^\\n]*/\n");

    g
}
