//! Lexical analysis for Vox: source text → [`Token`] stream.
//!
//! Tokens are generated by [`logos`](https://docs.rs/logos) and match the keyword / punctuation
//! inventory in `docs/src/reference/lexicon.md`. See [`token::Token`] for the full token set.
//!
//! Submodules:
//! - [`cursor`] — incremental / cursor-based lexing API.
//! - [`token`] — [`Token`] definition and [`logos`](https://docs.rs/logos) lexer.

mod compact;
/// Cursor-based lexer ([`lex`]).
pub mod cursor;
/// Token kinds and the [`logos`](https://docs.rs/logos) derive on [`Token`].
pub mod token;

/// Minify source for LLM-oriented tooling (comments/whitespace stripped; see [`compact::compact`]).
pub use compact::compact;
/// Lex a source string into a vector of spanned tokens (newlines preserved for indentation).
pub use cursor::lex;
/// The Vox token enum.
pub use token::Token;
