use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct SupportRegistry {
    template_managed_dependencies: TemplateManagedDependencies,
    wasi_unsupported_rust_imports: Vec<String>,
    support_entries: Vec<SupportEntry>,
}

#[derive(Debug, Deserialize, Clone)]
struct TemplateManagedDependencies {
    app: Vec<String>,
    script_native: Vec<String>,
    script_wasi: Vec<String>,
}

#[derive(Debug, Deserialize, Clone)]
struct SupportEntry {
    crate_family: String,
    decision: String,
    semantics_state: String,
    supported_targets: Vec<String>,
}

fn decision_variant(label: &str) -> &'static str {
    match label {
        "first_class" => "FirstClassWrapper",
        "internal_runtime_only" => "InternalRuntimeOnly",
        "escape_hatch_only" => "EscapeHatchOnly",
        "deferred" => "Deferred",
        other => panic!("unknown decision label in rust ecosystem registry: {other}"),
    }
}

fn semantics_variant(label: &str) -> &'static str {
    match label {
        "implemented" => "Implemented",
        "partially_implemented" => "PartiallyImplemented",
        "planned" => "Planned",
        "docs_only" => "DocsOnly",
        other => panic!("unknown semantics_state label in rust ecosystem registry: {other}"),
    }
}

fn target_variant(label: &str) -> &'static str {
    match label {
        "native" => "Native",
        "wasi" => "Wasi",
        "container" => "Container",
        other => panic!("unknown supported_target label in rust ecosystem registry: {other}"),
    }
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("vox-compiler must be at crates/vox-compiler");
    let registry_path = workspace_root.join("contracts/rust/ecosystem-support.yaml");
    println!("cargo:rerun-if-changed={}", registry_path.display());

    let raw = fs::read_to_string(&registry_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", registry_path.display()));
    let parsed: SupportRegistry = serde_yaml::from_str(&raw)
        .unwrap_or_else(|e| panic!("parse {}: {e}", registry_path.display()));

    let mut crates = BTreeMap::<String, SupportEntry>::new();
    for entry in &parsed.support_entries {
        for crate_name in entry.crate_family.split('+').map(str::trim) {
            if crate_name.is_empty() {
                panic!("empty crate name in crate_family '{}'", entry.crate_family);
            }
            if let Some(prev) = crates.get(crate_name) {
                if prev.decision != entry.decision
                    || prev.semantics_state != entry.semantics_state
                    || prev.supported_targets != entry.supported_targets
                {
                    panic!(
                        "conflicting policy rows for crate '{crate_name}' across crate_family entries"
                    );
                }
            } else {
                crates.insert(crate_name.to_string(), entry.clone());
            }
        }
    }

    let mut out = String::new();
    out.push_str(
        "// @generated by vox-compiler/build.rs from contracts/rust/ecosystem-support.yaml\n",
    );
    out.push_str("// Do not edit manually.\n\n");
    let app = parsed
        .template_managed_dependencies
        .app
        .iter()
        .map(|d| format!("\"{d}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let script_native = parsed
        .template_managed_dependencies
        .script_native
        .iter()
        .map(|d| format!("\"{d}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let script_wasi = parsed
        .template_managed_dependencies
        .script_wasi
        .iter()
        .map(|d| format!("\"{d}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let wasi_unsupported = parsed
        .wasi_unsupported_rust_imports
        .iter()
        .map(|d| format!("\"{d}\""))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "pub const GENERATED_TEMPLATE_MANAGED_APP_DEPS: &[&str] = &[{app}];\n"
    ));
    out.push_str(&format!(
        "pub const GENERATED_TEMPLATE_MANAGED_SCRIPT_NATIVE_DEPS: &[&str] = &[{script_native}];\n"
    ));
    out.push_str(&format!(
        "pub const GENERATED_TEMPLATE_MANAGED_SCRIPT_WASI_DEPS: &[&str] = &[{script_wasi}];\n\n"
    ));
    out.push_str(&format!(
        "pub const GENERATED_WASI_UNSUPPORTED_RUST_IMPORTS: &[&str] = &[{wasi_unsupported}];\n\n"
    ));
    out.push_str("pub const GENERATED_RUST_INTEROP_POLICY: &[RustInteropPolicyEntry] = &[\n");

    for (crate_name, entry) in &crates {
        let decision = decision_variant(&entry.decision);
        let semantics = semantics_variant(&entry.semantics_state);
        let targets = entry
            .supported_targets
            .iter()
            .map(|t| format!("RustInteropTarget::{}", target_variant(t)))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "    RustInteropPolicyEntry {{ crate_name: \"{crate_name}\", support_class: RustInteropSupportClass::{decision}, semantics_state: RustInteropSemanticsState::{semantics}, supported_targets: &[{targets}] }},\n"
        ));
    }

    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("rust_interop_policy.rs"), out).expect("write rust_interop_policy.rs");
}
