use vox_plugin_catalog::docs::{render_bundles_md, render_catalog_md};

#[test]
fn catalog_md_lists_every_plugin_and_includes_payload_kind() {
    let md = render_catalog_md();
    for plugin in vox_plugin_catalog::all_plugins() {
        assert!(
            md.contains(&plugin.id),
            "catalog md missing plugin: {}",
            plugin.id
        );
    }
    assert!(md.contains("payload-kind"));
    assert!(md.contains("default-source"));
}

#[test]
fn bundles_md_lists_every_bundle_and_resolved_plugin_count() {
    let md = render_bundles_md();
    for bundle in vox_plugin_catalog::all_bundles() {
        assert!(
            md.contains(&bundle.id),
            "bundles md missing bundle: {}",
            bundle.id
        );
    }
    assert!(
        md.contains("plugins"),
        "bundles md should mention plugin counts"
    );
}

#[test]
fn generated_md_starts_with_frontmatter_then_do_not_edit_marker() {
    let cat = render_catalog_md();
    let bun = render_bundles_md();
    assert!(cat.starts_with("---\n"), "catalog md missing frontmatter");
    assert!(bun.starts_with("---\n"), "bundles md missing frontmatter");
    let marker = "<!-- AUTOGENERATED";
    assert!(cat.contains(marker), "catalog md missing autogen marker");
    assert!(bun.contains(marker), "bundles md missing autogen marker");
}
