//! Emit `TOOL_REGISTRY` from `contracts/mcp/tool-registry.canonical.yaml`.

use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Root {
    #[allow(dead_code)]
    version: u32,
    tools: Vec<ToolEntry>,
}

#[derive(Debug, Deserialize)]
struct ToolEntry {
    name: String,
    description: String,
}

fn escape_rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("vox-mcp-registry must live at crates/vox-mcp-registry");
    let yaml_path = workspace_root.join("contracts/mcp/tool-registry.canonical.yaml");
    println!("cargo:rerun-if-changed={}", yaml_path.display());

    let raw = fs::read_to_string(&yaml_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", yaml_path.display()));
    let root: Root =
        serde_yaml::from_str(&raw).unwrap_or_else(|e| panic!("parse {}: {e}", yaml_path.display()));

    let mut names = std::collections::HashSet::<&str>::new();
    for t in &root.tools {
        if !names.insert(t.name.as_str()) {
            panic!("duplicate tool name in MCP registry: {}", t.name);
        }
    }

    let mut lines = String::new();
    lines.push_str("// @generated by vox-mcp-registry/build.rs — do not edit.\n\n");
    lines.push_str("pub const TOOL_REGISTRY: &[(&str, &str)] = &[\n");
    for t in &root.tools {
        let en = escape_rust_string(&t.name);
        let ed = escape_rust_string(&t.description);
        lines.push_str(&format!("    (\"{en}\", \"{ed}\"),\n"));
    }
    lines.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("tool_registry.rs"), lines).expect("write tool_registry.rs");
}
