//! Pretty-print a `WorkerDonationPolicy` as a canonical `donations.vox` source string.

use vox_mesh_types::donation_policy::WorkerDonationPolicy;

/// Render a `WorkerDonationPolicy` as canonical `donations.vox` source.
///
/// The output is deterministic: slots are ordered as given, booleans
/// use lowercase literals, comments are placed at the top.
/// Trailing comments from the original source are not preserved
/// (this is a known limitation; a full AST round-trip is a future task).
pub fn pretty_print(policy: &WorkerDonationPolicy) -> String {
    let mut out = String::new();
    out.push_str("// donations.vox — generated by vox-mesh-policy\n");
    out.push_str("// Edit via the dashboard donations editor or by hand.\n\n");

    for slot in &policy.slots {
        out.push_str(&format!(
            "slot {} {{ max_concurrent = {}, weight_pct = {} }}\n",
            slot.task_kind.as_str(),
            slot.max_concurrent,
            slot.weight_pct
        ));
    }
    if !policy.slots.is_empty() {
        out.push('\n');
    }

    out.push_str(&format!("let nsfw_allowed = {}\n", policy.nsfw_allowed));
    out.push_str(&format!(
        "let max_job_duration_secs = {}\n",
        policy.max_job_duration_secs
    ));
    out.push_str(&format!(
        "let public_mesh_opt_in = {}\n",
        policy.public_mesh_opt_in
    ));
    out.push_str(&format!("let min_priority = {}\n", policy.min_priority));
    out.push_str(&format!(
        "let accept_sensitive_workloads = {}\n",
        policy.accept_sensitive_workloads
    ));
    out.push_str(&format!(
        "let accepts_inference_workloads = {}\n",
        policy.accepts_inference_workloads
    ));
    out.push_str(&format!(
        "let accepts_training_workloads = {}\n",
        policy.accepts_training_workloads
    ));
    out.push_str(&format!("let cuda_tier = {}\n", policy.cuda_tier));
    out.push_str(&format!("let metal_tier = {}\n", policy.metal_tier));
    out.push_str(&format!("let vram_min_gb = {}\n", policy.vram_min_gb));
    out.push_str(&format!(
        "let accepts_sensitive_training_data = {}\n",
        policy.accepts_sensitive_training_data
    ));

    if let Some(ref scopes) = policy.allowed_scopes {
        let list = scopes
            .iter()
            .map(|s| format!("\"{}\"", s))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("let allowed_scopes = [{}]\n", list));
    }
    if let Some(ref users) = policy.allowed_users {
        let list = users
            .iter()
            .map(|s| format!("\"{}\"", s))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("let allowed_users = [{}]\n", list));
    }
    if let Some(ref denied) = policy.denied_users {
        let list = denied
            .iter()
            .map(|s| format!("\"{}\"", s))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("let denied_users = [{}]\n", list));
    }
    if let Some(ref nets) = policy.allowed_mesh_networks {
        let list = nets
            .iter()
            .map(|s| format!("\"{}\"", s))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("let allowed_mesh_networks = [{}]\n", list));
    }

    out
}
