/// Entry in the static reward definition pool.
#[derive(Debug, Clone)]
pub(super) struct RewardDef {
    pub(super) id: &'static str,
    pub(super) name: &'static str,
    pub(super) description: &'static str,
    pub(super) icon: &'static str,
    pub(super) xp_bonus: u64,
    pub(super) crystal_bonus: u64,
}

/// The 30-item pool of unique reward definitions, in rotation order.
pub(super) static REWARD_POOL: &[RewardDef] = &[
    RewardDef {
        id: "pax_romana",
        name: "Pax Romana",
        icon: "🕊️",
        xp_bonus: 200,
        crystal_bonus: 40,
        description: "Awarded for logging in 3 days this week.",
    },
    RewardDef {
        id: "triumph",
        name: "Triumph!",
        icon: "🏛️",
        xp_bonus: 500,
        crystal_bonus: 100,
        description: "Awarded for 5 green builds this week.",
    },
    RewardDef {
        id: "golden_laurel",
        name: "Golden Laurel",
        icon: "🌿",
        xp_bonus: 300,
        crystal_bonus: 0,
        description: "Awarded for maintaining a 7-day build streak.",
    },
    RewardDef {
        id: "vox_mens_week",
        name: "Vox Mens",
        icon: "📢",
        xp_bonus: 400,
        crystal_bonus: 80,
        description: "Awarded for giving 10 AI feedback events this week.",
    },
    RewardDef {
        id: "scribe_bonus",
        name: "Scribe Bonus",
        icon: "📜",
        xp_bonus: 250,
        crystal_bonus: 0,
        description: "Awarded for adding 20 doc items this week.",
    },
    RewardDef {
        id: "new_world",
        name: "The New World",
        icon: "🗺️",
        xp_bonus: 350,
        crystal_bonus: 70,
        description: "Awarded for first use of 3 different Vox features.",
    },
    RewardDef {
        id: "corpus_gold",
        name: "Corpus Gold",
        icon: "🧠",
        xp_bonus: 600,
        crystal_bonus: 120,
        description: "Awarded for promoting an example to examples/canonical/.",
    },
    RewardDef {
        id: "gladiator_week",
        name: "Gladiator Week",
        icon: "⚔️",
        xp_bonus: 400,
        crystal_bonus: 0,
        description: "Awarded for winning 5 bug battles this week.",
    },
    RewardDef {
        id: "iron_codex",
        name: "Iron Codex",
        icon: "📚",
        xp_bonus: 450,
        crystal_bonus: 0,
        description: "Awarded for 0 missing_docs warnings 3 days in a row.",
    },
    RewardDef {
        id: "marketplace_bonus",
        name: "Marketplace Bonus",
        icon: "🏪",
        xp_bonus: 0,
        crystal_bonus: 200,
        description: "Awarded for buying any shop item this week.",
    },
    RewardDef {
        id: "master_builder",
        name: "Master Builder",
        icon: "🏗️",
        xp_bonus: 500,
        crystal_bonus: 0,
        description: "Awarded for 20 successful builds this week.",
    },
    RewardDef {
        id: "caesars_coin",
        name: "Caesar's Coin",
        icon: "🪙",
        xp_bonus: 0,
        crystal_bonus: 500,
        description: "Awarded for maintaining a 30-day streak this week.",
    },
    RewardDef {
        id: "legion_bonus",
        name: "Legion Bonus",
        icon: "🦅",
        xp_bonus: 300,
        crystal_bonus: 60,
        description: "Awarded for 3 successful agent handoffs this week.",
    },
    RewardDef {
        id: "perfect_run",
        name: "Perfect Run",
        icon: "✨",
        xp_bonus: 800,
        crystal_bonus: 0,
        description: "Awarded for a day with: green build + tests pass + 0 warnings.",
    },
    RewardDef {
        id: "forum_speaker",
        name: "Forum Speaker",
        icon: "🎙️",
        xp_bonus: 200,
        crystal_bonus: 0,
        description: "Awarded for submitting 5 AI responses with comments.",
    },
    RewardDef {
        id: "architects_gift",
        name: "Architect's Gift",
        icon: "🏛️",
        xp_bonus: 250,
        crystal_bonus: 50,
        description: "Awarded for fixing a TOESTUB violation.",
    },
    RewardDef {
        id: "random_serendipity",
        name: "Serendipity",
        icon: "🎲",
        xp_bonus: 150,
        crystal_bonus: 30,
        description: "A lucky drop on any green build (1-in-50 chance).",
    },
    RewardDef {
        id: "early_bird",
        name: "Early Bird",
        icon: "🐦",
        xp_bonus: 150,
        crystal_bonus: 0,
        description: "Awarded for completing a build before 8am local time.",
    },
    RewardDef {
        id: "night_owl",
        name: "Night Owl",
        icon: "🦉",
        xp_bonus: 150,
        crystal_bonus: 0,
        description: "Awarded for completing a build after 10pm local time.",
    },
    RewardDef {
        id: "weekend_warrior",
        name: "Weekend Warrior",
        icon: "🏕️",
        xp_bonus: 200,
        crystal_bonus: 0,
        description: "Awarded for a green build on Saturday or Sunday.",
    },
    RewardDef {
        id: "thousand_tokens",
        name: "Thousand Tokens",
        icon: "💬",
        xp_bonus: 100,
        crystal_bonus: 0,
        description: "Awarded for an AI session generating 1,000+ tokens.",
    },
    RewardDef {
        id: "ten_k_tokens",
        name: "Ten Thousand Tokens",
        icon: "💎",
        xp_bonus: 300,
        crystal_bonus: 60,
        description: "Awarded for an AI session generating 10,000+ tokens.",
    },
    RewardDef {
        id: "first_million",
        name: "Million Token March",
        icon: "🚀",
        xp_bonus: 2_000,
        crystal_bonus: 400,
        description: "Awarded for generating 1M tokens lifetime.",
    },
    RewardDef {
        id: "daily_check_in",
        name: "Daily Check-In",
        icon: "☀️",
        xp_bonus: 50,
        crystal_bonus: 0,
        description: "Awarded for activity every day this week.",
    },
    RewardDef {
        id: "quest_master",
        name: "Quest Master",
        icon: "📋",
        xp_bonus: 300,
        crystal_bonus: 0,
        description: "Awarded for completing all 3 daily quests in one day.",
    },
    RewardDef {
        id: "double_quest_master",
        name: "Double Quest Master",
        icon: "📋",
        xp_bonus: 600,
        crystal_bonus: 0,
        description: "Awarded for completing all 3 quests 2 days in a row.",
    },
    RewardDef {
        id: "perfect_week",
        name: "Perfect Week",
        icon: "🏆",
        xp_bonus: 1_500,
        crystal_bonus: 300,
        description: "Awarded for completing all daily quests every day this week.",
    },
    RewardDef {
        id: "open_source_spirit",
        name: "Open Source Spirit",
        icon: "🌐",
        xp_bonus: 500,
        crystal_bonus: 0,
        description: "Awarded for contributing a research doc + example on the same day.",
    },
    RewardDef {
        id: "season_of_code",
        name: "Season of Code",
        icon: "🌸",
        xp_bonus: 1_000,
        crystal_bonus: 200,
        description: "Special seasonal reward — available once per quarter.",
    },
    RewardDef {
        id: "senatus_populusque",
        name: "SPQR",
        icon: "🏛️",
        xp_bonus: 750,
        crystal_bonus: 150,
        description: "Awarded for shipping a feature used by 3+ other contributors this week.",
    },
];
