//! Documentation linter for `docs/src/`. Checks frontmatter, code fences,
//! training rationale, and embedded Vox doctests.
//!
//! ## Modes
//!
//! - Default / `--lint-only`: lint all markdown in `docs/src/`. Exits non-zero on hard errors.
//! - `--fix`: auto-correct `status: draft` → `status: roadmap` before linting.
//! - `--paths <p1,p2,...>`: lint a subset of `docs/src/` paths for faster iteration.
//! - `--mode corpus`: emit `docs/src/corpus.jsonl` for training data export.
//!
//! SUMMARY.md and feed.xml are no longer generated by this crate. The Starlight
//! site generates the sidebar from frontmatter and RSS at Astro build time.

fn main() {
    vox_doc_pipeline::pipeline::run();
}
