use crate::achievement::{Achievement, AchievementCategory, AchievementId};

pub(super) fn part_b() -> Vec<Achievement> {
    vec![
        // ── Build Mastery ─────────────────────────────────────
        Achievement {
            id: AchievementId("first_green_build".into()),
            name: "First Light".into(),
            description: "First successful cargo build".into(),
            icon: "🏗️".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 50,
            crystal_reward: 10,
        },
        Achievement {
            id: AchievementId("build_streak_3".into()),
            name: "Triple Green".into(),
            description: "3 consecutive green builds".into(),
            icon: "🟢".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 150,
            crystal_reward: 30,
        },
        Achievement {
            id: AchievementId("build_streak_10".into()),
            name: "Unbroken Legion".into(),
            description: "10 consecutive green builds".into(),
            icon: "✅".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 400,
            crystal_reward: 80,
        },
        Achievement {
            id: AchievementId("build_streak_30".into()),
            name: "Iron Discipline".into(),
            description: "30 consecutive green builds".into(),
            icon: "💪".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 1_200,
            crystal_reward: 250,
        },
        Achievement {
            id: AchievementId("first_fix".into()),
            name: "Repaired in Battle".into(),
            description: "Fix a failing build in the same session it broke".into(),
            icon: "🔧".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 75,
            crystal_reward: 15,
        },
        Achievement {
            id: AchievementId("zero_warnings".into()),
            name: "Immaculate Code".into(),
            description: "cargo check with 0 warnings on first attempt".into(),
            icon: "🌟".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 200,
            crystal_reward: 40,
        },
        Achievement {
            id: AchievementId("toestub_clean_crate".into()),
            name: "Architectural Purity".into(),
            description: "0 TOESTUB violations in a crate".into(),
            icon: "🏛️".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 300,
            crystal_reward: 60,
        },
        Achievement {
            id: AchievementId("toestub_clean_workspace".into()),
            name: "Perfect Forum".into(),
            description: "0 TOESTUB violations across the entire workspace".into(),
            icon: "🏟️".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 2_000,
            crystal_reward: 400,
        },
        // ── Documentation ─────────────────────────────────────
        Achievement {
            id: AchievementId("first_doc".into()),
            name: "Pen to Scroll".into(),
            description: "Add your first /// doc comment to a public item".into(),
            icon: "✏️".into(),
            category: AchievementCategory::Documentation,
            xp_reward: 25,
            crystal_reward: 5,
        },
        Achievement {
            id: AchievementId("fifty_docs".into()),
            name: "Diligent Librarian".into(),
            description: "Add 50 doc comments".into(),
            icon: "📖".into(),
            category: AchievementCategory::Documentation,
            xp_reward: 200,
            crystal_reward: 40,
        },
        Achievement {
            id: AchievementId("five_hundred_docs".into()),
            name: "Grand Archivist".into(),
            description: "Add 500 doc comments".into(),
            icon: "📚".into(),
            category: AchievementCategory::Documentation,
            xp_reward: 800,
            crystal_reward: 160,
        },
        Achievement {
            id: AchievementId("crate_doc_clean".into()),
            name: "Crate Complete".into(),
            description: "Achieve 0 missing_docs warnings in a crate".into(),
            icon: "📗".into(),
            category: AchievementCategory::Documentation,
            xp_reward: 300,
            crystal_reward: 60,
        },
        Achievement {
            id: AchievementId("workspace_doc_clean".into()),
            name: "Omnia Scripta Sunt".into(),
            description: "0 missing_docs warnings across the entire workspace".into(),
            icon: "📕".into(),
            category: AchievementCategory::Documentation,
            xp_reward: 3_000,
            crystal_reward: 600,
        },
        Achievement {
            id: AchievementId("research_doc_written".into()),
            name: "Historian".into(),
            description: "Write a research document in docs/src/research/".into(),
            icon: "🔭".into(),
            category: AchievementCategory::Documentation,
            xp_reward: 200,
            crystal_reward: 40,
        },
        Achievement {
            id: AchievementId("adr_written".into()),
            name: "Architect's Decision".into(),
            description: "Write an Architecture Decision Record (ADR)".into(),
            icon: "📐".into(),
            category: AchievementCategory::Documentation,
            xp_reward: 300,
            crystal_reward: 60,
        },
    ]
}
