use crate::achievement::{Achievement, AchievementCategory, AchievementId};

pub(super) fn part_a() -> Vec<Achievement> {
    vec![
        // ── Tasks ─────────────────────────────────────────────
        Achievement {
            id: AchievementId("first_task".into()),
            name: "Hello World".into(),
            description: "Complete your first task".into(),
            icon: "🎯".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 50,
            crystal_reward: 10,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("five_tasks".into()),
            name: "Getting Started".into(),
            description: "Complete 5 tasks".into(),
            icon: "⭐".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 100,
            crystal_reward: 25,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("twenty_five_tasks".into()),
            name: "Workhorse".into(),
            description: "Complete 25 tasks".into(),
            icon: "🏆".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 500,
            crystal_reward: 100,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("hundred_tasks".into()),
            name: "Centurion's Burden".into(),
            description: "Complete 100 tasks".into(),
            icon: "🦅".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 1_500,
            crystal_reward: 300,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("five_hundred_tasks".into()),
            name: "Legion Commander".into(),
            description: "Complete 500 tasks".into(),
            icon: "👑".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 5_000,
            crystal_reward: 1_000,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("task_in_a_day".into()),
            name: "Dawn to Dusk".into(),
            description: "Complete 10 tasks in a single calendar day".into(),
            icon: "☀️".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 200,
            crystal_reward: 50,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_task_queued".into()),
            name: "In the Queue".into(),
            description: "Submit your first task to the orchestrator queue".into(),
            icon: "🧾".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 40,
            crystal_reward: 8,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("steady_queue".into()),
            name: "Flow State".into(),
            description: "Submit 25 tasks across your sessions".into(),
            icon: "🌊".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 250,
            crystal_reward: 40,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_checkpoint".into()),
            name: "Snapshot Scout".into(),
            description: "Capture your first workspace snapshot".into(),
            icon: "📸".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 60,
            crystal_reward: 12,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("checkpoint_habit".into()),
            name: "Historian".into(),
            description: "Capture 50 workspace snapshots".into(),
            icon: "📚".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 400,
            crystal_reward: 70,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_wave".into()),
            name: "Ping".into(),
            description: "Send your first inter-agent message on the bus".into(),
            icon: "📡".into(),
            category: AchievementCategory::Collaboration,
            xp_reward: 35,
            crystal_reward: 7,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("signal_traffic".into()),
            name: "Switchboard".into(),
            description: "Send 100 inter-agent messages".into(),
            icon: "🛰️".into(),
            category: AchievementCategory::Collaboration,
            xp_reward: 500,
            crystal_reward: 90,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_exclusive_lock".into()),
            name: "Claimed".into(),
            description: "Acquire your first exclusive workspace lock".into(),
            icon: "🔒".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 30,
            crystal_reward: 5,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("locksmith".into()),
            name: "Locksmith".into(),
            description: "Acquire 200 workspace locks (coordination practice)".into(),
            icon: "🗝️".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 450,
            crystal_reward: 75,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        // ── Collaboration ─────────────────────────────────────
        Achievement {
            id: AchievementId("first_handoff".into()),
            name: "Team Player".into(),
            description: "Successfully hand off a plan to another agent".into(),
            icon: "🤝".into(),
            category: AchievementCategory::Collaboration,
            xp_reward: 75,
            crystal_reward: 15,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("ten_handoffs".into()),
            name: "Legatus".into(),
            description: "Complete 10 agent handoffs".into(),
            icon: "📋".into(),
            category: AchievementCategory::Collaboration,
            xp_reward: 400,
            crystal_reward: 80,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("fifty_handoffs".into()),
            name: "Grand Coordinator".into(),
            description: "Complete 50 agent handoffs".into(),
            icon: "🌐".into(),
            category: AchievementCategory::Collaboration,
            xp_reward: 1_500,
            crystal_reward: 300,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("conflict_resolver".into()),
            name: "Peacemaker".into(),
            description: "Resolve a VCS conflict".into(),
            icon: "🕊️".into(),
            category: AchievementCategory::Collaboration,
            xp_reward: 100,
            crystal_reward: 20,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        // ── Streaks ───────────────────────────────────────────
        Achievement {
            id: AchievementId("streak_3".into()),
            name: "Three-Day Tribune".into(),
            description: "Maintain a 3-day activity streak".into(),
            icon: "🔥".into(),
            category: AchievementCategory::Streaks,
            xp_reward: 80,
            crystal_reward: 16,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("streak_7".into()),
            name: "Week Warrior".into(),
            description: "Maintain a 7-day activity streak".into(),
            icon: "🔥".into(),
            category: AchievementCategory::Streaks,
            xp_reward: 300,
            crystal_reward: 75,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("streak_14".into()),
            name: "Fortnight Forger".into(),
            description: "Maintain a 14-day activity streak".into(),
            icon: "🌙".into(),
            category: AchievementCategory::Streaks,
            xp_reward: 700,
            crystal_reward: 140,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("streak_30".into()),
            name: "Month Master".into(),
            description: "Maintain a 30-day activity streak".into(),
            icon: "🌕".into(),
            category: AchievementCategory::Streaks,
            xp_reward: 1_000,
            crystal_reward: 250,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("streak_90".into()),
            name: "Quarter Champion".into(),
            description: "Maintain a 90-day activity streak".into(),
            icon: "💫".into(),
            category: AchievementCategory::Streaks,
            xp_reward: 3_000,
            crystal_reward: 600,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("streak_365".into()),
            name: "Eternal Consul".into(),
            description: "Maintain a 365-day activity streak".into(),
            icon: "⚡".into(),
            category: AchievementCategory::Streaks,
            xp_reward: 10_000,
            crystal_reward: 2_000,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("error_free_five".into()),
            name: "Flawless Five".into(),
            description: "Complete 5 tasks in a row without errors".into(),
            icon: "💎".into(),
            category: AchievementCategory::Streaks,
            xp_reward: 200,
            crystal_reward: 50,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        // ── Efficiency ────────────────────────────────────────
        Achievement {
            id: AchievementId("budget_saver".into()),
            name: "Budget Conscious".into(),
            description: "Complete 10 tasks under $0.01 total cost".into(),
            icon: "💰".into(),
            category: AchievementCategory::Efficiency,
            xp_reward: 150,
            crystal_reward: 30,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("speed_demon".into()),
            name: "Speed Demon".into(),
            description: "Complete a task in under 30 seconds".into(),
            icon: "⚡".into(),
            category: AchievementCategory::Efficiency,
            xp_reward: 100,
            crystal_reward: 20,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("ultra_speed".into()),
            name: "Lightning Bolt".into(),
            description: "Complete a task in under 10 seconds".into(),
            icon: "⚡⚡".into(),
            category: AchievementCategory::Efficiency,
            xp_reward: 250,
            crystal_reward: 50,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("zero_cost_session".into()),
            name: "Frugal Senator".into(),
            description: "Complete a full session with zero AI cost (local inference only)".into(),
            icon: "🪙".into(),
            category: AchievementCategory::Efficiency,
            xp_reward: 300,
            crystal_reward: 60,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("offline_session".into()),
            name: "Self Sufficient".into(),
            description: "Complete a full session using only Ollama or Deterministic providers"
                .into(),
            icon: "🏕️".into(),
            category: AchievementCategory::Efficiency,
            xp_reward: 300,
            crystal_reward: 75,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        // ── Discovery ─────────────────────────────────────────
        Achievement {
            id: AchievementId("first_continuation".into()),
            name: "Self Starter".into(),
            description: "Receive an auto-continuation prompt".into(),
            icon: "▶️".into(),
            category: AchievementCategory::Discovery,
            xp_reward: 25,
            crystal_reward: 5,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("challenge_solved".into()),
            name: "Challenger".into(),
            description: "Successfully solve a daily coding challenge".into(),
            icon: "🧩".into(),
            category: AchievementCategory::Discovery,
            xp_reward: 200,
            crystal_reward: 50,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_memory".into()),
            name: "Elephant Memory".into(),
            description: "Store your first long-term memory entry".into(),
            icon: "🧠".into(),
            category: AchievementCategory::Discovery,
            xp_reward: 25,
            crystal_reward: 5,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("polyglot".into()),
            name: "Polyglot Programmer".into(),
            description: "Work on files in 5 different programming languages".into(),
            icon: "🌍".into(),
            category: AchievementCategory::Discovery,
            xp_reward: 150,
            crystal_reward: 30,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("polyglot_10".into()),
            name: "Translator".into(),
            description: "Work on files in 10 different programming languages".into(),
            icon: "🌐".into(),
            category: AchievementCategory::Discovery,
            xp_reward: 500,
            crystal_reward: 100,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        // ── AI Corpus ─────────────────────────────────────────
        Achievement {
            id: AchievementId("first_thumbs".into()),
            name: "Voice of the People".into(),
            description: "Give your first AI response feedback".into(),
            icon: "👍".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 25,
            crystal_reward: 5,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("ten_thumbs".into()),
            name: "Trusted Critic".into(),
            description: "Give 10 AI response feedback events".into(),
            icon: "👍".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 100,
            crystal_reward: 20,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("hundred_thumbs".into()),
            name: "Corpus Senator".into(),
            description: "Give 100 AI response feedback events".into(),
            icon: "🏛️".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 500,
            crystal_reward: 100,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_thumbs_down".into()),
            name: "Sine Timore".into(),
            description: "Give your first negative AI feedback (zero fear!)".into(),
            icon: "👎".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 30,
            crystal_reward: 6,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("balanced_feedback".into()),
            name: "Just Magistrate".into(),
            description: "Give both positive and negative AI feedback".into(),
            icon: "⚖️".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 50,
            crystal_reward: 10,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_vox_example".into()),
            name: "The First Tablet".into(),
            description: "Write your first .vox example file".into(),
            icon: "📜".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 100,
            crystal_reward: 20,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("five_vox_examples".into()),
            name: "Scroll Keeper".into(),
            description: "Write 5 .vox example files".into(),
            icon: "📚".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 300,
            crystal_reward: 60,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("canonical_example".into()),
            name: "Codex Canonicus".into(),
            description: "Have an example promoted to examples/canonical/".into(),
            icon: "✨".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 500,
            crystal_reward: 100,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_corpus_contribution".into()),
            name: "Mens Patron".into(),
            description: "Contribute your first training data to the Mens corpus".into(),
            icon: "🧠".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 150,
            crystal_reward: 30,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("ten_corpus_contributions".into()),
            name: "Training Senator".into(),
            description: "Contribute 10 training examples to the Mens corpus".into(),
            icon: "🧬".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 600,
            crystal_reward: 120,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_finetune".into()),
            name: "Forged in Fire".into(),
            description: "Complete your first QLoRA fine-tuning epoch".into(),
            icon: "🔥".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 800,
            crystal_reward: 160,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("inference_regular".into()),
            name: "Vox Vulgaris".into(),
            description: "Run local Mens inference 50 times".into(),
            icon: "💬".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 200,
            crystal_reward: 40,
            icon_slug: "todo".to_string(),
            secret: false,
        },
    ]
}
