use crate::achievement::{Achievement, AchievementCategory, AchievementId};

pub(super) fn part_c() -> Vec<Achievement> {
    vec![
        // ── Language Explorer ─────────────────────────────────
        Achievement {
            id: AchievementId("first_vox_web_page".into()),
            name: "Web Legionary".into(),
            description: "Compile your first Vox web module with @page or client routes".into(),
            icon: "🌐".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 100,
            crystal_reward: 20,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_island".into()),
            name: "Island Founder".into(),
            description: "Mount and build your first @island".into(),
            icon: "🏝️".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 150,
            crystal_reward: 30,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_migration".into()),
            name: "Schema Consul".into(),
            description: "Apply your first @migration to a live database".into(),
            icon: "📦".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 150,
            crystal_reward: 30,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_seed".into()),
            name: "Sower of Data".into(),
            description: "Run your first @seed function to completion".into(),
            icon: "🌱".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 50,
            crystal_reward: 10,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_workflow".into()),
            name: "Workflow Praetor".into(),
            description: "Run a durable workflow to completion".into(),
            icon: "⚙️".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 200,
            crystal_reward: 40,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_actor".into()),
            name: "Actor Recruiter".into(),
            description: "Spawn your first actor".into(),
            icon: "🤖".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 100,
            crystal_reward: 20,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_mcp_tool".into()),
            name: "MCP Tribune".into(),
            description: "Register your first @mcp.tool via the capability registry".into(),
            icon: "🔌".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 200,
            crystal_reward: 40,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_openapi".into()),
            name: "OpenAPI Consul".into(),
            description: "Generate your first OpenAPI spec for a handler".into(),
            icon: "📄".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 150,
            crystal_reward: 30,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("five_islands".into()),
            name: "Island Archipelago".into(),
            description: "Build and mount 5 islands".into(),
            icon: "🏝️".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 400,
            crystal_reward: 80,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_pkg_publish".into()),
            name: "Market Publisher".into(),
            description: "Publish your first package to VoxPM".into(),
            icon: "🏪".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 300,
            crystal_reward: 60,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        // ── Security ──────────────────────────────────────────
        Achievement {
            id: AchievementId("first_security_pass".into()),
            name: "Shield Bearer".into(),
            description: "Pass your first security review".into(),
            icon: "🛡️".into(),
            category: AchievementCategory::Security,
            xp_reward: 150,
            crystal_reward: 30,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("no_null_violations".into()),
            name: "Null Purger".into(),
            description: "Pass a codebase scan with 0 null-state violations".into(),
            icon: "🚫".into(),
            category: AchievementCategory::Security,
            xp_reward: 500,
            crystal_reward: 100,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("perf_regression_caught".into()),
            name: "Vigilant Sentinel".into(),
            description: "Catch a performance regression before it merges".into(),
            icon: "⚡".into(),
            category: AchievementCategory::Security,
            xp_reward: 200,
            crystal_reward: 40,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        // ── Daily Quest Milestones ─────────────────────────────
        Achievement {
            id: AchievementId("first_daily_quest".into()),
            name: "Daily Orders Received".into(),
            description: "Complete your first daily quest".into(),
            icon: "📋".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 75,
            crystal_reward: 15,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("daily_quest_streak_3".into()),
            name: "Three-Day Tribune".into(),
            description: "Complete at least one daily quest every day for 3 days".into(),
            icon: "📆".into(),
            category: AchievementCategory::Streaks,
            xp_reward: 200,
            crystal_reward: 40,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("daily_quest_streak_7".into()),
            name: "Week of the Legion".into(),
            description: "Complete daily quests every day for a full week".into(),
            icon: "🗓️".into(),
            category: AchievementCategory::Streaks,
            xp_reward: 600,
            crystal_reward: 100,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("daily_quest_streak_30".into()),
            name: "Month of the Imperium".into(),
            description: "Complete daily quests every day for 30 consecutive days".into(),
            icon: "🗓️".into(),
            category: AchievementCategory::Streaks,
            xp_reward: 3_000,
            crystal_reward: 500,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("perfect_daily_3".into()),
            name: "Triumphal March".into(),
            description: "Complete all 3 daily quests in a single day".into(),
            icon: "🏛️".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 350,
            crystal_reward: 70,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("perfect_week".into()),
            name: "Fortis et Constans".into(),
            description: "Complete all 3 daily quests every day for a full week".into(),
            icon: "🏆".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 2_500,
            crystal_reward: 400,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("legendary_quest_complete".into()),
            name: "Fato Prudentia".into(),
            description: "Complete a Legendary-modifier quest".into(),
            icon: "⭐".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 1_000,
            crystal_reward: 200,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("chains_quest_complete".into()),
            name: "Chain of Command".into(),
            description: "Complete a Chains-modifier quest and its follow-up".into(),
            icon: "🔗".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 500,
            crystal_reward: 80,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        // ── Level & Prestige Milestones ────────────────────────
        Achievement {
            id: AchievementId("reach_level_10".into()),
            name: "Decanus Rising".into(),
            description: "Reach Level 10".into(),
            icon: "🔟".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 100,
            crystal_reward: 20,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("reach_level_25".into()),
            name: "Optio Ascendant".into(),
            description: "Reach Level 25".into(),
            icon: "⚔️".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 300,
            crystal_reward: 60,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("reach_level_50".into()),
            name: "Signifer's Standard".into(),
            description: "Reach Level 50".into(),
            icon: "🏳️".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 700,
            crystal_reward: 120,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("reach_level_100".into()),
            name: "Centurion's Crown".into(),
            description: "Reach Level 100".into(),
            icon: "🦅".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 2_000,
            crystal_reward: 350,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("reach_level_200".into()),
            name: "Legatus Legionis".into(),
            description: "Reach Level 200 — eligible to prestige".into(),
            icon: "👑".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 5_000,
            crystal_reward: 800,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("reach_level_500".into()),
            name: "Consul of the Code".into(),
            description: "Reach Level 500".into(),
            icon: "🏟️".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 15_000,
            crystal_reward: 2_500,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("reach_level_1000".into()),
            name: "Imperator Eternus".into(),
            description: "Reach Level 1000".into(),
            icon: "💫".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 50_000,
            crystal_reward: 8_000,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_prestige".into()),
            name: "Vindex Coronatus".into(),
            description: "Prestige for the first time by reaching Level 200".into(),
            icon: "🌟".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 8_000,
            crystal_reward: 1_200,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("prestige_5".into()),
            name: "Quinquennium".into(),
            description: "Prestige 5 times".into(),
            icon: "💎".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 25_000,
            crystal_reward: 5_000,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("prestige_10".into()),
            name: "Divus Perpetuus".into(),
            description: "Prestige 10 times — achieved true immortality".into(),
            icon: "✨".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 100_000,
            crystal_reward: 20_000,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        // ── First-Time Actions ─────────────────────────────────
        Achievement {
            id: AchievementId("first_toestub_fix".into()),
            name: "Architectus Purus".into(),
            description: "Fix your first TOESTUB architecture violation".into(),
            icon: "🏛️".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 80,
            crystal_reward: 16,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_test_written".into()),
            name: "Primus Testis".into(),
            description: "Write your very first unit test".into(),
            icon: "🧪".into(),
            category: AchievementCategory::BuildMastery,
            xp_reward: 50,
            crystal_reward: 10,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_research_ingest".into()),
            name: "Explorator".into(),
            description: "Ingest your first URL into the Codex research collection".into(),
            icon: "🔭".into(),
            category: AchievementCategory::Documentation,
            xp_reward: 30,
            crystal_reward: 6,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_adr".into()),
            name: "Architect's Decision".into(),
            description: "Write your first Architecture Decision Record".into(),
            icon: "📐".into(),
            category: AchievementCategory::Documentation,
            xp_reward: 300,
            crystal_reward: 60,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_bug_battle".into()),
            name: "Prima Pugna".into(),
            description: "Enter your first bug battle".into(),
            icon: "⚔️".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 30,
            crystal_reward: 8,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_battle_won".into()),
            name: "Victor!".into(),
            description: "Win your first bug battle".into(),
            icon: "🏆".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 75,
            crystal_reward: 18,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_corpus_rating".into()),
            name: "Iudex Mens".into(),
            description: "Rate your first training pair in the corpus".into(),
            icon: "⚖️".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 25,
            crystal_reward: 5,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_handoff_received".into()),
            name: "Messenger Received".into(),
            description: "Receive your first agent handoff from a peer".into(),
            icon: "📨".into(),
            category: AchievementCategory::Collaboration,
            xp_reward: 40,
            crystal_reward: 10,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_peer_teach".into()),
            name: "Magister".into(),
            description: "Help a newer user resolve a Vox error and receive a 5-star rating".into(),
            icon: "🎓".into(),
            category: AchievementCategory::Collaboration,
            xp_reward: 150,
            crystal_reward: 30,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_unsafe_removed".into()),
            name: "Puritas Absoluta".into(),
            description: "Remove an `unsafe` block by replacing it with safe Rust".into(),
            icon: "🛡️".into(),
            category: AchievementCategory::Security,
            xp_reward: 200,
            crystal_reward: 40,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_v0_import".into()),
            name: "Island Trader".into(),
            description: "Import your first v0.dev component via `vox import-v0`".into(),
            icon: "🏝️".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 100,
            crystal_reward: 20,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_scheduled_job".into()),
            name: "Cron Consul".into(),
            description: "Register and run your first `@scheduled` job".into(),
            icon: "⏰".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 120,
            crystal_reward: 25,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_turso_query".into()),
            name: "Turso Tribune".into(),
            description: "Execute your first query against a Turso remote database".into(),
            icon: "🗄️".into(),
            category: AchievementCategory::LangExplorer,
            xp_reward: 100,
            crystal_reward: 20,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("first_populi_serve".into()),
            name: "Orator Mens".into(),
            description: "Serve a trained model locally via `vox mens serve`".into(),
            icon: "📡".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 500,
            crystal_reward: 100,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        // ── Social / Foundation ───────────────────────────────
        Achievement {
            id: AchievementId("ten_students_taught".into()),
            name: "Scholae Praepositus".into(),
            description: "Help 10 different users resolve Vox errors".into(),
            icon: "🎓".into(),
            category: AchievementCategory::Collaboration,
            xp_reward: 1_000,
            crystal_reward: 200,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("vox_foundation_contributor".into()),
            name: "Benefactor Publicus".into(),
            description: "Have a PR merged into a core Vox compiler crate".into(),
            icon: "🌐".into(),
            category: AchievementCategory::Collaboration,
            xp_reward: 5_000,
            crystal_reward: 800,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("million_lifetime_xp".into()),
            name: "Dives et Sapiens".into(),
            description: "Earn 1,000,000 total XP over your lifetime".into(),
            icon: "💰".into(),
            category: AchievementCategory::Tasks,
            xp_reward: 10_000,
            crystal_reward: 2_000,
            icon_slug: "todo".to_string(),
            secret: false,
        },
        Achievement {
            id: AchievementId("balanced_feedback_week".into()),
            name: "Iusta Statera".into(),
            description: "Give both positive and negative AI feedback in the same week".into(),
            icon: "⚖️".into(),
            category: AchievementCategory::AiCorpus,
            xp_reward: 80,
            crystal_reward: 20,
            icon_slug: "todo".to_string(),
            secret: false,
        },
    ]
}
