use crate::policy::SecretPolicy;
use crate::spec::ids::SecretId;
use crate::spec::types::*;

pub const SPECS_CONFIG: &[SecretSpec] = &[
    SecretSpec {
        id: SecretId::VoxOrchestratorEnabled,
        canonical_env: "VOX_ORCHESTRATOR_ENABLED",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable background orchestration in the current process (default: true).",
        scope_description: "Toggle for the core orchestrator engine.",
    },
    SecretSpec {
        id: SecretId::VoxOrchestratorLogLevel,
        canonical_env: "VOX_ORCHESTRATOR_LOG_LEVEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Internal tracing log level (info|debug|trace).",
        scope_description: "Verbosity control for orchestrator logs.",
    },
    SecretSpec {
        id: SecretId::VoxModel,
        canonical_env: "VOX_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Default model identifier.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxBudgetUsd,
        canonical_env: "VOX_BUDGET_USD",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Total budget in USD.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxDataDir,
        canonical_env: "VOX_DATA_DIR",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Data directory path.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxMcpBinary,
        canonical_env: "VOX_MCP_BINARY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Path to MCP binary.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxGamifyEnabled,
        canonical_env: "VOX_GAMIFY_ENABLED",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable gamification.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxGamifyMode,
        canonical_env: "VOX_GAMIFY_MODE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Gamification mode.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxWebRunMode,
        canonical_env: "VOX_WEB_RUN_MODE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Web server run mode.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxOrchestratorAttentionEnabled,
        canonical_env: "VOX_ORCHESTRATOR_ATTENTION_ENABLED",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable attention tracking.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxOrchestratorAttentionBudgetMs,
        canonical_env: "VOX_ORCHESTRATOR_ATTENTION_BUDGET_MS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Attention budget in MS.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxOrchestratorPlanningEnabled,
        canonical_env: "VOX_ORCHESTRATOR_PLANNING_ENABLED",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable autonomous planning.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxOrchestratorResearchModelEnabled,
        canonical_env: "VOX_ORCHESTRATOR_RESEARCH_MODEL_ENABLED",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable research model.",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxRepositoryRoot,
        canonical_env: "VOX_REPO_ROOT",
        aliases: &["VOX_REPOSITORY_ROOT"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_REPO_ROOT to the repository root directory.",
        scope_description: "Repository root path.",
    },
    SecretSpec {
        id: SecretId::VoxWorkspaceRoot,
        canonical_env: "VOX_WORKSPACE_ROOT",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_WORKSPACE_ROOT to the workspace root directory.",
        scope_description: "Workspace root path.",
    },
];
