use crate::policy::SecretPolicy;
use crate::spec::ids::SecretId;
use crate::spec::types::*;

pub const SPECS_LLM: &[SecretSpec] = &[
    SecretSpec {
        id: SecretId::GeminiApiKey,
        canonical_env: "GEMINI_API_KEY",
        aliases: &["VOX_GEMINI_API_KEY"],
        deprecated_aliases: &["GOOGLE_AI_STUDIO_KEY"],
        backend_key: None,
        auth_registry: Some("google"),
        policy: SecretPolicy::optional_skip(),
        remediation: "Run `vox secrets set google <token>` or set GEMINI_API_KEY. Required if VOX_GEMINI_ROUTE_POLICY=google_direct_only.",
        scope_description: "Google Gemini API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::GeminiDirectModel,
        canonical_env: "GEMINI_DIRECT_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Model ID for direct Google Gemini API calls.",
        scope_description: "Gemini direct model ID.",
    },
    SecretSpec {
        id: SecretId::OpenRouterGeminiModel,
        canonical_env: "OPENROUTER_GEMINI_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Model ID for Gemini via OpenRouter.",
        scope_description: "OpenRouter Gemini model ID.",
    },
    SecretSpec {
        id: SecretId::OpenRouterApiKey,
        canonical_env: "OPENROUTER_API_KEY",
        aliases: &["VOX_OPENROUTER_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: Some("openrouter"),
        policy: SecretPolicy::required_fail(),
        remediation: "Run `vox secrets set openrouter <token>` or set OPENROUTER_API_KEY.",
        scope_description: "OpenRouter API key for unified LLM access.",
    },
    SecretSpec {
        id: SecretId::OpenRouterModel,
        canonical_env: "OPENROUTER_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "OpenRouter model identifier (e.g. anthropic/claude-3.5-sonnet).",
        scope_description: "Default model identifier for OpenRouter.",
    },
    SecretSpec {
        id: SecretId::VoxOpenRouterChatModel,
        canonical_env: "OPENROUTER_CHAT_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Run `vox secrets set OPENROUTER_CHAT_MODEL <slug>` or set OPENROUTER_CHAT_MODEL when using PreferredModel strategy.",
        scope_description: "Preferred OpenRouter chat model (PreferredModel / CASCADE).",
    },
    SecretSpec {
        id: SecretId::VoxHfChatModel,
        canonical_env: "HF_CHAT_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Run `vox secrets set HF_CHAT_MODEL <org/model>` or set HF_CHAT_MODEL for Hugging Face router chat.",
        scope_description: "Hugging Face router chat model id.",
    },
    SecretSpec {
        id: SecretId::VoxHfDedicatedChatUrl,
        canonical_env: "HF_DEDICATED_CHAT_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set HF_DEDICATED_CHAT_URL via `vox secrets` for a dedicated HF endpoint.",
        scope_description: "Dedicated HF chat completions URL.",
    },
    SecretSpec {
        id: SecretId::VoxHfDedicatedChatModel,
        canonical_env: "HF_DEDICATED_CHAT_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set HF_DEDICATED_CHAT_MODEL via `vox secrets`.",
        scope_description: "Model id for dedicated HF deployment.",
    },
    SecretSpec {
        id: SecretId::VoxHfRouterChatCompletionsUrl,
        canonical_env: "VOX_HF_ROUTER_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override HF Inference Providers router URL (default https://router.huggingface.co/v1/chat/completions).",
        scope_description: "HF shared router chat completions URL.",
    },
    SecretSpec {
        id: SecretId::VoxAutoModelStrategy,
        canonical_env: "VOX_AUTO_MODEL_STRATEGY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VOX_AUTO_MODEL_STRATEGY to provider_auto or preferred_model via `vox secrets`.",
        scope_description: "OpenRouter auto vs preferred model strategy.",
    },
    SecretSpec {
        id: SecretId::VoxAutoRoutingPriority,
        canonical_env: "VOX_AUTO_ROUTING_PRIORITY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "CSV key=val weights for auto routing (efficiency, precision, latency, …).",
        scope_description: "Weighted auto-routing priorities.",
    },
    SecretSpec {
        id: SecretId::VoxGeminiRoutePolicy,
        canonical_env: "VOX_GEMINI_ROUTE_POLICY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "openrouter_first | google_direct_only | registry_default.",
        scope_description: "Gemini OpenRouter vs direct routing policy.",
    },
    SecretSpec {
        id: SecretId::VoxRoutingProfile,
        canonical_env: "VOX_ROUTING_PROFILE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "quality_first | cost_capped_quality | lowest_cost_sla (aligned with model-routing contract).",
        scope_description: "High-level routing profile / objective.",
    },
    SecretSpec {
        id: SecretId::VoxRoutingExplorationEpsilon,
        canonical_env: "VOX_ROUTING_EXPLORATION_EPSILON",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "0.0–1.0 exploration rate for model bandit (default from policy or 0.05).",
        scope_description: "Exploration epsilon for adaptive routing.",
    },
    SecretSpec {
        id: SecretId::VoxRoutingMaxSpendUsdPerSession,
        canonical_env: "VOX_ROUTING_MAX_SPEND_USD_PER_SESSION",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Cap USD spend per session for exploration (empty = no cap).",
        scope_description: "Session spend ceiling for routing.",
    },
    SecretSpec {
        id: SecretId::VoxRoutingProviderAllowlist,
        canonical_env: "VOX_ROUTING_PROVIDER_ALLOWLIST",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "CSV of allowed provider slugs (e.g. openrouter,google,anthropic).",
        scope_description: "Provider allow-list for routing.",
    },
    SecretSpec {
        id: SecretId::VoxRoutingProviderDenylist,
        canonical_env: "VOX_ROUTING_PROVIDER_DENYLIST",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "CSV of denied provider slugs.",
        scope_description: "Provider deny-list for routing.",
    },
    SecretSpec {
        id: SecretId::VoxCapabilityRequireImageGeneration,
        canonical_env: "VOX_CAPABILITY_REQUIRE_IMAGE_GENERATION",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "true | false — require models with image generation.",
        scope_description: "Hard-require image generation capability in routing.",
    },
    SecretSpec {
        id: SecretId::VoxCapabilityRequireToolUse,
        canonical_env: "VOX_CAPABILITY_REQUIRE_TOOL_USE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "true | false — require tool-capable models.",
        scope_description: "Hard-require tool use in routing.",
    },
    SecretSpec {
        id: SecretId::VoxCapabilityRequireReasoning,
        canonical_env: "VOX_CAPABILITY_REQUIRE_REASONING",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "true | false — require reasoning-capable models.",
        scope_description: "Hard-require reasoning in routing.",
    },
    SecretSpec {
        id: SecretId::VoxCapabilityRequireWebSearch,
        canonical_env: "VOX_CAPABILITY_REQUIRE_WEB_SEARCH",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "true | false — require web search capable models.",
        scope_description: "Hard-require web search in routing.",
    },
    SecretSpec {
        id: SecretId::VoxCapabilityPreferReasoning,
        canonical_env: "VOX_CAPABILITY_PREFER_REASONING",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "true | false — soft bonus for reasoning models when routing.",
        scope_description: "Prefer reasoning models (non-hard).",
    },
    SecretSpec {
        id: SecretId::VoxCapabilityImageGenerationModel,
        canonical_env: "VOX_CAPABILITY_IMAGE_GENERATION_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Pinned model id for image generation tasks.",
        scope_description: "Capability hard-pin: image generation model id.",
    },
    SecretSpec {
        id: SecretId::VoxCapabilityVisionModel,
        canonical_env: "VOX_CAPABILITY_VISION_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Pinned model id for vision / image understanding tasks.",
        scope_description: "Capability hard-pin: vision model id.",
    },
    SecretSpec {
        id: SecretId::VoxCapabilityCodeGenModel,
        canonical_env: "VOX_CAPABILITY_CODEGEN_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Pinned model id for codegen-heavy tasks.",
        scope_description: "Capability hard-pin: codegen model id.",
    },
    SecretSpec {
        id: SecretId::VoxRoutingHardPinModel,
        canonical_env: "VOX_ROUTING_HARD_PIN_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Force a single model id for all calls (incident response). Empty = off.",
        scope_description: "Hard pin model override.",
    },
    SecretSpec {
        id: SecretId::OpenaiApiKey,
        canonical_env: "OPENAI_API_KEY",
        aliases: &["VOX_OPENAI_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set OPENAI_API_KEY when OpenAI routes are enabled.",
        scope_description: "OpenAI API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::AnthropicApiKey,
        canonical_env: "ANTHROPIC_API_KEY",
        aliases: &["VOX_ANTHROPIC_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set ANTHROPIC_API_KEY when Anthropic routes are enabled.",
        scope_description: "Anthropic API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::GroqApiKey,
        canonical_env: "GROQ_API_KEY",
        aliases: &["VOX_GROQ_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set GROQ_API_KEY when Groq routes are enabled.",
        scope_description: "Groq API key for LPU-accelerated inference.",
    },
    SecretSpec {
        id: SecretId::MistralApiKey,
        canonical_env: "MISTRAL_API_KEY",
        aliases: &["VOX_MISTRAL_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set MISTRAL_API_KEY when Mistral routes are enabled.",
        scope_description: "Mistral API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::DeepSeekApiKey,
        canonical_env: "DEEPSEEK_API_KEY",
        aliases: &["VOX_DEEPSEEK_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set DEEPSEEK_API_KEY when DeepSeek routes are enabled.",
        scope_description: "DeepSeek API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::SambaNovaApiKey,
        canonical_env: "SAMBANOVA_API_KEY",
        aliases: &["VOX_SAMBANOVA_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set SAMBANOVA_API_KEY when SambaNova routes are enabled.",
        scope_description: "SambaNova API key for direct inference.",
    },
    SecretSpec {
        id: SecretId::HuggingFaceToken,
        canonical_env: "HF_TOKEN",
        aliases: &["VOX_HF_TOKEN"],
        deprecated_aliases: &["HUGGING_FACE_HUB_TOKEN"],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set HF_TOKEN if Hugging Face routes are needed.",
        scope_description: "Hugging Face Hub token for private model access.",
    },
    SecretSpec {
        id: SecretId::OllamaUrl,
        canonical_env: "OLLAMA_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Ollama instance root URL.",
        scope_description: "URL for local Ollama API.",
    },
    SecretSpec {
        id: SecretId::VoxPopuliLocalOllamaUrl,
        canonical_env: "VOX_POPULI_LOCAL_OLLAMA_URL",
        aliases: &[],
        deprecated_aliases: &["POPULI_URL"],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Canonical URL for local Populi/Ollama instance.",
        scope_description: "Populi/Ollama local URL.",
    },
    SecretSpec {
        id: SecretId::OllamaModel,
        canonical_env: "OLLAMA_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Ollama model tag (e.g. codellama).",
        scope_description: "Default model tag for Ollama.",
    },
    SecretSpec {
        id: SecretId::TogetherApiKey,
        canonical_env: "TOGETHER_API_KEY",
        aliases: &["VOX_TOGETHER_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set TOGETHER_API_KEY for Together training flows.",
        scope_description: "Together AI API key for training and inference.",
    },
    SecretSpec {
        id: SecretId::TogetherFinetuneModel,
        canonical_env: "TOGETHER_FINETUNE_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Model ID for Together finetuning result.",
        scope_description: "Together finetune model ID.",
    },
    SecretSpec {
        id: SecretId::CustomOpenaiApiKey,
        canonical_env: "CUSTOM_OPENAI_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set CUSTOM_OPENAI_API_KEY for custom OpenAI endpoints.",
        scope_description: "Custom OpenAI API key.",
    },
    SecretSpec {
        id: SecretId::V0ApiKey,
        canonical_env: "V0_API_KEY",
        // VOX_V0_API_KEY alias preserved from the deduplicated platform.rs entry.
        aliases: &["VOX_V0_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set V0_API_KEY for v0.dev access.",
        scope_description: "v0 API key.",
    },
    SecretSpec {
        id: SecretId::OpenClawToken,
        canonical_env: "OPENCLAW_TOKEN",
        // VOX_OPENCLAW_TOKEN alias preserved from the deduplicated platform.rs
        // entry; both spellings now resolve to the same secret.
        aliases: &["VOX_OPENCLAW_TOKEN"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set OPENCLAW_TOKEN for OpenClaw access.",
        scope_description: "OpenClaw token.",
    },
    SecretSpec {
        id: SecretId::OpenClawApiKey,
        canonical_env: "OPENCLAW_API_KEY",
        aliases: &["CLAWHUB_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set OPENCLAW_API_KEY (or CLAWHUB_API_KEY) to publish skills to an OpenClaw / ClawHub gateway.",
        scope_description: "API key for publishing skills to OpenClaw / ClawHub gateways.",
    },
    SecretSpec {
        id: SecretId::VoxRunpodApiKey,
        canonical_env: "RUNPOD_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set RUNPOD_API_KEY for RunPod GPU access.",
        scope_description: "RunPod API key.",
    },
    SecretSpec {
        id: SecretId::VoxVastApiKey,
        canonical_env: "VAST_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set VAST_API_KEY for Vast.ai GPU access.",
        scope_description: "Vast.ai API key.",
    },
    SecretSpec {
        id: SecretId::CerebrasApiKey,
        canonical_env: "CEREBRAS_API_KEY",
        aliases: &["VOX_CEREBRAS_API_KEY"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set CEREBRAS_API_KEY for Cerebras inference.",
        scope_description: "Cerebras API key.",
    },
    SecretSpec {
        id: SecretId::VoxAnthropicDirect,
        canonical_env: "VOX_ANTHROPIC_DIRECT",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Force direct Anthropic API usage bypassing OpenRouter.",
        scope_description: "Anthropic direct mode flag.",
    },
    SecretSpec {
        id: SecretId::VoxOpenrouterHttpReferer,
        canonical_env: "OPENROUTER_HTTP_REFERER",
        aliases: &["VOX_OPENROUTER_HTTP_REFERER"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "HTTP Referer for OpenRouter ranking.",
        scope_description: "OpenRouter referer.",
    },
    SecretSpec {
        id: SecretId::VoxOpenrouterAppTitle,
        canonical_env: "OPENROUTER_APP_TITLE",
        aliases: &["VOX_OPENROUTER_APP_TITLE"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "App Title for OpenRouter ranking.",
        scope_description: "OpenRouter app title.",
    },
    SecretSpec {
        id: SecretId::VoxOpenrouterRouteHint,
        canonical_env: "OPENROUTER_ROUTE_HINT",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Route preference hint for OpenRouter.",
        scope_description: "OpenRouter route hint.",
    },
    SecretSpec {
        id: SecretId::VoxOllamaHost,
        canonical_env: "OLLAMA_HOST",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override Ollama host address.",
        scope_description: "Ollama host override.",
    },
    SecretSpec {
        id: SecretId::VoxGroqChatCompletionsUrl,
        canonical_env: "VOX_GROQ_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override Groq chat completions URL.",
        scope_description: "Groq API URL.",
    },
    SecretSpec {
        id: SecretId::VoxCerebrasChatCompletionsUrl,
        canonical_env: "VOX_CEREBRAS_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override Cerebras chat completions URL.",
        scope_description: "Cerebras API URL.",
    },
    SecretSpec {
        id: SecretId::VoxMistralChatCompletionsUrl,
        canonical_env: "VOX_MISTRAL_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override Mistral chat completions URL.",
        scope_description: "Mistral API URL.",
    },
    SecretSpec {
        id: SecretId::VoxDeepseekChatCompletionsUrl,
        canonical_env: "VOX_DEEPSEEK_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override DeepSeek chat completions URL.",
        scope_description: "DeepSeek API URL.",
    },
    SecretSpec {
        id: SecretId::VoxSambanovaChatCompletionsUrl,
        canonical_env: "VOX_SAMBANOVA_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override SambaNova chat completions URL.",
        scope_description: "SambaNova API URL.",
    },
    SecretSpec {
        id: SecretId::VoxAnthropicChatCompletionsUrl,
        canonical_env: "VOX_ANTHROPIC_CHAT_COMPLETIONS_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Override Anthropic chat completions URL.",
        scope_description: "Anthropic API URL.",
    },
    SecretSpec {
        id: SecretId::TogetherTuningTemperature,
        canonical_env: "TOGETHER_TUNING_TEMPERATURE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Float value for Together temperature (e.g. 0.7).",
        scope_description: "Together inference temperature.",
    },
    SecretSpec {
        id: SecretId::TogetherTuningTopP,
        canonical_env: "TOGETHER_TUNING_TOP_P",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Float value for Together top_p (e.g. 0.9).",
        scope_description: "Together inference top_p.",
    },
    SecretSpec {
        id: SecretId::GeminiTuningTemperature,
        canonical_env: "GEMINI_TUNING_TEMPERATURE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Float value for Gemini temperature (e.g. 0.7).",
        scope_description: "Gemini inference temperature.",
    },
    SecretSpec {
        id: SecretId::GeminiTuningTopP,
        canonical_env: "GEMINI_TUNING_TOP_P",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Float value for Gemini top_p (e.g. 0.9).",
        scope_description: "Gemini inference top_p.",
    },
    SecretSpec {
        id: SecretId::OllamaTuningTemperature,
        canonical_env: "OLLAMA_TUNING_TEMPERATURE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Float value for Ollama temperature (e.g. 0.7).",
        scope_description: "Ollama inference temperature.",
    },
    SecretSpec {
        id: SecretId::OllamaTuningTopP,
        canonical_env: "OLLAMA_TUNING_TOP_P",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Float value for Ollama top_p (e.g. 0.9).",
        scope_description: "Ollama inference top_p.",
    },
    SecretSpec {
        id: SecretId::OllamaTuningNumCtx,
        canonical_env: "OLLAMA_TUNING_NUM_CTX",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Integer value for Ollama context size (e.g. 4096).",
        scope_description: "Ollama context window size.",
    },
    SecretSpec {
        id: SecretId::OpenaiTuningTemperature,
        canonical_env: "OPENAI_TUNING_TEMPERATURE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Float value for OpenAI temperature (e.g. 0.7).",
        scope_description: "OpenAI inference temperature.",
    },
    SecretSpec {
        id: SecretId::OpenaiTuningTopP,
        canonical_env: "OPENAI_TUNING_TOP_P",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Float value for OpenAI top_p (e.g. 0.9).",
        scope_description: "OpenAI inference top_p.",
    },
    SecretSpec {
        id: SecretId::AnthropicTuningTemperature,
        canonical_env: "ANTHROPIC_TUNING_TEMPERATURE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Float value for Anthropic temperature (e.g. 0.7).",
        scope_description: "Anthropic inference temperature.",
    },
    SecretSpec {
        id: SecretId::AnthropicTuningTopP,
        canonical_env: "ANTHROPIC_TUNING_TOP_P",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Float value for Anthropic top_p (e.g. 0.9).",
        scope_description: "Anthropic inference top_p.",
    },
];
