use crate::policy::SecretPolicy;
use crate::spec::ids::SecretId;
use crate::spec::types::*;

pub const SPECS_MESH: &[SecretSpec] = &[
    SecretSpec {
        id: SecretId::VoxMeshToken,
        canonical_env: "VOX_MESH_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Run `vox populi up` or set VOX_MESH_TOKEN for mesh auth.",
        scope_description: "General-purpose bearer token for mesh operations.",
    },
    SecretSpec {
        id: SecretId::VoxMeshJwtHmacSecret,
        canonical_env: "VOX_MESH_JWT_HMAC_SECRET",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::required_fail(),
        remediation: "Required API secret for JWT mesh bearer tokens.",
        scope_description: "HMAC secret for signing and verifying mesh JWTs.",
    },
    SecretSpec {
        id: SecretId::VoxMeshAuthScheme,
        canonical_env: "VOX_MESH_AUTH_SCHEME",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set to 'ed25519-envelope' (default), 'jwt-hs256' (deprecated), or 'both'.",
        scope_description: "Wire auth scheme for A2A control-plane messages (P5-T1c).",
    },
    SecretSpec {
        id: SecretId::VoxMeshGithubAttestationGistUrl,
        canonical_env: "VOX_MESH_GITHUB_ATTESTATION_GIST_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Run `vox populi pair github` to publish your attestation Gist.",
        scope_description: "Raw URL of the GitHub Gist containing this node's attestation manifest (P5-T2c).",
    },
    SecretSpec {
        id: SecretId::VoxMeshWorkerToken,
        canonical_env: "VOX_MESH_WORKER_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Worker token for mesh authentication.",
        scope_description: "Mesh worker token.",
    },
    SecretSpec {
        id: SecretId::VoxMeshSubmitterToken,
        canonical_env: "VOX_MESH_SUBMITTER_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Submitter token for mesh authentication.",
        scope_description: "Mesh submitter token.",
    },
    SecretSpec {
        id: SecretId::VoxMeshAdminToken,
        canonical_env: "VOX_MESH_ADMIN_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Admin token for mesh authentication.",
        scope_description: "Mesh admin token.",
    },
    SecretSpec {
        id: SecretId::VoxMeshWorkerResultVerifyKey,
        canonical_env: "VOX_MESH_WORKER_RESULT_VERIFY_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Verification key for mesh worker results.",
        scope_description: "Mesh worker result verify key.",
    },
    SecretSpec {
        id: SecretId::VoxMeshHttpJoin,
        canonical_env: "VOX_MESH_HTTP_JOIN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Join mesh via HTTP.",
        scope_description: "Mesh HTTP join flag.",
    },
    SecretSpec {
        id: SecretId::VoxMeshHttpHeartbeatSecs,
        canonical_env: "VOX_MESH_HTTP_HEARTBEAT_SECS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Heartbeat interval for HTTP mesh.",
        scope_description: "Mesh HTTP heartbeat interval.",
    },
    SecretSpec {
        id: SecretId::VoxMeshVisibility,
        canonical_env: "VOX_MESH_VISIBILITY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: Some("mesh_visibility"),
        policy: SecretPolicy::optional_skip(),
        remediation: "Set node visibility (private|public|hybrid).",
        scope_description: "Visibility level for the populi node.",
    },
    SecretSpec {
        id: SecretId::VoxMeshDonationPolicyJson,
        canonical_env: "VOX_MESH_DONATION_POLICY_JSON",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: Some("mesh_donation_policy"),
        policy: SecretPolicy::optional_skip(),
        remediation: "JSON-serialized WorkerDonationPolicy.",
        scope_description: "Policy governing GPU resource donation.",
    },
    SecretSpec {
        id: SecretId::VoxMeshFederationSigningKey,
        canonical_env: "VOX_MESH_FEDERATION_SIGNING_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Ed25519 private key (base64) for signing mesh announcements.",
        scope_description: "Private key used to sign federated mesh directory entries.",
    },
    SecretSpec {
        id: SecretId::VoxRoutingPreferMesh,
        canonical_env: "VOX_ROUTING_PREFER_MESH",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: Some("routing_prefer_mesh"),
        policy: SecretPolicy::optional_skip(),
        remediation: "Set to 'true' to prefer routing tasks to the local/federated mesh over paid APIs.",
        scope_description: "Routing preference for local/federated mesh GPUs over cloud APIs.",
    },
];
