use crate::policy::SecretPolicy;
use crate::spec::ids::SecretId;
use crate::spec::types::*;

pub const SPECS_SCHOLARLY: &[SecretSpec] = &[
    SecretSpec {
        id: SecretId::VoxZenodoAccessToken,
        canonical_env: "ZENODO_ACCESS_TOKEN",
        aliases: &["VOX_ZENODO_ACCESS_TOKEN"],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Set ZENODO_ACCESS_TOKEN for scholarly deposits.",
        scope_description: "Zenodo API token.",
    },
    SecretSpec {
        id: SecretId::VoxOpenReviewEmail,
        canonical_env: "VOX_OPENREVIEW_EMAIL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "OpenReview account email.",
        scope_description: "OpenReview email.",
    },
    SecretSpec {
        id: SecretId::VoxOpenReviewAccessToken,
        canonical_env: "VOX_OPENREVIEW_ACCESS_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "OpenReview API access token.",
        scope_description: "OpenReview token.",
    },
    SecretSpec {
        id: SecretId::VoxOpenReviewPassword,
        canonical_env: "VOX_OPENREVIEW_PASSWORD",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "OpenReview account password.",
        scope_description: "OpenReview password.",
    },
    SecretSpec {
        id: SecretId::VoxCrossrefPlusApiKey,
        canonical_env: "VOX_CROSSREF_PLUS_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Crossref Plus API key.",
        scope_description: "Crossref API key.",
    },
    SecretSpec {
        id: SecretId::VoxArxivAssistHandoffSecret,
        canonical_env: "VOX_ARXIV_ASSIST_HANDOFF_SECRET",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Secret for arXiv assist handoff.",
        scope_description: "arXiv handoff secret.",
    },
    SecretSpec {
        id: SecretId::VoxOrcidClientId,
        canonical_env: "VOX_ORCID_CLIENT_ID",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "ORCID API client ID.",
        scope_description: "ORCID client id.",
    },
    SecretSpec {
        id: SecretId::VoxOrcidClientSecret,
        canonical_env: "VOX_ORCID_CLIENT_SECRET",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "ORCID API client secret.",
        scope_description: "ORCID secret.",
    },
    SecretSpec {
        id: SecretId::VoxDataCiteRepository,
        canonical_env: "VOX_DATACITE_REPOSITORY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "DataCite repository ID.",
        scope_description: "DataCite repository.",
    },
    SecretSpec {
        id: SecretId::VoxDataCitePassword,
        canonical_env: "VOX_DATACITE_PASSWORD",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "DataCite repository password.",
        scope_description: "DataCite password.",
    },
    SecretSpec {
        id: SecretId::VoxScholarlyAdapter,
        canonical_env: "VOX_SCHOLARLY_ADAPTER",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Select scholarly adapter.",
        scope_description: "Scholarly adapter.",
    },
    SecretSpec {
        id: SecretId::VoxScholarlyDisable,
        canonical_env: "VOX_SCHOLARLY_DISABLE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Disable scholarly publication.",
        scope_description: "Scholarly disable.",
    },
    SecretSpec {
        id: SecretId::VoxScholarlyDisableLive,
        canonical_env: "VOX_SCHOLARLY_DISABLE_LIVE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Disable scholarly live mode.",
        scope_description: "Scholarly disable live.",
    },
    SecretSpec {
        id: SecretId::VoxScholarlyDisableZenodo,
        canonical_env: "VOX_SCHOLARLY_DISABLE_ZENODO",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Disable Zenodo scholarly adapter.",
        scope_description: "Scholarly disable zenodo.",
    },
    SecretSpec {
        id: SecretId::VoxScholarlyDisableOpenReview,
        canonical_env: "VOX_SCHOLARLY_DISABLE_OPENREVIEW",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Disable OpenReview scholarly adapter.",
        scope_description: "Scholarly disable openreview.",
    },
    SecretSpec {
        id: SecretId::VoxOpenReviewApiBase,
        canonical_env: "VOX_OPENREVIEW_API_BASE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "OpenReview API base URL.",
        scope_description: "OpenReview API base.",
    },
    SecretSpec {
        id: SecretId::VoxOpenReviewInvitation,
        canonical_env: "VOX_OPENREVIEW_INVITATION",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "OpenReview invitation ID.",
        scope_description: "OpenReview invitation.",
    },
    SecretSpec {
        id: SecretId::VoxOpenReviewSignature,
        canonical_env: "VOX_OPENREVIEW_SIGNATURE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "OpenReview signature ID.",
        scope_description: "OpenReview signature.",
    },
    SecretSpec {
        id: SecretId::VoxZenodoSandbox,
        canonical_env: "VOX_ZENODO_SANDBOX",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Enable Zenodo sandbox mode.",
        scope_description: "Zenodo sandbox.",
    },
    SecretSpec {
        id: SecretId::VoxZenodoApiBase,
        canonical_env: "VOX_ZENODO_API_BASE",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Zenodo API base URL override.",
        scope_description: "Zenodo API base.",
    },
    SecretSpec {
        id: SecretId::VoxZenodoAttachManifestBody,
        canonical_env: "VOX_ZENODO_ATTACH_MANIFEST_BODY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Attach manifest body to Zenodo uploads.",
        scope_description: "Zenodo manifest attach.",
    },
    SecretSpec {
        id: SecretId::VoxZenodoPublishDeposition,
        canonical_env: "VOX_ZENODO_PUBLISH_DEPOSITION",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Publish deposition on Zenodo.",
        scope_description: "Zenodo publish deposition.",
    },
    SecretSpec {
        id: SecretId::VoxZenodoDraftOnly,
        canonical_env: "VOX_ZENODO_DRAFT_ONLY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Keep Zenodo uploads as drafts only.",
        scope_description: "Zenodo draft only.",
    },
    SecretSpec {
        id: SecretId::VoxZenodoPublishNow,
        canonical_env: "VOX_ZENODO_PUBLISH_NOW",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Publish Zenodo deposition immediately.",
        scope_description: "Zenodo publish now.",
    },
    SecretSpec {
        id: SecretId::VoxZenodoStagingDir,
        canonical_env: "VOX_ZENODO_STAGING_DIR",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Staging directory for Zenodo uploads.",
        scope_description: "Zenodo staging dir.",
    },
    SecretSpec {
        id: SecretId::VoxZenodoUploadAllowlist,
        canonical_env: "VOX_ZENODO_UPLOAD_ALLOWLIST",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "Allowlist for Zenodo file uploads.",
        scope_description: "Zenodo upload allowlist.",
    },
];
