use vox_compiler::app_contract::project_app_contract;
use vox_compiler::hir::{HirHttpMethod, HirModule, HirRoute};

use super::stmt_expr::emit_stmt;
use super::tables::emit_db_setup;

pub fn emit_main(module: &HirModule, package_name: &str) -> String {
    let app_contract = project_app_contract(module);
    let mut out = String::new();
    out.push_str("// Generated by Vox Compiler\n");

    let has_tables = !module.tables.is_empty();

    let routes = crate::codegen_shared::lower_module_routes(module);

    // Collect which routing methods are actually used
    let mut needs_get = false;
    let mut needs_post = false;
    let mut needs_put = false;
    let mut needs_delete = false;
    for route in &routes {
        match route.method {
            crate::codegen_shared::RouteMethod::Get => needs_get = true,
            crate::codegen_shared::RouteMethod::Post => needs_post = true,
            crate::codegen_shared::RouteMethod::Put => needs_put = true,
            crate::codegen_shared::RouteMethod::Delete => needs_delete = true,
        }
    }
    // `@query` handlers are GET + query-string args; `@server` / `@mutation` stay POST + JSON body.
    for sf in &module.endpoint_fns {
        if sf.kind == vox_compiler::hir::HirEndpointKind::Query {
            needs_get = true;
        } else {
            needs_post = true;
        }
    }

    let mut routing_methods = Vec::new();
    if needs_get {
        routing_methods.push("get");
    }
    if needs_post {
        routing_methods.push("post");
    }
    if needs_put {
        routing_methods.push("put");
    }
    if needs_delete {
        routing_methods.push("delete");
    }

    if routing_methods.is_empty() {
        out.push_str("use axum::Router;\n");
    } else {
        out.push_str(&format!(
            "use axum::{{Router, routing::{{{}}}, Json}};\n",
            routing_methods.join(", ")
        ));
    }
    if module
        .endpoint_fns
        .iter()
        .any(|sf| sf.kind == vox_compiler::hir::HirEndpointKind::Query)
    {
        out.push_str("use axum::extract::Query;\n");
    }
    out.push_str("use axum::response::{Response, IntoResponse};\n");
    out.push_str("use axum::body::Body;\n");
    out.push_str("use axum::http::{StatusCode, header};\n");
    out.push_str("use std::net::SocketAddr;\n");
    out.push_str("use rust_embed::Embed;\n");
    if has_tables {
        out.push_str("use std::sync::Arc;\n");
        out.push_str("use axum::extract::Extension;\n");
        out.push_str("use vox_db::Codex;\n");
    }

    // Use the library crate by name (avoids `mod lib;` warning)
    let crate_name = package_name.replace('-', "_");
    out.push_str(&format!("use {}::*;\n\n", crate_name));

    // Embedded static assets
    out.push_str("#[derive(Embed)]\n");
    out.push_str("#[folder = \"public/\"]\n");
    out.push_str("struct Assets;\n\n");

    // Fallback handler for embedded assets
    out.push_str("async fn serve_embedded(uri: axum::http::Uri) -> Response {\n");
    out.push_str("    let path = uri.path().trim_start_matches('/');\n");
    out.push_str("    let path = if path.is_empty() { \"index.html\" } else { path };\n");
    out.push_str("    match Assets::get(path) {\n");
    out.push_str("        Some(file) => {\n");
    out.push_str("            let mime = mime_guess::from_path(path).first_or_octet_stream();\n");
    out.push_str("            (StatusCode::OK, [(header::CONTENT_TYPE, mime.as_ref().to_string())], file.data.to_vec()).into_response()\n");
    out.push_str("        }\n");
    out.push_str("        None => {\n");
    out.push_str("            // SPA fallback: serve index.html for client-side routing\n");
    out.push_str("            match Assets::get(\"index.html\") {\n");
    out.push_str("                Some(file) => (StatusCode::OK, [(header::CONTENT_TYPE, \"text/html\".to_string())], file.data.to_vec()).into_response(),\n");
    out.push_str(
        "                None => (StatusCode::NOT_FOUND, \"Not Found\").into_response(),\n",
    );
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("async fn serve_dispatch(req: axum::http::Request<Body>) -> Response {\n");
    out.push_str("    let uri = req.uri().clone();\n");
    out.push_str("    if *req.method() == axum::http::Method::GET {\n");
    out.push_str(&format!(
        "        if let Ok(base) = std::env::var(\"{}\") {{\n",
        app_contract.server_config.dev_proxy_env_var
    ));
    out.push_str("            let base = base.trim();\n");
    out.push_str("            if !base.is_empty() {\n");
    out.push_str("                let p = uri.path();\n");
    out.push_str("                if !p.starts_with(\"/api\") {\n");
    out.push_str(
        "                    let target = format!(\"{}{}\", base.trim_end_matches('/'), uri);\n",
    );
    out.push_str(
        "                    if let Ok(client) = vox_reqwest_defaults::client_builder()\n",
    );
    out.push_str("                        .timeout(std::time::Duration::from_secs(60))\n");
    out.push_str("                        .build()\n");
    out.push_str("                    {\n");
    out.push_str("                        if let Ok(resp) = client.get(target).send().await {\n");
    out.push_str("                            let status = resp.status();\n");
    out.push_str("                            let ct = resp.headers().get(reqwest::header::CONTENT_TYPE).cloned();\n");
    out.push_str(
        "                            let bytes = resp.bytes().await.unwrap_or_default();\n",
    );
    out.push_str("                            let code = axum::http::StatusCode::from_u16(status.as_u16())\n");
    out.push_str(
        "                                .unwrap_or(axum::http::StatusCode::BAD_GATEWAY);\n",
    );
    out.push_str(
        "                            let mut builder = Response::builder().status(code);\n",
    );
    out.push_str("                            if let Some(ct) = ct {\n");
    out.push_str("                                if let Ok(v) = ct.to_str() {\n");
    out.push_str(
        "                                    builder = builder.header(header::CONTENT_TYPE, v);\n",
    );
    out.push_str("                                }\n");
    out.push_str("                            }\n");
    out.push_str(
        "                            if let Ok(out) = builder.body(Body::from(bytes)) {\n",
    );
    out.push_str("                                return out;\n");
    out.push_str("                            }\n");
    out.push_str("                        }\n");
    out.push_str("                    }\n");
    out.push_str("                }\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    serve_embedded(uri).await\n");
    out.push_str("}\n\n");

    out.push_str("#[tokio::main]\n");
    out.push_str("async fn main() {\n");
    out.push_str("    tracing_subscriber::fmt::init();\n");

    // Database setup
    if has_tables {
        out.push_str(&emit_db_setup(module));
    }

    out.push_str("    if let Ok(wf_name_raw) = std::env::var(\"VOX_RUN_WORKFLOW\") {\n");
    out.push_str("        let wf_name = wf_name_raw.trim().to_string();\n");
    out.push_str("        if !wf_name.is_empty() {\n");
    out.push_str(
        "            let args_raw = std::env::var(\"VOX_WORKFLOW_ARGS\").unwrap_or_else(|_| \"[]\".to_string());\n",
    );
    out.push_str(
        "            let args: Vec<serde_json::Value> = match serde_json::from_str(&args_raw) {\n",
    );
    out.push_str("                Ok(v) => v,\n");
    out.push_str("                Err(e) => {\n");
    out.push_str("                    eprintln!(\"Invalid VOX_WORKFLOW_ARGS JSON: {}\", e);\n");
    out.push_str("                    std::process::exit(2);\n");
    out.push_str("                }\n");
    out.push_str("            };\n");
    out.push_str("            match __vox_run_workflow(&wf_name, &args).await {\n");
    out.push_str("                Ok(()) => {\n");
    out.push_str("                    vox_actor_runtime::builtins::vox_flush_exit_commands();\n");
    out.push_str("                    return;\n");
    out.push_str("                }\n");
    out.push_str("                Err(e) => {\n");
    out.push_str("                    eprintln!(\"Workflow execution failed: {}\", e);\n");
    out.push_str("                    vox_actor_runtime::builtins::vox_flush_exit_commands();\n");
    out.push_str("                    std::process::exit(2);\n");
    out.push_str("                }\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");

    let has_routes = !module.routes.is_empty() || !module.endpoint_fns.is_empty();

    // Setup routes
    if has_routes {
        out.push_str("    let app = Router::new()\n");
        // Manual routes
        for route in &app_contract.http_routes {
            let method = route_method_from_contract(route.method.as_str());
            out.push_str(&format!(
                "        .route(\"{}\", {}({}))\n",
                route.path,
                method,
                route_handler_name_from_contract(route)
            ));
        }
        // Auto-generated server function routes
        for sf in &app_contract.server_fns {
            out.push_str(&format!(
                "        .route(\"{}\", post(handle_sf_{}))\n",
                sf.route_path, sf.name
            ));
        }
        // `@query` — GET /api/query/<name> + deterministic JSON-in-query encoding (see vox-client.ts).
        for qf in &app_contract.query_fns {
            out.push_str(&format!(
                "        .route(\"{}\", get(handle_q_{}))\n",
                qf.route_path, qf.name
            ));
        }
        // `@mutation` — POST /api/mutation/<name>
        for mf in &app_contract.mutation_fns {
            out.push_str(&format!(
                "        .route(\"{}\", post(handle_m_{}))\n",
                mf.route_path, mf.name
            ));
        }
        out.push_str("        .fallback(serve_dispatch);\n\n");

        if has_tables {
            out.push_str("    let app = app.layer(Extension(db.clone()));\n");
        }

        out.push_str(&format!(
            "    let port: u16 = std::env::var(\"{}\")\n",
            app_contract.server_config.port_env_var
        ));
        out.push_str("        .ok()\n");
        out.push_str("        .and_then(|s| s.parse().ok())\n");
        out.push_str(&format!(
            "        .unwrap_or({});\n",
            app_contract.server_config.default_port
        ));
        out.push_str(&format!(
            "    let addr = SocketAddr::from(([{}, {}, {}, {}], port));\n",
            127, 0, 0, 1
        ));
        out.push_str("    println!(\"Listening on {}\", addr);\n");
        out.push_str(
            "    let listener = tokio::net::TcpListener::bind(addr).await.expect(\"Failed to bind TCP listener\");\n",
        );
        out.push_str(
            "    axum::serve(listener, app).await.expect(\"Server exited with error\");\n",
        );
        out.push_str("    vox_actor_runtime::builtins::vox_flush_exit_commands();\n");
    } else {
        out.push_str("    println!(\"No routes defined. Exiting.\");\n");
    }
    out.push_str("}\n\n");

    // Generate route handlers
    for route in &module.routes {
        out.push_str(&emit_route_handler(route, has_tables));
    }

    let mut mutation_idx = 0;
    for sf in &module.endpoint_fns {
        match sf.kind {
            vox_compiler::hir::HirEndpointKind::Server => {
                out.push_str(&emit_server_fn_handler(sf, has_tables, "handle_sf_", false));
            }
            vox_compiler::hir::HirEndpointKind::Query => {
                out.push_str(&emit_query_fn_handler(sf, has_tables, "handle_q_"));
            }
            vox_compiler::hir::HirEndpointKind::Mutation => {
                let wrap_mutation_tx = app_contract
                    .mutation_fns
                    .get(mutation_idx)
                    .map(|c| c.wraps_db_transaction)
                    .unwrap_or(has_tables);
                out.push_str(&emit_server_fn_handler(
                    sf,
                    has_tables,
                    "handle_m_",
                    wrap_mutation_tx,
                ));
                mutation_idx += 1;
            }
        }
    }

    out
}

fn route_method_from_contract(method: &str) -> &'static str {
    match method {
        "GET" => "get",
        "POST" => "post",
        "PUT" => "put",
        "DELETE" => "delete",
        _ => "get",
    }
}

fn route_handler_name_from_contract(route: &vox_compiler::app_contract::AppHttpRouteContract) -> String {
    let method = match route.method.as_str() {
        "GET" => HirHttpMethod::Get,
        "POST" => HirHttpMethod::Post,
        "PUT" => HirHttpMethod::Put,
        "DELETE" => HirHttpMethod::Delete,
        _ => HirHttpMethod::Get,
    };
    route_handler_name(&route.path, &method)
}

fn route_handler_name(path: &str, method: &HirHttpMethod) -> String {
    let clean_path = path.replace('/', "_").replace(['{', '}'], "");
    let m = match method {
        HirHttpMethod::Get => "get",
        HirHttpMethod::Post => "post",
        HirHttpMethod::Put => "put",
        HirHttpMethod::Delete => "delete",
    };
    format!("handle_{}{}", m, clean_path)
}

fn emit_route_handler(route: &HirRoute, has_tables: bool) -> String {
    let handler_name = route_handler_name(&route.path, &route.method);
    let mut out = String::new();
    out.push_str(&format!("async fn {handler_name}("));
    if has_tables {
        out.push_str("Extension(db): Extension<Arc<Codex>>, ");
    }
    out.push_str("Json(request): Json<serde_json::Value>) -> Json<serde_json::Value> {\n");

    let mut has_return = false;
    for stmt in &route.body {
        let emitted = emit_stmt(stmt, 1, true, false, false);
        if emitted.contains("return Json(") {
            has_return = true;
        }
        out.push_str(&emitted);
    }
    if !has_return {
        out.push_str("    Json(serde_json::Value::Null)\n");
    }
    out.push_str("}\n\n");
    out
}

/// Generate an Axum handler for a server function.
fn emit_server_fn_handler(
    sf: &vox_compiler::hir::HirEndpointFn,
    has_tables: bool,
    name_prefix: &str,
    wrap_mutation_tx: bool,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("async fn {name_prefix}{}(", sf.name));
    if has_tables {
        out.push_str("Extension(db): Extension<Arc<Codex>>, ");
    }
    out.push_str("Json(request): Json<serde_json::Value>) -> Json<serde_json::Value> {\n");

    // Extract params from request JSON
    for param in &sf.params {
        out.push_str(&format!(
            "    let {} = request[\"{}\"].clone();\n",
            param.name, param.name
        ));
    }

    if wrap_mutation_tx && has_tables {
        out.push_str("    let db = (*db).clone();\n");
        out.push_str("    match db.transaction(async move {\n");
        let mut has_return = false;
        for stmt in &sf.body {
            let emitted = emit_stmt(stmt, 2, true, false, true);
            if emitted.contains("return Ok(Json(") || emitted.contains("return Json(") {
                has_return = true;
            }
            out.push_str(&emitted);
        }
        if !has_return {
            out.push_str("        Ok(Json(serde_json::Value::Null))\n");
        }
        out.push_str("    }).await {\n");
        out.push_str("        Ok(resp) => resp,\n");
        out.push_str("        Err(e) => Json(serde_json::json!({\"error\": e.to_string()})),\n");
        out.push_str("    }\n");
    } else {
        let mut has_return = false;
        for stmt in &sf.body {
            let emitted = emit_stmt(stmt, 1, true, false, false);
            if emitted.contains("return Json(") {
                has_return = true;
            }
            out.push_str(&emitted);
        }
        if !has_return {
            out.push_str("    Json(serde_json::Value::Null)\n");
        }
    }
    out.push_str("}\n\n");
    out
}

/// Axum GET handler for `@query`: args are JSON-encoded query values (`name=<json>`), keys sorted on the client.
fn emit_query_fn_handler(
    sf: &vox_compiler::hir::HirEndpointFn,
    has_tables: bool,
    name_prefix: &str,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("async fn {name_prefix}{}(", sf.name));
    if has_tables {
        out.push_str("Extension(db): Extension<Arc<Codex>>, ");
    }
    out.push_str(
        "Query(q): Query<std::collections::BTreeMap<String, String>>) -> Json<serde_json::Value> {\n",
    );

    for param in &sf.params {
        out.push_str(&format!(
            "    let {} = q.get(\"{}\").and_then(|s| serde_json::from_str::<serde_json::Value>(s).ok()).unwrap_or(serde_json::Value::Null);\n",
            param.name, param.name
        ));
    }

    let mut has_return = false;
    for stmt in &sf.body {
        let emitted = emit_stmt(stmt, 1, true, false, false);
        if emitted.contains("return Json(") {
            has_return = true;
        }
        out.push_str(&emitted);
    }
    if !has_return {
        out.push_str("    Json(serde_json::Value::Null)\n");
    }
    out.push_str("}\n\n");
    out
}

#[cfg(test)]
mod tests {
    use super::emit_main;
    use vox_compiler::hir::lower_module;
    use vox_compiler::lexer::cursor::lex;
    use vox_compiler::parser::parse;

    #[test]
    #[ignore]
    fn emit_main_includes_generated_workflow_dispatch_env_branch() {
        let src = r#"
workflow hello() {
    ret
}
"#;
        let tokens = lex(src);
        let module = parse(tokens).expect("parse");
        let hir = lower_module(&module);
        let output = emit_main(&hir, "generated-demo");
        assert!(output.contains("VOX_RUN_WORKFLOW"));
        assert!(output.contains("VOX_WORKFLOW_ARGS"));
        assert!(output.contains("__vox_run_workflow(&wf_name, &args).await"));
    }
}
