use std::env;
use std::path::PathBuf;

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/ptx");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let ptx_path = out_dir.join("ptx.rs");

    // Pure-Rust build: always use pre-compiled PTX bundles.
    // No nvcc, no cl.exe, no C/C++ toolchain required at build time.
    // To regenerate PTX bundles, run a one-time nvcc pass in CI and copy
    // the resulting .ptx files into patches/candle-kernels-0.9.2/src/ptx/.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let ptx_src_dir = manifest_dir.join("src").join("ptx");

    let kernel_names = [
        "affine", "binary", "cast", "conv", "fill", "indexing",
        "quantized", "reduce", "sort", "ternary", "unary",
    ];

    let mut ptx_rs = String::from(
        "// Auto-generated by candle-kernels build.rs — DO NOT EDIT.\n\
         // Bundled pre-compiled PTX; no nvcc required.\n\n"
    );

    let mut any_missing = false;
    for name in &kernel_names {
        let ptx_file = ptx_src_dir.join(format!("{}.ptx", name));
        if ptx_file.is_file() {
            ptx_rs.push_str(&format!(
                "pub const {}: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/src/ptx/{}.ptx\"));\n",
                name.to_uppercase(), name
            ));
        } else {
            println!("cargo:warning=Missing pre-compiled PTX for kernel '{}' at {:?}", name, ptx_file);
            // Provide an empty string so downstream compiles but the kernel will be unusable.
            ptx_rs.push_str(&format!("pub const {}: &str = \"\";\n", name.to_uppercase()));
            any_missing = true;
        }
    }

    if any_missing {
        println!(
            "cargo:warning=One or more PTX bundles are missing. \
             CUDA inference will panic at runtime when those kernels are loaded. \
             Regenerate PTX by running nvcc in CI and copying .ptx files to src/ptx/."
        );
    }

    std::fs::write(&ptx_path, ptx_rs).unwrap();

    // MOE kernels are GPU-specific and require nvcc to compile.
    // They are not bundled as PTX because they depend on WMMA intrinsics
    // that vary per GPU architecture. MOE paths are disabled in the pure-Rust
    // build — the feature flag `moe` (not enabled by default) gates them.
    // No link directives for libmoe or cudart here; cudarc handles the
    // runtime CUDA linkage at runtime via dlopen.
}
