// AUTO-GENERATED by style-dictionary. Do not edit. Run `pnpm tokens:build`.
export const tokens = {
  "color": {
    "neutral": {
      "50": "#fafafa",
      "300": "#d4d4d8",
      "400": "#a1a1aa",
      "700": "#3f3f46",
      "800": "#27272a",
      "900": "#18181b",
      "950": "#09090b"
    },
    "brass": {
      "default": "#d4af37"
    },
    "basalt": {
      "600": "#2b343a",
      "700": "#1f262b",
      "800": "#15191c",
      "850": "#11151a",
      "900": "#0c0e10",
      "950": "#0a0c0d"
    },
    "travertine": {
      "50": "#f6f1e7",
      "100": "#f4eee1",
      "200": "#ece5d6",
      "300": "#e3dbc8",
      "ink": "#2a2620",
      "ink-soft": "#4a443a",
      "ink-muted": "#6b6457"
    },
    "gold": {
      "300": "#e0c478",
      "400": "#d4af37",
      "500": "#c9a24a",
      "600": "#a8842f",
      "700": "#7d5f20"
    },
    "verdigris": {
      "300": "#79c8ba",
      "400": "#4a9e8f",
      "600": "#2f7d6f",
      "700": "#1f5a50"
    },
    "terracotta": {
      "400": "#d98b6a",
      "600": "#9f4e2f"
    },
    "oxblood": {
      "600": "#a3402f",
      "700": "#7e2d20"
    },
    "status": {
      "pass": "#79c8ba",
      "fail": "#f0a59a",
      "warn": "#d98b6a",
      "info": "#bfdbfe"
    },
    "bg": {
      "base": "#0c0e10",
      "surface": "#15191c",
      "elevated": "#1f262b"
    },
    "text": {
      "primary": "#fafafa",
      "secondary": "#c4ccd2",
      "muted": "#8b949a"
    },
    "border": {
      "subtle": "#1f262b",
      "strong": "#3a444b"
    },
    "accent": {
      "default": "#c9a24a",
      "secondary": "#4a9e8f"
    },
    "overlay": {
      "subtle": "rgba(255,255,255,0.04)",
      "hover": "rgba(255,255,255,0.07)",
      "solid": "#11151a"
    }
  },
  "space": {
    "0": "0px",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "6": "24px",
    "8": "32px",
    "12": "48px"
  },
  "radius": {
    "sm": "6px",
    "md": "10px",
    "lg": "16px",
    "xl": "24px"
  },
  "font": {
    "size": {
      "xs": "12px",
      "sm": "14px",
      "base": "16px",
      "lg": "18px",
      "xl": "24px",
      "2xl": "32px"
    },
    "weight": {
      "regular": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700"
    },
    "leading": {
      "tight": "1.25",
      "normal": "1.5"
    },
    "family": {
      "display": "Cinzel, Georgia, serif",
      "sans": "Inter, system-ui, sans-serif",
      "serif": "EB Garamond, Georgia, serif",
      "mono": "ui-monospace, Consolas, monospace"
    }
  },
  "motion": {
    "fast": "120ms",
    "base": "200ms",
    "slow": "400ms"
  },
  "z": {
    "base": "0",
    "dropdown": "1000",
    "modal": "1300",
    "toast": "1500"
  }
} as const;
