use crate::component::map_vox_type_to_ts;
use crate::jsx::emit_stmt;
use vox_ast::decl::ActivityDecl;

/// Generate a TypeScript async function from a Vox activity declaration.
/// Returns the TypeScript source code for the activity.
pub fn generate_activity(activity: &ActivityDecl) -> String {
    let name = &activity.name;
    let mut out = String::new();

    // Build parameter list with type annotations
    let params: Vec<String> = activity
        .params
        .iter()
        .map(|p| {
            let ts_type = p
                .type_ann
                .as_ref()
                .map_or("any".to_string(), map_vox_type_to_ts);
            format!("{}: {}", p.name, ts_type)
        })
        .collect();

    // Return type
    let return_type = activity
        .return_type
        .as_ref()
        .map_or("Promise<any>".to_string(), |t| {
            format!("Promise<{}>", map_vox_type_to_ts(t))
        });

    // Function signature
    out.push_str(&format!(
        "export async function {}({}): {} {{\n",
        name,
        params.join(", "),
        return_type
    ));

    // Body
    for stmt in &activity.body {
        out.push_str(&emit_stmt(stmt, 1));
    }

    out.push_str("}\n\n");
    out
}

/// Generate a TypeScript wrapper function that applies `with` options
/// at the call site. This emits a helper that wraps the activity call
/// with retry/timeout logic.
pub fn generate_activity_runner() -> String {
    let mut out = String::new();
    out.push_str("// Activity execution helper generated by Vox compiler\n");
    out.push_str("export interface ActivityOptions {\n");
    out.push_str("  retries?: number;\n");
    out.push_str("  timeout?: string | number;\n");
    out.push_str("  initial_backoff?: string;\n");
    out.push_str("  max_backoff?: string;\n");
    out.push_str("  backoff_multiplier?: number;\n");
    out.push_str("  activity_id?: string;\n");
    out.push_str("}\n\n");

    out.push_str("function parseDuration(s: string): number {\n");
    out.push_str("  if (s.endsWith('ms')) return parseInt(s);\n");
    out.push_str("  if (s.endsWith('s')) return parseInt(s) * 1000;\n");
    out.push_str("  if (s.endsWith('m')) return parseInt(s) * 60000;\n");
    out.push_str("  if (s.endsWith('h')) return parseInt(s) * 3600000;\n");
    out.push_str("  return parseInt(s) * 1000;\n");
    out.push_str("}\n\n");

    out.push_str("export async function executeActivity<T>(\n");
    out.push_str("  name: string,\n");
    out.push_str("  fn: () => Promise<T>,\n");
    out.push_str("  options: ActivityOptions = {}\n");
    out.push_str("): Promise<T> {\n");
    out.push_str("  const maxAttempts = (options.retries ?? 0) + 1;\n");
    out.push_str("  const timeoutMs = typeof options.timeout === 'string'\n");
    out.push_str("    ? parseDuration(options.timeout)\n");
    out.push_str("    : typeof options.timeout === 'number'\n");
    out.push_str("      ? options.timeout * 1000\n");
    out.push_str("      : undefined;\n");
    out.push_str("  let backoff = options.initial_backoff\n");
    out.push_str("    ? parseDuration(options.initial_backoff)\n");
    out.push_str("    : 100;\n");
    out.push_str("  const maxBackoff = options.max_backoff\n");
    out.push_str("    ? parseDuration(options.max_backoff)\n");
    out.push_str("    : 60000;\n");
    out.push_str("  const multiplier = options.backoff_multiplier ?? 2;\n\n");

    out.push_str("  let lastError: Error | undefined;\n");
    out.push_str("  for (let attempt = 1; attempt <= maxAttempts; attempt++) {\n");
    out.push_str("    try {\n");
    out.push_str("      if (timeoutMs) {\n");
    out.push_str("        const result = await Promise.race([\n");
    out.push_str("          fn(),\n");
    out.push_str("          new Promise<never>((_, reject) =>\n");
    out.push_str("            setTimeout(() => reject(new Error(`Activity '${name}' timed out`)), timeoutMs)\n");
    out.push_str("          ),\n");
    out.push_str("        ]);\n");
    out.push_str("        return result;\n");
    out.push_str("      }\n");
    out.push_str("      return await fn();\n");
    out.push_str("    } catch (err) {\n");
    out.push_str("      lastError = err instanceof Error ? err : new Error(String(err));\n");
    out.push_str("      if (attempt < maxAttempts) {\n");
    out.push_str("        await new Promise(resolve => setTimeout(resolve, backoff));\n");
    out.push_str("        backoff = Math.min(backoff * multiplier, maxBackoff);\n");
    out.push_str("      }\n");
    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("  throw lastError ?? new Error(`Activity '${name}' failed`);\n");
    out.push_str("}\n");

    out
}
