name: Docs Link Checker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: --base . --verbose --no-progress '**/*.md'
          fail: true
