name: Docs Link Checker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: --base . --verbose --no-progress --max-retries 5 --retry-wait-time 5 --timeout 40 --exclude '.*cursor\.com/.*' --exclude '.*sigstore\.dev/.*' --exclude '.*tanstack\.com/.*' --exclude '^https://slsa\\.dev/how-to/get-started/?$' --exclude 'docs/src/archive/' --exclude 'crates/.*' --exclude 'scripts/.*' --exclude '\.agents/.*' --exclude 'docs/news/templates/.*' --exclude '.*iclr\.cc/.*' --exclude '.*ascentcore\.com/.*' --exclude '.*eslint-react.*' --exclude '.*modelcontextprotocol\.io.*' --exclude '.*docs\.doppler\.com.*' --exclude '.*learn\.microsoft\.com.*' '**/*.md'
          fail: true
